### ISSUE TITLE
Module scaffolding

### ISSUE THREAD

**Issue by kosz** [aurelia/cli#1]
One area that most yeoman scaffolding tools don't support is the creation of a Module. They all scaffold a SPA structure ... 

But what if you have multiple projects. And you want to create a library (module), which is not a SPA, but instead it can be imported into SPA's to provide functionality. You'd want to share this amongst multiple projects ? You'd want it to be scaffolded in a special manner. And you'd want it to be ready to be linked locally or added to some sort of (ideally private) repository that you can then import it from into your application. 

The project structure and packaging would differ from a normal SPA, things like index.html should not be packaged in the dist.

**Comment by EisenbergEffect** [comment]
Absolutely. We should definitely support this scenario through the cli. It's a really important use case FYI @kosz If you are trying to build a plugin for aurelia now, there's a skeleton called skeleton-plugin that is set up for that in the mean time.

**Comment by kosz** [comment]
Great. I was just tossing out an idea, based on things I feel are missing from the current standard yeoman generators, but with that skeleton already in place I can see that you're already ahead of me.
