### ISSUE TITLE
Execution Load Time

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#10]
Regardless of the command executed, we see a 700ms  lag, before the command is actually executed. This is due to the amount of logic being ran on execution. This can be eliminated one of two ways.

1: Remove the Commander module.

2: Create conditions, allowing commands to be created on runtime based on process.argv

For a quick fix, I say we make the conditions, and only create the commands if necessary. For Example

If process.argv only contains `['new']`

Then we should not create the commands `bundle, help, plugin` and so forth. 
However, because these commands contain the their descriptions, when the help command is executed, we should then create all commands. 

Once we eliminate Commander.js we will be able to be more flexible with what logic is being required at run time.

**Comment by joelcoxokc** [comment]
This should almost be resolved from most recent refactor.

**Comment by ahmedshuhel** [comment]
Which one is causing the delay? Liftoff or commander.js. You removed liftoff.

**Comment by joelcoxokc** [comment]
Both

**Comment by joelcoxokc** [comment]
Commander's delay is worse than liftoffs. But I am waiting before I strip Commander out. I have forked commanderjs, and re writing the way it Is substantiated. Once I am finished I will just simply replace it. It won't affect our code,because I am providing the same api.

**Comment by joelcoxokc** [comment]
***the way it is instantiated
