### ISSUE TITLE
CLI + JSPM at the end did not install all necessary dependencies

### ISSUE THREAD

**Issue by PWKad** [aurelia/cli#1005]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
Local aurelia-cli v1.0.0-beta.8

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.6

* **Node Version:**
v10.13.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
ESNext

* **Loader/bundler:**
SystemJS

**Current behavior:**

* **What is the expected behavior?**

After choosing to install dependencies at the end of the process when I try to `au build` I get an error that bundled deps are missing - 

```
// .......
INFO [Bundler] Auto tracing package: 1.3.1      aurelia-route-recognizer
INFO [Bundle] Writing app-bundle.js...
ERROR [Bundle] Error while trying to read node_modules/@babel/polyfill/browser.js
ERROR [Bundle] Failed to write the bundle
INFO [Bundle] Error: ENOENT: no such file or directory, open 'node_modules/@babel/polyfill/browser.js'
{ uid: 10,
  name: 'writeBundles',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open 'node_modules/@babel/polyfill/browser.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/@babel/polyfill/browser.js' },
  duration: [ 0, 204032794 ],
  time: 1545419670893 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open 'node_modules/@babel/polyfill/browser.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/@babel/polyfill/browser.js' },
  duration: [ 0, 298392046 ],
  time: 1545419670896 }
{ [Error: ENOENT: no such file or directory, open 'node_modules/@babel/polyfill/browser.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/@babel/polyfill/browser.js' }
```

* **What is the motivation / use case for changing the behavior?**

Trying to test out whether an old skeleton JSPM project can be converted to JSPM, since the deps weren't found I'm going to investigate why and possibly put up a PR if it seems simple.

**Comment by PWKad** [comment]
Ok I found a file named `browser.js` and updated the bundle section to reference that file but it failed.

**Comment by PWKad** [comment]
Also tried on 8.12.x node with npm 6.4.x and having the same result with the other projects besides webpack.

**Comment by PWKad** [comment]
Yeah no idea here I went and looked in the @babel/polyfill repo and as I best I can tell they delete that file after publishing so presumably it is supposed to get published and do something here but I don't see what. 🤷‍♂️

**Comment by PWKad** [comment]
https://github.com/babel/babel/issues/9227

**Comment by PWKad** [comment]
Linked the issue but the babel polyfill plugin was released yesterday but did not include the dist files that it was supposed to AFAICT, leaving this open until that is resolved since it is going to cause anyone else who starts a new JSPM or Require.js project with the CLI to run in to the same problem

**Comment by PWKad** [comment]
Linked issue fixed, closing this.

**Comment by huochunpeng** [comment]
FYI, not for this issue, but the reason we use prepend for babel polyfill instead of direct `import '@babel/polyfill';` is that cli bundler has issue to support tracing babel polyfill.

It's about stubbing the usage of Nodejs global variable "global". I have fixed the issue in my own WIP [bundler](https://github.com/dumberjs/dumber) in [this commit](https://github.com/dumberjs/dumber/commit/a1975c4a6e0556b694aebe1f966a94d79ec8a59d), but I cannot fix it in cli yet because cli uses rjs parser which I don't want to change too much.
