### ISSUE TITLE
Aurelia CLI bundler incorrectly traces the dependencies of Font Awesome v5 JS  SVG Core

### ISSUE THREAD

**Issue by AquilaSands** [aurelia/cli#1013]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.9

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.0.0

* **NPM Version:**
5.5.1

* **Browser:**
Chrome 71

* **Language:**
TypeScript 3.2.2

* **Loader/bundler:**
SystemJS

**Current behavior:**
Installing and using Font Awesome JS + SVG causes the app to fail to load.

When bundled an incorrect dependency trace causes a fetch call to /fa when loading the Font Awesome module this results in a console error 'Error: Unexpected token <' because the path /fa does not exist so the index.html is returned (it can also result in a 404 error for a .net core based app).

I think this is caused by this line https://github.com/FortAwesome/Font-Awesome/blob/34dff97269eb4d4142218af6a9dbc44024524ba2/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L1607 in fontawesome-svg-core/index.es.js. That line is a recursive call of a function called define, it looks like the auto tracing is seeing this as module define and is creating an incorrect define in the vendor bundle like so:

    define('@fortawesome/fontawesome-svg-core/index.es',["exports"], function (_exports) { // This is the correct define for index.es.js
        // Contents of index.es.js omitted
    });define("@fortawesome/fontawesome-svg-core/index.es", ["fa"], function(m){return m;}); // This is the bad define with the fa dependency

Removing the bad define fixes the issue and the app loads and the font awesome icons work.
Removing the recursive call to define in index.es.js also fixes the issue as the bad define is no longer added to the vendor bundle.

* **What is the expected behavior?**
Font Awesome JS + SVG should have the dependencies traced correctly.

* **Steps to Reproduce**

1.  Create a new cli project with the following options
 - Platform: Web
 - Bundler: Aurelia-CLI
 - Loader: SystemJS
 - Transpiler: TypeScript
 - Markup Processor: Minimal Minification
 - CSS Processor: PostCSS
 - Unit Test Runner: None
 - Integration Test Runner: None
 - Editor: None
2. Install Font Awesome `npm i @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons --save`
3. Configure and use a Font Awesome icon, the app will fail to load

I have created a github repo with a minimal example of the issue here https://github.com/AquilaSands/au-cli-fontawesome-bug `font-awesome.ts` configures Font Awesome and the `load` function is called in main.ts
 

* **What is the motivation / use case for changing the behavior?**
Font Awesome JS + SVG should work with Aurelia

**Comment by huochunpeng** [comment]
The fa index.es.js has an internal func named as `function define(...)` which confused rjs parser (cli uses it). It thought that `define('fa',` is an AMD define but it's actually a call to local internal define func.

There is a very strange temporary fix for you. Switch from SystemJS to RequireJS, that actually doesn't fix the generated code, but bypasses the issue. SystemJS and RequireJS treats duplicated module definition differently, SystemJS overwrites first definition, RequireJS ignores second definition.

So with RequireJS, it ignores `define("@fortawesome/fontawesome-svg-core/index.es", ["fa"], function(m){return m;});`.

I am not sure how much I can do with rjs parser. It doesn't do proper scope analysis so it doesn't know where a `define()` call is really calling global AMD define func or local define func. I have another WIP bundler project (independent of cli) which does fix this find of code analysis issue.

The other possible fix is to send forawesome a PR to rename their local `define` call to something else like `_define`. I might do that.

**Comment by Alexander-Taran** [comment]
I think it would be a good call on FA guys to rename the function
define is pretty much a keyword in js world

**Comment by huochunpeng** [comment]
Check the fa issue, they will rename it.

**Comment by Alexander-Taran** [comment]
@AquilaSands you can close this one and track FA issue. Meanwhile using the workaround provided.
Thanks

**Comment by AquilaSands** [comment]
@huochunpeng Thanks for the workaround that allowed us to move a skeleton based project to the CLI which is so much nicer to use 👍

@Alexander-Taran will do, thanks.

**Comment by huochunpeng** [comment]
Note this is now fixed in font-awesome v5.7.1.
