### ISSUE TITLE
Running jest fails when adding bootstrap, popper.js  (navigator is undefined)

### ISSUE THREAD

**Issue by shahabganji** [aurelia/cli#1018]
Hello guys, 

I have added bootstrap and wanted to start unit testing with jest, then I faced the following issue:

![image](https://user-images.githubusercontent.com/4405518/51235825-b9cbd980-1985-11e9-9462-92b1acd7b129.png)

I think this is due to the fact that popper has been used with bootstrap, so after investigating through this error we find that the issue will be resolved if we add the following lines [here](https://github.com/aurelia/cli/blob/cb78d99a79d721e841fa4ddf4a648314edd1db97/lib/commands/new/buildsystems/general/unit-test-runners/jest.js#L29) and/or [here](https://github.com/aurelia/cli/blob/cb78d99a79d721e841fa4ddf4a648314edd1db97/lib/commands/new/buildsystems/general/unit-test-runners/jest.js#L67).

```json
"jest": {
...
 "globals": {
      "navigator": {
        "userAgent": "node.js"
      }
    },
...
```

[here](https://stackoverflow.com/questions/37078882/mocha-chai-throws-navigator-not-defined-due-to-react-router-component#comment94967911_37084875) is a stackoverflow thread pointing to the solution.

**Comment by huochunpeng** [comment]
jest by default simulate a browser env which provides navigator as one of the global variables.

But Aurelia did something special to turn off the default.
1. it switches the default jest env to node, in your package.json, you can find
```js
"jest": {
  "testEnvironment": "node",
}
```
2. it uses special aurelia-pal-nodejs instead of normal aurelia-pal-browser, you can find in `test/jest-pretest.js`
```js
import {globalize} from 'aurelia-pal-nodejs';
globalize();
```

## The truth is, we don't need to do that.

Try this:
1. remove `"testEnvironment": "node",` from package.json
2. update `test/jest-pretest.js` to this:
```js
import 'aurelia-polyfills';
import {Options} from 'aurelia-loader-nodejs';
import path from 'path'; // this line will be different is you use TS
Options.relativeToDir = path.join(__dirname, 'unit');

// aurelia-pal-nodejs is what you see from some
// reference aurelia jest setup.
// To use aurelia-pal-nodejs, you need
// testEnvironment: "node" in jest.config.js

// import {globalize} from 'aurelia-pal-nodejs';
// globalize();

// jest actually can work with aurelia-pal-browser
// by default.
import {initialize} from 'aurelia-pal-browser';
initialize();
```

It worked for me on a small app. Let's see whether it works on bigger scale.

**Comment by shahabganji** [comment]
@huochunpeng 

Thanks for your reply, I'll test that and will let you know of the results.

These lines on `test/jest-pretest.ts` can also be used to tackle the issue:

```ts
import 'aurelia-polyfills';
import {Options} from 'aurelia-loader-nodejs';
import {globalize} from 'aurelia-pal-nodejs';
import * as path from 'path';

// @ts-ignore
 global.navigator = {
   userAgent: 'node.js'
};

Options.relativeToDir = path.join(__dirname, 'unit');
globalize();
```
