### ISSUE TITLE
Beta Version Marked Latest in NPM

### ISSUE THREAD

**Issue by TonyLugg** [aurelia/cli#1025]
The latest beta (11 today) is marked as "latest" in NPM.  This results in the beta version being installed if one doesn't request the latest stable version with `@0.35.1`.  If requesting `@latest`, shouldn't the latest stable version get installed instead of the latest beta version?  Or are you recommending using the beta for production development?

**Comment by huochunpeng** [comment]
Based on semver, 0.35.1 before 1.0 is not stable either.
Practically our v1 beta should be stabler then the old version with more bug fixes.

**Comment by TonyLugg** [comment]
@huochunpeng You are saying there has not yet been a production ready release of Aurelia CLI even though we are using it to build production apps?

**Comment by TonyLugg** [comment]
Understood.  Thank you for the detailed explanation.  I am one of the developers that moved to Webpack.  I am keen to try the new built-in bundler, but my application is complex and I don't want to attempt to move it until the new builder is stable (ish).  Keep up the great work.  I love Aurelia.

**Comment by huochunpeng** [comment]
The new bundler is considered quite stable now, we even started pumping in new features for it in these beta versions. You can try it now.

As I said, now some other issues kept cli in beta. The built-in bundler is in good shape.

**Comment by TonyLugg** [comment]
Any way to easily convert from Webpack to built-in, or is it best to just `au new` and copy everything over?

**Comment by huochunpeng** [comment]
Sorry for late reply. Copy over should be easier, especially to avoid add/remove deps in package.json.
