### ISSUE TITLE
[notice] webpack is broken

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/cli#1045]
This affects new webpack based app generated by aurelia-cli.
webpack/webpack#8768

Temporary fix from the thread:

### If you use yarn
add below to package.json

```
  "resolutions": {
    "ajv": "6.8.1"
  }
```
then run `yarn install`

### if you use npm
```
npm uninstall ajv
npm install ajv@6.8.1
```

**Comment by fkleuver** [comment]
PR'd a quick fix to ajv, hopefully it's picked up soon https://github.com/epoberezkin/ajv/pull/943

**Comment by huochunpeng** [comment]
Fixed by ajv.
