### ISSUE TITLE
Suggestion for documentation on aurelia.io

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/cli#1050]
On this page https://aurelia.io/docs/cli/cli-bundler/basics#copy-other-files-eg-fonts it explains how to use copyFiles.

It would be useful to also mention that if you need to copy sub-directories you need to be explicit

```
    "copyFiles": {
      "src/locales/en/*": "wwwroot/locales/en",
      "src/locales/fr/*":"wwwroot/locales/fr",
      "node_modules/@fortawesome/fontawesome-pro/webfonts/*": "wwwroot/@fortawesome/fontawesome-pro/webfonts"
    },
```

I've just spent hours trying all variations on
```
copyFiles:{
 "src/locales/** : "wwwroot/locales
}
```

It would also be even more useful if the build throws an exception if it can't find the source files.

**Comment by huochunpeng** [comment]
If you open your local `aurelia_project/tasks/copy-files.ts`, you will see it uses minimatch.

`**` means arbitrary (0 to n) deep folders, it does not match any files.

The correct glob for your copy is:
```
"copyFiles": {
 "src/locales/**/*" : "wwwroot/locales"
}
```

**Comment by jeremy-holt** [comment]
Oh - that must be the only variation I didn't try!
