### ISSUE TITLE
CLI Build target directory change causes Content-Security-Policy errors

### ISSUE THREAD

**Issue by airboss001** [aurelia/cli#1056]
Bug report

CLI version
1.0.0-beta.13

I ran into an issue with a project when I redirected build artifacts to a 'dist' directory to prevent src & root pollution, and to ease files needed to be moved to staging and production as can be seen in the following link:
https://discourse.aurelia.io/t/aurelia-cli-built-in-bundler-recreating-the-dist-folder-for-deployments/2271

This issue is that CSP starts triggering errors such as:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-KpHv3zgivMSB4dPnfYfqMt2lBibsYvM36EdoBBAsfbM='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

So I have discovered how use the base CLI generated template to get this to recreate using the following inputs:
au new
csp-test
3 - custom
3 - builtin bundler Alameda
2 - Typescript
3 - max minification
3 - Sass
2 - Karma
2 - Protractor
1 - VS Code
2 - Navigation
1 - Create
1 - install modules

I then modified aurelia.json as noted in the referenced discourse thread, and built and ran the project.

This is occurring in dev, stage, and prod builds

**Comment by huochunpeng** [comment]
Can you show me the final index.html? Not your local file, view source in browser.

**Comment by huochunpeng** [comment]
Does this help? https://stackoverflow.com/questions/17766817/refused-to-apply-inline-style-because-it-violates-the-following-content-security

**Comment by airboss001** [comment]
No changes to the generated index.html was made or any other .ts or .html,, only change was to aurelia.json.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body aurelia-app="main">
    <script src="scripts/vendor-bundle.js" data-main="aurelia-bootstrapper"></script>
  </body>
</html>
```

**Comment by airboss001** [comment]
As to the link, sure, if you setup your web server to reset the CSP to allow unsafe-inline it works, but this is using 'au run' and it fails to with that message with the default out of the box if you change where the files are place, oddly it works if you don't change the build folder.

**Comment by huochunpeng** [comment]
You missed index.html in dist folder, update copyFiles to add
`"index.html": "dist"`

**Comment by airboss001** [comment]
Gah, missed that due to that infinite loop issue that is not live yet and my copy/paste of those changes.
I have the issue on my full project in stage/prod and was trying to replicate it in a sample project.
I'll close this, till I can get that localized.

Sorry, and thank you.
