### ISSUE TITLE
au build --watch/alameda/typescript - fails to refresh browser

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/cli#1059]
Hi

As requested https://discourse.aurelia.io/t/aurelia-cli-alameda-au-run-as-proxy/2255/15?u=jeremyholt

Thanks
Jeremy

**Comment by 3cp** [comment]
@jeremy-holt adding option `noEmitOnError: true` to gulp-typescript can avoid sending broken js to bundler.
