### ISSUE TITLE
(Suggestion) Rename custom_typings to types

### ISSUE THREAD

**Issue by michaelw85** [aurelia/cli#1061]
**I'm submitting a change request**

* **Library Version:**
cli latest

* **Operating System:**
N/A

* **Node Version:**
N/A

* **NPM Version:**
N/A

* **Browser:**
all 

* **Language:**
TS

* **Loader/bundler:**
Webpack

**Current behavior:**
Additional typing are placed in a folder called `custom_typings`

* **What is the requested behavior?**
Place typings in a folder called `types`

* **What is the motivation / use case for changing the behavior?**
If you use vscode to auto generate a typing it will place it in a folder called `types` and automatically updated the tsconfig for you. Not sure if this is a standard for placing custom typings but it would be nice to match vscode's preferred location.

Please let me know your thoughts, if you agree I can implement this small change.

**Comment by zewa666** [comment]
I recently discovered said functionality in Vscode. I agree that it makes sense to rename to "types" to stay in line with VSCode, allthough this is no strict standard.

**Comment by michaelw85** [comment]
@zewa666 Added a PR changing the folder name.
