### ISSUE TITLE
Sourcemaps producing absolute paths for html and json files in bundles (1.0.0-beta13)

### ISSUE THREAD

**Issue by salminio** [aurelia/cli#1063]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta13

**Please tell us about your environment:**
* **Operating System:**
Windows  10

* **Node Version:**
10.0.0

* **NPM Version:**
6.8.0

* **Browser:**
chrome

* **Language:**
ESNext

* **Loader/bundler:**
RequireJS

**Current behavior:**
Trying to generate a code coverage report for my app and the remap-instanbul is failing and as best I can tell it's because the generated map file has absolute paths for html and json... Js file references are fine. Remap logic goes into an infinite loop trying to resolve. Below is a sample of the first two lines. (I should mention that sourceMaps seem to be working fine for js files in chrome dev tools).
```
{"version":3,"sources":["app.js","c:/Users/kminio/src/tw-composer/app/composer-worx/src/app.html","destination-config.js","environment.js","main.js","resources/index.js","views/analytics/analytics-main.js","c:/Users/kminio/src/tw-composer/app/composer-worx/src/views/analytics/analytics-main.html","views/analytics/mashup-analytics.js","c:/Users/kminio/src/tw-composer/app
```

* **What is the expected behavior?**
Coverage report runs.

* **What is the motivation / use case for changing the behavior?**
It looks like it might have been addressed in the past - https://stackoverflow.com/questions/40923744/how-can-i-remove-absolute-paths-of-html-files-in-sourcemap-for-aurelia-cli-proje. Maybe with the overhaul of the cli this has not yet been identified as an issue. 

app bundle include *.js, *.json and *.html

**Comment by salminio** [comment]
After studying a bit more, I was able to work around this by breaking up my app bundle into 2 separate bundles - one that just includes just js and one that includes html and json... Interestingly enough the non-js bundle didn't even create a source map file.

**Comment by huochunpeng** [comment]
You can try editing your `aurelia_project/tasks/process-markup.js` (and `process-json.js`, `process-json.js`).
```js
gulp.src(project.markupProcessor.source, {sourcemaps: true})
```

We will have the sourcemaps turned on by default after my current refactoring work.

**Comment by 3cp** [comment]
@salminio can you check is this again? It seems fixed in current cli.

**Comment by 3cp** [comment]
Pls reopen if needed.
