### ISSUE TITLE
Navigation App option says Bootstrap v4, installs v3

### ISSUE THREAD

**Issue by jmoerdyk** [aurelia/cli#1073]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.14

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **Yarn Version:**
1.13.0

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
all

**Current behavior:**
The Custom App option for scaffolding with the _Navigation App_ option claims 
>  Add a router and some sample routes, Bootstrap v4 and Font Awesome v4.

But it does not install v4, it installs v3, and the supplied skeleton contain Bootstrap v3 markup.

The `package.json` generated contains the version `"bootstrap": "^3.3.6`

* **What is the expected behavior?**
That the installed version of Bootstrap is v4, and the navigation skeleton files contain bootstrap v4 markup.  Or change  the help text of the option to match the actual installed version.

* **What is the motivation / use case for changing the behavior?**
That the versions contained in the option help text match the installed version.

**Comment by huochunpeng** [comment]
That was my fault. I thought about upgrading the demo code to bootstrap v4, then left it out because the change in PR #1069 is big enough.
