### ISSUE TITLE
Deprecated libraries warnings on scaffolding a new project

### ISSUE THREAD

**Issue by veikkoeeva** [aurelia/cli#1082]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.15

* **Operating System:**
Windows 10

* **Node Version:**
10.9.0

* **NPM Version:**
6.2.0

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
Webpack

**Current behavior:**

* **What is the expected behavior?**
No deprecation warnings when scaffolding a new project.

* **What is the motivation / use case for changing the behavior?**
Deprecation warnings make feel like changing the components immediately upon starting a new project. :) In the following there is a screenshot from a initial project scaffolding situation and NPM prints a warning that 

- Istanbul@0.45 is no longer maintained and one should look at [nyc](https://www.npmjs.com/package/nyc).
- Circular-json@0.5.9 (CircularJson) is in maintenance mode and [flatten](https://www.npmjs.com/package/flatten) is the successor.
![Aurelia-cli scaffolding deprecation warnings](https://user-images.githubusercontent.com/5158694/55530469-efdc4800-56ae-11e9-9d40-dd2746aaa861.png)

**Comment by huochunpeng** [comment]
circular-json can be removed by upgrading karma from 3.1.4 to latest 4.0.1. We will do that.

istanbul is a dep of karma-coverage which has no new version for last year. There is nothing we can do about it unless migrate to another coverage setup for karma. cc @Alexander-Taran

**Comment by Alexander-Taran** [comment]
circular and istanbul are no longer on the list, but some other dependencies are deprecated now
![image](https://user-images.githubusercontent.com/1029452/128890190-fd0b5d42-ffc3-4c54-b2b7-a3e9f22beff3.png)

**Comment by Alexander-Taran** [comment]
@veikkoeeva I don't think npm ecosystem will ever have an evergreen day now.
Transitive dependencies can use outdated dependencies and still get the job done.

@3cp can be closed, I think.

**Comment by 3cp** [comment]
We have dependency on gulp v4 which introduces many stale dependencies. Unfortunately gulp is not as actively maintained as we expect despite its huge user base.
