### ISSUE TITLE
SASS does not get extracted to CSS for production

### ISSUE THREAD

**Issue by arjendeblok** [aurelia/cli#1083]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.15

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.13..0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript

* **Loader/bundler:**
Webpack 

* **Current behavior:**
When running a build for production, CSS is extracted to .CSS files, but SASS files do not get extracted.

* **What is the expected behavior?**
That SASS and CSS are both extracted to .CSS files.

* **What is the motivation / use case for changing the behavior?**
For production all CSS should be in seperate files.

**Comment by CollinHerber** [comment]
This is probably the biggest annoyance with the current beta build of the CLI. Please fix this!

**Comment by huochunpeng** [comment]
If someone can clean up the webpack config, we would love to merge it.

For requirejs build, I am not sure whether we need to seperate css files. Currently css files are bundled in as a wrapped text module. We could use seperate css files for requirejs to do dynamic loading at runtime, requirejs/systemjs supports that. But it creates additional burden for app deployer to maintain correct requirejs baseUrl setting.

Another thing devs can do, is to totally avoid `import "some.css"` and `<require from="some.css"></require>`. Use traditional `<style>` tag to load css, it means you compile all css asserts outside of webpack config (or cli-bundler). The traditional way actually simplifies the toolchain setup, what you lose is per component css file and style on demand.

**Comment by arjendeblok** [comment]
I will have a look and make a pull request.

The last thing that you mention is not a solution for SASS files. Or if you use a third party component library that uses SASS.

**Comment by arjendeblok** [comment]
Problem solved with merge.
