### ISSUE TITLE
when to set baseurl

### ISSUE THREAD

**Issue by tomsean** [aurelia/cli#109]
aurelia cli  in my project ,bundle sucess ,but template not work .Aureliafile in root of project,and my src is in www folder.if i use template: {
        'www/app-bundle': {
            pattern: 'www/*.html',
            options: {
                inject: true
            }
        }
    },
it is bundle ,but in app-bundle.html file,<template id="www/welcome.html!view">,   should be <template id="welcome.html!view">.

**Comment by ahmedshuhel** [comment]
@tomsean template bundling was not in the last release. Update the cli to the latest release. It should work now.

**Comment by tomsean** [comment]
yes,it is work,thanks
