### ISSUE TITLE
Build Error TS4090 when using Protractor

### ISSUE THREAD

**Issue by MichaelPetrinolis** [aurelia/cli#1090]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.15

* **Operating System:**
Windows [10]

* **Node Version:**
v10.15.0

* **NPM Version:**
6.4.1

* **Browser:**
Chrome 73 

* **Language:**
TypeScript 3.4

* **Loader/bundler:**
Webpack

**Current behavior:**
au run returns
[tsl] ERROR
      TS4090: Conflicting definitions for 'q' found at 'xxx/node_modules/@types/q/index.d.ts' and 'xxx/node_modules/protractor/node_modules/@types/q/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
* **What is the expected behavior?**
should compile

* **What is the motivation / use case for changing the behavior?**
the OOB experience should be succesful

if define typesRoots in tsconfig.json the problem is solved

    "typeRoots": ["./node_modules/@types"]

**Comment by huochunpeng** [comment]
I could not reproduce this issue. But I encountered another typing issue with latest TypeScript even without protractor, just with default webpack typescript jest app.
```
ERROR in /Users/huocp/playground/w3/test/unit/app.spec.ts
[tsl] ERROR in /Users/huocp/playground/w3/test/unit/app.spec.ts(5,1)
      TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
```

**Comment by huochunpeng** [comment]
typeRoots also solves the issue I saw. I will get the fix in.

**Comment by zewa666** [comment]
Can you remove your dependency on @types/q? Protractor is going to provide it anyways

**Comment by MichaelPetrinolis** [comment]
@zewa666 i tried to remove @types/q but it cannot be removed, it exists in the package-lock probably is a dependency. You must manualy remove the conflicting @types/xxx from protractor/node_modules in order the au build to work

**Comment by huochunpeng** [comment]
For reference, @MichaelPetrinolis noticed the issue can be reproduced with
```
au new testapp -u -s http2,typescript,htmlmin-max,sass,postcss-typical,karma,protractor,vscode
```

The conflicting @types/q is from cssnano (by selecting postcss-typical).
```
⋊> ~/p/testapp npm list @types/q
testapp@0.1.0 /Users/huocp/playground/testapp
├─┬ cssnano@4.1.10
│ └─┬ cssnano-preset-default@4.0.7
│   └─┬ postcss-svgo@4.0.2
│     └─┬ svgo@1.2.2
│       └─┬ coa@2.0.2
│         └── @types/q@1.5.2 
└─┬ protractor@5.4.2
  └── @types/q@0.0.32 
```

**Comment by Krossmaskinen** [comment]
I downloaded aurelia cli fresh today, created a project with typescript using protractor. Got the same message.

**Comment by MichaelPetrinolis** [comment]
Aurelia Cli is still in beta 15 so the fix for protractor with cssnano is not included. What options do you use to create the new project? What error do you get?

**Comment by jmzagorski** [comment]
the commit attached this issue adding the `typeRoots` does not seem to fix this issue for any typescript project built with the cli.

The change to `ts-loader` in `webpack.config.js` will fix it, referenced in https://github.com/aurelia/cli/pull/1091/commits/36d384ec985ee197c27ac115e7d9722d0d2f4a0f
