### ISSUE TITLE
VS Code F5 Debug starts Chrome, loads page and closes chrome

### ISSUE THREAD

**Issue by MichaelPetrinolis** [aurelia/cli#1092]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.15

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
10.15.3

* **NPM Version:**
6.2.0

* **Browser:**
Chrome 73

* **Language:**
TypeScript 3.4

* **Loader/bundler:**
Webpack

**Current behavior:**
create new webpack project
au run
F5 from vscode
chrome opens, displays app and closes

OS: win32 x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.7.45
debugger-for-chrome: 4.11.3
got chrome PID: 8388
Got browser version: Chrome/73.0.3683.103
Got debug protocol version: 1.3
.......
Terminated: Got disconnect request
Waiting for any pending steps or log messages.
Killing Chrome process by pid: taskkill /PID 8388
Looking up process by pid: tasklist /FI "PID eq 8388" /FO CSV
Chrome process with pid 8388 is still alive, waiting...
To client: {"seq":0,"type":"response","request_seq":7,"command":"disconnect","success":true}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/disconnect","data":{"Versions.DebugAdapterCore":"6.7.45","Versions.DebugAdapter":"4.11.3","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@e82a658d8159cabbd4938c1660f9bb00b4a82a23","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36","Versions.Target.V8":"7.3.492.27","Versions.Target.Project":"Chrome","Versions.Target.Version":"73.0.3683.103","successful":"true","timeTakenInMilliseconds":"496.3303","requestType":"request"}}}
Current step and log messages complete
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"Versions.DebugAdapterCore":"6.7.45","Versions.DebugAdapter":"4.11.3","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@e82a658d8159cabbd4938c1660f9bb00b4a82a23","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36","Versions.Target.V8":"7.3.492.27","Versions.Target.Project":"Chrome","Versions.Target.Version":"73.0.3683.103","reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"event","event":"terminated"}

* **What is the expected behavior?**
VSCode should start a debug session with chrome

Project previously created with 1.0.0-beta.14 works as expected. Also Aurelia Bundler works as expected

**Comment by MichaelPetrinolis** [comment]
Found who to blame :)
I use VS Code 1.33.1 , rolled back to 1.29.1 and F5 debugging works just fine.
VSCode auto updated to latest version, and after reopening IDE the same project does not work. So it seems to be an issue with VSCode, neither aurelia-cli/webpack nor vscode-chrome-adapter unless there is some special option that i did not find...

**Comment by MichaelPetrinolis** [comment]
I close the issue, a quick fix for anyone else facing the same bug is to set VSCode's update.mode to manual/none and downgrade to a previous version.

**Comment by huochunpeng** [comment]
Is there any related issue on vs code repo?

**Comment by MichaelPetrinolis** [comment]
Could not find something similar. Tried Code Insider, and issue still exists.

**Comment by MichaelPetrinolis** [comment]
After VSCode 1.32.3 something causes the 'cheap-module-eval-source-map' to terminate the chrome debug session.
