### ISSUE TITLE
Error trying to bundle

### ISSUE THREAD

**Issue by lukeapage** [aurelia/cli#110]
I am trying to follow your instructions for bundling but no matter what I do I get

```
info: Using Aureliafile: c:\path\to\Aureliafile.js
info: Creating bundle ...

c:\path\to\node_modules\aurelia-cli\dist\lib\bundler.js:204
  if (!pathMatch) throw 'Unable to calculate path for ' + address;
                                                        ^
Unable to calculate path for file:c:/path/to/app.js
```

I am using a branch for aurelia-skeleton-navigation and copied your aurelia file from the readme..

```
var aurelia = require('aurelia-cli');

aurelia.command('bundle', {
  js: {
    app: {
      modules: [
        'src/*',
      ],
      options: {
        inject: true
      }
    },
    'aurelia-bundle': {
      modules: [
        "aurelia-dependency-injection"
      ],
      options: {
        inject: false
      }
    }
  },
  template: {
    app: {
      pattern: 'dist/*.html',
      options: {
        inject: true,
      }
    }
  }
});
```

I've been deleting and modifying things but no matter what I do, I seem to always get the same error  (If I remove the app module, it errors on aurelia-bundle).

Given the error is on the name of the property in the js and it seems to have already resolved a path, I have no idea what to do to fix it.

If this is my mistake, sorry, but perhaps the error could be better in this scenario?

**Comment by lukeapage** [comment]
aha, if I change it to..

```
var aurelia = require('aurelia-cli');

aurelia.command('bundle', {
  js: {
    'dist/app': {
      modules: [
        'src/*',
      ],
      options: {
        inject: true
      }
    },
    'dist/aurelia-bundle': {
      modules: [
        "aurelia-dependency-injection"
      ],
      options: {
        inject: false
      }
    }
  },
  template: {
    app: {
      pattern: 'dist/*.html',
      options: {
        inject: true,
      }
    }
  }
});
```

it now works. so perhaps the example should have paths? and the cli shouldn't throw an error if you want the bundles in your root directory?

**Comment by ahmedshuhel** [comment]
The readme has become a little outdated. We need to fix it. We will do that. A post on bundling will be published soon explaining all the details.

**Comment by nitech** [comment]
@ahmedshuhel Any post on bundling published yet? I'm struggelig a bit with this one too, and @lukeapage's fix doesn't solve my issue.

**Comment by EisenbergEffect** [comment]
On the official blog. New content usually every week there :) http://blog.durandal.io/

**Comment by nitech** [comment]
Ah, yes. Of course. Thanks @EisenbergEffect

**Comment by nitech** [comment]
Hm. Still not having success here. This is my aurealiafile.js: 

```javascript
var aurelia = require("aurelia-cli");

aurelia.command("bundle", {
    js: {
        "wwwroot/app-bundle": {
            modules: [
                "wwwroot/app/*",
                "aurelia-bootstrapper",
                "aurelia-framework",
                "aurelia-router",
                "aurelia-http-client",
                "aurelia-validation"
            ],
            options: {
                inject: true,
                minify: true
            }
        }
    },
    template: {
        "wwwroot/app-bundle": {
            pattern: "app/**/*.html",
            options: {
                inject: true
            }
        }
    }
});
```

And my project structure looks like the following: 
```
aureliafile.js
- wwwroot
    - app
       - app.js
       - app.html
    - config.js
    - index.html
 ...
```

And this is the beginning of my config.js
```javascript
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "es7.decorators",
      "es7.classProperties",
      "runtime"
    ]
  },
  "paths": {
    "*": "app/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
  "buildCSS": false
});
```

**Comment by lukeapage** [comment]
> Still not having success here.

What is going wrong?

I wrote up my experiences and a couple of gotchas whilst adding bundling here: http://blog.scottlogic.com/2015/06/29/aurelia-part-two.html

Maybe something will help.

**Comment by nitech** [comment]
Thank you @lukeapage, and forgive me if my post was confusing. I was in a rush going out of the office :-) 

I get the same error message as you got: 

```
C:\top-secret\nsa\nsa-citizen-aurelia-control\src\nsa-citizen-aurelia-control>aurelia bundle
info: Using Aureliafile: C:\top-secret\nsa\nsa-citizen-aurelia-control\src\nsa-citizen-aurelia-
control\aureliafile.js
info: Creating bundle ...

C:\top-secret\nsa-\nsa-citizen-aurelia-control\src\nsa-citizen-aurelia-control\node_module
s\aurelia-cli\dist\lib\bundler.js:204
  if (!pathMatch) throw 'Unable to calculate path for ' + address;
                                                        ^
Unable to calculate path for file:C:/top-secret/nsa/nsa-citizen-aurelia-control/src/nsa-citiz
en-aurelia-control/wwwroot/wwwroot/app-bundle.js
```
If I modify `aureliafile.js` so that `"wwwroot/app-bundle"` becomes `"app-bundle"` I still get the error message. 

I will read your gotchas and see if I can spot any mistake.
