### ISSUE TITLE
aurelia-cli v1.0.0-beta.15 - .NET Core, Webpack, TypeScript - broken

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/cli#1107]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.15

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **NPM Version:**
6.4.1

* **Yarn Version:**
1.16.0

* **Browser:**
all 

* **Language:**
TypeScript 3.4.5

* **Loader/bundler:**
Webpack

**Current behavior:**
After creating new CLI project with following options:
Global aurelia-cli v1.0.0-beta.15
```
                      _ _          ____ _     ___
  __ _ _   _ _ __ ___| (_) __ _   / ___| |   |_ _|
 / _` | | | | '__/ _ \ | |/ _` | | |   | |    | |
| (_| | |_| | | |  __/ | | (_| | | |___| |___ | |
 \__,_|\__,_|_|  \___|_|_|\__,_|  \____|_____|___|

√ Would you like to use the default setup or customize your choices? · Custom App
√ Which bundler would you like to use? · Webpack
√ Which HTTP Protocol do you wish the outputted Webpack bundle to be optimised for? · HTTP/1.1
√ What platform are you targeting? · .NET Core
√ What transpiler would you like to use? · TypeScript
√ How would you like to setup your HTML template? · Minimum Minification
√ What css preprocessor would you like to use? · Sass
√ Do you want to add PostCSS processing · Typical
√ Which unit test runner would you like to use? · Jest
√ Would you like to configure integration testing? · Protractor
√ What is your default code editor? · Visual Studio Code
√ Which features do you want scaffolded into your project? · Navigation App

 Getting started
Now it's time to get started. It's easy.
Simply run your new app in dev mode with  dotnet run .
If you want to build your app for production, run  au build --env prod .
If you need help, simply run  au help .
```

Project is unable to start using `dotnet run` or running `Debug` in Visual Studio.
Issues are:

- Index.cshtml and _Layout.cshtml have wrong link references to scripts and css files.
- TypeScript UnitTests using Jest+Mocka failing to compile (even after adding  @types/jest` or ` @types/mocha`)

* **What is the expected behavior?**
Project works correctly out of the box

* **What is the motivation / use case for changing the behavior?**
We need more working projects out of the box when using Aurelia CLI

**Comment by 3cp** [comment]
This should be fixed on master.

Can you try latest github master branch with?

```
npx aurelia/cli new —here
```

**Comment by rusch1981** [comment]
```
Global aurelia-cli v1.0.0-beta.15
                      _ _          ____ _     ___
  __ _ _   _ _ __ ___| (_) __ _   / ___| |   |_ _|
 / _` | | | | '__/ _ \ | |/ _` | | |   | |    | |
| (_| | |_| | | |  __/ | | (_| | | |___| |___ | |
 \__,_|\__,_|_|  \___|_|_|\__,_|  \____|_____|___|

√ Please enter a name for your new project: · AuCore
√ Would you like to use the default setup or customize your choices? · Custom App
√ Which bundler would you like to use? · Webpack
√ Which HTTP Protocol do you wish the outputted Webpack bundle to be optimised for? · HTTP/1.1
√ What platform are you targeting? · .NET Core
√ What transpiler would you like to use? · TypeScript
√ How would you like to setup your HTML template? · Minimum Minification
√ What css preprocessor would you like to use? · Sass
√ Do you want to add PostCSS processing · None
√ Which unit test runner would you like to use? · None
√ Would you like to configure integration testing? · None
√ What is your default code editor? · Visual Studio Code
√ Which features do you want scaffolded into your project? · Navigation App
```
Same issue for me.

**Comment by 3cp** [comment]
What’s your dotnet core version?

**Comment by 3cp** [comment]
Can one of you try latest master branch?

**Comment by arjendeblok** [comment]
This issue was reported before. It is solved in the 1.0.0 release. So please update the CLI.

**Comment by nenadvicentic** [comment]
@arjendeblok with aureli-cli v1.0.0 this is working!

However, I am not sure now how to run protractor tests? Documentation states:

> However, Protractor is a bit different. It has to be started through nps, so make sure that you've  installed that globally (npm install nps -g). Afterwards, run nps e2e to start Protractor.

But when I do what is described above I get exception "Unable to find a config file and none was specified". `nps` version is 5.9.5.

**Comment by 3cp** [comment]
Check the generated readme.

au protractor

**Comment by nenadvicentic** [comment]
@3cp Yes, that worked. 

Two command lines, `au run` in the first one and then  `au protractor` in the second one.

Thanks!

**Comment by 3cp** [comment]
@nenadvicentic pls close if it's resolved, thx.
