### ISSUE TITLE
Unable to load package metadata (package.json) of ...

### ISSUE THREAD

**Issue by m0ngr31** [aurelia/cli#1109]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.15

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 18.04)

* **Node Version:**
8.11.3

* **NPM Version:**
5.6.0

* **Browser:**
Firefox 67

* **Language:**
TypeScript 3.1.2

* **Loader/bundler:**
Gulp

**Current behavior:**
Developing an AU plugin right now. Trying to use mapped paths but having issues doing imports:

```
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of helpers:                                                                                                                                                     
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "helpers"
ERROR [Bundler] Unable to analyze helpers
INFO [Bundler] Error: Unable to find package metadata (package.json) of helpers
ERROR [Bundler] Failed to add Nodejs module helpers/copy-to-clipboard
```

That's when I try to do something like `import {copyToClipboard} from 'helpers/copy-to-clipboard';`

My aurelia.json file looks like this: 

```
"paths": {
  "root": "dev-app",
  "resources": "../src",
  "elements": "../src/elements",
  "attributes": "../src/attributes",
  "helpers": "../src/helpers",
  "valueConverters": "../src/value-converters",
  "bindingBehaviors": "../src/binding-behaviors"
},
```

It seems to compile fine, but I get that in the console when it's `INFO [Bundler] Tracing files ...`. Browser seems to 404 on all of those files as well.

Full console output: https://pastebin.com/raw/80qcSiTE

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Would be nice to do imports from a mapped path.

**Comment by 3cp** [comment]
I got no problem with your setup. I only see the error if I remove `"helpers": "../src/helpers",` from `aurelia.json`, can you share a small sample repo to reproduce it?

**Comment by 3cp** [comment]
Can you try `au clear-cache`? It might cached tracing result before you add that line to aurelia.json.

**Comment by m0ngr31** [comment]
Yeah I've tried that a few times with no luck. I ended up fixing it by setting up a new plugin with cli and copying the files over what I had and it worked. So something got messed up, not sure which considering the git diff was pretty minimal.

**Comment by 3cp** [comment]
Can you close this one for now? You can reopen it when you find the condition to replicate the error.
