### ISSUE TITLE
view bundle injection occurs twice if you rename the bundle name

### ISSUE THREAD

**Issue by lukeapage** [aurelia/cli#111]
If you have view bundling configured to inject and decide to change the name, it injects a new bundle with the new name to index.html, but does not remove the old one.

Its a minor issue, but I thought you might want to fix it.

**Comment by ahmedshuhel** [comment]
Yes we would like to fix it. Thanks for reporting.

**Comment by ahmedshuhel** [comment]
@lukeapage we have  `unbundle` command now which will clean any injection including invalids.
