### ISSUE TITLE
VSCode launch.json has incorrect extension for new projects using the cli bundler 

### ISSUE THREAD

**Issue by AquilaSands** [aurelia/cli#1113]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows10

* **Node Version:**
12.3.1

* **NPM Version:**
6.9.0

* **Browser:**
n/a

* **Language:**
all

* **Loader/bundler:**
RequireJS

**Current behavior:**
Creating a new app or plugin which uses the built in cli bundler and VSCode as the editor places the file launch.json_if_cli-bundler in the .vscode directory. This cause VSCode debugging to not find the config until it is renamed to launch.json

* **What is the expected behavior?**
The file has the correct extension `.json`

* **Steps to reproduce.**
   * Use `au new` to scaffold a new app or plugin using the custom option
   * Ensure that the built in cli bundler and VSCode are selected
   * The resulting .vscode directory will have the incorrectly named launch.json 

* **What is the motivation / use case for changing the behavior?**
Debugging in VSCode should just work

**Comment by 3cp** [comment]
My bad. Will fix the file name.
