### ISSUE TITLE
Potentially unhandled rejection [6] Error: Error loading "aurelia-cli"

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/cli#112]
Created a new project (cherry picked bits and all working) and followed the blog post. Aurelia bundle starts to work, then I get this: 
```
D:\Code\Test>aurelia bundle
info: Using Aureliafile: D:\Code\Test\aureliafile.js
info: Creating bundle ...
Potentially unhandled rejection [6] Error: Error loading "aurelia-cli" at file:D:/Code/Test/aurelia-cli.js
Error loading "aurelia-cli" from "aureliafile" at file:D:/Code/Test/aureliafile.js
ENOENT, open 'D:\Code\Test\aurelia-cli.js'
    at Error (native)
```

Installed both locally and globally. with and without admin console. 

On Windows 8.1, npm 2.11.2. 

```
"dependencies": {
    "aurelia-cli": "^0.21.",
    "body-parser": "~1.8.1",
    "bootstrap-sass": "^3.3.5",
    "browser-sync": "latest",
    "cookie-parser": "~1.3.3",
    "debug": "~2.0.0",
    "del": "latest",
    "express": "~4.9.0",
    "gulp": "latest",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-babel": "latest",
    "gulp-changed": "latest",
    "gulp-jade": "latest",
    "gulp-minify-css": "^1.1.6",
    "gulp-nodemon": "^2.0.3",
    "gulp-plumber": "latest",
    "gulp-rename": "latest",
    "gulp-sass": "latest",
    "gulp-sourcemaps": "latest",
    "require-dir": "latest",
    "run-sequence": "latest",
    "vinyl-paths": "latest"
  },
```

![](http://i.imgur.com/9EfOB70.png)

global installs:

![](http://i.imgur.com/fLDvwaN.png)

**Comment by ngib** [comment]
Same error message here. 

Windows 7, npm 2.7.4

**Comment by decademoon** [comment]
Same error message for me.

Mac OS X 10.10.3, iojs 2.3.1, npm 2.11.3

**Comment by decademoon** [comment]
Ok I figured it out. In my config.js, I had mapped "*" to "*.js" instead of the default "dist/*.js". This means that when I specified "*" as module to bundle in my aureliafile.js, it would try to bundle all files in my project root directory, including the aureliafile.js itself. Jspm will then parse aureliafile.js for dependencies, and try to resolve the require('aurelia-cli'), which causes it to fail.

So I changed "*" in my aureliafile.js to "scripts/*" (this is specific to my project; I keep all of my modules organized in this folder).

**Comment by MeirionHughes** [comment]
Good to know. A little unfortunate though. I don't serve my files from the root. I serve directly from dist. I then have a mapping in the static serve for jspm_packages. I guess I'll have to go back to serving from root. :(

**Comment by MeirionHughes** [comment]
Nope... its not fixed; Builds okay, but it bombs out trying to load it. 

My issue stems from NOT serving the root folder. In express I have: 
```
app.use('/config.js', function (req, res) { res.sendFile(path.join(__dirname, 'config.js'));});
app.use('/jspm_packages', express.static(path.join(__dirname, 'jspm_packages')));
app.use(express.static(path.join(__dirname, paths.output)));
```
so the content is accessable like: `domain.com/somefile.js` rather than `domain.com/dist/somefile.js`

so for now, I have to go back to bundling `dist/*`. I HAVE to keep
```
"paths": {
    "*": "dist/*.js",
```
for the bundling process... but now I'm back to jspm making requests to `domain.com/dist/somefile.js`. 

Ideally, it would be nice to have an exclusion like: 
```
 js: {
      "dist/app-bundle": {
        modules: [
          '!aureliafile.js',
          '*',
```

**Comment by MeirionHughes** [comment]
Original issue on this is resolved. Added new one for the mapping problem https://github.com/aurelia/cli/issues/116
