### ISSUE TITLE
Please remove editorconfig from the cli defaults

### ISSUE THREAD

**Issue by mattgaspar** [aurelia/cli#1121]
**I'm submitting a feature request**

* **Library Version:**
aurelia-cli v1.0.0-beta.13

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Editor:**
VSCode

* **Request:**
Please consider not generating a .editorconfig file by default.  It was overriding my VSCode settings and caused a lot of confusion!  
I thought it was a bug in VSCode that was not detecting my indentation size and line endings until I was finally able to track it down to the editorconfig file that the Aurelia CLI created.

**Comment by 3cp** [comment]
Understand, what I will do is to not overwrite existing file if there is any. Will fix it in coming patch release.
