### ISSUE TITLE
add file versioning ability 

### ISSUE THREAD

**Issue by devmondo** [aurelia/cli#113]
the bundling is great, but as you browsers tend to cache things aggressively if we dont change the files names, so adding ability for the bundler to version bundle file name will make this issue go away and we wont risk our users loading outdated files.

thanks in advanced.

**Comment by BlueHayes** [comment]
:+1:

**Comment by ahmedshuhel** [comment]
:+1:  This can be nice feature for the next release.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect Do you think this will be useful for bundle files?

**Comment by devmondo** [comment]
@ahmedshuhel if you guys dont see it useful, ( while i see it very important)  we can solve this easily with gulp once CLI can be used from there

**Comment by Aaike** [comment]
cache bustom is already supported with jspm : https://github.com/aurelia/framework/issues/94 
it should work for bundled files also.

**Comment by amitaibu** [comment]
@Aaike I'm not sure cache busting is always enough. Sometimes the cache isn't invalidated in CDN's just by a query parameter, and then it's useful to have a reved file name (i.e. `app.1234.js` vs `app.js?1234`)

**Comment by devmondo** [comment]
@Aaike  i agree with @amitaibu  i have been bitten by query string many times, file name reving is only way to go

**Comment by amitaibu** [comment]
however, we should probably use gulp-rev, rather then baking it directly into the cli.
Although the question, for me, remains -  how to bake it :)

**Comment by EisenbergEffect** [comment]
If there's an underlying library that gulp-rev relies on, we can could require that in our CLI and use it. I haven't investigated though. If not, perhaps we could contact the author and convince or work with them to split it into two pieces or refactor a bit around that scenario.

**Comment by ahmedshuhel** [comment]
I will investigate that.
