### ISSUE TITLE
Files are no longer watched after update from Gulp 4 alpha to v4

### ISSUE THREAD

**Issue by Atfreeman240** [aurelia/cli#1133]
* **Library Version:**
"aurelia-cli": "^0.30.1"

* **Operating System:**
Windows [10]

* **Node Version:**
12.4.0

* **NPM Version:**
6.9.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 1.0.2

* **Browser:**
Chrome v75.0.3770.100

* **Language:**
TypeScript 3.4

**Current behavior:**
The application had no issues before our team switched from the alpha version of Gulp 4 to version 4. After upgrading, files are no longer being watched and changes are not reflected in the browser until the project is re-built and run. However, the code for the watch _is_ being hit (we used console.log to check) - it's just not actually watching anything. 

Has anyone else run into this?

**Expected/desired behavior:**
Files are being watched and updated in the browser as changes are made to the code.

Below is the run.ts file that was previously functioning:

```import * as gulp from 'gulp';
import * as browserSync from 'browser-sync';
import * as historyApiFallback from 'connect-history-api-fallback/lib';
import * as project from '../aurelia.json';
import build from './build';
import { CLIOptions } from 'aurelia-cli';


function onChange(path) {
  console.log(`File Changed: ${path}`);
}

function reload(done) {
  browserSync.reload();
  done();
}

let serve = gulp.series(
  build,
  done => {
    browserSync({
      online: false,
      open: true,
      port: 4747,
      logLevel: 'silent',
      server: {
        baseDir: ['.'],
        middleware: [historyApiFallback(), function (req, res, next) {
          res.setHeader('Access-Control-Allow-Origin', '*');
          next();
        }]
      }
    }, function (err, bs) {
      let urls = bs.options.get('urls').toJS();
      console.log(`Application Available At: ${urls.local}`);
      console.log(`BrowserSync Available At: ${urls.ui}`);
      done();
    });
  }
);

let refresh = gulp.series(
  build,
  reload
);


let watch = function () {
  console.log("In Watch")
  gulp.watch(project.transpiler.source, refresh).on('change', onChange);
  gulp.watch(project.markupProcessor.source, refresh).on('change', onChange);
  gulp.watch(project.cssProcessor.source, refresh).on('change', onChange);
}

let run;

if (CLIOptions.hasFlag('watch')) {
  console.log("Watch Called")
  run = gulp.series(
    
    serve,
    watch
  );
} else {
  console.log("Watch Skipped")
  run = serve;
}

export default run;
```

**Comment by EisenbergEffect** [comment]
I've moved this to the CLI repo so that @3cp can properly triage.

**Comment by 3cp** [comment]
Looks like your setup didn't use default cli watch task, our default watch is still using gulp-watch, not switched to native gulp.watch yet. But this non-default setup is not an issue, I tried with your run task, it works perfectly here locally on my machine.

Could you try following to help investigation?

1. remove node_modules, package-lock.json or yarn.lock and try reinstall all deps again.

2. if the above didn't help, are you using a network drive or docker for your source code? If so, you can try `gulp.watch(project.transpiler.source, {usePolling: true}, refresh)`. (But I don't know why gulp v4 alpha worked before)

3. try a clean app with `au new`. If that works, move your code over and try.

**Comment by Atfreeman240** [comment]
Thank you very much for the reply! My company's office is closed tomorrow so I will not be able to try your suggestions until this Friday. I will try them and post progress.

**Comment by Atfreeman240** [comment]
Good morning! 
I have tried your suggestions but the result it still the same. The application runs without issue, but files are not being watched. In order to view changes in the browser, I need to build and re-run. I have a couple of follow-up questions:

1. The below line is triggering an error:
`` gulp.watch(project.transpiler.source, refresh).on('change', onChange);
  ``
Error: Property 'transpiler' does not exist on type 'typeof import("*.json")'.ts(2339)

(Each of the gulp.watch lines produce a similar error)

Do you think this could be the culprit?

2. Since the code is working for you locally, can you suggest any other places in a project that could cause the watch function to break?


I apologize if these questions are elementary. This is an older app created by people who no longer work at the company so I don't have a lot of experience with it and am having trouble finding information relevant to this issue online.

**Comment by 3cp** [comment]
Oh, I didn’t try ts project. I think you are a victim of typing:-)

Try `project['transpiler']['source']`.

If this is the case, it’s due to your jump on TypeScript version.

**Comment by Atfreeman240** [comment]
Thank you for your reply today! I am only able to work on this project while I am in the office, so I will be working on this next week. I appreciate your responses and will try your suggested code :)

**Comment by Atfreeman240** [comment]
Good morning! Unfortunately nothing I've tried has worked so far. This app was created a while ago so I'm thinking the problem lies elsewhere and not in the run.ts file. I'll continue working on the issue but will also leave the existing package.json dependencies here (leaving out the company specific stuff at the beginning). 
I've tried using newer versions of things like Typescript, Aurelia CLI, and Gulp, but that just comes with it's own issues. 

Since the app _works_ this is not a priority issue, but still something we'd like to fix eventually.
If anyone sees any deps that might be causing the issue, please let me know. 
Thank you for all of your responses and suggestions!

```{
  "license": "MIT",
  "scripts": {
    "gulp": "./node_modules/gulp/bin/gulp.js",
    "test": "au test"
  },
  "dependencies": {
    "aurelia-animator-css": "^1.0.0",
    "aurelia-bootstrapper": "^1.0.0",
    "aurelia-configuration": "^1.0.17",
    "aurelia-dialog": "^1.0.0-rc.1.0.2",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-http-client": "^1.1.1",
    "aurelia-kendoui-bridge": "^1.0.1",
    "aurelia-notify": "^0.8.1",
    "aurelia-validation": "^1.0.0",
    "bluebird": "^3.4.1",
    "bootstrap": "~3.3.6",
    "jquery": "^2.2.4",
    "kendo-ui-core": "^2016.3.1118",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "msal": "0.2.2",
    "numeral": "^2.0.6",
    "tslib": "^1.9.3"
  },
  "peerDependencies": {},
  "devDependencies": {
    "@types/jasmine": "^2.5.38",
    "@types/lodash": "^4.14.110",
    "@types/numeral": "0.0.18",
    "aurelia-cli": "^0.30.1",
    "aurelia-testing": "^1.0.0-beta.2.0.0",
    "aurelia-tools": "^0.2.2",
    "browser-sync": "^2.13.0",
    "connect-history-api-fallback": "^1.2.0",
    "del": "^2.2.2",
    "event-stream": "^3.3.3",
    "font-awesome": "^4.7.0",
    "gulp": "^4.0.0",
    "gulp-changed": "^1.3.2",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-clean-css": "^2.0.13",
    "gulp-cli": "^1.2.2",
    "gulp-concat": "^2.6.1",
    "gulp-flatten": "^0.3.1",
    "gulp-less": "^3.1.0",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-tslint": "^5.0.0",
    "gulp-typescript": "^2.14.1",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-typescript-preprocessor": "^0.2.1",
    "minimatch": "^3.0.2",
    "through2": "^2.0.1",
    "tslint": "^3.11.0",
    "typescript": "^2.1.6",
    "uglify-js": "^2.6.3",
    "vinyl-fs": "^2.4.3"
  },
  "main": "karma.conf.js",
  "directories": {
    "test": "test"
  },
  "author": ""
}`

**Comment by Atfreeman240** [comment]
Update:
The below code works! I had to use paths instead. Now I just need to figure out how to make this work with versioning. We need to have some kind of cleanup- but not to the point where it is erasing all of the bundle files.

  ``gulp.watch('src//**//*.ts', refresh).on('change', onChange);``
  ``gulp.watch('src/**/*.html', refresh).on('change', onChange);``
  ``gulp.watch('src//**//*.less', refresh).on('change', onChange);``


Thank you for your suggestions and comments! 
Since the files are being watched now and versioning is a different issue, I am closing this thread.

**Comment by 3cp** [comment]
You can turn on "rev" on dev in aurelia.json. That will give you unique bundle file names when something changed.

**Comment by Atfreeman240** [comment]
Thank you for your reply! When I turn on rev, code changes do not show up in the browser without cleaning and rebuilding first. I can only get the desired outcome of gulp.watch if rev is set to false.

**Comment by 3cp** [comment]
Something is not right. I guess it's better for you to just create a clean `au new` project and move code over.
