### ISSUE TITLE
au run --watch doesn't pick up changes from linked scss files

### ISSUE THREAD

**Issue by arnederuwe** [aurelia/cli#1138]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.16.0

* **NPM Version:**
6.2.0

* **Browser:**
all

* **Language:**
TypeScript 3.5.1

* **Loader/bundler:**
RequireJS

**Current behavior:**
When you link multiple sass files with import statements, the changes of imported sass files aren't reflected in the app when the browser refreshes as a result of ```au run --watch```,  only the root required sass files's changes are reflected.
[sasstest.zip](https://github.com/aurelia/cli/files/3391315/sasstest.zip)

In the attached project, test.scss is directly required in app.html, any style change there is directly reflected in the app when running ```au run --watch```, test.scss imports test-imported.scss, changes to that file are only reflected when you kill ```au run --watch``` and execute it again, greatly slowing down development

* **What is the expected behavior?**

changes to imported sass files should also be reflected in the browser on refresh using ```au run --watch```

**Comment by 3cp** [comment]
Are those "linked scss files" not in src/ folder?

You have to update watch task `aurelia_project/tasks/watch.ts`.
```
{ name: 'CSS', callback: processCSS, source: [ ...project.cssProcessor.source, 'path/to/linked/**/*.scss' ] },
```

BTW, you don't need `--watch` for `au run` any more, it by default rans watch mode, and there is no way to watch node off. Why not, `au run` is dev server, nobody want to disable watching.

**Comment by 3cp** [comment]
Sorry, I missed this, update your `aurelia_project/tasks/process-css.ts`, remove `, since: gulp.lastRun(processCSS)`.

Because scss compilation is not one-to-one compilation, we cannot only send mutated files over watch mode, have to send all files to sass processor again.

Will fix this is next version.

**Comment by arnederuwe** [comment]
Thank you for the quick reply and workaround!
