### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by euglv** [aurelia/cli#1141]
**I'm submitting a bug report**

* **Library Version:**
latest

**Please tell us about your environment:**
* **Operating System:**

Windows 10 Pro (Build 1809)

* **Node Version:**
12.6.0

* **NPM Version:**
6.9.0

**Current behavior:**
After running `npm install aurelia-cli -g` and rebooting - `aurelia-cli` does not work.
I got the following error when trying to run `au`:
```
'au' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by avrahamcool** [comment]
do you have npm in your path variable?

**Comment by euglv** [comment]
Sorry, the problem was that I installed nodejs as another user, and there was no `%UserProfile%\AppData\Roaming\npm\` in path.
