### ISSUE TITLE
.NET 5 will deprecate SpaServices and NodeServices

### ISSUE THREAD

**Issue by vuorinem** [aurelia/cli#1142]
ASP.NET team announcement: https://github.com/aspnet/Announcements/issues/379

Aurealia CLI currently generates an application that depends on now obsolete _WebpackDevMiddleware_ and _aspnet-webpack_. The official recommendation is that each framework would provide their own integration with AspNetCore without relying on SpaServices or NodeServices.

Any thoughts on how this affects Aurelia CLI and it's DotNetCore version of the template? Or is https://github.com/aurelia/dotnet maybe more relevant repository for the discussion?

**Comment by brandonseydel** [comment]
The new template will not be effected as it uses only the spaservices.extensions.  You can the templae from the link below.
https://www.nuget.org/packages/Aurelia.DotNet/
