### ISSUE TITLE
Missing package in bundle

### ISSUE THREAD

**Issue by lukeapage** [aurelia/cli#115]
full source code here - https://github.com/less/less-preview

my Aurelia file looks like this
```
aurelia.command('bundle', {
  js: {
    'dist/app-bundle': {
      modules: [
        '*',
        "aurelia-dependency-injection",
        "aurelia-event-aggregator",
        "aurelia-framework",
        "aurelia-loader-default",
        "aurelia-logging-console",
        "aurelia-templating-binding",
        "aurelia-templating-resources",
        "codemirror",
        "polymer/mutationobservers"
      ],
      options: {
        inject: true,
        minify: true
      }
    }
  },
```

now, aurelia-loader-default references aurelia-loader, which references web componentjs (from the config.js file)

```
    "github:aurelia/loader-default@0.8.0": {
      "aurelia-loader": "github:aurelia/loader@0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0"
    },
    "github:aurelia/loader@0.7.0": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "core-js": "npm:core-js@0.9.15",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
```

and that gets downloaded...

![webcomponentjsdownloaded](https://cloud.githubusercontent.com/assets/309321/8325349/d2a0ed84-1a50-11e5-8a15-0528f7eaa7b5.png)

and when I run in chrome all is fine, but it seems at least some of the files (HTMLImports.min.js) are not included in the bundle, so in firefox, the site fails to load because the file is not bundled.

![mozilla-error](https://cloud.githubusercontent.com/assets/309321/8325365/f7edbfea-1a50-11e5-9f5e-1604ece3cc14.png)

Shouldn't it be included as a sub dependency? is it because it is an optional polyfill?

**Comment by ahmedshuhel** [comment]
Polyfills are loaded when necessary. For now, could you try including it in the bundle explicitly and see if it works?

**Comment by lukeapage** [comment]
so after *alot* of trial and error, I got it to work by putting this into my module list in the aurelia file - `"github:webcomponents/webcomponentsjs@0.6.3/*"`

My first attempt was `"webcomponents/webcomponentsjs"`, then `"webcomponentsjs"` then `"github:webcomponents/webcomponentsjs@0.6.3"` then `"github:webcomponents/webcomponentsjs@0.6.3/HTMLImports.min.js"` before finally finding the * worked.

Next I tried IE and that was missing `"aurelia-html-template-element"` so I tried `"github:aurelia/html-template-element@^0.2.0/*"` which included the package in the bundle, but it didn't get picked up because it was required as `"aurelia-html-template-element"`, so to get it to work I had to jspm install it as a root dependency and then add `"aurelia-html-template-element"` to my AureliaFile...

I think you really need a `includeOptional` option..

**Comment by lukeapage** [comment]
Note: this includes the minified and non minified version of the files!!!

**Comment by lukeapage** [comment]
aha, got it to work with including a single file by omitting the extension - `"github:webcomponents/webcomponentsjs@0.6.3/HTMLImports.min"`

**Comment by lukeapage** [comment]
new definition is this:

```
aurelia.command('bundle', {
  js: {
    'dist/app-bundle': {
      modules: [
        '*',
        "aurelia-dependency-injection",
        "aurelia-event-aggregator",
        "aurelia-framework",
        "aurelia-loader-default",
        "aurelia-logging-console",
        "aurelia-templating-binding",
        "aurelia-templating-resources",
        "aurelia-html-template-element",
        "codemirror",
        "polymer/mutationobservers",
        "github:webcomponents/webcomponentsjs@0.6.3/HTMLImports.min",
      ],
      options: {
        inject: true,
        minify: true
      }
    }
  }
```

**Comment by alexisargyris** [comment]
@lukeapage when you don't bundle your app, is firefox working?

**Comment by lukeapage** [comment]
@alexisargyris yes it is - I just checked. Feel free to browse my source code and nick anything you need (it was based on the skeleton code)

**Comment by alexisargyris** [comment]
Thanks. That boostrapper.js looks very-very interesting

**Comment by lukeapage** [comment]
> Thanks. That boostrapper.js looks very-very interesting

Ah, its not actually - I took aurelia-bootstrap and removed references to router and http - so its a straight fork with removals. I had problems setting the url if the router was included, even if it wasn't setup and as a bonus I don't get those modules included in the bundle. I hope Aurelia will become more configurable in terms of including/excluding bits and *not* having them included at all, then I can drop it. If I can get the url changing working I might switch back to aurelia-bootstrap anyway just for ease of maintainability and take the hit on the extra bundle bytes (which I guess aren't *that* much)

**Comment by PWKad** [comment]
Interesting about the bootstrapper - I'm not sure whether it would make sense to have multiple bootstrappers or to have one which conditionally loads things but consider releasing this on jspm as something like bootstrapper-lite

**Comment by alexisargyris** [comment]
update: the problem with firefox (when the app is _not_ bundled) is present only in the developer edition for some reason.
