### ISSUE TITLE
New project webpack build error: "There are multiple modules with names that only differ in casing."

### ISSUE THREAD

**Issue by matthewcorven** [aurelia/cli#1154]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.0

* **NPM Version:**
6.12.1

* **Browser:**
N/A

* **Language:**
TypeScript 3.1.2

* **Loader/bundler:**
Webpack

**Current behavior:**
Upon `au run` immediately after scaffolding of project from CLI, the error block below is emitted.
```
WARNING in (webpack)/buildin/global.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Source\exp\sample64\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    C:\Source\exp\sample64\node_modules\node-libs-browser\node_modules\punycode\punycode.js
* C:\source\exp\sample64\node_modules\webpack\buildin\global.js
    Used by 3 module(s), i. e.
    C:\source\exp\sample64\node_modules\aurelia-pal\dist\native-modules\aurelia-pal.js
 @ (webpack)/buildin/global.js
 @ C:/Source/junk/usingsmccomponents3/node_modules/node-libs-browser/node_modules/punycode/punycode.js
 @ C:/Source/junk/usingsmccomponents3/node_modules/url/url.js
 @ (webpack)-dev-server/client/utils/createSocketUrl.js
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
```

Steps to reproduce:
`au new sample64 --unattended --select typescript,htmlmin-max,sass,vscode --here`

* **What is the expected behavior?**
No warnings on first `au run`

* **What is the motivation / use case for changing the behavior?**
Prevent user process delay

**Comment by 3cp** [comment]
I could not reproduce the issue, even on win10.

It sounds like some issue when webpack tries to stub Nodejs globals (could be `global` or `process`).

Since you used `--here`, is there something existing node stuff in your folder? Can you try to reproduce the issue with a clean app without `--here`?

**Comment by matthewcorven** [comment]
No longer producing issue
