### ISSUE TITLE
aurelia-cli: webpack configuration incorrect for postcss with sass

### ISSUE THREAD

**Issue by alexisszabo** [aurelia/cli#1159]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli: 1.2.3
sass-loader: 8.0.x

* **Current behavior:**
I created a new aurelia project using the following options:
√ Would you like to use the default setup or customize your choices? · Custom App
√ Which bundler would you like to use? · Webpack
√ Which HTTP Protocol do you wish the outputted Webpack bundle to be optimised for? · HTTP/1.1
√ What platform are you targeting? · Web
√ What transpiler would you like to use? · TypeScript
√ How would you like to setup your HTML template? · Maximum Minification
√ What css preprocessor would you like to use? · Sass
√ Do you want to add PostCSS processing · Typical
√ Which unit test runner would you like to use? · None
√ Would you like to configure integration testing? · None
√ What is your default code editor? · None
√ Which features do you want scaffolded into your project? · Minimum
√ Would you like to add a Dockerfile? · No

aurelia-cli created the following in webpack.config.js:

```
const sassRules = [
  {
    loader: "sass-loader",
    options: {
      includePaths: ["node_modules"]
    }
  }
];
```

```
{
  test: /\.scss$/,
  use: ['css-loader', 'sass-loader'],
  issuer: /\.html?$/i
},
``` 

* **What is the expected behavior?**
aurelia-cli should instead create the following in webpack.config.js:

sass-loader options should be changed to the following due to changes in sass-loader v8+ (assuming that the sass-loader version is upgraded)

```
const sassRules = [
  {
     loader: "sass-loader",
     options: {
       sassOptions: {
         includePaths: ["node_modules"]
       }
     }
  }
];
```

The scss processing rules should be updated to use the postcss configuration

```
{
  test: /\.scss$/,
  use: [...cssRules, ...sassRules],
  issuer: /\.html?$/i
},
```

* **What is the motivation / use case for changing the behavior?**
The change above will enable postcss with the latest version of sass-loader in projects created with the aurelia-cli

**Comment by 3cp** [comment]
This exactly what v1.2.3 does, I double checked with new project. Can you verify your **global aurelia-cli version**?

The sass upgrade was done in v1.2.3, https://github.com/aurelia/cli/commit/80bf3524fe907f66e2ea8173d2a0f9f6576be3ac

**Comment by alexisszabo** [comment]
Ah! I must not have updated my global version properly. Thank you! I updated my global and re-ran. It is as expected now. I will make sure to check the global version in the future first!

**Comment by 3cp** [comment]
:-)
This gives us another reasoning to extract the skeleton out of aurelia-cli npm package. For example, aurelia 2 skeleton is always up to date because `npx makes aurelia` targeting github repo (not npm package) master branch https://github.com/aurelia/new.

We can extract au1 skeleton out, and let `au new` to wrap a makes command to target an always up to date github repo something like https://github.com/aurelia/v1. There is more work to be done if we want to introduce zero breaking change as makes simplified command arguments design. This is in the deep backlog of my todos, with a low priority.
