### ISSUE TITLE
Add path mapping override to aureliafile.js

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/cli#116]
I have a jspm `config.js` that is setup with: 
```
"paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
```
I then have express serve files from the dist folder (not the root folder): 

```
app.use('/config.js', function (req, res) { res.sendFile(path.join(__dirname, 'config.js'));});
app.use('/jspm_packages', express.static(path.join(__dirname, 'jspm_packages')));
app.use(express.static(path.join(__dirname, paths.output)));
```
unfortunately, the config.js isn't valid like this during bundling. During bundling and only during bundling. I need to set: 

```
"paths": {
    "*": "dist/*.js",
```

Would it be possible to add this path mapping override to the `aureliafile.js`? this would mean not having to maintain two `config.js` files.

**Comment by ahmedshuhel** [comment]
Could you please share your `aureliafile.js`? Bundle should be placed relative to `baseURL` of `SystemJS`

**Comment by MeirionHughes** [comment]
Its just the default one from the blog with the `"*"` selector. So that gets mapped to `"*" : "dist/*.js" in the system.config... but I don't want to do that while serving in production. i.e. I don't want it asking for `domain.com/dist/somefile.js`, I want:  `domain.com/somefile.js`.
