### ISSUE TITLE
 Generate `const typescriptCompiler` instead of `var`

### ISSUE THREAD

**Issue by Ryuno-Ki** [aurelia/cli#1173]
**I'm submitting a feature request**

* **Library Version:**
 1.3.0

**Please tell us about your environment:**
* **Operating System:**
 Sabayon Linux

* **Node Version:**
12.16.1

* **NPM Version:**
 6.14.4

* **Browser:**
Node.js

* **Language:**
TypeScript 3.8.2

* **Loader/bundler:**
RequireJS

**Current behavior:**
`aurelia_project/tasks/transpile.ts` [uses](https://github.com/aurelia/cli/blob/1.3.0/skeleton/cli-bundler/aurelia_project/tasks__if_typescript/transpile.ts#L26) `var typescriptCompiler`.

* **What is the expected behavior?**
The assignment is not changed, so could be turned into a `const typescriptCompiler = typescriptCompiler || null;`.

* **What is the motivation / use case for changing the behavior?**
`const` adds an additional guard against accidential reassigment of the variable.

**Comment by 3cp** [comment]
Thx. Will be released in next version.

**Comment by Ryuno-Ki** [comment]
My first actual contribution to Aurelia :tada:

**Comment by bigopon** [comment]
@Ryuno-Ki 🎉
