### ISSUE TITLE
index.d.ts is blank

### ISSUE THREAD

**Issue by davidsk** [aurelia/cli#1175]
**I'm submitting a bug report**

* **Library Version:**
1.3.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.3

* **NPM Version:**
6.11.1

* **Browser:**
n/a

* **Language:**
TypeScript 3.8.3

* **Loader/bundler:**
RequireJS

**Current behavior:**
index.d.ts is blank but is used as a source for many imports in a cli project.  This is generating a warning when using the `au run` command

* **What is the expected behavior?**
index.d.ts should contain the correct definitions

* **What is the motivation / use case for changing the behavior?**
It's incorrect and generates warnings

**Comment by 3cp** [comment]
I did not see any warning, can you share your full terminal logs?

**Comment by netcitylife** [comment]
Also confirm, in v1.3.1 index.d.ts is blank in dist folder

**Comment by 3cp** [comment]
We know is blank. Because the code is converted to use typescript compiler but no code is converted from js to ts yet.

My question is where is your warning? Pls show some screenshots.

**Comment by davidsk** [comment]
It shows up in the problems tab in the vscode console

**Comment by netcitylife** [comment]
I see this in WebStorm in aurelia_project/tasks/run.ts

<img width="968" alt="Снимок экрана 2020-04-29 в 11 34 05" src="https://user-images.githubusercontent.com/2089893/80581394-614f0d00-8a0d-11ea-97fc-d820dfe73f3c.png">

**Comment by 3cp** [comment]
I see, that is kind of expected, because there is no typing from the code.
Unless we
1. convert part of the code base from js from ts.
2. or get rid of the setup of TypeScript compiler, go to the old setup (without any compiler). Then add d.ts file manually.

**Comment by 3cp** [comment]
Interestly, removing the index.d.ts file can silent the vscode. I will try to move `lib/index.ts` back to `lib/index.js` to prevent tsc to generate the empty d.ts file.

**Comment by 3cp** [comment]
Removed empty index.d.ts file. Will be shipped in next version release.
