### ISSUE TITLE
Problem with toastr (jquery plugin) when bundling

### ISSUE THREAD

**Issue by peebles** [aurelia/cli#118]
I have a class that uses toastr that works normally but fails after bundling.  The class is Notify.js:

    import 'bootstrap';
    import toastr from 'toastr/toastr';
    import 'toastr/toastr.css!';
    
    export class Notify {
      constructor() {
	  toastr.options = {
              "closeButton": false,
              "debug": false,
              "positionClass": "toast-bottom-right",
              "onclick": null,
              "showDuration": "1000",
              "hideDuration": "1000",
              "timeOut": "5000",
              "extendedTimeOut": "1000",
              "showEasing": "swing",
              "hideEasing": "linear",
              "showMethod": "fadeIn",
              "hideMethod": "fadeOut"
	    };
        }
        notify( body, title, severity ) {
	  toastr[severity || 'info']( body, title );
        }
    }

I installed toastr with "jspm install toastr=github:CodeSeven/toastr".  After bundling, the variable toastr in the constructor is {}, not the object that the toastr js creates, and thus in the notify() method, there is no function hanging off of it.

But things work ok before bundling.  Am I importing incorrectly?  The bottom of toastr.js looks like:

    }(typeof define === 'function' && define.amd ? define : function (deps, factory) {
        if (typeof module !== 'undefined' && module.exports) { //Node
            module.exports = factory(require('jquery'));
        } else {
            window['toastr'] = factory(window['jQuery']);
        }
    }));

So I might wonder if there is a module.exports w/out bundling and after bundling, window.toastr might exist, but I tried that and its null (in the bundling case).

**Comment by ahmedshuhel** [comment]
Could please you try `jspm bundle` and see if it works and report back.

**Comment by 32graham** [comment]
@ahmedshuhel any resolution here? I am having a similar issue.

**Comment by peebles** [comment]
I haven't gotten around to trying to bundle again.  So, I don't have a solution.
A

**Comment by ahmedshuhel** [comment]
Any body tried `jspm bundle`?

**Comment by ahmedshuhel** [comment]
I will try with jspm and let you know, For js bundling we are using system-builder similar to jspm. So if jspm fails the CLI will fail too. Problem may be with `systemjs-builder`. I will let you know.

**Comment by 32graham** [comment]
@ahmedshuhel I have tried it with `jspm bundle` and it does not work there either.

I have opened an issue jspm/jspm-cli#921 on the jspm-cli repo with an [example repo (using jspm bundle and failing)](https://github.com/32graham/jspm-toastr-bundle-problem) linked.
