### ISSUE TITLE
Running task e2e:headless does not exit the process after run tests

### ISSUE THREAD

**Issue by AlbertoMonteiro** [aurelia/cli#1184]
**I'm submitting a bug report**

* **Library Version:**
```json
"dependencies": {
    "aurelia-bootstrapper": "^2.3.3",
    "aurelia-animator-css": "^1.0.4",
    "whatwg-fetch": "^3.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "bootstrap": "^3.3.6",
    "font-awesome": "^4.6.3",
    "jquery": "^3.3.1"
},
"devDependencies": {
    "aurelia-cli": "^1.3.0",
    "aurelia-testing": "^1.0.0",
    "gulp": "^4.0.0",
    "minimatch": "^3.0.4",
    "through2": "^3.0.1",
    "vinyl-fs": "^3.0.3",
    "promise-polyfill": "^8.1.3",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "@types/node": "^13.7.6",
    "@types/lodash": "^4.14.149",
    "@types/webpack": "^4.41.6",
    "typescript": "^3.8.2",
    "html-webpack-plugin": "^3.2.0",
    "copy-webpack-plugin": "^5.1.1",
    "mini-css-extract-plugin": "^0.9.0",
    "aurelia-webpack-plugin": "^4.0.0",
    "duplicate-package-checker-webpack-plugin": "^3.0.0",
    "clean-webpack-plugin": "^3.0.0",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",
    "expose-loader": "^0.7.5",
    "style-loader": "^1.1.3",
    "url-loader": "^3.0.0",
    "css-loader": "^3.4.2",
    "file-loader": "^5.1.0",
    "app-settings-loader": "^1.0.3",
    "json-loader": "^0.5.7",
    "html-loader": "^0.5.5",
    "istanbul-instrumenter-loader": "^3.0.1",
    "webpack-bundle-analyzer": "^3.6.0",
    "tree-kill": "^1.2.1",
    "@cypress/webpack-preprocessor": "^4.1.2",
    "cypress": "^4.0.2"
}
```

**Please tell us about your environment:**
* **Operating System:**
Microsoft Windows 10 Pro
10.0.19041 N/A compilação 19041

* **Node Version:**
v12.16.2

* **NPM Version:**
6.14.4

* **Browser:**
all

* **Language:**
TypeScript 3.8.2

* **Loader/bundler:**
Webpack

**Current behavior:**
Creating an app with the following command 
```bash
au new aurelia-app2 --unattended --select typescript,cypress,vscode,scaffold-navigation
``` 
after restoring packages I ran the `npm run e2e:headless`, all tests passed, but the process didn't finish. To close it I had to `CTRL + C` on terminal.

**What is the expected behavior?**
- The process should exit 
  - with code 0 when all tests passed
  - with code != 0 with some test failed

**Comment by 3cp** [comment]
It's fixed here. 
https://github.com/aurelia/v1/blob/9b644977fcea3e44e62eec20e875a5a7c04d4288/cypress/aurelia_project/tasks/cypress.ext#L23-L28

You can copy the fix to your project `aurelia_project/tasks/cypress.ts`.

Note that's from a different repo, we have decoupled skeleton from cli repo.

In next aurelia-cli v2 (to be released), we will promote `npx makes aurelia/v1`. The existing `au new` will simply calls that command. You can start using that makes command to create new project now.

The unattended mode is similar with one less argument.
```
npx makes aurelia/v1 your-project-name -s typescript,cypress,vscode,scaffold-navigation
```

**Comment by 3cp** [comment]
Note the makes command requires zero tool installation, and it always uses latest skeleton http://github.com/aurelia/v1 master branch.

It will free users from upgrading global aurelia-cli to latest version.
