### ISSUE TITLE
Can bundle transpile to es5 too?

### ISSUE THREAD

**Issue by andrevlins** [aurelia/cli#119]
There is any option that compile to es5 in the bundle process?

**Comment by ahmedshuhel** [comment]
Yes, I believe it can.

**Comment by andrevlins** [comment]
It's possible in current version? if so, how?

**Comment by ahmedshuhel** [comment]
No special configuration/option is needed, Just the bundle configuration for cli pointing to  the `untranspiled src` should work.

Something like:
```javascript
aurelia.command('bundle', {
  js: {
    "app-build" :{
        "modules" : ['*']
     }
  }
})
```
Where path is configured in `config.js`
```javascript
paths: {
   '*' : 'src/*.js'
}
```

> Assuming all the untranspiled files are under src folder,
