### ISSUE TITLE
Dependencies for array.prototype.filter and available-typed-arrays need updating

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/cli#1191]
https://discourse.aurelia.io/t/for-anyone-seeing-problems-with-bootstrap-5-0-1/4224

**Comment by 3cp** [comment]
Are you sure you are using latest aurelia-cli?

I uses aurelia-cli with requirejs, bootstrap5, gulp-dart-sass. No problem at all.
array.prototype.filter shows v1.0.0, not the v0.1.1 as in your screenshot.

```
huocp@chunpengs-mbp ~/p/b5> npm ls array.prototype.filter
b5@0.1.0 /Users/huocp/playground/b5
└─┬ aurelia-cli@2.0.3
  └─┬ util@0.12.3
    └─┬ is-typed-array@1.1.5
      └─┬ available-typed-arrays@1.0.3
        └── array.prototype.filter@1.0.0
```

**Comment by jeremy-holt** [comment]
This is on my machine

```
PS C:\Visual Studio\AmbFactoryMonitor\AmbFactoryMonitorClient> npm ls array.prototype.filter
ambrcntradeclient@0.1.0 C:\Visual Studio\AmbFactoryMonitor\AmbFactoryMonitorClient
+-- array.prototype.filter@0.1.1
`-- aurelia-cli@2.0.3
  `-- util@0.12.3
    +-- is-typed-array@1.1.5
    | `-- available-typed-arrays@1.0.3
    |   `-- array.prototype.filter@1.0.0
    `-- which-typed-array@1.1.4
      `-- available-typed-arrays@1.0.3
        `-- array.prototype.filter@1.0.0
```

If I update array.prototype.filter to 1.0.0 I go back to the `not loaded ‘define-properties’ errors in almada.js.

![image](https://user-images.githubusercontent.com/2135027/119260921-86885d80-bbc4-11eb-84ed-8d8046632f27.png)

If I run yarn upgrade - it upgrades available-typed-arrays to 1.0.3 and the app breaks again.

I just have to remember to manually upgrade the outdated dependencies, so it doesn't automatically upgrade `available-typed-arrays`

**Comment by 3cp** [comment]
I still cannot reproduce it. Pls share a minimal repo to reproduce the error.

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : 4weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by 3cp** [comment]
```
ambrcntradeclient@0.1.0 C:\Visual Studio\AmbFactoryMonitor\AmbFactoryMonitorClient
+-- array.prototype.filter@0.1.1
```
Looks like the outdated array.prototype.filter is brought in by your ambrcntradeclient, not aurelia-cli.
