### ISSUE TITLE
Error on execution 'au twx-run' from aurelia proj

### ISSUE THREAD

**Issue by p-vaishnav** [aurelia/cli#1192]
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of jquery:
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "jquery"
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of aurelia-bootstrapper:INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "aurelia-bootstrapper"     
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of ag-grid-aurelia:     
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "ag-grid-aurelia"
ERROR [Bundler] Unable to analyze jquery
INFO [Bundler] Error: Unable to find package metadata (package.json) of jquery
ERROR [Bundler] Unable to analyze aurelia-bootstrapper
INFO [Bundler] Error: Unable to find package metadata (package.json) of aurelia-bootstrapper   
ERROR [Bundler] Unable to analyze ag-grid-aurelia
INFO [Bundler] Error: Unable to find package metadata (package.json) of ag-grid-aurelia        
Error: Unable to find package metadata (package.json) of jquery

**Comment by 3cp** [comment]
What's `au twx-run`?

**Comment by Alexander-Taran** [comment]
@p-vaishnav looks like you don't have node modules installed.. Please check with your team.
