### ISSUE TITLE
bundles are not loaded for pushState

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/cli#1195]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 2.0.3 (latest)

**Please tell us about your environment:**
* **Operating System:**
OSX 11.6.2

* **Node Version:**
v17.4.0 (latest)

* **NPM Version:**
8.3.1 (latest)

* **Loader/bundler:**
Webpack 5.66.0 (latest)

**Current behavior:**

aurelia-cli generates settings for pushState as follows on webpack.config.js. When we reload a page with a deep URL, bundles are not loaded.

       const baseUrl = '';
       historyApiFallback: true,

[Here is an explanation.](https://stackoverflow.com/questions/37271062/historyapifallback-doesnt-work-in-webpack-dev-server/67428081#67428081) 

* **What is the expected behavior?**

`output.publicPath: ` should be an absolute path. So, baseUrl has to be '/' instead of ''.

       const baseUrl = '/';
       historyApiFallback: true,

**Comment by 3cp** [comment]
Thx! Fixed.
