### ISSUE TITLE
PackageAnalyzer and Bundler incorrectly identifying plugin/ts references as npm packages

### ISSUE THREAD

**Issue by jamesg1** [aurelia/cli#1199]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 3.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX

* **Node Version:**
16.14.0

* **NPM Version:**
8.3.1

* **Browser:**
all

* **Language:**
4.6.4

* **Loader/bundler:**
RequireJS

**Current behavior:**

Hi I have some aurelia code which is defined in another package (as a plugin which is bundled into one file) and I have some custom typescript code to generate some types for consumer apps.

Example example.d.ts which is imported as a custom type into my consumer aurelia app.

```
declare module 'services/example-a' { export class ExampleA {
    navigate(url: string): Promise<void>;
    static navigate(url: string): Promise<void>;
    static relocate(url: string): Promise<void>;
}
declare module 'services/example-b' { export class ExampleB {
    navigate(url: string): Promise<void>;
    static navigate(url: string): Promise<void>;
    static relocate(url: string): Promise<void>;
}
```

This code is set globally with requireJS modules on the page separately so I don’t need to include it in my app bundle.

How can I **exclude these errors** from occuring when bundling?
```
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of services:
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "services"
ERROR [Bundler] Unable to analyze services
INFO [Bundler] Error: Unable to find package metadata (package.json) of services
ERROR [Bundler] Failed to add Nodejs module services/example-a
INFO [Bundler] Error: Unable to find package metadata (package.json) of services
ERROR [PackageAnalyzer] Unable to load package metadata (package.json) of services:
INFO [PackageAnalyzer] Error: cannot resolve npm package folder for "services"
ERROR [Bundler] Unable to analyze services
INFO [Bundler] Error: Unable to find package metadata (package.json) of services
ERROR [Bundler] Failed to add Nodejs module services/example-b
INFO [Bundler] Error: Unable to find package metadata (package.json) of services
```
“services” is not an npm package rather a custom ts module. TS passes ok and the code is working when deployed.

* **What is the expected behavior?**

I was using an old cli 0.28.0/0.35.0 which didn't have this 

* **What is the motivation / use case for changing the behavior?**
Would like to have the option to exclude certain `packageName` from PackageAnalyzer / Bundler so the cli works like it did in old versions.

Ref - https://discourse.aurelia.io/t/excluding-packageanalyzer-and-bundling-of-external-lib/4901

**Comment by 3cp** [comment]
Bundler doesn't bundle d.ts file. It could be some .ts file importing "services/*".
Can you share a mini repo to demo the issue?

**Comment by 3cp** [comment]
> This code is set globally with requireJS modules on the page separately

Sounds like you want bundler to ignore this module. Check doc section: "1. ignore certain moduleId at bundling time, supply it at runtime"

https://aurelia.io/docs/cli/cli-bundler/advanced#onrequiringmodule

**Comment by 3cp** [comment]
The old bundler 0.x doesn't do auto tracing. It was not a full featured bundler, it didn't trace a module unless you explicitly add the module to aurelia.json dependencies.

Cli v1+ (including v2 and v3) does auto tracing (like webpack and parcel), but you can explicitly ignore some module (or perform other tricks).
