### ISSUE TITLE
Property 'configure' does not exist on type 'typeof import("C:/Users/Dilan/Desktop/qwasar/my_yelp/node_modules/aws-amplify/lib-esm/index")'.

### ISSUE THREAD

**Issue by ndilanwil** [aurelia/cli#1201]
I try to use configure on my react-app linked to my amplify account 
Amplify.configure(awsConfig), but I get the following error

ERROR in src/App.tsx:12:9
TS2339: Property 'configure' does not exist on type 'typeof import("C:/Users/Dilan/Desktop/qwasar/my_yelp/node_modules/aws-amplify/lib-esm/index")'.
    10 | import { onCreateRestaurant } from './graphql/subscriptions';
    11 |
  > 12 | Amplify.configure(awsConfig);
       |         ^^^^^^^^^
    13 |
    14 | type Restaurant = {
    15 |   name: string;

**Comment by 3cp** [comment]
That's a type error for Amplify.configure, you should check with the aws-amplify npm package provider.

**Comment by ndilanwil** [comment]
@3cp Thanks but do you have any hint of what it could be?

**Comment by 3cp** [comment]
You can try to ask in aws-amplify repo.
