### ISSUE TITLE
built-in bundler cannot process .mjs third party files

### ISSUE THREAD

**Issue by swalters** [aurelia/cli#1204]
The bundler wants to append .js to every file name.  Can we get a fix so that it ignores this for .mjs extensions?

For now, I'm having to rename any .mjs files to .js to make it work.

**Comment by 3cp** [comment]
It's in your local `aurelia_project/aurelia.json` field `transpiler.fileExtension`. Change it from ".js" to ".mjs" and try again.

**Comment by 3cp** [comment]
BTW, with `.cjs` and `.mjs` file, it's required to use explicit `import foo from "./foo.mjs";`.

Implicit `import foo from "./foo";` only works with the old `.js` for Nodejs https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#all-together.

**Comment by 3cp** [comment]
Sorry, not `transpiler.fileExtension`, that's affects the aurelia_project/ files.

Update `transpiler.source` from "src/**/*.js" to "src/**/*.mjs".

Note you need to update all src/ files import to explicit `import envirnoment from "./environment.mjs";`.

One more thing, update `aurelia_project/tasks/transpile.js` from `.pipe(rename('environment.js'))` to `.pipe(rename('environment.mjs'))`.

**Comment by 3cp** [comment]
My bad. For 3rd party file, we will release a patch soon.

**Comment by 3cp** [comment]
Please try aurelia-cli v3.0.2.

**Comment by swalters** [comment]
@3cp works great.  Thanks so much for keeping Aurelia-cli up to date.
