### ISSUE TITLE
A plugin installed as 'resources' folder isn't handled correctly by aurelia bundle.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/cli#121]
I have a 'pseudo' plugin in my codebase as per following recommendation in the aurelia documentation:

"Note: A recommended practice for your own apps is to place all your app-specific extensions, value converters, etc. into a resources folder. Then create an index.js file that turns them all into an internal plugin. Finally, install that plugin during your app's bootstrapping phase. This will keep your resources located in a known location, along with their registration code. It will also keep your configuration file clean and simple."

The bootstrapping of the plugin goes as follows:
```
import config from './authConfig';
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css')
    .plugin('./myplugin/index', (baseConfig)=>{   
    	baseConfig.configure(config);
    });

  aurelia.start().then(a => a.setRoot());
}
```
So, the plugin sources are in the relative folder myplugin.
This works perfectly in normal dev mode, when using gulp watch.
When runing the app after bundling, aurelia is looking for the specific index file in the plugin folder, although the content of the plugin is in the bundled js file.

Thanks for helping me to get this working.

**Comment by PWKad** [comment]
Can you create a path in your config.js to point to the plugin?  I think this will fix your issue since system.js will know where to retrieve it from.

**Comment by paulvanbladel** [comment]
False problem.
My problem was caused by upgrading jspm to jspm@beta, which caused the problem described here: https://github.com/aurelia/bootstrapper/issues/10

So, good to know that the bundling has no effect at all when you include a plugin as 'resource'.
