### ISSUE TITLE
Using different bundles for different use cases.

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/cli#125]
I want to use a bundle for development with all aurelia files, but without my app files, so I dont have to re-bundle after every change.
In addition to that, I want to have a deployment bundle with all files included.

How can I configure and use that?

**Comment by CharlesPockert** [comment]
As far as I know you can create multiple bundles by specifying more than one bundle name/config in your aureliafile.js

```
js: {
    "dist/app-bundle": {
      modules: [
        '*',
        'aurelia-bootstrapper',
        'aurelia-http-client',
      ],
      options: {
        inject: true,
        minify: true
      }
    },
    "dist/another-bundle": {
      modules: [
        'something-else',
      ],
      options: {
        inject: true,
        minify: true
      }
    }
  },
```

Give that a try, it certainly works with templates

**Comment by kuechlerm** [comment]
@CharlesPockert, I know that this is an option, but I still don't know how to use that in my workflow. This creates two bundles, say:
- libs.js (all of aurelia)
- app.js (all my files)

In a dev setting, I dont want to use app.js, only libs.js. But in a deployment setting, I want both files (or even better, one file with all content).
Now I need two different index.html files or some concat-action into some theRealFileForIndexHtml.js, or some other hacking. And I cannot inject the bundle into config.js.

But what I really like to do is:
`gulp deploy`
and this calls some thoretical api 
`aurelia-cli.useBundle('bundle-number-two')`
that puts the disired bundle into the config.js.

Sounds reasonable?

**Comment by CharlesPockert** [comment]
Yes, I understand - you want a bundled Aurelia for dev that you don't touch and a bundled app.js for production

Only problem I can see is that without a custom gulp task that wraps jspm you are either bundled using aurelia-cli which bundles everything, or you are unbundled.

You don't actually need two index files - `config.js` specifies how system should load modules (and which js files contain those modules), but you do need a build task that doesn't ever unbundle Aurelia - might be worth looking at jspm to see if you can "part unbundle" as `jspm unbundle` may take args. 

On the other hand, I've got a gulp task to bundle Aurelia and another that bundles my app. 

The workflow is:
* Bundle aurelia manually when I get an updated version (creates `lib/aurelia.js`)
* Run my bundle task when I need
* Unbundle when I want to - this requires a re-bundle of Aurelia but it only takes a minute or so

The only bit I'm not sure about is why you need a bundled app during dev? Usually you only bundle for deploy...

**Comment by kuechlerm** [comment]
My motivation is the dev experience. Bundling aurelia (+ other jspm modules) cuts > 2 seconds on every page load. All those steps in the build pipeline add up...

I would like to use the aurelia cli because the aureliafile.js is much more convenient than dealing with the jspm cli. 
But its really unfortunate that there seems to be no option for:
- using different aureliafiles
- using different bundle-configs in a given aureliafile
- setting a different output path

**Comment by kuechlerm** [comment]
I think I will do the following:

- have 3 files: aureliafile.js / aureliafile.dev.js / aureliafile.deploy.js with the same bundle name, but different modules
- gulp tasks for bundle-dev and bundle-deploy
- eg. bundle-dev: copy aureliafile.dev.js to aureliafile.js -> run `aurelia b -f`

Sounds like overkill... but hey, we're living on the bleeding edge ;)

**Comment by ahmedshuhel** [comment]
@kuechlerm @CharlesPockert If we have something like this in the aureliafile for bundle config:

aurelia.command('bundle', {
  dev:{
   js: {
    "dist/app-bundle": {
      modules: [
        '*',
        'aurelia-bootstrapper',
      ],
      options: {
        inject: true,
        minify: true
      }
    }
  },
  template: {
    "dist/app-bundle": {
      pattern: 'dist/*.html',
      options: {
        inject: true
      }
    }
  }
},
prod :{
  ...
  ...
},
..
..
});

Later, 
- `aurelia bundle --profile/-p dev` will use the `dev` profile for bundling and 
- `aurelia bundle --profile/-p prod` will use the `prod` profile and so on.

This way different bundle profile may have completely different settings that may be used in different development stages. 

Does this help? @EisenbergEffect

**Comment by CharlesPockert** [comment]
It sounds like a good addition but I don't have the same problems as @kuechlerm with the 2 second delay whilst unbundled

The problem is that the cli will always either bundle or not bundle. Is it smart enough in it's current incarnation to understand that no files have changed and that bundling isn't required?

The best thing would be this feature and the ability to bundle only when files have changed

Is there something file that could be generated which contained a "last bundle" hash stamp for a particular bundle config (we could .gitignore it)

The cli could check this to see if a new bundle was required for each bundle config
