### ISSUE TITLE
Do not inject the source index.html with the link, inject the dist index.html

### ISSUE THREAD

**Issue by rquast** [aurelia/cli#126]
Currently, when using inject:true with template bundling, the source index.html is injected (the one in the project root). This is very problematic for a number of reasons (source control, removing the link when you don't want to bundle it, etc).

Can this be fixed to update the dist/index.html only?

**Comment by ahmedshuhel** [comment]
By convention it find's `index.html` in the root for injection. Not everybody will go with `dist/index.html` though. But, we can have an extra configuration in aureliafile's template section like:

```javascript
* inject-destination : `dist/inject.html`
```

This way it will be usable for everyone. If you don't set this property, cli will follow the convention.

* property name is not final. suggestions for suitable name will be appreciated. 
cc/ @EisenbergEffect

**Comment by rquast** [comment]
Every scripting system I've ever used always creates a distribution separate from the source. I don't understand why you would want to mix the two?

**Comment by ejsmith** [comment]
I've wondered about this as well.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Is working on this. @ahmedshuhel When you work on an issue, if you could, please assign it to yourself and select the In Progress pipeline step so that the community (and me) can understand the progress of the work. Thanks!

**Comment by ahmedshuhel** [comment]
@EisenbergEffect will do that from now. Can we add another "label" as `fixed pending release` or something like that? Basically, to say this is fixed and will be part of the next release.

**Comment by EisenbergEffect** [comment]
Not sure if we should add a label. You could add a comment. If we add the label that could get confusing for historical reasons, if we don't remove it after release.

**Comment by ahmedshuhel** [comment]
Comment works too.
