### ISSUE TITLE
A separate config.js for aurelia bundle?

### ISSUE THREAD

**Issue by rquast** [aurelia/cli#127]
Is it possible to have a separate config.js when using aurelia bundle so config.js isn't changed all the time? Updating config.js is problematic for source control.

**Comment by ahmedshuhel** [comment]
No, The purpose of setting `inject` to true is to change `config.js` and inject the bundle there so that systemjs can find the modules included automatically. If you don't want cli to do that, set inject to false and manually include a script tag in the `index.html` with the bundle file.

**Comment by rquast** [comment]
This wouldn't be an issue if all of the files were copied to the dist directory first (including config.js), then transformed.
