### ISSUE TITLE
Can't seem to bundle templates for plugins

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/cli#128]
I've tried all sorts of combinations - maybe I'm doing this wrong, but I'd like to bundle my plugin into a demo app.

The templates in my dist correctly bundle, but no matter what I do I cannot seem to get the plugin HTML to bundle (JS bundles are fine and include my controls)

I've resorted to manually bundling by debugging and figuring out what path Aurelia was requesting for my template assets.

Here's my aureliafile.js at the moment

```
var aurelia = require('aurelia-cli');

aurelia.command('bundle', {
    js: {
        "dist/app-bundle": {
            modules: [
                '*',
                'aurelia-bootstrapper',
                'aurelia-http-client',
                'aurelia-router',
                'aurelia-animator-css',
                'github:aurelia/templating@0.13.1',
                'github:aurelia/history@0.6.0',
                'github:aurelia/history-browser@0.6.0',
                'github:aurelia/templating-router@0.14.0',
                'github:aurelia/templating-resources@0.13.0',
                'github:aurelia/templating-binding@0.13.0',
                'github:aurelia/binding@0.8.0',
                'github:aurelia/loader-default@0.9.0',
                'github:aurelia/logging-console@0.6.0',
                'github:charlespockert/**/*',
                'github:gooy/aurelia-compiler@0.0.5',
                'github:aurelia/html-template-element@0.2.0/**/*',  
                'github:webcomponents/webcomponentsjs@0.6.3/**/*',
            ],
            options: {
                inject: true,
                minify: true
            }
        }
    },
    template: {
        "dist/app-bundle": {
            pattern: ['dist/*.html'],
            options: {
                inject: true
            }
        }
    }
});
```

I've tried all sorts but I was expecting this to work as it appears to work in the JS

```
    template: {
        "dist/app-bundle": {
            pattern: ['dist/*.html', 'github:charlespockert/**.*.html'],
            options: {
                inject: true
            }
        }
    }
```

I've tried all combinations of globs, absolute paths etc etc.

Bundling manually with the following works:

```
<template id="github:charlespockert/aurelia-bs-grid@0.0.1/grid/grid.html!view"><require from="../pager/pager"></require>
    <div style="position:relative;">
   /// etc.
```

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Being able to pick up html views from inside the jspm folders and bundle them is pretty important. That's the only way to get plugins for components to bundle correctly. Can you check into this and see if there's an issue or if it's just a configuration problem?

**Comment by ahmedshuhel** [comment]
@CharlesPockert 

Could you please try this config:

```javascript
   template: {
        "dist/app-bundle": {
            pattern: ['dist/*.html',               'path_of_plugin_folder_relative_to_base_url/**/*.html'
           ],
            options: {
                inject: true
            }
        }
    }
```
As,  `dist` is directly within `baseURL` your pattern for bundling view templates is  `dist/*.html` 
Likewise, if your plugin folder is `jspm_packages/github/your_plugin` then your bundle pattern will be `jspm_packages/github/your_plugin/**/*.html`

This should work. If it does not we may have a bug and I will resolve it as soon as possible.

**Comment by CharlesPockert** [comment]
Ah great, yes that worked, I'm pretty sure I tried that but maybe I didn't include the subdirectories glob - thanks!
