### ISSUE TITLE
Navigation when using bundled templates doesn't look in the bundle

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/cli#129]
When I first load my demo page I get 9 requests. This includes the js bundle and the template bundle.

Nothing else is loaded (apart from config.js and the loader modules and a couple of images/css)

This correctly opens my application and displays templates which are contained in a bundle. 

Navigating after the initial load appears to try to resolve the template from the original path instead of checking the bundle:

![image](https://cloud.githubusercontent.com/assets/9073518/8543655/391751c6-2496-11e5-89a3-83861e2ad258.png)

The only reason the second request works in the above is because I also deployed my unbundled templates (just to get it working)

Any ideas? If you need a live demo go here: http://charlespockert.github.io/aurelia-grid

You can see Aurelia request the pages from the server as you navigate around - shouldn't these requests be absent since all the HTML is already in the bundle?

(unfortunately the above app bundle is minified but I could un-minify it if needed)

**Comment by EisenbergEffect** [comment]
Is your template bundle html import marked with the `aurelia-view-bundle` attribute?

**Comment by PWKad** [comment]
@CharlesPockert Wasn't this reproducible only if you load a plugin and bundle those templates as well?

**Comment by CharlesPockert** [comment]
@PWKad yeah, the above example is using a plugin (github:charlespockert/aurelia-bs-grid) and I'm bundling that with the `app-bundle.js` and `app-bundle.html` (in which I've manually written the bundled templates due to issue #128)

@EisenbergEffect I've got this in my `index.html`:

```
<link aurelia-view-bundle="" rel="import" href="./dist/app-bundle.html">
```

I've debugged and I can see all my templates in the template registry so I think this bit is all working correctly.

**Comment by EisenbergEffect** [comment]
Is the loader trying to look up your plugin's view by ID in the imported document first? If so, there may be an ID mismatch. This could be a result of the bundle process not handling plugin views correctly.

**Comment by CharlesPockert** [comment]
Yes it may be something like that - I did a quick debug and saw that `importDocument` was being called on navigate when I expected `findBundledTemplate` to fire in the loader - I could have a poke around if it would help with the fix

**Comment by EisenbergEffect** [comment]
Yes, you are looking the right area. Whatever you find there will assist.

**Comment by CharlesPockert** [comment]
Ok so I don't understand how the pieces fit together enough at the moment to work out why but this is happening:

Initial load, `findBundledTemplate` kicks off and `bundleChecked` doesn't exist on the `DefaultLoader` - this causes the bundle template to be imported

![image](https://cloud.githubusercontent.com/assets/9073518/8549439/aafb8542-24c2-11e5-9ae2-ab5fd2d11df2.png)

Meaning that other requests for templates continue looking in this bundle....

![image](https://cloud.githubusercontent.com/assets/9073518/8549377/59fc72c8-24c2-11e5-9bca-08c7e4f6e873.png)

Everything loads OK - no extra requests. Then I try to navigate and this happens:

![image](https://cloud.githubusercontent.com/assets/9073518/8549345/3d8790d2-24c2-11e5-87eb-a44393e58d8b.png)

It's a different loader instance - I checked using a global:

![image](https://cloud.githubusercontent.com/assets/9073518/8549540/3ca163a4-24c3-11e5-9cf3-31dde3ec0ae6.png)

Only on navigation does `globalLoader` not equal the loader that's doing the loading

What should be the correct behaviour here?

**Comment by ahmedshuhel** [comment]
@CharlesPockert Could you confirm you still have this issue as #128 is resolved?

**Comment by CharlesPockert** [comment]
Hi @ahmedshuhel - yes I still have the issue. I've checked the bundle and my manual bundling matched the cli bundle more or less, so I don't think the two issues are related.

**Comment by ahmedshuhel** [comment]
@CharlesPockert 
I believe I have found the problem. Let me try to explain it.

After the initial load, the `body` in `index.html` get's completely replaced by the `app` template from bundle. And, `<link aurelia-view-bundle="" rel="import" href="./dist/app-bundle.html">` get's removed from the `body` as well. So, when we navigate to other view, `loader` does not find any link with `aurelia-view-bundle` in index.html any more and fall back to requiring from server.

Use, chrome dev tool's `Elements` tab to see it.

@EisenbergEffect Could you please take a look at it as well? Why router is replacing the body content altogether? We can place the `bundle link` in the `head` but we decided to go with `body` because of the blocking nature of html imports if that contains scripts.

**Comment by CharlesPockert** [comment]
It's probably due to it targeting the body because my aurelia-app is on the body, I wonder if a placed a div inside the body and placed the link outside of this if it would solve it... I'll give it a try

**Comment by ahmedshuhel** [comment]
Yes that may solve the problem as well but question still remains. Should the router completely wipe out the body? @EisenbergEffect

**Comment by EisenbergEffect** [comment]
The aurelia-app attribute can be placed on any html element. Whatever it is placed on  becomes the host for the aurelia app. So, any content therein will be replaced. If you don't want that to happen, then it's best to use a different element.

**Comment by CharlesPockert** [comment]
Yes, just to confirm, this fixed the issue - might be worth putting this info in the docs somewhere as it's not so obvious without some digging

```
<body>
    <div aurelia-app="animation-main">
        <div class="splash">
            <div class="message">Aurelia Bootstrap Grid</div>
            <p class="subtitle">Loading... please wait</p>
        </div>
    </div>
    <script src="loader/system.js"></script>
    <script src="config.js"></script>
    <script>
    System.import('aurelia-bootstrapper');
    </script>
    <link aurelia-view-bundle="" rel="import" href="./dist/app-bundle.html">
</body>
```
