### ISSUE TITLE
Change baseURL

### ISSUE THREAD

**Issue by olanod** [aurelia/cli#132]
We should be able to specify the `baseUrl` that the bundler uses overriding the one it gets from the loader.  
```
aurelia.command('bundle', {
    js: {...},
    template: {...}
}, {
    force: true,
    baseUrl: 'some/other/base/for/bundling'
});
```

**Comment by ahmedshuhel** [comment]
@olanod Could you please tell us more about your use case? When do you need to set baseURL etc? 

Is it that the cli does not respect the `baseURL` set in `config.js`? More info on this will be greatly appreciated.

**Comment by ahmedshuhel** [comment]
We can now set packagePath (the path of `package.json`) which includes the `baseURL` etc. So this should solve the problem.
