### ISSUE TITLE
Expose bundler function

### ISSUE THREAD

**Issue by olanod** [aurelia/cli#134]
I have a custom building/bundling process with gulp and I'd like to use the `bundle` function in `aurelia-cli/dist/lib/bundler` from my build script. One option would be to expose it in the aurelia-cli export or even better would be to make it a separate repo so I don't have to pull the hole `aurelia-cli` package.
```
// change this
var bundle = require('aurelia-cli/dist/lib/bundler');
// to maybe this?
var bundle = require('aurelia-bundler');

bundle({
    js: {...},
    template: {...}
}, 
{...});
```

**Comment by ahmedshuhel** [comment]
This is on our list. We will provide an api for every cli functionality.
