### ISSUE TITLE
bundle does not run with jspm@beta

### ISSUE THREAD

**Issue by reinholdk** [aurelia/cli#138]
I'm using aurelia with jspm beta (SystemJS v0.18.4).
However, the app_bundle.js generated with aurelia-cli runs into:
  _System.get(...).retrieveGlobal is not a function_ 
Any idea how to workaround this?

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Please review this as part of the current work. The jspm beta is being released today and so are all the Aurelia updates that correspond to that, so we need to make sure the bundler is working both with the latest master of Aurelia and with jspm beta.

**Comment by ahmedshuhel** [comment]
We are currently using the master branch of `jspm` because we are using some features that were not released in the last jspm beta (0.16.0-beta.3). I will update the dependency as soon as jspm is released and will test it against the latest aurelia-skeleton.

**Comment by stoffeastrom** [comment]
FYI: The *aurelia-skeleton* is not working with jspm beta and latest released *cli*

**Comment by EisenbergEffect** [comment]
@stoffeastrom You mean that bundling isn't working correct? Not that the skeleton isn't working at all, in unbundled form...

**Comment by stoffeastrom** [comment]
@EisenbergEffect Yes the bundling isn't working!

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Please treat this as top priority. We need to get a new cli release out asap that has bundling working with latest jspm beta and aurelia. If there are any changes we need to make in aurelia itself, please let me know.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect We have resolved it already. Bundling (both js and template) is working with aurelia-cli. We will have a release after I discuss with you.

**Comment by alexmills** [comment]
@EisenbergEffect how's progress moving on a new release? I'm having the same issue with @stoffeastrom when bundling on a file that is injected inline using <require...

**Comment by EisenbergEffect** [comment]
We are testing it out. It should hopefully be released in the next day or two.

**Comment by ahmedshuhel** [comment]
A new version of `CLI` is released.

**Comment by stoffeastrom** [comment]
`babel-runtime` seems to be missing as a dependency to the *cli*. I had to manually to into the local `node_modules/aurelia-cli` and do a
`npm install babel-runtime` to get it to work. Also I had to uninstall global + local *cli* and reinstall to make sure it has the right version.

**Comment by stevies** [comment]
I had exactly the same experience.  On windows 10.  Initial error was like:
```
PS D:\WebstormProjects\aurelia-starter-kit\tmp> aurelia bundle
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-runtime/helpers/create-class'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\WebstormProjects\aurelia-starter-kit\node_modules\aurelia-cli\dist\index.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by stoffeastrom** [comment]
When loading a deployed bundle I got an error when loading a css file. I had to go into `config.js` and remove `bundleCSS: false` and regenerate the bundle to get it to load.

**Comment by ahmedshuhel** [comment]
@stoffeastrom Thanks for reporting about `babel-runtime`.  We will give it a try and make the fix.

**Comment by stevies** [comment]
v0.3.1 appears to have fixed this issue.
