### ISSUE TITLE
Unbundle not working

### ISSUE THREAD

**Issue by ldrews1** [aurelia/cli#148]
larry@larry-Aspire-M3985 ~/Projects/aurelia $ aurelia unbundle
info: Un bundling ... 

TypeError: Cannot read property 'packagePath' of undefined
    at unbundle (/usr/lib/node_modules/aurelia-cli/dist/lib/unbundler.js:46:40)
    at InitCommand.action (/usr/lib/node_modules/aurelia-cli/dist/commands/unbundle.js:43:34)
    at Command.listener (/usr/lib/node_modules/aurelia-cli/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib/node_modules/aurelia-cli/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/lib/node_modules/aurelia-cli/node_modules/commander/index.js:458:21)
    at Aurelia.run (/usr/lib/node_modules/aurelia-cli/dist/index.js:120:30)
    at /usr/lib/node_modules/aurelia-cli/bin/aurelia.js:77:13
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
l

**Comment by stoffeastrom** [comment]
Are you sure that your **local** *aurelia-cli* is upgraded to *0.3.0*?

**Comment by ldrews1** [comment]
Just reinstalled aurelia-cli locally, same error.

**Comment by ahmedshuhel** [comment]
@ldrews1 Have you got the problem solved?

**Comment by ldrews1** [comment]
Nope.  For me aurelia unbundle still has the same problem.

**Comment by ahmedshuhel** [comment]
@ldrews1 Do you have an `aureliafile.js` with a bundle configuration like [this]( https://github.com/aurelia/cli#configuration) ?

**Comment by ahmedshuhel** [comment]
I just ran the command without an aureliafile and got the same error as you have got. `Unbundle` works if you have a bundle configuration.

**Comment by ldrews1** [comment]
On Thu, 2015-08-13 at 08:45 -0700, Shuhel Ahmed wrote:
> I just ran the command without an aureliafile and got the same error
> as you have got. Unbundle works if you have a bundle configuration.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Please see attached AureliaFile.txt (renamed to get around email
filters).


/**
 * Created by larry on 6/11/15.
 */
var aurelia = require('aurelia-cli');

aurelia.command('bundle', {
    js: {
        "dist/app-bundle": {
            modules: [
                'dist/*',
                'aurelia-bootstrapper',
                'aurelia-router',
                'github:aurelia/templating-binding@0.13.2',
                'github:aurelia/templating-resources@0.13.4',
                'github:aurelia/templating-router@0.14.1',
                'github:aurelia/loader-default@0.9.3',
                'github:aurelia/history-browser@0.6.2'
            ],
            options: {
                inject: true,
                minify: true
            }
        }
    },
    template: {
        "dist/app-bundle": {
            pattern: 'dist/*.html',
            options: {
                inject: true
            }
        }
    }
});

**Comment by stoffeastrom** [comment]
You have to add the `unbundle` command also with the same bundle config.
