### ISSUE TITLE
Create a project generator

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#15]
Let's consider creating a project generator. 

What is a Project?

If you would like an example, you can consider an old cli tool I made called Ari

However, This will be much simpler, yet more robust. 

A project will be your typical skeleton navigation. 
When creating a project directory we should also create a plugins directory outside of the project. 

This plugins directory will contain generated plugins that have their own repositories. 

Similar to SOA (Service Oriented Architecture) However, Aurelia-CLI should automate all build and watch tasks for each plugin included in the project. 

This is very beneficial, especially if you want to be able to modify your plugins, yet see the changes immediately within you project. 

What should we Automate?

After creating a project, and a plugin, We should allow a command named `link`

`link` will make a local jspm link form the plugin, and a local `jspm install --linked` from the project directory. 

I will list other functionality once I have it properly described.

**Comment by EisenbergEffect** [comment]
CLI deprecated for now.
