### ISSUE TITLE
ghdownload is not defined

### ISSUE THREAD

**Issue by Depool** [aurelia/cli#155]
'aurelia new project' fails having both aurelia-cli 0.3.1 and 0.3.0 installed on Windows.
Getting 'ghdownload is not defined' in /aurelia-cli/dist/lib/installer/index.js.
Using aurelia-cli 0.2.1 went ok

**Comment by zewa666** [comment]
Hi there, yep sry for the stupid mistake ... will get that fixed soon, PR is already created
