### ISSUE TITLE
Exclude modules from bundle

### ISSUE THREAD

**Issue by cscleison** [aurelia/cli#159]
In jspm you can tell which modules you don't want in the bundle using -
Is there a way to do it in aurelia-cli?

**Comment by ahmedshuhel** [comment]
Finally somebody wanted that. :)  Currently, no. Hope to add the feature in the next release.

**Comment by stevies** [comment]
I've also hit a scenario where I need this. One of my modules imports an external json resource containing environment specific properties. Running locally, this will be a file that lives in a directory outside the main source.  Import will be like this: 
```
import data from 'environment/properties!json';
```
At runtime, the resource will be served up from the server, so the original local file cannot be included in the bundle.

I'm  hoping your next release will be soon and allow the above.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Let's add this feature to the bundler next after you finish up your current tasks. @stevies We've move bundler specific issues over to the new bundler repo for now. We're moving that out of cli so it can more easily be consumed from gulp tasks and other similar task runners.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect OK.

**Comment by ahmedshuhel** [comment]
This feature is already added to [aurelia-bundler](http://github.com/aurelia/bundler)
