### ISSUE TITLE
Systemjs-builder 0.13.4 breaks template bundling

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#161]
System-js builder 0.13.4 had some changes to `getCanonicalName()`(https://github.com/systemjs/builder/commit/290b84bfb90a8786900e8652671a0aab36f7e5fc)

These changes changed the behaviour and caused paths in the templating bundle (`app-bundle.html`) to contain the dist folder (or other `*` mapping in `config.js`)

Example: `<template id="dist/components/projectDetailView/projectDetailView.html!view">`

If I install systemjs-builder 0.13.2 the problem is gone. Not sure why 0.13.4 gets installed though.

Possibly also causing this issue: https://github.com/aurelia/skeleton-navigation/issues/146

**Comment by JeroenVinke** [comment]
Workaround:

go into the node_modules\aurelia-cli folder and make this change to `package.json`: https://github.com/JeroenVinke/cli/commit/829db74e7da5418d6a5a4d52b819a4bb4b4c8db7

then run npm install. To confirm you can check if `node_modules\aurelia-cli\node_modules\systemjs-builder\package.json` has the version `0.13.2`

**Comment by ahmedshuhel** [comment]
Thanks for reporting and the PR.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel Has this been addressed? Can we close this?

**Comment by ahmedshuhel** [comment]
@EisenbergEffect I think it's resolved already. We are using systemjs-builder v0.13.5 now. Hopefully @JeroenVinke is using aurelia-bundler now with latest version of Aurelia. 

@JeroenVinke Feel free to open an issue [here](http://github.com/aurelia/bundler/issues), if you still have the problem.

**Comment by JeroenVinke** [comment]
aurelia-bundler works great :smile:
