### ISSUE TITLE
Error in Visual Studio Community 2015 when building aurelia

### ISSUE THREAD

**Issue by laurentiustamate94** [aurelia/cli#164]
I have the following error [which I detailed here](http://stackoverflow.com/questions/32129931/aurelia-bundle-in-visual-studio-2015-community) and [commented on the official nodejs-tools for vstudio](https://github.com/Microsoft/nodejstools/issues/208).

I've searched this repo and found out that `aurelia update` is just a wrapper for `npm install` and I don't find it's usefulness, at least in my case, `npm install` is run when i open visual studio.

**Comment by EisenbergEffect** [comment]
Closing this since we are deprecating the CLI and moving to a bundling library that can be used from any build tool.
