### ISSUE TITLE
aurelia bundle no such file or directory aurelia-cli.js

### ISSUE THREAD

**Issue by Cedware** [aurelia/cli#165]
I installed aurelia-cli twice, once with -g and once with --save-dev:
When I'm running aurelia bundle this error is thrown:

> Unhandled rejection Error on fetch for aurelia-cli.js at file:///C:/path/to/project/aurelia-cli.js
>         Loading aureliafile.js
>         Error: ENOENT: no such file or directory, open 'C:\path\to\project\aurelia-cli.js'
>     at Error (native)
> 

I'm working with windows 7

**Comment by EisenbergEffect** [comment]
There's a very BIG notice in the readme that says:

This project is DEPRECATED and no longer MAINTAINED.
