### ISSUE TITLE
[TypeError: Cannot read property 'getTaskMetadata' of null]

### ISSUE THREAD

**Issue by Narven** [aurelia/cli#167]
After install aurelia-cli using: `npm install aurelia-cli -g` and `npm install aurelia-cli --save-dev` when I run aurelia, i get:

```
[TypeError: Cannot read property 'getTaskMetadata' of null]
```

**Comment by EisenbergEffect** [comment]
It's not ready to be used yet.

**Comment by Narven** [comment]
Is it ready now?

**Comment by EisenbergEffect** [comment]
It should. Make sure you have the latest release.

**Comment by Narven** [comment]
Yes I have the latest release. I found the problem.. it seams I had a local version of aurelia-cli that was overriding the global. When i deleted it... it works now. Thanks and sry to annoy you.

**Comment by mwrand** [comment]
I'm getting the same error: [TypeError: Cannot read property 'getTaskMetadata' of null], and I just download the CLI today.  Version 0.16.1  Any thoughts on how to resolve?

**Comment by EisenbergEffect** [comment]
Make sure your local version is correct. You need to run `aurelia -v` from inside your project folder.

**Comment by mwrand** [comment]
That's what I did. :-(

**Comment by mwrand** [comment]
Thanks, Rob.  But that's what I did. :-(

![aurelia-cli](https://cloud.githubusercontent.com/assets/4163403/17029358/901cee98-4f30-11e6-896c-50ac5169208e.png)

**Comment by EisenbergEffect** [comment]
What is `aurelia bundle`? Is that a custom command you wrote? It isn't provided by the CLI. But, besides that, it is telling you that "no aurelia project" was found. Are you running this from inside an aurelia project that was created by the cli?

**Comment by mwrand** [comment]
I'm following the instructions in this article: http://blog.durandal.io/2015/06/23/bundling-an-aurelia-application/

**Comment by wgrs** [comment]
Everything downloaded fresh today - same error.

**Comment by EisenbergEffect** [comment]
@mwrand That article on bundling does not apply to the cli. That predates the cli which uses an entirely different bundling solution.
