### ISSUE TITLE
reuse TS code templates for ES6/ES7

### ISSUE THREAD

**Issue by atsu85** [aurelia/cli#169]
@EisenbergEffect, I noticed, that code templates are duplicated for both [TypeScript and ES6/ES7 versions of the generated source code](https://github.com/aurelia/cli/tree/master/lib/resources/src).

I'm wondering, if it is worth writing both TypeScript and ES6/ES7 versions of each class. Ideally ES6/ES7 should be generated from TypeScript. I guess You have considered it? Probably TypeScript compiler can't be used to only strip the type annotations (that might be what is desired here) so probably some other tool could be used instead? TypeScript compiler removes type annotations, but additionally:
- replaces decorators with `__decorate(...)`
- replaces class declarations with class expressions (that is more verbose and may be harder to grasp)

What are Your thoughts?

**Comment by EisenbergEffect** [comment]
Are you saying we should, during creating a new project, invoke the TS compiler to compile TS code into ES2015 in order to get the source code that we create into a Babel project?

**Comment by atsu85** [comment]
No, not when the developer is creating a new project, but when building aurelia-cli project. That is what I had in mind - makes more sense to me ;)

**Comment by EisenbergEffect** [comment]
Ah. Interesting. I'll think about it. Currently there isn't a build process for the cli, which is kind of nice.

**Comment by EisenbergEffect** [comment]
I think this is a good idea...however, I don't think it will work 100% since TS requires using a different import syntax with NodeJS than Babel does. Maybe Babel can support the same syntax though? If so, I would be interested in trying this out. It would be nice not to have to write and maintain two versions of everything. Would you be interested in investigating further and possibly sending a PR for the build task? @atsu85

**Comment by atsu85** [comment]
>I think this is a good idea

I'm glad to hear it, did You consider reopening this issue?

Actually I'm surprised, that at this point where [skeleton-typescript still uses js instead of ts for building](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript/build/tasks), You are attempting to write gulp tasks also in TypeScript :)

> however, I don't think it will work 100% since TS requires using a different import syntax with NodeJS than Babel does.
> Maybe Babel can support the same syntax though?

Looks like Babel supports TypeScript syntax:
1) https://babeljs.io/docs/learn-es2015/
2) http://stackoverflow.com/a/31387018/4973640
But I haven't tried it and unfortunately I'm not familiar with Babel.

I'm surprised (maybe based on my incomplete understanding of ES6 modules), that Babel even works with that syntax (with that module), because as I understand [this line](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/build-markup.js#L2):
`import changed from 'gulp-changed';`
means that `gulp-changed` should have a default export, that is imported with alias `changed` (it could have named exports as well in addition to default).

So if gulp-changed [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/gulp-changed/gulp-changed.d.ts#L59) would contain
`export default changed;`
instead of
`export = changed;`
then the "Babel way" would also work [with TypeScript](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/build-markup.ts#L2):
`import changed from 'gulp-changed';`

**Comment by atsu85** [comment]
> but perhaps the TS syntax is actually correct

So far it still seems to me, that this is standard ES6 module import syntax, and not specific to TS

**Comment by atsu85** [comment]
I don't know why i didn't think about it before, when i wrote
> Probably TypeScript compiler can't be used to only strip the type annotations (that might be what is desired here) so probably some other tool could be used instead?

but probably "transform-flow-strip-types" Babel plugin would do just what is desired here (remove TypeScript type info, but leave everything else, like ES7 decorators and class declarations there). But I haven't tested it, so I might have guessed incorrectly ;)

**Comment by EisenbergEffect** [comment]
Bingo! That's probably the best fit. I didn't think of it either :)

**Comment by AdamWillden** [comment]
Just in case - I don't know if this TS flag helps? https://github.com/Microsoft/TypeScript/pull/2901

**Comment by doktordirk** [comment]
that removes extend and öhm decorators or something. would need to provide those helpers oneself

**Comment by atsu85** [comment]
I think that the correct flag is allowSyntheticDefaultImports. It worked for me with i18n related issue.

**Comment by Alexander-Taran** [comment]
@jwx this one is for you (-:

**Comment by 3cp** [comment]
Most ts/es6 template files are merged in current skeleton. Only those with too much differences are kept as two files.
