### ISSUE TITLE
Extendable new application options

### ISSUE THREAD

**Issue by rquast** [aurelia/cli#170]
I know it's not released yet, but have been looking through and admiring the code.

One thing I noticed was, when you create a new application, it reads the new-application.json configuration file inside of aurelia cli. The problem would be trying to add a new editor, markup parser, etc, and drop the config file into the new aurelia project.

Maybe one day in the future (after releasing it, and things have settled), you can make it so a developer can register each one of these things with the commands, so someone could write an extension like aurelia-cli-mygreateditor

**Comment by EisenbergEffect** [comment]
Yes, absolutely, that is something we would like to do one day. Right now we are trying to use an iterative design to get the core features working that most people will want. In the future, we do hope people will be able to declare their own workflows for the cli, perhaps even publishing them to a gist that can be referenced from the cli.

**Comment by Alexander-Taran** [comment]
I think https://github.com/makesjs/makes answers just this question.

@bigopon can be closed
