### ISSUE TITLE
ASP.Net Core Generator adds wwwroot to script urls

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/cli#173]
The ASP.Net Core Generator is properly placing the transpiled and bundled scripts in `wwwroot\scripts`. Unfortunately, `wwwroot` is being written to the paths placed in `requirejs.config` in `vendor-bundle.js`. This means that requirejs tries to load `wwwroot/scripts/app-bundle.js` instead of `scripts/app-bundle.js`. This keeps the Aurelia app from properly loading.

When I hand edit `vendor-bundle.js` to change the location for `app-bundle.js` from 
```javascript
"app-bundle": "../wwwroot\\scripts/app-bundle"
```
to
```javascript
"app-bundle": "../scripts/app-bundle"
```
the aurelia app runs successfully.

Also, all of the instances of `\\` can simply be replaced with `/` in `aurelia.json`.

**Comment by clearmeasurebrian** [comment]
I'm seeing the same thing.

**Comment by EisenbergEffect** [comment]
Yes, it's an early attempt. We can probably get this fixed within the next week.

**Comment by searus** [comment]
I have a workaround for this which means you don't have to manually edit the vendor-bundle.js every time.  Maybe the solution could be incorporated, but I don't feel confident enough with this repository yet to make a pull request.

In the aurelia_project/aurelia.json file, add the following additional property:

``` javascript
 "build": {
    "targets": [
      {
        "id": "aspnetcore",
        "displayName": "ASP.NET Core",
        "output": "wwwroot/scripts",
        "baseUrl": "scripts" // new property to handle module path generation correctly
      }
    ],
```

Then, make a small edit in `node_modules/aurelia-cli/lib/build/bundle.js` as follows:

In the `createRequireJSConfig` method, replace the following line:

``` javascript
config.paths[currentBundle.moduleId] = '../' + platform.output + '/' + currentBundle.moduleId;
```
with this line:
``` javascript
config.paths[currentBundle.moduleId] = '../' + platform.baseUrl + '/' + currentBundle.moduleId;
```

Hope this helps!

**Comment by EisenbergEffect** [comment]
@searus Great work. I was planning something very similar. I need to review a few areas to be sure, but we'll get a fix in soon....probably the exact code you have here.

**Comment by searus** [comment]
@EisenbergEffect Happy to help.  I'm really loving the way the CLI is working and I'm already converting my project to use this instead of JSPM.

**Comment by alfkonee** [comment]
@EisenbergEffect  Yeah I Also run into the same bug but I'm loving the CLI Migrating form JSPM Now on

**Comment by EisenbergEffect** [comment]
We should be able to get this fixed next week. @searus has a solution that's probably correct. I just need to review a few things to be sure. I'll update this post when we have a release so you all can test it out.

**Comment by searus** [comment]
@EisenbergEffect I am trying to use automated builds (Visual Studio Team Services) so I have forked this repository and made my change, then updated my package.json to point to my fork instead of the npm package.

But, now I get an error on `au build` because of a dependency:

```shell
module.js:327
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at G:\Source\VSTS\reynoltd\CanonburyWeb\src\Web\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:5:62
    at Array.map (native)
    at define (G:\Source\VSTS\reynoltd\CanonburyWeb\src\Web\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:5:36)
    at Object.<anonymous> (G:\Source\VSTS\reynoltd\CanonburyWeb\src\Web\node_modules\aurelia-cli\lib\build\amodro-trace\lib\parse.js:10:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Clearly it's not as simple as simply re-pointing the dependency in my package.json.  Can you offer any advice?

**Comment by EisenbergEffect** [comment]
@searus That is an odd error. There is no npm dependency on esprima. Rather, the cli embeds the necessary library directly.

**Comment by MisterGoodcat** [comment]
Any news on when the fix by @searus will be included in the official build? At the moment, all devs would have to apply this fix manually after each pulling the code and doing a node modules install.

**Comment by EisenbergEffect** [comment]
Released as version 0.14.0

**Comment by EisenbergEffect** [comment]
Much thanks to @searus

**Comment by kodeek** [comment]
In version 0.23.0 I just needed to change build>targets>output in aurelia_project/aurelia.json to "wwwroot/scripts" from "scripts". So it seems the issue still persists.
