### ISSUE TITLE
au run does not display the "Access URLs", they are just blank (Windows 10, 64bit, powershell)

### ISSUE THREAD

**Issue by m-andrew-albright** [aurelia/cli#176]
A team member on Mac discovered it runs on port 9000, so I checked and it *does* appear to be running there, but there was no indication in the output of the CLI.

Screenshot: http://i.imgur.com/Y5fZSn8.png

Also, just noticed the output "Invalid Command: run" but it just appears to be erroneous output?

**Comment by EisenbergEffect** [comment]
Funny. It's there. Your console background color is obscuring it. We'll look into that and the invalid command.

**Comment by m-andrew-albright** [comment]
I tried highlighting the text to see if that would bring it out, but it
didn't; copy/paste confirms that the text is in fact there.

**Comment by ebekker** [comment]
In my case, the --watch flag also didn't appear to be working, any changes I made to didn't get picked up on the console and didn't get reflected in the browser.  (I have the same OS and console setup.)

**Comment by EisenbergEffect** [comment]
@AshleyGrant You tested this combination correct?

**Comment by AshleyGrant** [comment]
Not power shell, I use Git Bash. I'll test and verify this.

**Comment by EisenbergEffect** [comment]
@AshleyGrant Any chance you can check to see if there's some way we can affect the browser sync output color?
