### ISSUE TITLE
`au run` generates environment.js even when using TypeScript

### ISSUE THREAD

**Issue by atsu85** [aurelia/cli#177]
# Problem
`au run` in project configured with TypeScript generates `src\environment.js` that shouldn't be needed, as `src\environment.ts` already exists since creating the project with `au new`.

# Details
(Not sure if OS is relevant, but)
I used Windows to generate project with `au new` and custom setup:
```cmd
Project Configuration

    Name: cli-experiment
    Platform: Default
    Transpiler: TypeScript
    CSS Processor: Sass
    Unit Test Runner: Karma
    Editor: Visual Studio
```

**Comment by EisenbergEffect** [comment]
Fixed and released. You can update the incorrect file extension in your own project by opening the aurelia_project/tasks/transpiler.ts task. You will see an accidental .js in there.
