### ISSUE TITLE
IDE support for editing TypeScript files in aurelia_project dir

### ISSUE THREAD

**Issue by atsu85** [aurelia/cli#183]
# main idea

Currently build scripts, generators etc are typescript scripts when aurelia project is generated with TypeScript transpiler selection. Right now it doesn't add much value, as IDEs (at least Atom) won't do anything with them, because aurela_project folder is not included in tsconfig.json
## changes that can be made to improve the situation

I've created sample project with aurelia-cli and added to github. I created [a PR](https://github.com/atsu85/aurelia-cli-experiment/pull/1) to show the changes that fix most of the problems:
- added as much TS declarations using as available through `typings`
- added aurelia_project/tsconfig.json to be able to compile TS from aurelia_project folder
- changed syntax for importing json files, so that TypeScript compiler would work with them
## future work

Some TS declarations are still missing. See the `tsc` output from the [PR](https://github.com/atsu85/aurelia-cli-experiment/pull/1)

**Comment by AStoker** [comment]
Is this still an issue? Does using VS Code solve your issue?

**Comment by Alexander-Taran** [comment]
Works for vscode for the packages with typings.
![image](https://user-images.githubusercontent.com/1029452/36926280-ed7ad3d4-1e87-11e8-941a-170fc9bea178.png)

**Comment by Alexander-Taran** [comment]
@EisenbergEffect can be closed

**Comment by EisenbergEffect** [comment]
Closing as fixed.
