### ISSUE TITLE
au new generates only gulp tasks but not webpack.config.js

### ISSUE THREAD

**Issue by rajajhansi** [aurelia/cli#184]
I understand that cli is in early stages. Are there plans to make gulp and webpack as choices as well instead of always using gulp? I thought of using skeleton-webpack project for now until cli supports webpack but that skeleton-webpack typescript project is currently broken :(

**Comment by EisenbergEffect** [comment]
We will consider it, but currently we are working on core CLI capabilities.
As states in the RC post, we are in the process of working on a new Webpack solution. It's almost ready but needs a bit more time.

**Comment by kamilglod** [comment]
@EisenbergEffect what's the current status of adding webpack to the CLI?

**Comment by EisenbergEffect** [comment]
The work on that hasn't started yet. We need to do some refactoring of the CLI to make it possible. I'm hoping we can start on that soon. Fortunately, the new Webpack setup is almost ready and I think it will be pretty easy to use, even without CLI integration.
