### ISSUE TITLE
Add integration of aurelia-kendoui-bridge

### ISSUE THREAD

**Issue by bdenham** [aurelia/cli#187]
Need option to install kendoui-bridge for a new project.

**Comment by adriatic** [comment]
Just to be safe: aurelia-cli generated projects use RequireJS (not jspm, not webkit)

**Comment by EisenbergEffect** [comment]
For the moment yes. We will enable other loader options. But, require.js is the most stable, performant and cross-browser solution in our experience, so as a practical matter, we started with that first. The cli can be taught to output for other loaders though. We'll probably add system.js next, so this will be an interesting way to use system.js but without really needing jspm to configure it. We are also considering if we could have the cli generate a webpack-based project in the future as well. However, that will take a bit more time...we still need to get a full handle on Webpack first. We're getting close on that.

**Comment by bdenham** [comment]
Ok, great. With all the changes and troubles I've encounter with both jspm and webpack, I'm ready for something stable and simple. I'm starting my project from scratch, so I can use anything I want. Simpler the better. But I do need to use kendoui pro controls, so jspm will have to be part of my mix. I look forward to when controls are more plentiful and easily integrated. Thanks.

**Comment by adriatic** [comment]
Bruce, 

I saw that what you really care about is the full stack solution with aurelia as the front end. As you must have realized, there is no single tool that will generate the skeleton code for both "ends" and the closest to what you want is to use a combination of **[aurelia cli]** and **[dotnet cli](https://github.com/aurelia/cli)** - tools that are at the moment, "unaware" of each other.

As a developer, you are likely not very interested in application tooling - you would prefer a situation where you have a single tool, presenting you the form (which replaces the "dialog" you conduct with a cli tool), chose all parameters available including to simple accept all defaults in the best case -- and with a single click one the `create` button you get the **complete** skeleton in a few minutes, built and ready. 

If you would care about such tool - you should expect one from Aurelia-Tools group - the same folks that gave you the KendoUI bridge, It is still in the initial definition stage, and you could help us if you provide a complete definition of the full stack app you need. As a thank you we will build that skeleton manually :-)

**Comment by bdenham** [comment]
Sounds great to me! Let me know more and I’ll start helping today.

**Comment by adriatic** [comment]
@bdenham since this discussion is morphing into KendoUI support issue, let's please continue it **[here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/541)**

**Comment by adriatic** [comment]
This issue could be closed now.

**Comment by EisenbergEffect** [comment]
Thanks @adriatic !
