### ISSUE TITLE
Blue text on a black background is illegible...

### ISSUE THREAD

**Issue by jsobell** [aurelia/cli#189]
Minor enhancement request - Perhaps it's only on my monitors, but blue text on a black console is illegible. A minor issue, but if you could use either cyan or another higher contrast colour for the appropriate CLI data items, that would be awesome

**Comment by EisenbergEffect** [comment]
Is this referring to things like `generator-name`?

**Comment by EisenbergEffect** [comment]
Reference to workaround for future fix: https://github.com/BrowserSync/browser-sync/issues/1137#issuecomment-231535505
