### ISSUE TITLE
Error not reported

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/cli#190]
Hi, 

I have the following result while using au run

```
Tracing konnect/viewmodels/core/components/event-img...
Tracing konnect/viewmodels/core/components/konnect-combo...
Tracing konnect/viewmodels/core/components/konnect-combosearch...
Tracing konnect/viewmodels/core/components/konnect-docs...
Tracing konnect/viewmodels/core/components/konnect-plan...
Tracing konnect/viewmodels/core/components/lkf...
Tracing konnect/viewmodels/core/components/markdown...
Tracing konnect/viewmodels/core/components/transac-launcher...
Tracing konnect/viewmodels/core/designer/data-source...
Tracing konnect/viewmodels/core/designer/k-view-designer...
Tracing konnect/viewmodels/core/designer/k-view-preview...
[ggrimbert@ggrimbert testWebApp]$ 
```

I found that the problem is because the file imports another that doesn't exist anymore. Doesn't this error be shown ?

**Comment by ggrimbert** [comment]
Little update, 

The process never goes to the end. At each time, it ends on a file, but this file has no error. Even if the file contains nothing (juste export class XXXXX).

I am lost...

**Comment by EisenbergEffect** [comment]
Looks like you are using Kendo bridge. Is that correct?

**Comment by ggrimbert** [comment]
Yes I am, the loading of kendo fails, but it's at the beginning.

A lot of files are read after.

The strange thing is that I ended by setting the code of a passing file into the failing one, but it still fails.

**Comment by EisenbergEffect** [comment]
This isn't the build that is failing, it's the process of tracing the dependencies.

**Comment by ggrimbert** [comment]
I am trying to completely remove kendo from my app, will see if something better occurs.

**Comment by ggrimbert** [comment]
Ok, Kendo was responsible for that failing. So I have to wait kendo-ui-bridge to make all requirements for the CLI.

**Comment by JeroenVinke** [comment]
@ggrimbert are you still having issues with the cli+aurelia-kendoui-bridge combo?

**Comment by ggrimbert** [comment]
Well, I've forgot about this issue...

No the problem hasn't happened for a while. I can close this.
