### ISSUE TITLE
Minify markup

### ISSUE THREAD

**Issue by Gheoan** [aurelia/cli#191]
In order to reduce bundle size, views should be minifed.

**Comment by TylerJPresley** [comment]
I've implemented this in my own project. I'll post some code when I get back to the office.

**Comment by TylerJPresley** [comment]
`npm install gulp-htmlmin --save-dev`
*/aurelia_project/tasks/process_markup.js*
```import gulp from 'gulp';
import changedInPlace from 'gulp-changed-in-place';
import project from '../aurelia.json';
import htmlMin from 'gulp-htmlmin';
import {build} from 'aurelia-cli';

export default function processMarkup() {
  return gulp.src(project.markupProcessor.source)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(htmlMin({collapseWhitespace:true}))
    .pipe(build.bundle());
}```

**Comment by TylerJPresley** [comment]
I've got another issue out for access to env vars so that you can enable/disable based on env.

**Comment by EisenbergEffect** [comment]
I think we can build the minification in, just like we do for JS. That would allow us to control it with the same environmental flag we do today. We could build css minification in as well. Building it in would enable it to also handle plugins, not just app source. The gulp-based approach you have above is always an option and is what I'd recommend people do until we instrument the build system more fully with this.

**Comment by Gheoan** [comment]
Fixed by https://github.com/aurelia/cli/commit/23da2b6a1d06fc44ba42d06e093899e4e5c9d8c6.
