### ISSUE TITLE
Trying to get aurelia-i18n running with typescript

### ISSUE THREAD

**Issue by masterpoi** [aurelia/cli#192]
I've added this to aurelia.json

``` json
       {
            "name": "i18next",
            "path": "../node_modules/i18next/dist/umd",
            "main": "i18next"
          },
          {
            "name": "i18next-browser-languagedetector",
            "path": "../node_modules/i18next-browser-languagedetector/dist/umd",
            "main": "i18nextBrowserLanguageDetector"
          },
          {
            "name": "i18next-localstorage-cache",
            "path": "../node_modules/i18next-localstorage-cache/dist/umd",
            "main": "i18nextLocalStorageCache"
          },
          {
            "name": "i18next-xhr-backend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },
          {
            "name": "aurelia-i18n",
            "path": "../node_modules/aurelia-i18n/dist/amd",
            "main": "aurelia-i18n"
          }
```

however the package name specified in for instance i18next-xhr-backend is actually i18nextXHRBackend:

``` javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define('i18nextBrowserLanguageDetector', factory) :
  (global.i18nextBrowserLanguageDetector = factory());
}(this, function () { 'use strict';
```

So these imports

``` typescript
import * as XHR from 'i18next-xhr-backend';
import * as Cache from 'i18next-localstorage-cache';
import * as LanguageDetector from 'i18next-browser-languagedetector';
```

import `undefined` since the package names don't match.

If i change the imports to 

``` typescript
import * as XHR from 'i18nextXHRBackend';
```

the tracer won't find src/i18nextXHRBackend.js

If i change the declarations like:

``` json

                    {
            "name": "i18nextXHRBackend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },

```

the package analyser uses the wrong directory to try to find package.json "../node_modules/i18nextXHRBackend/package.json".

There doesn't seem to be a way to change this behavior of using the name of the package to find the package.json file.

Is this an aurelia-thing (i18n, cli?)  or an i18next thing?
One way i can see this issue being resolved is to be able to override the path the analyser looks for package.json, but not sure if that is the most elegant way.

**Comment by EisenbergEffect** [comment]
It's an alpha cli bug.

**Comment by masterpoi** [comment]
Workaround / Solution: add this to require.js mapping configuration:

```typescript
require.config({
map: {
      "*" : {
            "i18next-xhr-backend": "i18nextXHRBackend",
            "i18next-localstorage-cache": "i18nextLocalStorageCache",
            "i18next-browser-languagedetector": "i18nextBrowserLanguageDetector"
        }
}
})
```

**Comment by gbouteiller** [comment]
@masterpoi Thank you for the workaround. Can you tell me where to put it?

**Comment by masterpoi** [comment]
Create a config.js file in your scripts folder and include that in the prepend in aurelia.json vendor-bundle:
```json
"bundles": [
      {
        "name": "vendor-bundle.js",
        "prepend": [

          "node_modules/bluebird/js/browser/bluebird.js",
          "scripts/require.js",
          "scripts/config.js"
        ],
....

```

**Comment by gbouteiller** [comment]
@masterpoi that's what I've just done waiting for your answer ;). Thanks again for the tip. ;)

**Comment by gravsten** [comment]
I am having a similar problem in a TypeScript-based Aurelia project, which was working until I installed aurelia-i18n following the instructions.

Now, 'gulp build' fails with the error message:
main.ts(2,20): error TS2307: Cannot find module 'aurelia-i18n'.
main.ts(3,21): error TS2307: Cannot find module 'i18next-xhr-backend'

This is based on Aurelia 1.0 (not RC1 !), and specifically aurelia-i18n 1.0.
Any idea how gulp-typescript looks up for these modules ?

They are both present under .\jspm_packages\npm,
although obviously there is no *.d.ts for 'aurelia-i18n',
yet I have copied i18next-xhr-backend.d.ts to the .\typings folder.

**Comment by gravsten** [comment]
Problem solved for me. There were several issues:
1) aurelia-i18n installed with jspm has no .d.ts file,
-> copy https://raw.githubusercontent.com/aurelia/i18n/master/dist/aurelia-i18n.d.ts
and fix its contents
2) also fix the contents of i18next-xhr-backend.d.ts
3) change gulpfile.js to process those custom .d.ts files
4) change main.ts to fix errors in the documentation of aurelia-i18n,
specifically: import * as Backend from 'i18next-xhr-backend';
and: ns: ['translation', 'nav'],
        defaultNS: 'translation',

If only Aurelia 1.0 had shipped with all (and correct) .d.ts files needed, as well as correct documentation, it would have saved me a sleepless night.

**Comment by len-ro** [comment]
I managed to get the i18n working with the following:
In aurelia.json
```
{
            "name": "aurelia-i18n",
            "path": "../node_modules/aurelia-i18n/dist/amd",
            "main": "index"
          },
          {
            "name": "i18next-xhr-backend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },
          {
            "name": "i18next",
            "path": "../node_modules/i18next/dist/umd",
            "main": "i18next"
          }
```

added typings as decribed here: https://github.com/aurelia/i18n

in code:

```
import { I18N } from 'aurelia-i18n';
import * as XHR from 'i18next-xhr-backend';
```

**Comment by mttmccb** [comment]
This seems to be resolved, I've got it working in the same way as @len-ro

**Comment by JeroenVinke** [comment]
The instructions provided by @len-ro seem to be described in the [docs](http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/1) now
