### ISSUE TITLE
Access to environment varialbles

### ISSUE THREAD

**Issue by TylerJPresley** [aurelia/cli#194]
I see that you can access the env by `let env = CLIOptions.getEnvironment();`. Can we get a function that loads the vars as well? ex: `let envVars = CLIOptions.getEnvironmentVars();`

I want to be able to set a minify and gzip flag in `/aurelia_project/environments/*` and be able to use that in my gulp tasks.

**Comment by EisenbergEffect** [comment]
Those environment modules are intended to be used at runtime, imported into the actual application. As long as you realize that, it could be possible to provide such a helper.

**Comment by TylerJPresley** [comment]
I understand that. I just think it would be better to be able to use the environment flag instead of the environment. Then it doesn't matter what I name the env. ex: local, local-machine1, remote-test, etc. Otherwise, I'm forced to write conditions for every env in my tasks.

**Comment by JeroenVinke** [comment]
You could do

```
let myTask = () => {
  const envSettings = require(`../environment/${CLIOptions.getEnvironment()}`);
}
```

While this is possible, I wouldn't recommend it for the reasons mentioned before. Instead, I'd put these settings in aurelia.json:

```
{
  "configs": {
    "minify": "dev & prod"
  }
}
```

and use the Configuration API that the CLI exposes to parse that:

```
import project from '../aurelia_project.json';
import {Configuration} from 'aurelia-cli';

let myTask = () => {
  let config = new Configuration(project.config);
  // this would take the env into account
  config.isApplicable('minify');
}
```
