### ISSUE TITLE
requirejs paths

### ISSUE THREAD

**Issue by dpinart** [aurelia/cli#197]
Hi

Using jspm/Systemjs I could manually map paths like done in config.js file. How can I map paths with requirejs?

**Comment by EisenbergEffect** [comment]
Open up the aurelia_project/aurelia.json file.
Inside the build section, you will see the bundle definitions. Have a look at those and you will see how you can add some path information there.

**Comment by dpinart** [comment]
Maybe I'm doing something wrong or it's not possible to achieve what I'm trying with requirejs. I could with systemjs.
Thanks to dependency-injection I'd like to create services that are "injected" at run time. As I'm coding in typescript I can easily declare a module like the following one
```

declare module 'my-service
{
  export class MyService
  {
    doSomething();
  }
}
```

then, in a view model I can inject the service:
```
import {MyService} from 'my-service';
@autoinject
export class MyViewModel
{
  constructor(private myService: MyService)
  {}
  activate(){
    this.myService.doSomething();
  }
}
```
I can define several implementations of this service. For example, depending on the targetting backend implementation may be different... I also like to supply an implementation for local dev.

With systemjs I could define a default mapping in config.js file, i.e "my-servce": "default-my-service" but I could also override mappings at runtime invoking System.config({map:{...}});

Do you think I can achieve same behaviour with requirejs?

**Comment by masterpoi** [comment]
There is this: http://requirejs.org/docs/api.html#config-map

**Comment by dpinart** [comment]
thanks @masterpoi. It's working like a charm
