### ISSUE TITLE
`au new --here` crashes

### ISSUE THREAD

**Issue by AnderssonPeter** [aurelia/cli#199]
When i run `au new --here` in a directory i get the following crash:
```
C:\Users\...\AppData\Roaming\npm\node_modules\aurelia-cli\bin\aurelia-cli.js:3
const resolve = require('../lib/resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
node version: 0.12.2(node -v) / 5.4.1(properties of the exe)
npm version: 2.7.4
OS: Windows 10, build 10586.420

**Comment by AnderssonPeter** [comment]
Same crash happens if i just write au

**Comment by EisenbergEffect** [comment]
NodeJS version 4.x or higher is required by the CLI.

**Comment by EisenbergEffect** [comment]
(You are running a very old version of Node.)

**Comment by AnderssonPeter** [comment]
im using the version provided by visual studio community installation.

**Comment by EisenbergEffect** [comment]
@AshleyGrant Do you know anything about this? If that's the case, VS is way, way out of date. How is this normally handled?

**Comment by AnderssonPeter** [comment]
Im confused.
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External`: 5.4.1
`C:\Program Files (x86)\nodejs`: 0.12.2
im unsure how those got installed i didn't do it manually.

**Comment by AnderssonPeter** [comment]
i uninstalled the 0.12.2 version and installed 4.4.6 and now it works correctly.

**Comment by EisenbergEffect** [comment]
Excellent. If you have any feedback on how we can improve our docs for future VS devs, please don't hesitate to share. Sorry for the confusion!

**Comment by AshleyGrant** [comment]
@madskristensen what version of Node is VS2015 shipping with these days?

**Comment by AnderssonPeter** [comment]
Checked my work computer and it also has `0.12.2`.
