### ISSUE TITLE
wrong bundle path when setting relative tagret in config

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/cli#200]
I like the idea of clean output of CLI workflow.
I also am in the process of enriching a web site with aurelia.enchance
I figured that I don't want to pollute already crowded folder of a mvc5 app and had set up the aurelia cli based app in an adjacent folder.

Then I instructed CLI to output bundles to the scripts folder of mvc app

```
 "build": {
    "targets": [
      {
        "id": "default",
        "displayName": "Default",
        "output": "../mvc.app/scripts"
      }
    ], 
```

now bundle metadata in vendor-bundle contains additional path for app-bundle
`"app-bundle":"../../mvc.app/scripts/dynamic-comments-bundle"`

**Comment by EisenbergEffect** [comment]
I'll be honest, we hadn't considered that type of organization at all. We'll need to see how we can address this but it may take some time, since we need to focus on issues related to more standard setups. Feel free to make recommendations for a fix or submit PRs. As usual, community help is welcomed and encouraged.

**Comment by flytzen** [comment]
I've just run into this problem as well. As far as I can tell, this is essentially the same as this PR: https://github.com/aurelia/cli/issues/173. 
The work-around described in there fixed it for me.

**Comment by Alexander-Taran** [comment]
To be fair, I worked that around.
For development I used symlinks from au project /dist to /scripts folder or something in mvc project
and for deployment I created another cmd file that published /dist or export to subpath on IIS..

If this scenario is not interesting to anybody else, this can be closed

**Comment by Alexander-Taran** [comment]
related question on SO
https://stackoverflow.com/questions/43857681/aurelia-cli-build-to-parent-folder
can't answer it )-:

**Comment by Alexander-Taran** [comment]
Workaraundable..
