### ISSUE TITLE
error installing fetch in typescript project

### ISSUE THREAD

**Issue by dpinart** [aurelia/cli#201]
Hi
Not sure if this is the right place for this issue...
I've created a new Typescript aurelia project that uses http-fetch-client plugin. As I need to support edge browser I need to install fetch polyfill si I run 'npm install fetch --save' command that throws following error:
npm WARN package.json patient-appointments@0.1.0 No README data
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fetch" "--save"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.9.0-dev.20160627-1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.12.1 wants typescript@>=1.7.3

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\ics-web\patient-appointments\npm-debug.log

Despite the above error I can see 'fetch' folder in the node_modules folder.
I then added the 'fetch' module within the  vendors-bundle dependencies.

running au run command I got following error:

{ uid: 9,
  name: 'writeBundles',
  branch: false,
  error:
   { [Error: ENOENT: no such file or directory, open 'C:\Projects\ics-web\patient-appointments\src\http.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Projects\\ics-web\\patient-appointments\\src\\http.js',
     moduleTree: [ 'fetch' ],
     fileName: 'C:/Projects/ics-web/patient-appointments/node_modules/fetch/lib/fetch.js' },
  duration: [ 3, 555100087 ],
  time: 1467153449344 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error:
   { [Error: ENOENT: no such file or directory, open 'C:\Projects\ics-web\patient-appointments\src\http.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Projects\\ics-web\\patient-appointments\\src\\http.js',
     moduleTree: [ 'fetch' ],
     fileName: 'C:/Projects/ics-web/patient-appointments/node_modules/fetch/lib/fetch.js' },
  duration: [ 5, 4261441 ],
  time: 1467153449354 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { [Error: ENOENT: no such file or directory, open 'C:\Projects\ics-web\patient-appointments\src\http.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Projects\\ics-web\\patient-appointments\\src\\http.js',
     moduleTree: [ 'fetch' ],
     fileName: 'C:/Projects/ics-web/patient-appointments/node_modules/fetch/lib/fetch.js' },
  duration: [ 5, 5977479 ],
  time: 1467153449355 }

**Comment by dtaalbers** [comment]
I have the same problem with the `aurelia-http-client` Any suggestion on this?

**Comment by EisenbergEffect** [comment]
You need to follow two steps currently:

1. First npm install the library.
2. Add the library to the bundle config in the aurelia.json file.

In the future we will have a cli command to assist in this, but it is manual for now.

**Comment by dpinart** [comment]
Sorry @EisenbergEffect 
That's what exactly I did, I first added fetch library with npm install fetch --dev and then added "fetch" library into the vendors bundle.

I've seen in fetch.js library that it first requires a set of libraries (http, https, dns,...).

For some reason it seems that npm install does not downloads dependencies (I installed nodejs 4.4 a few days ago in order to use aurelia-cli)

**Comment by EisenbergEffect** [comment]
It sounds like you are using a Node only fetch implementation, not one designed for the browser. Per the docs, we recommend this: https://github.com/github/fetch

**Comment by dpinart** [comment]
yes you're right, I installed fecth instead of whatwg-fetch. Now it's working fine

Thanks a lot

**Comment by iturner100** [comment]
I'm also having problems with bundling fetch within a typescript cli project but I'm already using whatwg-fetch as recommended.

I suspect I'm referencing it incorrectly in aurelia.json. I'm just adding ```"whatwg-fetch"``` to the vendor-bundle dependencies.

The error is:

```
{ uid: 1,
  name: 'readProjectConfiguration',
  branch: false,
  error: 
   { [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\node_modules\fetch\package.json']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\node_modules\\fetch\\package.json' },
  duration: [ 0, 11338823 ],
  time: 1467898466168 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\node_modules\fetch\package.json']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\node_modules\\fetch\\package.json' },
  duration: [ 0, 41414886 ],
  time: 1467898466197 }
{ [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\node_modules\fetch\package.json']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\node_modules\\fetch\\package.json' }
```

I also tried changing the dependency to be:

```
{
"name": "fetch",
"path": "../node_modules/whatwg-fetch",
"main": "fetch"
}
```

but still get the same error...

I've attached the example.

Any pointers?

[Aurelia.Vscode.zip](https://github.com/aurelia/cli/files/352269/Aurelia.Vscode.zip)

**Comment by EisenbergEffect** [comment]
I believe that's a non-modular code file. Try adding it to the prepend section of the bundle. I'll keep this open to investigate further.

**Comment by iturner100** [comment]
I had tried that too and was still getting an error:

```
Tracing main...
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error: 
   { [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\src\fetch.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\src\\fetch.js',
     moduleTree: [ 'main' ],
     fileName: 'd:/Source/Tests/aurelia-cli-test/src/Aurelia.Vscode/src/main.js' },
  duration: [ 1, 416240082 ],
  time: 1467901888991 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\src\fetch.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\src\\fetch.js',
     moduleTree: [ 'main' ],
     fileName: 'd:/Source/Tests/aurelia-cli-test/src/Aurelia.Vscode/src/main.js' },
  duration: [ 3, 926665435 ],
  time: 1467901889007 }
{ [Error: ENOENT: no such file or directory, open 'd:\Source\Tests\aurelia-cli-test\src\Aurelia.Vscode\src\fetch.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'd:\\Source\\Tests\\aurelia-cli-test\\src\\Aurelia.Vscode\\src\\fetch.js',
  moduleTree: [ 'main' ],
  fileName: 'd:/Source/Tests/aurelia-cli-test/src/Aurelia.Vscode/src/main.js' }
```

The vendor-bundle prepend section of aurelia.json was

```
"prepend": [
  "node_modules/bluebird/js/browser/bluebird.core.js",
  "node_modules/whatwg-fetch/fetch.js",
  "scripts/require.js"
]
```

**Comment by EisenbergEffect** [comment]
The paths you show above don't seem to match your configuration at all. Are you sure you don't have something else going on? some other configuration you forgot to remove? For example, why is it looking for `src/fetch.js`. Are you importing that in code? If so, then you will need a proper module dependency. I will need to investigate further if that's the case.

**Comment by iturner100** [comment]
Ah, good shout! I was doing an ```import "fetch"``` at the top of main.

I've exclusively used jspm with Aurelia until now, and that's a hangover from the guidance in the docs http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/2 

Still finding my way with the cli...

**Comment by EisenbergEffect** [comment]
Well, that *should* work so it's probably a bug in the cli as well. But, maybe you can remove that and the use the prepend as a temporary workaround?

**Comment by iturner100** [comment]
It seems to work fine without the import and just using the prepend (based on a simple test of whether Edge displays anything!). Thanks.
