### ISSUE TITLE
bundling HTML imports

### ISSUE THREAD

**Issue by dpinart** [aurelia/cli#202]
Hi

How can/must I set up aurelia.json file in order to bundle HTML imports like described in 
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-your-app-for-deploy/8 ?

**Comment by EisenbergEffect** [comment]
We don't support html import bundling at this time. It's not something we are planning for the near-term with the CLI. We may revisit this at a later time.

**Comment by dpinart** [comment]
I guess I can try to vulcanize polymer elements and see if it works

**Comment by AnderssonPeter** [comment]
Now that you have hit 1.0 with Aurelia are there any news on this? Aurelia CLI is great but its sad that you can't use some of the awesome plugins that the community has created.

**Comment by dpinart** [comment]
@AnderssonPeter I think you do not longer need this plugin, you can use and bundle your polymer apps like you do with any other widget library like bootstrapp,.. following link might interest you
[issue 14](https://github.com/aurelia/html-import-template-loader/issues/14)

**Comment by Alexander-Taran** [comment]
maybe can be closed

**Comment by EisenbergEffect** [comment]
I think the best path is to move to Webpack and then ask the web components community to support Webpack.
