### ISSUE TITLE
Creating multiple bundle

### ISSUE THREAD

**Issue by dpinart** [aurelia/cli#203]
Hi
I have an aurèlia application organized in modules, the folder structure looks like
src/
     module1/
         services/
         views/
     module2/
         services/
         views/
     app.html
     app.ts
     main.ts
     environment.ts
I'm trying to create 4 sepaate bundles, vendor-bundle, app-bundle, module1-bundle and module2-bundle. I configured bundle section in aurèlia.json as follows:

```
"bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[*.js]",
          "*.{css,html}"
        ]
      },
      {
        "name": "module1-bundle.js",
        "source": [
          "[module1/**/*.js]",
          "module1/**/*.{css,html}"
        ]
      },
      {
        "name": "module2-bundle.js",
        "source": [
          "[module2/**/*.js]",
          "module2/**/*.{css,html}"
        ]
      },

      {
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "scripts/require.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-fetch-client",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-polymer",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-html-import-template-loader",
          "aurelia-templating-binding",
          {
            "name": "text",
            "path": "../scripts/text"
          },
          {
            "name": "aurelia-templating-resources",
            "path": "../node_modules/aurelia-templating-resources/dist/amd",
            "main": "aurelia-templating-resources"
          },
          {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev"
          }
        ]
      }
    ]

```

so, for app-bundle I expect it only contains app.ts, app.html, main.ts and environment.ts
for module1-bundle I expect it contains all files in module1 folder and subfolders, same for module2, but after runnin au build command all, app-bundle.js, module1-bundle.js and module2-bundle.js are empty

**Comment by EisenbergEffect** [comment]
@AshleyGrant Can you confirm if the globs above are correct?

**Comment by AshleyGrant** [comment]
I don't believe they are. The first bundle's glob would likely override the second two (the module globs). I'll have to test to make sure. It might be a few hours before I can get to this.

**Comment by dpinart** [comment]
Hi any new about this issue? Am I'm doing something wrong, is there a bug on aurelica-cli bundler or is a not supported yet feature?

I'd like to decide wether to continue with an aurelia-cli project or create a new classic jspm/systemjs

**Comment by EisenbergEffect** [comment]
There was at least one bug in bundling that was discovered independently which may affect this. The update will be going out shortly. Perhaps you can try that and see if it addresses your issue.

**Comment by EisenbergEffect** [comment]
Released version 0.13.7.
See if that happens to address your issue. It seems at least related.

**Comment by dpinart** [comment]
Hi @EisenbergEffect 
I just run npm install -g aurelia-cli. Version 0.13.8 was installed. No luck, all bundles, except vendor-bundle.js are still empty

**Comment by TylerJPresley** [comment]
This is the only way I could get it to fill in the files. I still get errors where things can't find each other.

```
    "bundles": [
      {
        "name": "app.js",
        "source": [
          "[*.js]",
          "*.html",
          "[**/account/**/*.js]",
          "**/account/**/*.html",
          "[**/dashboard/**/*.js]",
          "**/dashboard/**/*.html",
          "[**/resources/**/*.js]",
          "**/resources/**/*.html"
        ],
        "dependencies": [
          "jquery",
          "toastr",
          "moment",
          "nprogress",
          "clone",
          "numeral",
          "store",
          "bootstrap-datepicker",
          {
            "name": "chart.js",
            "path": "../node_modules/chart.js/dist/",
            "main": "Chart.bundle"
          },
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist/js",
            "main": "bootstrap"
          }
        ]
      },
      {
        "name": "login.js",
        "source": [
          "[**/login/**/*.js]",
          "**/login/**/*.html"
        ]
      }

**Comment by Jenselme** [comment]
I have the same issue. With @TylerJPresley answer I can fill the bundles. However, they are not loaded, so my app is just a blank page. @TylerJPresley how did you make aurelia load you bundles?

**Comment by TylerJPresley** [comment]
@Jenselme I had the same issue. I could get the files to fill, but nothing knew about anything else. I'm just using a single bundle for now.

**Comment by Jenselme** [comment]
@TylerJPresley I got it. In my bundles, I was missing app.js, app.html, main.js, enviroment.js and a few files specific to my app. Since these files were missing and are required for the app to work, I was stuck with a blank page. To fix this, I created a `common-bundle.js` with these files:

```json
{
    "name": "common-bundle.js",
    "source": [
        "[**/app.js]",
        "[**/environment.js]",
        "[**/main.js]",
        "[**/services/options.js]",
        "[**/services/storage.js]",
        "[**/services/browser-sniffer.js]",
        "[**/widgets/aot-options/*.js]",
        "**/app.html",
        "**/widgets/aot-options/*.html"
    ]
}
```

**Comment by TylerJPresley** [comment]
@Jenselme I was able to get it to mostly work. The issue I'm seeing now is that some of the files are still getting loaded. Like if I load login it still loads members.js although it doesn't load organizations.js. I'm not sure why some files get loaded and others don't.

**Comment by AStoker** [comment]
Does this have any improvement?
I don't want to have to define each sub folder for the bundles.  
I used to (with the SystemJS setup) be able to define an `includes` which "defined" all the files, and then use the `excludes` to ignore the files that would make up the second bundle. And then in the second bundle, just include the files there were previously excluded.  
This doesn't seem to be possible so far with the CLI, correct?

**Comment by AStoker** [comment]
@dpinart, do the new changes on how you can define bundles solve your issue?

**Comment by EisenbergEffect** [comment]
Is this still an issue? We've had a bunch of improvements over the last couple of months.

**Comment by AStoker** [comment]
My guess is this issue is closed now with the new updates. Unless @dpinart is still having issues.

**Comment by dpinart** [comment]
I finally got back to jspm so currently all my projects are still with jspm. I do expect to start a new project in short and want to try cli again and migrate everything if I succeed

**Comment by AStoker** [comment]
Sound good. Perhaps if you run into the issue again, raise up the issue (and feel free to reference this one), but in the mean time, perhaps we can close it @EisenbergEffect ?
