### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by rapitkan** [aurelia/cli#205]
It should be possible to add an arbitrary version number to the end of bundles (app-bundle.js and vendor-bundle.js) for preventing cache problems after version updates. At the moment there is a hard coded file name (vendor-bundle.js) in index.html.

**Comment by kuechlerm** [comment]
Is there a strategy for cache busting?

**Comment by rapitkan** [comment]
Timestamp could be a great start. Another options is to generate version number by content of the bundle. It would be different each time. Maybe the timestamp with milliseconds is an easier option...? Generated vendor-bundle-xxxxxx.js file could be injected into index.html so that user wouldn't have to worry about it.

**Comment by TylerJPresley** [comment]
I've been playing with a final build step that is working, but is not the best solution. I've renamed a few things from stock, and this won't account for multiple bundles.

**aurelia_project/tasks/revision.js**
```
import gulp from 'gulp';
import replace from 'gulp-replace';
import rev from 'gulp-rev';
import intercept from 'gulp-intercept';
import del from 'del';
import moment from 'moment';
import project from '../aurelia.json';

let timestamp = moment().format('YYYYMMDDHHmmss');
let appBundle = null;

export function cacheBuster() {
  return gulp.src('index.html')
    .pipe(replace(/\?rev=\d{14}/g, `?rev=${timestamp}`))
    .pipe(gulp.dest('./'));
}

export function appVersion() {
  return gulp.src('version.json')
    .pipe(replace(/\d{14}/g, timestamp))
    .pipe(gulp.dest('./'));
}

export function revAppBundle() {
  del(['app/app-*.js']).then(paths => {
    console.log('Deleted files and folders:\n', paths.join('\n'));
  });
  return gulp.src('app/app.js')
    .pipe(rev())
    .pipe(intercept((file) => {
      appBundle = file.path.split('/').splice(-1)[0];
      return file;
    }))
    .pipe(gulp.dest('app/'));
}

export function injectAppBundle() {
  return gulp.src('app/aurelia.js')
    .pipe(replace(/\.\.\/app\/app-.*'/g, `../app/${appBundle.split('.')[0]}'`))
    .pipe(gulp.dest('./app'));
}

export default gulp.series(
  cacheBuster,
  appVersion,
  revAppBundle,
  injectAppBundle
);
```

**aurelia_project/tasks/build.js**
```
...
import revision from './revision';

export default gulp.series(
  readProjectConfiguration,
  gulp.parallel(
    transpile,
    processMarkup,
    processCSS,
  ),
  writeBundles,
  revision
);

...
```

**Comment by rapitkan** [comment]
Good to know that there is progress with version numbering.

**Comment by egeland** [comment]
Isn't it normal to just use a hash of the file as the "version", so that if the contents don't change, the hash will be the same, and you get the benefit of caching. Basing on timestamp might completely negate those caching benefits?

I think there's a gulp plugin for file versioning that does this already?

**Comment by TylerJPresley** [comment]
@egeland you're right. And that's happening with app-bundle in the example above. You could do this better. This was a quick way to handle cache busting. While not the most optimized, it is easy. Everyone's setup is going to be a little different. This offers some level of flexibility. You could rev() every single file.

**Comment by Boolos** [comment]
I noticed this flag in the source: https://github.com/aurelia/cli/blob/master/lib/build/bundler.js#L20

Are there any plans to implement this natively into the cli relatively soon?  I'm trying to decide if I should do a temporary hack similar to what @TylerJPresley suggested or wait for it to be included into the cli.

**Comment by AStoker** [comment]
Bump. Is there any progress on this anywhere? There's a line in the cli for revisions, but it's not being used anywhere. If there's no progress, I'm going to take a stab at it and make a PR, but if somebody is working on it, it would be good to know so that I don't step on toes :)

**Comment by EisenbergEffect** [comment]
Go for it!

**Comment by AStoker** [comment]
So one of the issues that will arise with revision numbers is how we reference the vendor bundle in the `index.html`. If the `vendor-bundle.js` suddenly has a different name, then the `index.html` must update that name.  
We could put an additional option in the `aurelia.json` that points to the `index.html` so that we can automatically update the script tag. Thoughts?
