### ISSUE TITLE
Adding support for creating a new Aurelia project with a Wakanda Backend

### ISSUE THREAD

**Issue by Ganbin** [aurelia/cli#206]
According to [this post on Twitter](https://twitter.com/AureliaEffect/status/747811794496983040) I come to you to see how we could integrate a scaffolding of Aurelia inside a Wakanda solution and integrate it in your CLI.

I see that in your CLI, we have 6 steps : 
1. Choose the name.
2. Choose the default setup.
3. Choose the transpiler.
4. Choose the css processor.
5. Choose if we want unit testing.
6. Choose the code editor.

So I see we could add a step to choose the backend solution. Maybe we could choose a nodeJS/mongoDB solution or in my case a Wakanda backend.

So this way we could have a full stack solution to develop our app.

Maybe we could choose in the first step if we want to integrate our Aurelia app inside an existing backend or create a fullstack solution.

Then we could be able to choose a Wakanda backend.

A Wakanda solution need a Wakanda Server to run. We can download the Server and the Studio in the [official website](https://wakanda.github.io/)

So how do you see we could integrate a Wakanda project with the Aurelia CLI?

**Comment by EisenbergEffect** [comment]
Currently we support the `--here` flag like this `aurelia new --here` which allows the selection of a platform. One idea is that you could create your Wakanda project like normal, then cd into the project folder and run `aurelia new --here`, select the Wakanda platform options and then we can add/alter the Wakanda project files to include Aurelia based on the developer's selections.

**Comment by Ganbin** [comment]
Ok I see now. I have try to use the `--here` parameter and we could have the Wakanda option in the first step when we choose a custom setup.

So I have try to setup an app inside my Wakanda project, but when I try to run `aurelia run` I get an error.

Here is my config :

```
Project Configuration

    Name: Wakanda-AureliaCLI
    Platform: Default
    Transpiler: Babel
    CSS Processor: None
    Unit Test Runner: None
    Editor: Atom
```

Here is the error code : 

```
Starting 'readProjectConfiguration'...
{ uid: 3,
  name: 'readProjectConfiguration',
  branch: false,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 16206754 ],
  time: 1467280496590 }
{ uid: 2,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 40572825 ],
  time: 1467280496614 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 42334505 ],
  time: 1467280496615 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 44739021 ],
  time: 1467280496616 }
{ [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/aurelia-binding/package.json' }
MacBook-Pro-de-Gabriel:web Gabriel$ aurelia run
Starting 'readProjectConfiguration'...
{ uid: 2,
  name: 'readProjectConfiguration',
  branch: false,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 12205119 ],
  time: 1467280622605 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 24940685 ],
  time: 1467280622617 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/aurelia-binding/package.json' },
  duration: [ 0, 26599666 ],
  time: 1467280622618 }
{ [Error: ENOENT: no such file or directory, open 'node_modules/aurelia-binding/package.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/aurelia-binding/package.json' }
```


I have another question. What is the choice `What is your default code editor?` influence in the build of the app?

**Comment by Ganbin** [comment]
Ok I see now my mistake was to not install the dependencies at the end of the prompt. If I let the CLI install dependencies I am able to use the project.

**Comment by Ganbin** [comment]
So if we could choose the Wakanda platform when using the `--here` flag, we could imagine to set up a default Aurelia build with the wakanda-javascript-client included, inside the webfolder of a Wakanda project.

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @Ganbin ?

**Comment by Alexander-Taran** [comment]
@3cp hmm.. I'd close this one (-:
