### ISSUE TITLE
Adding typescript files while running watch crashes typescript project

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/cli#208]
When running 
`au run --watch`
and
`au generate element test`

Causes the following error:

> Error: gulp-typescript: A project cannot be used in two compilations at the same time. Create multiple projects with createProject instead.

When I change tasks/transpile.ts to

```
[...]
function buildTypeScript() {
  // create tsProj every time to avoid error
  //if(!typescriptCompiler) {
    typescriptCompiler = ts.createProject('tsconfig.json', {
      "typescript": require('typescript')
    });
  //}
[...]
```

... the error is gone, but I am not sure about the performance implications. Maybe you can think of a better way.

**Comment by TylerJPresley** [comment]
There's a similar error with es6. where it breaks during watch, but as soon as i reload the run it will build and run fine.

**Comment by EisenbergEffect** [comment]
@TylerJPresley That is probably a different issue.

**Comment by swalters** [comment]
@EisenbergEffect cli was basically useless to me when using typescript and webstorm.  It crashed on about every 5th save.  I made the changes specified above and haven't had a problem since.

**Comment by EisenbergEffect** [comment]
Would someone be able to submit a PR for this?

**Comment by Thanood** [comment]
See #404, just removed the `if(!typescriptCompiler)` check.

**Comment by mttmccb** [comment]
This looks like it can be closed.

**Comment by EisenbergEffect** [comment]
Thanks!
