### ISSUE TITLE
How to install dependencies

### ISSUE THREAD

**Issue by dpinart** [aurelia/cli#209]
Hi
I created a new typescript project with aurelia-cli. I pushed it to a git repo and want to clone in another labtop. Once git downloads the project I run npm install but only dependencies present at package.json (aurelia-animator-css, aurelia-bootstrapper and aurelia-fetch-client) have been downloaded to the node_modules folder. If I execute command 'au-run' I get an error about node_modules/aurelia-binding is missing

**Comment by EisenbergEffect** [comment]
You need to use NPM 3 to restore a project so that it makes all dependencies at the top level.

**Comment by vinodkanpurne** [comment]
Hi while installing project dependencies for ESnext project it is giving me error "npm Err! git clone-- .....Undefined"

**Comment by EisenbergEffect** [comment]
You need to have a Git client installed.

**Comment by 1q2q1q1q** [comment]
I have an issue to run the first app in windows by using aurelia.io framework. When I run the app, the page did not bund data properly. I have install a Git client in windows, still have the bunch of same error "npm Err! git clone-- .....Undefined" . How to deal with this problem

**Comment by DevVIN** [comment]
@1q2q1q1q  Please try to using Git-Bash for installing aurelia cli instead cmd

**Comment by 1q2q1q1q** [comment]
Yeah, fixed it. Thanks, DevVIN. Another way to fixed this problem is use "cache clean npm" command on cli. Then after clean the cache, we install aurelia-cli by using "npm install -g aurelia-cli".
