### ISSUE TITLE
Referencing (global) 3rd party libraries

### ISSUE THREAD

**Issue by teves-castro** [aurelia/cli#210]
When referencing certain 3rd party libraries (circular-json in my case) when using aurelia with jspm requires us to specify the library format as global, otherwise the library won't be correctly bundled.

How can the same be accomplished using aurelia-cli?

Put in another form, when the above library is intalled from npm while using aurelia-cli, it doesn't get correctly bundled.

**Comment by EisenbergEffect** [comment]
We will be enabling `shim` config in the near future with globals support. As a workaround, you can use the library as a standard global script by adding it to the `prepend` section of the bundle.

**Comment by EisenbergEffect** [comment]
This is now possible with CLI 0.16.0.

I'm writing an update now for the readme that explains configuring 3rd party libraries.

If you can't wait another hour or two, I've updated the `app-contacts` sample to be based on the CLI. It uses jQuery, Bootstrap and NProgress.
