### ISSUE TITLE
Font Colors do not work for PowerShell Blue

### ISSUE THREAD

**Issue by Vaccano** [aurelia/cli#211]
The CLI Home page says to use powershell if you can't use bash.

But if you do then you can't read the Urls when you enter `au run`.

They show up fine with a black background (ie cmd prompt).  But look as if they are not there on powershell (even when selected).  

But if you copy paste it to another editor they are there.

**Comment by EisenbergEffect** [comment]
We are investigating. The particular urls are generated by browser sync, not by the CLI directly. We are trying to find out if we can change the colors somehow.

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate for now. We've got it tracked elsewhere with a temporary workaround we'll be applying soon.
