### ISSUE TITLE
What are the steps after runing `new`

### ISSUE THREAD

**Issue by bigopon** [aurelia/cli#213]
Hi, currently I'm getting error of 'no such file or directory' when trying to import HttpClient from 'aurelia-fetch-client'

code: 
```javascript
import {HttpClient} from 'aurelia-fetch-client'
...
```

error:
```
Error: ENOENT: no such file or directory, open '...\aurelinew\src\aurelia-fetch-client.js'
```

Do I need to install or configure anything or what am I doing wrong here? I run `au run` immediately after finished and don't use any plugins

**Comment by EisenbergEffect** [comment]
First you need to `npm install aurelia-fetch-client`.
After that, you need to go into the `aurelia_project/aurelia.json` file and add the following to the dependencies section:

```
"aurelia-fetch-client"
```

That should do it for you. In the future we'll have cli commands for importing libraries into a project so you won't need to edit the project file.

**Comment by bigopon** [comment]
Sorry for making you type the readme again. Overlooked that part.

Thanks

**Comment by wallaceturner** [comment]
Rob is this still the current way of doing this? i've looked at the 'au' CLI help but doesnt appear to be an 'install' or similar there yet

**Comment by JeroenVinke** [comment]
@wallaceturner initial work has been done in this area. Take a look at https://github.com/aurelia/cli/pull/454 which has recently been merged and will be available in the next CLI release.

**Comment by wallaceturner** [comment]
btw there is no mention of *how* to install either package in the docs
e.g. on this page [1] it would be *really* handy for all the n00bs (which is pretty much everyone wrt aurelia) if you could specify how to do it
e.g. insert Robs instructions above into the docs in a nicely highlighted box somewhere near the top

[1]: http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/1



[1]: http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/3

**Comment by sbolel** [comment]
[here's an excellent post](https://ilikekillnerds.com/2016/08/adding-aurelia-fetch-client-aurelia-cli-project/) on adding the fetch client to a CLI project. If you search for "aurelia fetch client cli" in Google, it should be the first one that comes up -- just in case you forget to bookmark it. Hope that helps! i did the same thing a few days ago, let me know if you run into any issues.
