### ISSUE TITLE
Enable New Plugin Project

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/cli#215]
@levan-g commented on [Wed Mar 09 2016](https://github.com/aurelia/skeleton-plugin/issues/20)

---

@doktordirk commented on [Sat Mar 26 2016](https://github.com/aurelia/skeleton-plugin/issues/20#issuecomment-201837251)

working on it sortof. have added it to the spoonx plugins. so i have quite the good idea now on howto for community plugins

---

@EisenbergEffect commented on [Mon Jul 04 2016](https://github.com/aurelia/skeleton-plugin/issues/20#issuecomment-230329334)

We'll be adding support to the CLI for creating plugins.

**Comment by doktordirk** [comment]
on this note. i'm trying to get out plugins working with cli. in on oth them we have
import jwtDecode from 'jwt-decode'. i can add it to the aurelia.json dependencies, but this plugin consists of several files. au run will complain with 
```sh
Tracing app...
{ uid: 9,
  name: 'writeBundles',
  branch: false,
  error:
   { [Error: ENOENT: no such file or directory, open 'C:\Users\dirk\aurelia\aurelia-authentication-loopback-sample\client-cli-es2015\src\base64_url_decode.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\dirk\\aurelia\\aurelia-authentication-loopback-sample\\client-cli-es2015\\src\\base64_url_decode.js',
     moduleTree: [ 'jwt-decode' ],
     fileName: 'C:/Users/dirk/aurelia/aurelia-authentication-loopback-sample/client-cli-es2015/node_modules/jwt-decode/lib/index.js' },
  duration: [ 0, 318871375 ],
  time: 1467654544164 }
```

suggestions?

**Comment by EisenbergEffect** [comment]
We'll be supporting the same build resources section of the package.json that our webpack setup does. We just haven't implemented that in the cli just yet.

**Comment by levan-g** [comment]
any progress on this feature?

**Comment by maikelRA** [comment]
I'm trying to migrate an application to aurelia-cli, but I have the same error with jwt-decode. Some solution for this issues.

**Comment by mttmccb** [comment]
Isnt #195 a duplciate? Although this is more active the other should probably be closed.

**Comment by EisenbergEffect** [comment]
Yep. Good catch. Thanks for helping with the maintenance. I'll close the other as a dupe.

**Comment by tochoromero** [comment]
Would this feature allow the Aurelia CLI create a Typescript Plugin skeleton?

In the meanwhile, what are you guys currently using when creating plugins in typescript?

**Comment by JeroenVinke** [comment]
Closing in favor of https://github.com/aurelia/cli/issues/658, it's close to being done
