### ISSUE TITLE
Styling plugin

### ISSUE THREAD

**Issue by bigopon** [aurelia/cli#216]
Hi, currently when choosing `stylus` / `postcss`, how do I tell Aurelia cli to include the plugin for those preprocessors (`nib` for `stylus`, `cssnext` ... for `postcss`).

And what is a good approach for styling in aurelia? styling component individually or all in 1 style file?

Beside this, is there option to to add a pre-processor in an existing cli-generated project ?

**Comment by EisenbergEffect** [comment]
You can add plugins after the cli sets up your project really easily. If you look in `aurelia_project/tasks` you will see the `process-css` task. These tasks are just souped-up gulp tasks. They use Gulp 4 and are written in ESNext/Typescript (depending on what you told the CLI you wanted). So, all you have to do is configure the gulp tasks with the plugins you want.

There are various approaches you can take for styling in Aurelia. Personally, I like to have a single CSS file per view.

To add preprocessors to an existing CLI project, simply locate the `process-css` task and customize it to use whatever you want.

**Comment by bigopon** [comment]
Thanks Rob,

Another question regarding loading styl, currently I'm doing it like this:
```html
<require from="./styles/main.styl"></require>
```

The `main.style` file is under `styles` folder inside `src` folder. However, i'm getting this error
```
GET http://localhost:9000/src/styles/main.styl.js 404 (Not Found)
Unhandled rejection Error: Script error for "styles/main.styl"
```

when doing
```html
<require from="./styles/main.css"></require>
```
it works as expected

**Comment by EisenbergEffect** [comment]
If you want to use .styl in your html, you would need to write an Aurelia plugin for that (to convert that to a .css load). It's probably easier to just use .css in your html since that is what the build process generates.

**Comment by EisenbergEffect** [comment]
Would you be interested in submitting a pull request to update the readme with this?

**Comment by bigopon** [comment]
#221
