### ISSUE TITLE
Support adding a CSS file

### ISSUE THREAD

**Issue by Vaccano** [aurelia/cli#218]
I was super excited for the Aurelia CLI.  It solves Aurelia's biggest problem, package loading.  (Which isn't really Aurelia's problem at all).

But after I got past the "new project" and "run" phase, I started trying to do real stuff.  That includes CSS.

I can't seem to figure out how to add a css file.  

I added one to my project, but it is not recognized.  (Does not affect the page.)  I added an `include` statement for it (like I do for Webpack) and that gave me an error looking for `styles.css.js`.

Some CSS guidance would be nice.

**Comment by EisenbergEffect** [comment]
Just add css files into the src folder and then use aurelia's `require` to bring them into a view. Or if you don't like that, you can handle css however you like in a more traditional way.

**Comment by Vaccano** [comment]
Ah, I did not need realize I needed to `require` them in.  Thank you!
