### ISSUE TITLE
Add "typed command" support for wizard questions.

### ISSUE THREAD

**Issue by advancedrei** [aurelia/cli#220]
Let me start this off first by saying: I was an idiot. 

I ran the CLI for a new project. For the first answer I picked "2". For the second question, for some stupid reason, I thought I needed to type "restart" instead of picking Option 2 to go back and selection more options. I had just typed a number for the first question, so this should not have been a difficult thing for me to understand. Yet somehow, it was.

The CLI treated by input as a confirmation to continue with the defaults, and did a bunch of stuff to my project.

Having previously established that I was an idiot, you might want to consider having the CLI accept the "label" values next to the number as alternative acceptable answer. That way, you can prevent future idiots like me from idioting all over themselves.

HTH! :D

**Comment by EisenbergEffect** [comment]
LOL 

This is good feedback. The CLI is till alpha and we definitely want to continue working on the user experience.
