### ISSUE TITLE
Add Jade / Pug as a markup processor choice in the wizard

### ISSUE THREAD

**Issue by ap91484** [aurelia/cli#223]
I am in the process of transferring a former navigation-skeleton based project to aurelia cli. All my templates are written in Jade (now renamed Pug), because I find the indent based structure of Jade much more readable and easier to use. You don't have to worry about tag endings etc.
I have added the support manually and used the css processor for Stylus as a blueprint.
After declaring the markup processor in aurelia.json, I use the following process-markup.js:

```
import gulp from 'gulp';
import changedInPlace from 'gulp-changed-in-place';
import sourcemaps from 'gulp-sourcemaps';
import jade from 'gulp-jade';
import project from '../aurelia.json';
import {build} from 'aurelia-cli';

export default function processMarkup() {
  return gulp.src(project.markupProcessor.source)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(sourcemaps.init())
    .pipe(jade())
    .pipe(build.bundle());
}
```

You have to install gulp-jade as a development dependency.

Best regards

Alex

**Comment by egeland** [comment]
This would be a very welcome addition to the cli tool!

**Comment by EisenbergEffect** [comment]
We've got a placeholder for other markup processors, so it shouldn't be difficult to add it. Thanks for putting together the task info. That should be all the info we need.

**Comment by EisenbergEffect** [comment]
I'm working on this now and just need a little help. Can someone show me how the following file would be written in pug?

https://github.com/aurelia/cli/blob/master/lib/resources/src/app.html

**Comment by ap91484** [comment]
Hi Rob,

in Pug this would be:

template
  h1 ${message}

The indent of the h1 is important.
There is an online converter at http://html2jade.org <http://html2jade.org/> . Just put in the html it converts to jade / pug.

Best regards,

Alex

**Comment by EisenbergEffect** [comment]
Is the file extension still `.jade` or is it `.pug` now?

**Comment by ap91484** [comment]
The extension is still .jade. They are in the conversion process and have gained the rights to use it somewhat further.
There is also a gulp-pug module, which should use the extension .pug. But I haven’t tried it.

**Comment by gbouteiller** [comment]
Hello, as everything is going to be "pugged", I think it would be wise to use .pug extension. I personally use gulp-pug a lot and it works well.

**Comment by ap91484** [comment]
I agree, for using pug. Its only a renaming and nothing else has changed as far as I know. Since aurelia-cli is in alpha the conversion should be complete when aurelia-cli RC is ready.

**Comment by ghidello** [comment]
And the next version, which is being developed, will be pug only so I guess that pug is the way to go.

**Comment by jlissner** [comment]
Has this been implemented yet?

**Comment by JeroenVinke** [comment]
Hey @jlissner, not yet. The quickest way to get this feature in is to work on it yourself. If you are interested, let me know. I can provide guidance.

**Comment by hcbelias** [comment]
Hi, I have interest in making it work in my project, could you provide some guidance?

**Comment by JeroenVinke** [comment]
@hcbelias I haven't tried this yet, but there is already a [process-pug.js](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/process-pug.js) and [process-pug.ts](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/process-pug.ts). You'd use this task instead of the html process task you have now. Although these tasks seem to use jade, and i'm not sure if that still works.

In order to get this into the CLI we need to know if those tasks still work and we'll have to add pug as an option [here](https://github.com/aurelia/cli/blob/81b029191f4752fecdaf0192bb03c7cd0bc87d8f/lib/commands/new/new-application.json#L302-L337).

**Comment by hcbelias** [comment]
It works nicely - for both gulp-jade and gulp-pug. 

If tyou want I can create a PR for it,

**Comment by JeroenVinke** [comment]
Glad that it works and a PR would be very welcome! Since webpack support is now in master we will have to add the necessary pug config for webpack as well to [this file](https://github.com/aurelia/cli/blob/master/lib/resources/content/webpack.config.template.js).

If that would be too much work then feel free to just add pug to [this file](https://github.com/aurelia/cli/blob/81b029191f4752fecdaf0192bb03c7cd0bc87d8f/lib/commands/new/new-application.json#L302-L337) and I will add the necessary configuration so that it works with webpack as well. 

Instructions on setting up a development environment for the cli can be found in our readme: https://github.com/aurelia/cli/blob/master/README.md#building

**Comment by Alexander-Taran** [comment]
stale since mid 2017
but looked almost ready

**Comment by EisenbergEffect** [comment]
Yes. If I recall it's partially implemented. @JeroenVinke might have some idea as to how much work would be required to complete this.

**Comment by jpravetz** [comment]
I've had pug working with cli for ages, but am migrating to webpack while da boss is out of town and not reming me of the feature list. I've got this so far.

## webpack.config.js rules and plugins

```javascript
  rules: [
    { test: /\.pug$/, loader: 'pug-loader', options: { pretty: true } }
    ]
```

```javascript
  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.pug',
      inject: true,
      metadata: {
        // available in index.pug under locals
        title, server, baseUrl
      }
    })
  ]
```

## index.pug 

```pug
- var metadata = locals.htmlWebpackPlugin.options.metadata
doctype html
html
  head
    meta(charset='utf-8')
    title #{locals.htmlWebpackPlugin.options.metadata.title}
    meta(name='viewport' content='width=device-width, initial-scale=1')
    base(href=metadata.baseUrl)
    // imported CSS are concatenated and added automatically

  body(aurelia-app='main')
    // Webpack Dev Server reload
    if (metadata.server)
      script(src='/webpack-dev-server.js')
```

## main.js

```
var Promise = require('bluebird') // Promise polyfill for IE11;
import {bootstrap} from 'aurelia-bootstrapper-webpack';
import {ViewLocator} from 'aurelia-framework';
```

```
bootstrap(function(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  ViewLocator.prototype.convertOriginToViewUrl = function (origin) {
    let moduleId = origin.moduleId;
    let id = (moduleId.endsWith('.js') || moduleId.endsWith('.ts')) ? moduleId.substring(0, moduleId.length - 3) : moduleId;
    return id + '.pug';
  }

  aurelia.start().then(() => aurelia.setRoot('app', document.body));
})
```

*But* my components aren't loading, with the complaint that the view can't be found `Unable to find module with ID: resources/elements/sort.pug`

I'm pretty sure this is a webpack.config.js rule thing, and I've found references to what I think are _dated_ fixes. Any ideas on the complete formula to get this working?

**Comment by Alexander-Taran** [comment]
@jpravetz could you create a step by step guide and PR it here https://github.com/aurelia-contrib/aurelia-getting-started/tree/master/guides ?
would be great to have a recipe for that (-:

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia-contrib/aurelia-getting-started/blob/master/guides/how-to-add-pug-to-cli-with-webpack.md

@jpravetz  thanks.. 4 years later (-:


@3cp can be closed I think
