### ISSUE TITLE
Minor: ESLint reports "Newline required at end of file but not found." for generated js files

### ISSUE THREAD

**Issue by egeland** [aurelia/cli#226]
Very minor thing, but it's a bit of a niggle to always see this error with newly generated files.
Can we add a newline, to make `ESLint` happy?

I see this when opening the `js` giles in the Atom editor, with the ESLint plugin installed.

```
$ au -v
0.13.8
```

**Comment by EisenbergEffect** [comment]
@egeland Ok, so to be clear, the js files like `main.js` and `app.js` are causing issues because they need an empty line at the end of the file. Is that correct?

**Comment by bigopon** [comment]
Not really relevant but having an option to define the perferred indent
would be nice. Currently it's fixed with 2.
