### ISSUE TITLE
cli switch processing errors

### ISSUE THREAD

**Issue by bcdev-com** [aurelia/cli#227]
A tiny bug, but one that had me looking for an hour in the wrong places:

"au build -env prod" executes a build without any errors, but not a production build.  "au build --env prod" works as expected.  

Requiring the double '--' for a long option is traditional, but should give an error when only a '-' is provided.  (Or short options should be available with a single '-'.)

**Comment by EisenbergEffect** [comment]
We do support `-e` actually. We'll need to enhance the parameter system to see if we can account for this mistake.

**Comment by bcdev-com** [comment]
Ah, perhaps "-env" was trying to use a non-existent environment "nv".  I didn't consider that.  Should still throw an error of course.

Thanks for all the great work.  Both Caliburn.Micro and Durandal served me well in the past, and my first Aurelia-based solution is live as of yesterday.

**Comment by EisenbergEffect** [comment]
Excellent news! Thanks for the feedback!
