### ISSUE TITLE
`au test --watch` and TypeScript SourceMaps

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/cli#232]
## aurelia-cli user story

> As a typescript developer
> - I want a TDD-based cli command (like `au test --watch`) that lets me set breakpoints
> - so that i can inspect my code as i'm developing 

notes: because the current implementation doesn't have source maps, i can only see the transpiled code for setting breakpoints.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Please use the issue template.

Also, source maps should be enabled. I've used them myself. Are you referring to the tests themselves or the app source?

**Comment by EisenbergEffect** [comment]
This is pretty low priority for me personally compared to other issues so the best way to get this fixed is going to be to submit a PR. My guess is that you are talking about source maps for the tests themselves, which probably has something to do with Karma configuration.

**Comment by cmichaelgraham** [comment]
i'll see if i can fix it...  would like to be able to set breakpoints and see typescript for both the tests and the app source
