### ISSUE TITLE
Typescript on Asp.net Core

### ISSUE THREAD

**Issue by beatsm** [aurelia/cli#234]
**I'm submitting a bug report**
- **Library Version:**
  0.15.0

**Please tell us about your environment:**
- **Operating System:**
  Windows [8.1]
- **Node Version:**
  4.4.5
  
  
- **NPM Version:**
  3.10.5
  
  
- **Language:**
  TypeScript 1.8.6 & 2

**Current behavior:**
I have tried to set-up Aurelia on latest ASP.NET Core using CLI.
I am getting error attached in picture when using au build

![image](https://cloud.githubusercontent.com/assets/3408087/16868857/cd5786a6-4a71-11e6-816e-995cbefeb389.png)

**Expected/desired behavior:**

Steps to reproduce:
1) Create Asp.net Core project in VS2015 Update 3
2) Change to the xproj directory
3) Run au new --here with the below options
    a) Platform -> ASP.NET Core
    b) Transpiler -> Typescript
    c) CSS Processor -> None
    d) Unit tests -> No
    e) Create this project -> Yes
    f) Install dependencies -> Yes
4) Run au build
- **What is the expected behavior?**
  
  Be able to bundle app.
- **What is the motivation / use case for changing the behavior?**

**Comment by iturner100** [comment]
That's probably because VS2015 has already transpiled the aurelia_project typescript files before you run au build. You can verify that by manually deleting the .js and .js.map files first then re-running au build.

Ideally you need to stop VS from doing the transpilation if you are using the aurelia-cli build tasks. Either that or change the cli tasks so it doesn't do the transpile step.

**Comment by beatsm** [comment]
@iturner100 thanks, deleting all the transpiled files allows it to build with au build and adding this to the tsconfig stops Visual Studio from complaining about aurelia-cli.

`"exclude": [
    "node_modules",
    "aurelia_project",
    "custom_typings"
  ],` 

Ideally I just want to press F5 and everything work, so do I just need to somehow lift the bundling step into VS and not use au build?

**Comment by iturner100** [comment]
The sweet spot for me would be to have VS do the tranpiling so you get any TS errors integrated in to the usual VS error pane. Then use the aurelia-cli for bundling etc.. And finally use Kestrel for dev server, with BrowserSync etc..

I've not got there yet unfortunately...

Using the Command Task Runner extension (https://visualstudiogallery.msdn.microsoft.com/e6bf6a3d-7411-4494-8a1e-28c1a8c4ce99) to add ```au build``` as a post-build task in VS helps to some 

Or you can call some of the aurelia-cli functionality directly from gulp within VS.

Using aurelia-cli inside VSCode works better, but being able to live just within VS2015 is the goal (for me, at least)...

**Comment by EisenbergEffect** [comment]
@AshleyGrant Since you just did a bunch of work on the asp.net skeletons, can you take a look at this and see what we can do as part of the CLI asp.net setup to improve this?

**Comment by AshleyGrant** [comment]
Yeah, I'll see what I can figure out

**Comment by JeroenVinke** [comment]
I believe that the we no longer need [this message](https://github.com/aurelia/framework/blob/master/doc/article/en-US/the-aurelia-cli.md#aspnet-core) if we merge the PR above:

> Info Since Aurelia-CLI should be in charge of building your client side code, make sure before running the new command from Aurelia-CLI you add <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked> to your .xproj file inside the first <PropertyGroup></PropertyGroup> you find to stop Visual Studio from compiling the .ts files in your project. If you build your solution before doing this, Visual Studio will compile your .ts files breaking some of the Aurelia-CLI commands.

I do wonder why we have included that message in the docs though. Simply running the project from VS will transpile the typescript files (and launch IIS), but it does not invoke the CLI at all, so it is not going to regenerate the bundles. On the other hand, running `au run --watch` runs the project using browsersync, and you'll not be using ASP.NET Core at all. [This bit](https://github.com/aurelia/framework/blob/master/doc/article/en-US/the-aurelia-cli.md#aspnet-core) leaves a lot to the imagination when it comes to running the app. @AshleyGrant when you are looking into [this issue](https://github.com/aurelia/cli/issues/531), can you also see whether or not i'm missing something or if the docs is really missing this info? 

My gut feeling is that we will want ASP.NET Core to serve the files from `wwwroot` (e.g. by adding `app.UseFileServer()` to the `Configure` method in `Startup.cs`). Then in the background we need to keep the bundles updated, but we don't need to run browsersync, so `au build --watch` could be helpful here. `au build --watch` was proposed in https://github.com/aurelia/cli/issues/265 for exactly this reason
