### ISSUE TITLE
Issue creating a project after npm update

### ISSUE THREAD

**Issue by jadrake75** [aurelia/cli#235]
**I'm submitting a bug report**

* **Library Version:**
0.16.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v5.3.0

* **NPM Version:**
3.8.3

* **Browser:**
N/A - command line

* **Language:**
all

**Current behavior:**
running `au new` results in a failed dependency

C:\src>au new
module.js:328
    throw err;
    ^

```
Error: Cannot find module 'vinyl-fs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\jadra\AppData\Roaming\npm\node_modules\aurelia-cli\lib\build\source-inclusion.js:4:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

```

**Expected/desired behavior:**
If vinyl-fs was needed I would have expected it to be called out in the package.json and installed/updated as needed.

**Workaround**
Manually install vinyl-fs with `npm install -g vinyl-fs`

**Comment by EisenbergEffect** [comment]
Try updating your global CLI. That is what sets up the project with vinyl-fs. It should be in there.

**Comment by jadrake75** [comment]
Nope.  That is what I did..... I ran "npm update -g aurelia-cli".  Until I manually install vinyl-fs it does not get past this point.  I also updated to Node 6.3 and npm 3.10 in an attempt to verify that is not the problem. So unless "global CLI" is not the same as the above line then that does not quite work.

**Comment by EisenbergEffect** [comment]
What version of the cli are you running globally. You can run `au -v` outside of an aurelia project to see the global version. Is that 0.16.0 or greater?

**Comment by jadrake75** [comment]
yes, after running npm update -g Aurelia-cli from a random location (look c:\temp) and then running au -v it reports as 0.16.0

One way you should be able to test.... do 
npm uninstall -g vinyl-fs
npm update -g Aurelia-cli
au new

**Comment by EisenbergEffect** [comment]
I....know what the issue is. One moment.

**Comment by EisenbergEffect** [comment]
Ok, try updating your global install to 0.16.1. That should do it.

**Comment by jadrake75** [comment]
yep.... I uninstalled globally vinyl-fs and did a npm install -g Aurelia-cli and it operates correctly.

**Comment by EisenbergEffect** [comment]
Sorry about that ;)

**Comment by jadrake75** [comment]
These are easy problems for an early implementer to workaround.... but I believe in the project and want to see it become a hit amongst everyone!  So whatever way I can help to make it better I am game.... keep rolling....!
