### ISSUE TITLE
CSS resources of dependencies are not locatable at Runtime on Windows

### ISSUE THREAD

**Issue by jadrake75** [aurelia/cli#236]
**I'm submitting a bug report**
- **Library Version:**
  0.16.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.3.0
- **NPM Version:**
  3.10.6
- **Language:**
  ESNext

**Current behavior:**
The CLI bundles are not able to locate any css dependencies which are loaded as resources with dependencies.  Examples include bootstrap.css, bootstrap-datepicker3.css, select2.css etc.

I believe this is a windows only issue.  After analyzing the dependency definitions of my generated css from less, I noticed a key difference in the define strings.  When my css/less is references the define statements have the path segments separated as '/'.  Whereas for resource included items the page segments are '\'.  It would appear the moduleId is being referenced using an OS specific path separator.

Manually changing the bundled files resolves this issue.

After hunting, I believe the place to possibly make the change/fix is on line 50/51 of source-inclusion.js in the addAllMatchingResources function.  In this function, before the item.moduleId is set, forcing/coercing the moduleId into WEB URI standard format (aka / ) resolves this issue.  I added a 

`moduleId = moduleId.replace(/\\/g, '/');`

and the problem is resolved.

**Comment by EisenbergEffect** [comment]
This one has bit us more than once before. I'll get the fix in shortly and make a patch release. Thanks for PRing it!

**Comment by JeroenVinke** [comment]
@EisenbergEffect I believe this was fixed. Can this issue be closed?
