### ISSUE TITLE
Provide the ability to exclude files from a bundle

### ISSUE THREAD

**Issue by jadrake75** [aurelia/cli#238]
**I'm submitting a feature request**

* **Library Version:**
0.16.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.6

* **Browser:**
N/A

**Expected/desired behavior:**
Provide the ability to exclude source or resource patterns from bundling.  From poking through the source I do not see this ability at first glance, but documenting the various options esp. around the bundle config options would be a *huge* help.

* **What is the motivation / use case for changing the behavior?**
You may have source based elements that make sense to process with your other src elements, but they may be further processed or managed by other build artifacts.  The example I have is a splash screen less file which I want to build and process using the theme less files from src into a .css, but want to deploy it to a target resource folder in place of the scripts folder in a bundled resource.  Effectively anything in src/ that matches the .css/.html/.js extension will get picked up in the bundling.  

The other case is you want to partition a portion of the src into different bundles.  Without an exclude rule you have to implicitly declare the inclusions which gets cumbersome.

**Comment by EisenbergEffect** [comment]
You can negate the blog patterns. is that sufficient?
All globbing is done with https://www.npmjs.com/package/minimatch

**Comment by jadrake75** [comment]
Perhaps my globulation skills are amiss.....  in my case I am trying an example to exclude the theme css since it will be included in a bootstrap-theme bundle.  In order to make this work I needed to do the following...

1. Modify the cssProcessor to exclude the theme files since it pipes it to the bundler

```
    "cssProcessor": {
        "id": "less",
        "displayName": "Less",
        "fileExtension": ".less",
        "source": [
            "src/**/*.less",
            "!src/theme/*.less"
          ]
   }
```

I did not have to change the app-bundle.js module, but this may be because of the ! above I am effectively not generating css into the bundle pipeline for that directory, so I am assuming that I will have to also use it there?

```
        "bundles": [
            {
                "name": "app-bundle.js",
                "source": [
                    "[**/*.js]",
                    "[**/*.{css,html}]",
                    "![**/theme/*.css]"
                ]
            } ]

```

I was hoping I could just exclude them in the bundles config and avoid the processCSS source exclusion, because I still want them to be processed, just not into the app-bundle

**Comment by EisenbergEffect** [comment]
Do you want the theme css to go into a different bundle other than app? or no bundle at all?

**Comment by jadrake75** [comment]
Ideally I would like to generate a second bundle.  Similar to how you might partition your application.  One use case brought up on gitter was to have bundles for the Administrative client separate from the main end-user app for example

**Comment by AStoker** [comment]
Bump. Any resolution to this?

**Comment by EisenbergEffect** [comment]
I haven't had a chance to look at it yet. If it's pressing, we'd love for you to investigate :)

**Comment by AStoker** [comment]
Yah, we need a way to define what is essentially a "sub-module" that's a section of the code inside the `src` folder. Used to be able to do this with the regular aurelia bundler. I imagine that the CLI uses the aurelia bundler underneath? So it might just be a matter of getting that to interface correctly. But since I'm on a time crunch trying to get some stuff working, I was secretly hoping that it was already resolved, and I had just been doing it stupidly ;)

**Comment by EisenbergEffect** [comment]
It's completely unrelated to the other bundler. The other bundler is very system-builder specific. The cli bundler should be able to do this...there must be a bug lurking in there. If someone can set up a very simple little project with bundle config and explanation of what should happen, I can probably take a look next week.

**Comment by AStoker** [comment]
Think I just found my weekend project 😃

**Comment by AStoker** [comment]
I'm thinking about adding this to the `source-inclusion.js` file:
```javascript
isExcluded(item){
    let found = this.excludes.findIndex(x => {			
      let exclusion = new this.bundle.Minimatch(x);
      return exclusion.match(item.path);
    });
    return found > -1;
  }

  trySubsume(item) {
    if (this.matcher.match(item.path) && !this.isExcluded(item)) {
      item.includedBy = this;
      item.includedIn = this.bundle;
      this.items.push(item);
      return true;
    }

    return false;
  }
```  
This would then allow an `excludes` option in the bundle alongside `source`. It would simply act as a filter for whatever was included. So an example would be like this:
```
"source": [
          "[**/*.js]",
          "**/*.{css,html}"
        ],
"excludes": [
          "**/sub-module/**/*",
          "**/*.test.js"
        ]
```
This would result in the defined bundle including all files _except_ ones that exist inside the `sub-module` folder, and files that have the `.test.js` extension.  
How would this approach sound @EisenbergEffect? Would that approach be sufficient for at least a first go at this option? If so, I'll make a PR with it and we can discuss further there.

**Comment by EisenbergEffect** [comment]
Is there some way we could do it under the existing `source` array property but using a `!` instead?

**Comment by AStoker** [comment]
That's what I had tried to do, but the regex for this got complex fast, and ultimately couldn't get it to work (either from me doing it incorrectly, or minimatch not working the way I'd expect it).

**Comment by EisenbergEffect** [comment]
I thought that minimatch already handled that syntax though...

**Comment by AStoker** [comment]
The use case that we ran up against was this.
We needed 3 bundles:  
 1. Vendor Bundle
 2. Application Bundle
 3. Form Bundle (used for both the application and external iframes to load up a minimum set of files alongside the Vendor Bundle)

With this setup. We needed the app bundle to exclude all files that ended with `.test` or `.spec`, as well as any file in the folder `form/viewer`. And then likewise, we needed the form bundle to have all the files inside the `form/viewer` folder.  
What we tried was the following pattern (which failed).
```
 "[**/!(form/viewer)/**/!(*.spec|*.test).js]",
```
After many hours of trying to get just the right pattern set up, I thought it would be helpful to have a more similar syntax and bundling set up like the one in the Aurelia Bundler (which supports the `excludes` option). It definitely simplifies the configuration for patterns, especially for people who are not too savvy on glob routes.
Thoughts?

**Comment by AStoker** [comment]
To clarify what failed in the provided pattern, files that contained `.spec` or `.test` were still included in the bundle.

**Comment by EisenbergEffect** [comment]
Ok, got it. I'm just not sure about adding an excludes property at that location. What if we made the value of `source` take either an array or an object:

```json
"source": [
  "[**/*.js]",
  "**/*.{css,html}"
]
```

or 

```json
"source": {
  "include": [
    "[**/*.js]",
    "**/*.{css,html}"
  ],
  "exclude": [
    "**/sub-module/**/*",
    "**/*.test.js"
  ]
}
```

We could provide backwards compat and simplicity with the older structure but add the new one on for the future. This also keeps source related settings together so they aren't confused with something related to dependencies or other properties we may add in the future. That do you think?

**Comment by AStoker** [comment]
I like that much better :)

**Comment by EisenbergEffect** [comment]
Cool. Feel free to put together a PR. Make sure to test your own scenario as well as the basic setup from the cli.

**Comment by AStoker** [comment]
Sounds like a plan. I didn't notice a testing setup like we have for a few of the plugins. Is there an appropriate way to test this? Or just use the skeleton project to test?

**Comment by EisenbergEffect** [comment]
At the moment we don't have a real good test strategy around this. I usually just run the cli and test various scenarios. We'll need to address that eventually.
