### ISSUE TITLE
BrowserSync Proxy

### ISSUE THREAD

**Issue by gbouteiller** [aurelia/cli#239]
**I'm submitting a feature request**

* **Library Version:**
0.16.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.5

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Currently, BrowserSync is configured as a server.

**Expected/desired behavior:**
It would be great to have the possibility to choose between a server or a proxy ( for example, in the aurelia.json configuration file).

* **What is the motivation / use case for changing the behavior?**
Many of my Aurelia projects are also Wordpress projects ( I use Aurelia as a Theme ) with custom directories and handled locally with Apache as vhosts.

**Comment by EisenbergEffect** [comment]
Is there some reason you can't just go into the run task and change the configuration? One of the reasons why we generate the tasks like that is so that they can be customized.

**Comment by gbouteiller** [comment]
@EisenbergEffect That's what I'm currently doing but I thought it was meant to be configured in the config file and that modifying tasks directly was kind of a hack.

**Comment by EisenbergEffect** [comment]
The tasks are literally there so you can modify them to your specific needs.

**Comment by EisenbergEffect** [comment]
If you feel very strongly about this, submit a PR to update the cli with this capability and we can take a look at it and discuss it in more detail.

**Comment by gbouteiller** [comment]
It's ok for me as it is as long as you say it is not by practice to modify the tasks ( I did the same for pug template files and saw that someone posted an issue about it, that is why I created this one ) :)
