### ISSUE TITLE
au build --watch

### ISSUE THREAD

**Issue by Aniel** [aurelia/cli#240]
**I'm submitting a feature request**
- **Library Version:**
  0.16.1

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  v6.2.2
  
  
- **NPM Version:**
  3.10.3
  
  
- **Browser:**
  all
- **Language:**
  all 

**Current behavior:**
The build command has no support for a --watch argument

**Expected/desired behavior:**

Let the build command watch files for changes with the --watch flag

**What is the motivation / use case for changing the behavior?**
If i want to use a different server (asp.net core kestrel) for serving my files au run --watch has unnecessary overhead.

**Comment by TylerJPresley** [comment]
Remove the server section and port number from the browsersync config in run.js. You'll still be able to run. You'll just have to include the browsersync reload script on your page.

**Comment by zamotany** [comment]
Replace `aurelia_project/tasks/build.js` with:
```
import gulp from 'gulp';
import transpile from './transpile';
import processMarkup from './process-markup';
import processCSS from './process-css';
import {build} from 'aurelia-cli';
import project from '../aurelia.json';
import {CLIOptions} from 'aurelia-cli';

function readProjectConfiguration() {
  return build.src(project);
}

function writeBundles() {
  return build.dest();
}

function onChange(path) {
  console.log(`File Changed: ${path}`);
}

let buildTask = gulp.series(
  readProjectConfiguration,
  gulp.parallel(
    transpile,
    processMarkup,
    processCSS
  ),
  writeBundles
);

let watch = function() {
  gulp.watch(project.transpiler.source, buildTask).on('change', onChange);
  gulp.watch(project.markupProcessor.source, buildTask).on('change', onChange);
  gulp.watch(project.cssProcessor.source, buildTask).on('change', onChange)
}

let task;

if (CLIOptions.hasFlag('watch')) {
  task = gulp.series(
    buildTask,
    watch
  );
} else {
  task = buildTask;
}

export default task;
```


Original answer: ['watch' option for the 'build' task #265](https://github.com/aurelia/cli/issues/265)

**Comment by jedd-ahyoung** [comment]
This issue was referenced during the Amsterdam meetup. While it's possible to add the watch by altering the gulp scripts, it may be worth it to have this as a default option.

**Comment by JeroenVinke** [comment]
Let's continue in https://github.com/aurelia/cli/issues/265 as it seems to be about the same enhancement
