### ISSUE TITLE
au build fails if output folder does not exist

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/cli#241]
**I'm submitting a bug report**

* **Library Version:**
0.16.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.5

* **Browser:**
n/a

* **Language:**
TypeScript 2.0.0

**Current behavior:**

I changed in aurelia.json:
platform.output = 'build'
build.targets[0].output = 'build' 

`au build` fails with log-output:

`
Writing vendor-bundle.js...                                                                                                                 
{ uid: 8,                                                                                                                                   
  name: 'writeBundles',                                                                                                                     
  branch: false,                                                                                                                            
  error:                                                                                                                                    
   { [Error: ENOENT: no such file or directory, open 'c:\Users\[...]\build\app-bundle.js']        
     errno: -4058,                                                                                                                          
     code: 'ENOENT',                                                                                                                        
     syscall: 'open',                                                                                                                       
     path: 'c:\\Users\\[...]\\build\\app-bundle.js' },                                        
  duration: [ 17, 887043932 ],                                                                                                              
  time: 1468919595509 }                                                                                                                     
[...]                                        
`

There is no error, if I create the folder 'build' before 'au build'.

**Expected/desired behavior:**
Should work without 'build' (or other configured target) being present //
the missing folder should be created by aurelia-cli (/gulp-task).

**What is the motivation / use case for changing the behavior?** 
CI-Server checks out code -> no 'build'-Folder present.

**Comment by CasiOo** [comment]
Very annoying when you want a clean prod build.
Building the project doesn't clean the output directory, so you'll manually have to clean it. The most direct way is to remove the output directory all together. Removing the directory then results in the above error when building.

**Comment by diefans** [comment]
how do I define separate output directories for `au run --watch`and `au build --env prod`?
I do not want to change code when generating the final distribution...
