### ISSUE TITLE
Configure paths for LESS import files in "cssProcessor" section of `aurelia.json`

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/cli#244]
**I'm submitting a feature request**

* **Library Version:**
0.16.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.7

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When processing LESS files, it is NOT possible to specify paths for `@import` directives in `aurelia.json` "cssProcessor" section. Paths are used by `gulp-less` plugin to find imported files, like in the basic usage example from their [page](https://github.com/plus3network/gulp-less):

```
var less = require('gulp-less');
var path = require('path');

gulp.task('less', function () {
  return gulp.src('./less/**/*.less')
    .pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ]
    }))
    .pipe(gulp.dest('./public/css'));
});
```

**Expected/desired behavior:**
It should be possible to specify additional paths for `@import` directives in `aurelia.json` "cssProcessor" section.

* **What is the expected behavior?**
To be able to specify paths for `@import` directives.

* **What is the motivation / use case for changing the behavior?**
To build bootstrap with bootstrap theme and with additional user specific modifications.
For example:

```
@import '../../node_modules/bootstrap/less/variables.less';
@import '../../node_modules/bootstrap/less/bootstrap.less';

@import 'Bootswatch/Slate-3.3.6/variables.less';
@import 'Bootswatch/Slate-3.3.6/bootswatch.less';

@import 'https://fonts.googleapis.com/css?family=Roboto';
body {
    font-family: 'Roboto', sans-serif;
}
```

**Comment by EisenbergEffect** [comment]
I'm confused. What is stopping you from updating the task for your needs?

**Comment by nenadvicentic** [comment]
OK, I got it.

In this particular case `paths` are not needed. Problem was a `**` wild card in the "cssResource" property `"source": "src\\**\\*.less"`. When I configure it to point to a single file everything works fine:

```
  "cssProcessor": {
    "id": "less",
    "displayName": "Less",
    "fileExtension": ".less",
    "source": "src\\theme\\site.less"
  },
```
Thanks
