### ISSUE TITLE
html template - require from fails for absolute URL

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/cli#245]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 0.16.2

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.2.2

* **NPM Version:**
3.9.5

* **Browser:**
Chrome Version 52.0.2743.82 m (64-bit)

* **Language:**
TypeScript 1.8.10

**Current behavior:**

> When I require a local html file, it works, but when I require an html file from an absolute URL, i get an error in the debugger and the app doesn't load.

> * Note: I am using github, so i believe the CORS headers are automatically returned.
> * Note: There is no network request in the chrome debugger for the html file.

Here's the error that happens right away:

```
vendor-bundle.js:3675 Uncaught TypeError: h.load is not a function

(anonymous function) @ vendor-bundle.js:3675
(anonymous function) @ vendor-bundle.js:3661
w @ vendor-bundle.js:3665
callPlugin @ vendor-bundle.js:3673
fetch @ vendor-bundle.js:3671
check @ vendor-bundle.js:3671
enable @ vendor-bundle.js:3677
enable @ vendor-bundle.js:3681
(anonymous function) @ vendor-bundle.js:3676
(anonymous function) @ vendor-bundle.js:3661
y @ vendor-bundle.js:3660
enable @ vendor-bundle.js:3675
init @ vendor-bundle.js:3670
(anonymous function) @ vendor-bundle.js:3680
3
```

and then a few seconds later, this error:

```
Unhandled rejection Error: Load timeout for modules: html-resource-plugin!http://cmichaelgraham.github.io/plotter/views/test01/test01.html,template-r…html,text!http://cmichaelgraham.github.io/plotter/views/test01/test01.html

http://requirejs.org/docs/errors.html#timeout
    
at Error (native)
    
at F (http://localhost:9001/scripts/vendor-bundle.js:3661:290)
    
at H (http://localhost:9001/scripts/vendor-bundle.js:3667:56)
    
at http://localhost:9001/scripts/vendor-bundle.js:3667:227
```

**Expected/desired behavior:**

steps to reproduce:

1. run bash shell
2. create directory
3. change to the new directory
4. `au new --here`
    1. choose (1) Web
    2. choose (2) TypeScript
    3. choose (2) Less
    4. choose (1) Yes - Configure unit testing
    5. choose (1) Visual Studio Code
    6. choose (1) Yes - create this project
    7. choose (1) Yes - install project dependencies

Project Configuration:

```
    Name: cli-test3           
    Platform: Web             
    Transpiler: TypeScript    
    CSS Processor: Less       
    Unit Test Runner: Karma   
    Editor: Visual Studio Code
```

then change `app.html` to this:

```html
<template>
  <require from="http://cmichaelgraham.github.io/plotter/views/test01/test01.html"></require>
  <h1>${message}</h1>
</template>
```
* **What is the expected behavior?**

> I would like to be able to load html and css from absolute URLs

* **What is the motivation / use case for changing the behavior?**

> Loading html and css files from absolute URLs allows me to build an Aurelia app that can be extended by customers.
> * They can place their extensions on an internal server behind their firewall
> * I can then use the Aurelia `compose` custom element to load their extensions

**Comment by cmichaelgraham** [comment]
my issue could be related to [XHR restrictions](https://github.com/requirejs/text#xhr-restrictions) on the text plugin

> if the text plugin determines that the request for the resource is on another domain, it will try to access a ".js" version of the resource by using a script tag. Script tag GET requests are allowed across domains. The .js version of the resource should just be a script with a define() call in it that returns a string for the module value.

i did try creating [test01.html.js](https://github.com/cmichaelgraham/cmichaelgraham.github.io/blob/master/plotter/views/test01/test01.html.js) also, but with the same result

i also noticed that i get the same result if i put in an invalid URL

**Comment by EisenbergEffect** [comment]
Does this fix your issue? https://github.com/aurelia/cli/pull/243
Also, for the xhr, you can always use a custom text plugin if it's an issue in there. I think we do for the docs site.

**Comment by cmichaelgraham** [comment]
i modified my `bundle.js` (hardwired to the absolute path in the PR above.  then i ran `au run --watch`

i got the same result described in the initial issue.

i'll look at modifying the text plugin next :smile:

**Comment by cmichaelgraham** [comment]
@EisenbergEffect - where is the requirejs module config set in the cli app?

[XHR restrictions](https://github.com/requirejs/text#xhr-restrictions)

> In some cases, you may want the text plugin to not try the .js resource, maybe because you have configured CORS on the other server, and you know that only browsers that support CORS will be used. In that case you can use the module config (requires RequireJS 2+) to override some of the basic logic the plugin uses to determine if the .js file should be requested:

```javascript
requirejs.config({
    config: {
        text: {
            useXhr: function (url, protocol, hostname, port) {
                //Override function for determining if XHR should be used.
                //url: the URL being requested
                //protocol: protocol of page text.js is running on
                //hostname: hostname of page text.js is running on
                //port: port of page text.js is running on
                //Use protocol, hostname, and port to compare against the url
                //being requested.
                //Return true or false. true means "use xhr", false means
                //"fetch the .js version of this resource".
            }
        }
    }
});
```

**Comment by cmichaelgraham** [comment]
also, the error mentions: `html-resource-plugin` - where is that defined?

```
html-resource-plugin!http://cmichaelgraham.github.io/plotter/views/test01/test01.html,template-registry-entry!http://cmichaelgraham.github.io/plotter/views/test01/test01.html,text!http://cmichaelgraham.github.io/plotter/views/test01/test01.html
```

**Comment by EisenbergEffect** [comment]
It auto-defined at runtime by Aurelia. That's probably not the real issue. It just uses the text plugin.

**Comment by cmichaelgraham** [comment]
@EisenbergEffect - i replaced the minimized require.js with the unminimized version, the problem is more clear:

![image](https://cloud.githubusercontent.com/assets/10272832/17078618/0f0f6318-50b5-11e6-8133-082b7083b4c2.png)

one of the plugins doesn't provide the `load` method.

the plugins are:

1. html-resource-plugin
2. template-registry-entry
3. text

where can i find the code for the 1st two?  does it make sense that they'd be missing the `load` function?

**Comment by cmichaelgraham** [comment]
ok, got it working in a reproducible set of steps:

1. run bash shell
2. create directory
3. change to the new directory
4. `au new --here`
    1. choose (1) Web
    2. choose (2) TypeScript
    3. choose (2) Less
    4. choose (1) Yes - Configure unit testing
    5. choose (1) Visual Studio Code
    6. choose (1) Yes - create this project
    7. choose (1) Yes - install project dependencies


Project Configuration:

```
    Name: cli-test3           
    Platform: Web             
    Transpiler: TypeScript    
    CSS Processor: Less       
    Unit Test Runner: Karma   
    Editor: Visual Studio Code
```

8. set `"stub": false` in loader section of `aurelia_project/aurelia.json`

```javascript
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": false
        }
      ]
```

9. edit `scripts/text.js` - always return true in `useXhr` function:

```javascript
        useXhr: function (url, protocol, hostname, port) {
            return true;
        },
```

10. create html and js files on github.io for compose element

> * [test01.html](https://github.com/cmichaelgraham/cmichaelgraham.github.io/blob/master/plotter/views/test01/test01.html)

```html
<template>
  <h1>Test01</h1>
  <p>${message}</p>
</template>
```

> * [test01.js](https://github.com/cmichaelgraham/cmichaelgraham.github.io/blob/master/plotter/views/test01/test01.js)

```javascript
define(["require", "exports"], function (require, exports) {
    "use strict";
    var Test01 = (function () {
        function Test01() {
            this.message = 'Hello World, from Test01 on GitHub !!! :)';
        }
        return Test01;
    }());
    exports.Test01 = Test01;
});
```

11. modify `app.html`

```html
<template>
  <h1>${message}</h1>
    <compose view-model="http://cmichaelgraham.github.io/plotter/views/test01/test01.js"></compose>
</template>
```

12. enter `au run --watch` in bash shell

13. point browser at `localhost:9000` (or whatever port is assigned)

14. you should see this:

![image](https://cloud.githubusercontent.com/assets/10272832/17080265/e3a49780-50e5-11e6-9ab5-9cbd083dd013.png)
