### ISSUE TITLE
aurelia-karma should use paths.root from aurelia.json

### ISSUE THREAD

**Issue by Jenselme** [aurelia/cli#246]
**I'm submitting a bug report**

* **Library Version:**
0.16.2

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora)

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Currently, for `aurelia-karma` to work correctly, the source files must be in a `src`. This is hard coded [here](https://github.com/aurelia/cli/blob/master/lib/resources/test/aurelia-karma.js#L52). So if your sources are in a different directory (like `app`) you will get errors like this from karma:

```
24 07 2016 22:03:51.578:WARN [web-server]: 404: /base/app/app
Firefox 47.0.0 (Fedora 0.0.0) ERROR
  Error: Script error for "app/app", needed by: test/unit/app.spec.js
  http://requirejs.org/docs/errors.html#scripterror
  at dist/vendor-bundle.js:3661
```

**Expected/desired behavior:**
- Configure in `aurelia.json` the paths for your app (eg sources in `app`)
- Run `au test`
- No errors, aurelia-karma should figure from `paths.root` in `aurelia.json` how to load the files correctly.

*Note:* If using `path.root` in `aurelia-karma` is too complicated, I think that a proper section in the documentation should be enough.

**Comment by EisenbergEffect** [comment]
Can you send a PR?

**Comment by Jenselme** [comment]
@EisenbergEffect do you have any idea how I can get access to the content of aurelia.json in aurelia-karma? I tried to use something from `global` or `global.karma` without success.

**Comment by Jenselme** [comment]
Just thought of another way to do this:

- ask the user in which folder the code must be
- replace ``/base/src`` based on the response of the user in the copied file.

What do you think? This could also be used to generate an ``aurelia.json`` file with the correct paths from the start.

**Comment by Jenselme** [comment]
@EisenbergEffect any thoughts on my previous comment? I am OK to create a PR for this, I just need your input.

**Comment by EisenbergEffect** [comment]
I would recommend just getting the info from aurelia.json. In the karma.conf file it is already loaded, so you just need to pass that info along to karma, the same way that the files are passed probably. You probably just need to research karma to see if there's a way to pass custom info along to the karma test page.

**Comment by Jenselme** [comment]
Go it! I have to use client.args to pass the config. PR under way.
