### ISSUE TITLE
npm-like commands

### ISSUE THREAD

**Issue by Gheoan** [aurelia/cli#252]
**I'm submitting a feature request**

**Current behavior:**
Current commands are hard to remember and do not match `git`'s and `npm`'s commands.

**Expected/desired behavior:**

* **What is the expected behavior?**
`cli`'s commands should match `git`'s and `npm`'s commands:
   - `init` instead of `new`
   - `start` instead of `run`
   - `publish` instead of `build` (debatable)
   - ...

* **What is the motivation / use case for changing the behavior?**
`cli`'s commands should be easier to remember.

**Comment by EisenbergEffect** [comment]
I don't see why we should copy something else or why these are easier to remember.
