### ISSUE TITLE
au test does not rebuild src

### ISSUE THREAD

**Issue by hadrienl** [aurelia/cli#254]
**I'm submitting a bug report**

* **Library Version:**
0.17.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
Chrome 51

* **Language:**
ESNext

**Current behavior:**
 I add a new file in src, a spec file in test folder, then I exec `au test`. My src file is not found (404)

**Expected/desired behavior:**

* **What is the expected behavior?**
If I want the file to be found I have to exec `au build` before starting tests. So I cannot use `au test --watch` because it will not build automatically my src files.

**Comment by zamotany** [comment]
You can manually modify `test.js` inside `aurelia_project/tasks` like this:
```
import build from './build';
import * as gulp from 'gulp';
import {Server as Karma} from 'karma';
import {CLIOptions} from 'aurelia-cli';
import * as project from '../aurelia.json';

let buildAndRun = gulp.series(
  build,
  done => {
    new Karma({
      configFile: __dirname + '/../../karma.conf.js',
      singleRun: true
    }, done).start();
  }
);

function onChange(path) {
  console.log(`File Changed: ${path}`);
}

function watch() {
  gulp.watch(project.transpiler.source, buildAndRun).on('change', onChange);
  gulp.watch(project.markupProcessor.source, buildAndRun).on('change', onChange);
  gulp.watch(project.cssProcessor.source, buildAndRun).on('change', onChange);
  gulp.watch(project.unitTestRunner.source, buildAndRun).on('change', onChange);
}

let exec;

if (CLIOptions.hasFlag('watch')) {
  exec = gulp.series(
    buildAndRun,
    watch
  );
} else {
  exec = buildAndRun;
}

export default exec;
```
This is `run.js` and oryginal `test.js` combined together to achive expected behaviour.
