### ISSUE TITLE
Feat: Move build output to its own directory

### ISSUE THREAD

**Issue by CasiOo** [aurelia/cli#255]
**I'm submitting a feature request**

* **Library Version:**
0.17.0

**Current behavior:**
Output is being mixed with module loader dependencies.
+-- /scripts
|   +-- require.js <- module loader dependency
|   +-- text.js
|   +-- app-bundle.js
|   +-- app-bundle.js.map
|   +-- vendor-bundle.js

**Expected/desired behavior:**
We do not want to mix our build with our dependencies. They should be separated into their own directories. Our module loader dependencies are already part of the vendor-bundle.

Following the structure of Aurelia's other repositories, we should place the output in `/dist`
+-- /dist
|   +-- app-bundle.js
|   +-- app-bundle.js.map
|   +-- vendor-bundle.js

Module loader dependencies can either be placed in `/aurelia_project/module_loader` or `/vendor/requirejs`. I do not like the `/scripts` naming, as it could contain just about anything.

**Comment by EisenbergEffect** [comment]
You can just change this yourself. It's all in the aurelia.json file.

**Comment by CasiOo** [comment]
You're right, I did make the changes and it worked. The issue is more about making it more convenience for others who are going to use the CLI. I think the above structure would make it easier to take your build and deploy it. Also it removes any confusion if `require.js` and `text.js` should be on your production server. I had that confusion myself, so I'm probably not the only one.

**Comment by danechitoaie** [comment]
> The issue is more about making it more convenience for others who are going to use the CLI

It would be. Better defaults would make more sense. Just started using the cli and I find it very confusing to how to generate the final bundle and what it needs to go on production and what not, and what is the structure of the folder in which app/vendor-bundle is loaded from...
