### ISSUE TITLE
Proxy capability in dev server

### ISSUE THREAD

**Issue by ldrews1** [aurelia/cli#256]
I am submitting a feature request.

Currently when debugging/testing with the dev server, http requests to a backend api on localhost require CORS permissions.  It would be much more convenient to have a proxy capability as exists in Webpack.  The production version of the application will be running on the same server as the api.

**Comment by stsje** [comment]
You can make browser-sync use a proxy middleware. Just edit the `run` task to use the middleware.
https://www.npmjs.com/package/http-proxy-middleware can help you setup a proxy.

Example:
```
var proxyMiddleware = require('http-proxy-middleware');
var proxy = proxyMiddleware('/foo-endpoint', {
    target: 'http://my.api.com',
    changeOrigin: true // for vhosted sites, changes host header to match to target's host
});

browserSync({
    online: false,
    open: false,
    ghostMode: false,
    port: 9000,
    server: {
      baseDir: ['.'],
      middleware: [proxy]
    }
  }, done);
```

**Comment by Ganbin** [comment]
Hello I come here because I have a problem bundle the `http-proxy-middleware`inside the `aurelia.json` config file.

I have add this : 

    {
      "name": "lodash",
      "path": "../node_modules/lodash/lodash",
      "main": "lodash"
    },
    {
      "name": "http-proxy",
      "path": "../node_modules/http-proxy/",
      "main": "index"
    },
    {
      "name": "http-proxy-middleware",
      "path": "../node_modules/http-proxy-middleware/lib/",
      "main": "index",
      "deps": ["lodash","http-proxy"]
    }

But still I get an error on the `au run` when it try to bundle the `http-proxy-middleware`.

I need to use this proxy to enable CORS on my application on the dev, because my app use a server on a different port.

**Comment by EisenbergEffect** [comment]
You shouldn't add that to the aurekis.json file unless you need it on the
client. That sounds like a server thing to me.

**Comment by psevestre** [comment]
Hi,

I´ve  tried to setup this middleware but after strugling with dependencies I eventually gave up and opted for a setup using caddy. 

Now I use "au run --watch" as usual but I point the browser to the caddy port. Its config file has two proxy entries, one for the aurelia cli server and another to my api server.

**Comment by alpox** [comment]
Hi all. I was able to setup the aurelia-cli with proxy to an ASP.NET server on a different localhost port with simply changing the browsersync task in run.ts:

```
let serve = gulp.series(
  build,
  done => {
    browserSync({
        proxy: {
          target: 'localhost:5000',
          notify: true,
          open: true,
          port: 9000,
          logLevel: 'debug',

    }, function (err, bs) {
      let urls = bs.options.get('urls').toJS();
      console.log(`Application Available At: ${urls.local}`);
      console.log(`BrowserSync Available At: ${urls.ui}`);
      done();
    });
  }
);
```

**Comment by Ganbin** [comment]
Effectively, no need to add the gulp server dependencies in the aurelia.json which concern only the build for the application itself. Thanks for the correction.

After that the proxy work correctly according to the configuration. Just be sure to install all the dependencies and save them using the `npm install` `--save-dev` flag.

**Comment by Thanood** [comment]
@alpox Does this still "watch" with your solution?
I tried this and is doesn't rebuild or reload when I change something.

**Comment by Thanood** [comment]
For anyone interested, here's my working browserSync proxy:

```javascript
let serve = gulp.series(
  build,
  done => {
    browserSync({
      open: false,
      port: 9000,
      logLevel: 'silent',
      proxy: {
        target: 'localhost:20626'
      }
    }, function(err, bs) {
      let urls = bs.options.get('urls').toJS();
      log(`Application Available At: ${urls.local}`);
      log(`BrowserSync Available At: ${urls.ui}`);
      done();
    });
  }
);
```

The proxied url is `localhost:20626`.

What do you think of a recipe collection hosted inside Aurelia Hub? Just came to my mind, users could quickly find configuration artifacts like this.
