### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/cli#259]
**I'm submitting a feature request**

* **Library Version:**
1.0.1 (I think)

**Please tell us about your environment:**
* **Operating System:**
Arch Linux

* **Node Version:**
v6.3.1

* **NPM Version:**
3.10.3

* **Browser:**
PhantomJS

* **Language:**
TypeScript

**Current behavior:**
trying to use phatomjs results in the following error. I installed   ` "karma-phantomjs-launcher": "^1.0.1",` changed `karma.conf.js` to have `browsers: ['PhantomJS'],` and ran `au test --watch`. I received this error

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Expected an identifier but found 'originalDefine' instead
  at /home/xenoterracide/IdeaProjects/rpf-ui/test/aurelia-karma.js:49
```

**Expected/desired behavior:**

after installing the launcher and configuring the browser PhantomJS should work

* **What is the motivation / use case for changing the behavior?**

using PhantomJs for headless tests in a docker container on CI.

The skeleton for webpack/typscript works with phantomjs

**Comment by bootrider** [comment]
Modify aurelia-karma.js at line 49 from:
`let originalDefine = global.define;`
to:
`var originalDefine = global.define;`

**Comment by AStoker** [comment]
@bootrider, are you saying that changing the `let` to a `var` solved the issue?

**Comment by bootrider** [comment]
yes, it solved the issue. 
I do not why, but it works.

**Comment by AStoker** [comment]
Is there any way to look at the transpiled output of the `aurelia-karma.js` file? The `let` should have been transpiled to a `var`, and I'm rather curious about what it is being transpiled to.

**Comment by EisenbergEffect** [comment]
The aurelia-karma.js file doesn't get transpiled. That is run directly by node I believe. So, that probably explains the issue. Does someone want to submit a PR to make this compatible with phantom?
