### ISSUE TITLE
Consider ES6

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/cli#26]
The rest of Aurelia itself is written with ES6/7. Consider setting up a process that would allow the cli to use ES6. This would likely involve configuring babel to compile and generate modules in CommonJS format. I haven't used Babel in this context yet, but I think it would be worth investigating for consistency sake.

**Comment by joelcoxokc** [comment]
Yes I would really like to run this in ES6 however I believe babel or IO.js have a note on their site about not using ES6 if creating node libraries just yet. Otherwise, I'll get started on this one.

**Comment by EisenbergEffect** [comment]
Sounds good. We can keep this in the backlog until we feel comfortable we know how to make it work. If you want to investigate that further go ahead. If not, no big deal. I don't want to distract you all from the feature work.
