### ISSUE TITLE
support for generating with webpack

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/cli#260]
support for generating with webpack/typescript with the cli (I know about skeleton). This is probably a minor issue for me long run since conversion will be a 1 and done, but having to convert is moderately annoying and I'll probably hit issues.

**Comment by EisenbergEffect** [comment]
We plan to add webpack support to the cli in the future. We've got to do a bit more work with the cli first in order to make that possible though. It is planned.

**Comment by AbraaoAlves** [comment]
The great way to make this is to use a solid abstraction.
From Aug / 2016 to today, we had webpack, rollup, webpack2 with many hot features released, and today we have [Fuse_Box] (https://github.com/fuse-box/fuse-box), an amazing fast bundler too.

Bundlers had great growth in diversity and improvements. But today we have a question: and tomorrow?

**Comment by EisenbergEffect** [comment]
Yes, we'll put an abstraction in place to represent the bundling system so that we can make this extensible in the future.

**Comment by JeroenVinke** [comment]
There are a couple of things we need to do to make this work. 

- [ ] Change the [new-application.json](https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json) to include the webpack as an option
- [ ] Add support to select multiple unit test runners during `au new` since the webpack skeleton supports multiple unit test runners as well
- [ ] Move all folders that are in [this folder](https://github.com/aurelia/cli/tree/master/lib/commands/new) into a new folder called `requirejs`. An index.js file is the entry point to this folder which takes the project model (all options selected by the user during `au new`) and configures the project based on this model. This should make it easier to scaffold different kinds of projects in the future
- [ ] Create the Webpack version of the above folder
- [ ] Extract requirejs-specific instructions from the [ProjectTemplate](https://github.com/aurelia/cli/blob/master/lib/commands/new/project-template.js) so that the [default configurations](https://github.com/aurelia/cli/blob/master/lib/commands/new/project-template.js#L105) can be used for webpack projects as well
- [ ] Generate a [`webpack.config.js`](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/webpack.config.js) file based on the options selected during `au new`. For example, when typescript is selected a different webpack config should be used than when babel is used. Same for postcss vs sass
  - [ ] Manually find correct configurations for all possible options (postcss, sass, typescript, babel etc)
  - [ ] Generate a valid webpack.config.js using [preprocess](https://www.npmjs.com/package/preprocess) where only relevant configurations end up in webpack.config.js

**Comment by EisenbergEffect** [comment]
Woohoo! Let's do it :)

One quick note is that we want to enable the requirejs build for systemjs in the future. That should be just a new build-time configuration generation, with everything else being the same. Just want to mention that so you know the requirejs process should be the same for systemjs. That's secondary to getting Webpack up and running. But after Webpack is added as an option, we'll probably want to add systemjs next.

**Comment by JeroenVinke** [comment]
I'd love to add systemjs as well, will keep that in mind!

**Comment by adriatic** [comment]
Very impressive - despite aurelia-cli not being Monterey 😼

**Comment by Thanood** [comment]
Maybe I can contribute fusebox when the infrastructure is in place. :smiley:

**Comment by EisenbergEffect** [comment]
@Thanood Absolutely. If it's similar to the requirejs and systemjs workflow, then it might be very easy to add once we add systemjs.

**Comment by vegarringdal** [comment]
@Thanood 👍

**Comment by adriatic** [comment]
> Maybe I can contribute fusebox when the infrastructure is in place 

The buck stops at that point, @Thanood - I am not joining the core team even if everyone begs me to do that :-). I believe that there is a lot more work on the area outside of core team's domain and that Aurelia's success (at this point) depends a lot more on the successful work in that outside area.

**Comment by aligneddev** [comment]
What's the status with the using the CLI with webpack?

**Comment by JeroenVinke** [comment]
I am hours away from creating a pull request. There is a lot of testing to be done, but we'll try and get it releases as soon as possible

**Comment by JeroenVinke** [comment]
@aligneddev https://github.com/aurelia/cli/pull/657 ✨

**Comment by jemhuntr** [comment]
Aurelia CLI + Webpack =
![Breathing Intensifies](http://i.imgur.com/w0t0pW3.png)

More importantly, will we be able to switch current CLI projects to webpack easily?

**Comment by JeroenVinke** [comment]
I'm very excited about this as well! As for switching, you will need to
- install webpack dependencies
- remove requirejs-specific dependencies and setup
- replace the gulp tasks with ones for webpack
- update aurelia.json (webpack doesn't need much of the configuration in there)

So there's quite a bit of work involved, and my recommendation would probably be to create a new webpack app through the CLI (when that feature is released) and copy over your source and test files. But i'll take a closer look at this when webpack support is in

**Comment by jemhuntr** [comment]
I see. That's great! That's what I'm planning to do as well (copy over configs from au new).

**Comment by jemhuntr** [comment]
@JeroenVinke Hey! I tried this out on the latest master with `npm install -g aurelia/cli`

I'm getting the following error on the very basic config:

```
/Users/jerome.indefenzo/Documents/Projects/test/aurelia_project/tasks/build.js:24
var buildOptions = new _aureliaCli.Configuration(_aurelia2.default.build.options);
                   ^

TypeError: _aureliaCli.Configuration is not a constructor
    at Object.<anonymous> (/Users/jerome.indefenzo/Documents/Projects/test/aurelia_project/tasks/build.js:6:22)
    at Module._compile (module.js:570:32)
    at loader (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jerome.indefenzo/Documents/Projects/test/aurelia_project/tasks/run.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.nextTick (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/aurelia-cli/lib/commands/gulp.js:28:43)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Is this related to the build not being released yet? Or am I just missing something else?

**Comment by jemhuntr** [comment]
Additionally, `file-loader` isn't listed as a dependency and wasn't installed on the first run.

**Comment by JeroenVinke** [comment]
Hey @jemhuntr. You need to install from master locally too: `npm install aurelia/cli#master` in the project directory. About the file loader, i'll look into it

**Comment by JeroenVinke** [comment]
@jemhuntr thanks for letting me know! I have added the dependencies to master.

**Comment by jemhuntr** [comment]
Here's another error:

```
webpack: Compiling...
/Users/jerome.indefenzo/Documents/Projects/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145
			if(key.startsWith(what))
			      ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.watcher.once (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

It shows up whenever the app recompiles on `au run --watch`. Everything compiles nicely at the start, but the watch task crashes upon editing a file.

---

Another one:

```
Starting 'run'...
{ uid: 0,
  name: 'run',
  branch: false,
  error:
   { WebpackDevServerOptionsValidationError: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
    - configuration has an unknown property 'watch'. These properties are valid:
      object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
       at new Server (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/webpack-dev-server/lib/Server.js:27:9)
       at run (/Users/jerome.indefenzo/Documents/Projects/test/aurelia_project/tasks/run.js:33:16)
       at bound (domain.js:280:14)
       at runBound (domain.js:293:12)
       at asyncRunner (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/async-done/index.js:36:18)
       at _combinedTickCallback (internal/process/next_tick.js:73:7)
       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
     name: 'WebpackDevServerOptionsValidationError',
     message: 'Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.\n - configuration has an unknown property \'watch\'. These properties are valid:\n   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }',
     validationErrors: [ [Object] ],
     domain:
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: true },
  duration: [ 0, 35394902 ],
  time: 1500910693670 }
{ WebpackDevServerOptionsValidationError: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'watch'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
    at new Server (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/webpack-dev-server/lib/Server.js:27:9)
    at run (/Users/jerome.indefenzo/Documents/Projects/test/aurelia_project/tasks/run.js:33:16)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/Users/jerome.indefenzo/Documents/Projects/test/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'WebpackDevServerOptionsValidationError',
  message: 'Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.\n - configuration has an unknown property \'watch\'. These properties are valid:\n   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }',
  validationErrors:
   [ { keyword: 'additionalProperties',
       dataPath: '',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties',
       schema: false,
       parentSchema: [Object],
       data: [Object] } ],
  domain:
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

Webpack seems to be expecting no `watch` option in its Server constructor config. See the [run tasks for webpack](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run-webpack.js#L24).

If I remove line 24, the task successfully builds and serves the bundle. Although I noticed `au run` still watches the files for changes just like `au run --watch`. Is this intended behavior?

---

Sorry about all these; should I be posting these bugs in a separate issue?

**Comment by JeroenVinke** [comment]
Don't feel sorry @jemhuntr! I'd rather catch these issues sooner than later.

The first one seems to be caused by https://stackoverflow.com/a/45281483/3922366. The second one is an oversight on my part. Webpack has a `watch` option, but webpack-dev-server doesn't. There is a `lazy` option, but that gives me a 404 when I enable that. Will look into that

**Comment by JeroenVinke** [comment]
`au run` works now: https://github.com/aurelia/cli/commit/7f5e84ce48ea1920a8c13ba244be2bba33d376a3

**Comment by davidpeden3** [comment]
Nice work, @JeroenVinke. Thanks for getting this done!

@Thanood, is adding [Fusebox](http://fuse-box.org) support still on your radar?
