### ISSUE TITLE
Error bundling dependencies that require folders

### ISSUE THREAD

**Issue by srollinet** [aurelia/cli#263]
When I try to add auth0 in the bundle dependencies, the bundling fails because it cannot find `src\management.js` which in fact is a folder

Here is the content of the main module
```
module.exports = {
  ManagementClient: require('./management'),
  AuthenticationClient: require('./auth')
};
```

the bundler should search `./management/index.js` but instead, it adds the `.js` extension to management

**Comment by EisenbergEffect** [comment]
Check to see if they have an amd distribution you can use. If not, you'll need to add further configuration to add management as a package config. You will need to explicitly add that to the dependencies with a name, path and main.
