### ISSUE TITLE
Completion message not shown for new TS projects

### ISSUE THREAD

**Issue by BBosman** [aurelia/cli#269]
**I'm submitting a bug report**
- **Library Version:**
  0.17.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  5.11.1
- **NPM Version:**
  3.10.5
- **Browser:**
  n/a
- **Language:**
  TypeScript

**Current behavior:**
After creating a new TS project using `au new` the completion message isn't shown.

**Expected/desired behavior:**
Creating a new ESNext based project creates, with all the default options chosen, gives the following output:

```
Installing project dependencies.
[Bunch of npm related stuff]

Congratulations! Your Project "TestJS" Has Been Created!


Now it's time for you to get started. It's easy. First, change directory into your new project's folder. You can use cd TestJS to get there. Once in your project folder, simply run
your new app with au run. Your app will run fully bundled. If you would like to have it auto-refresh whenever you make changes to your HTML, JavaScript or CSS, simply use the
--watch flag. If you want to build your app for production, run au build --env prod. That's just about all there is to it. If you need help, simply run au
help.

Happy Coding!
```

Creating a new TypeScript based project creates, with all the default options chosen, gives the following output:

```
Installing project dependencies.
[Bunch of npm related stuff]

Installing Typings
⸨                 ░⸩ ⠙ runTopLevelLifecycles: sill install printInstalled
├── angular-protractor (global dev)
├── jasmine (global dev)
├── node (global dev)
└── selenium-webdriver (global dev)
```

As you can see the completion message isn't shown.
- **What is the expected behavior?**
  The completion message should be shown.
- **What is the motivation / use case for changing the behavior?**
  New users won't know they need to change into the newly generated directory, resulting in issues like #258.

**Comment by EisenbergEffect** [comment]
I think that the external TS task is returning before it is complete. Need to look into it to see what is going on there.

**Comment by kassobasi** [comment]
I experience a similar problem with some additions (windows 10, node v6.9.1, npm v3.10.8)

It prints the following at the end but never exits the command to the prompt:

Installing Typings
(node:10676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): typings WARN deprecated 2016-09-15: "registry:dt/selenium-webdriver#2.44.0+20160317120654" is deprecated (updated, replaced or removed)

+-- angular-protractor (global dev)
+-- jasmine (global dev)
+-- node (global dev)
`-- selenium-webdriver (global dev)

It was my first ride with modern JS tools like node and such so I wasn't sure if it was still generating code or installing stuff. Is it safe to break out of the command with Ctrl-C at this point?

**Comment by mttmccb** [comment]
I just had this problem today, the first time it didn't create the folder.

**Comment by EisenbergEffect** [comment]
Strange. I wonder if there's an async operation that's not chained properly.

**Comment by JeroenVinke** [comment]
I haven't heard of this issue presenting itself since. Let me know if this occurs again and we'll reopen
