### ISSUE TITLE
Use https: in lieu of git: when cli makes a git clone call in support of Corporate Proxy

### ISSUE THREAD

**Issue by themaneuver** [aurelia/cli#272]
**I'm submitting a feature request**

* **Library Version:**
Aurelia cli 0.17.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
v5.4.0

* **NPM Version:**
3.3.12

* **Browser:**
Chrome 52.0.2743.116 m | IE 11 

* **Language:**
all | TypeScript 1.8 | ESNext

**Current behavior:**

**Expected/desired behavior:**

au new fails to install packages from github during the Installation project dependencies phase

* **What is the expected behavior?**
Use https instead of git when making git clone calls

* **What is the motivation / use case for changing the behavior?**
Allow for the use of the aurelia cli behind a corporate proxy.
![image](https://cloud.githubusercontent.com/assets/3909276/17533706/3c401bac-5e43-11e6-9f3d-ac019c3304db.png)

**Comment by EisenbergEffect** [comment]
I don't think there's anything we can do about this. Aurelia CLI just uses NPM. It doesn't do anything fancy. Please consider making the NPM team aware of issues related to corporate proxies or research to see if there's some special configuration that is needed on your machine to make this work.
