### ISSUE TITLE
Cannot import css files in javascript

### ISSUE THREAD

**Issue by hadrienl** [aurelia/cli#273]
**I'm submitting a bug report**

* **Library Version:**
0.17.0

* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I want to import a css file in src/main.js so I write:

    import mycss from './mycss.css!text';

But when I `au run` I have the following error : "{ Error: ENOENT: no such file or directory, open '…/src/mycss.css.js'"

**Comment by kamilglod** [comment]
+1

**Comment by AStoker** [comment]
The CLI uses RequireJS, so I believe the import must be like this: `import mycss from 'text!mycss.css';`

**Comment by hadrienl** [comment]
It doesn't work.

**Comment by zewa666** [comment]
you should go with the require tag if possible as described here https://github.com/aurelia/cli#styling-your-application.
If you really need to load the css file into your VM there are a few options. Either you load it via the text plugin and do whatever you want with the imported string, like creating a style tag and injecting it.

as an example:
```
import {inject, DOM} from 'aurelia-framework';
import mycss from 'text!test.css';

@inject(DOM, Element)
export class App {

  constructor(DOM, element) {
    this.dom = DOM;
    this.element = element;
  }
  
  attached() {
      let css = this.dom.injectStyles(mycss);
      this.element.appendChild(css);
  }
}
```

or you try to look for a require css loader plugin which most of the time work in the format of
```
import 'css!yourstyle';
```
and automatically load the dependency

**Comment by hadrienl** [comment]
It's sad it's not the same syntax like jspm and webpack… it will be complicate if someday we have to switch to webpack for exemple :(

**Comment by Thanood** [comment]
Actually, I have to agree with @hadrienl..

> import mycss from 'text!test.css';

When you build a library (not an app) you would have to take care of three different loaders that people may use. How would be the best approach here? How would you do css imports loader-agnostic?

The only "distinction" between them that's relatively reliable is module format. AMD => Aurelia CLI, CommonJS => webpack, SystemJS => JSPM.
But really, that's not reliable at all.. :smile: 

Or did I miss something here?

**Comment by EisenbergEffect** [comment]
It's an unfortunate reality of the state of module loaders. There's no standard mechanism for handling plugins. When I need to do things like this in a plugin that needs to work with multiple loaders, I usually use the aurelia loader's `loadText` method so that the runtime loader can use whatever technique it uses to accomplish the load.

**Comment by corneliutusnea** [comment]
@EisenbergEffect Is there an example of using loadText to load the css for a component?

**Comment by EisenbergEffect** [comment]
You can see an example of that here: https://github.com/aurelia/templating-resources/blob/master/src/css-resource.js#L43
