### ISSUE TITLE
build and run used with --env prod|stage|dev changes src/environment.js

### ISSUE THREAD

**Issue by diefans** [aurelia/cli#274]
**I'm submitting a bug report**

* **Library Version:**
0.16.1

**Current behavior:**
`src/environment.js` gets changed when `au build|run` is used with `--env prod|stage|dev`

**Expected/desired behavior:**

Either don't change the source code or put a comment into this file e.g.: _"this file was created by aurelia-cli, edit aurelia_project/environments/\*.js"_ and put it into `.gitignore`

**What is the motivation / use case for changing the behavior?**
I do not want tools change parts of my source code! So I suppose this file belongs to `.gitignore` or the way the environment gets injected into the transpilation should be changed.

**Comment by EisenbergEffect** [comment]
The environment system is setup to let you provide variables and other code that is specific to the build environment that you are targeting. The build system does not change your code, it simply copies your code from one place to another. If you look in the aurelia_project folder, you will see an environments folder where the various environment-specific modules are organized. You can simply change those to match whatever the environment-specific needs you have are. If you don't like this feature, you can simply go into the tasks folder (under aurelia_prject) and remove the environment copy step from the transpiler task.
