### ISSUE TITLE
Windows path separators used in aurelia.json file (when project is generated on Windows)

### ISSUE THREAD

**Issue by atsu85** [aurelia/cli#279]
**I'm submitting a bug report**
When project is generated on Windows, then Windows path separators are used in aurelia.json file

* **Library Version:**
0.17.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v6.3.0

* **NPM Version:**
3.10.3

**Current behavior:**
after generating the project with `au new`, aurelia.json file contains "\\" instead of "/"
```json
{
...
  "paths": {
    "root": "src",
    "resources": "src\\resources",
    "elements": "src\\resources\\elements",
    "attributes": "src\\resources\\attributes",
    "valueConverters": "src\\resources\\value-converters",
    "bindingBehaviors": "src\\resources\\binding-behaviors"
  },
...
}
```

**Expected/desired behavior:**
"\\" should be replaced with "/"

* **What is the expected behavior?**
File should look like:
```json
{
...
  "paths": {
    "root": "src",
    "resources": "src/resources",
    "elements": "src/resources/elements",
    "attributes": "src/resources/attributes",
    "valueConverters": "src/resources/value-converters",
    "bindingBehaviors": "src/resources/binding-behaviors"
  },
...
}
```

* **What is the motivation / use case for changing the behavior?**
To allow development for teams where some people use windows and some use linux/mac, etc.

**Comment by AStoker** [comment]
@atsu85, Issue is being tracked here: https://github.com/aurelia/cli/issues/332
