### ISSUE TITLE
Bundling resource path

### ISSUE THREAD

**Issue by leon-andria** [aurelia/cli#284]
**I'm submitting a feature request**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.3.12

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
By default, the generated project by the cli configure the output to scripts folder. So that app-bundle is loaded as "scripts/app-bundle.js". And we have the same behavior for the vendor-bundle.js in the index.html

**Expected/desired behavior:**
This is path is correct when Users navigate with hash in the browser because the base url is always "/".
But if we have a url friend slug "/products/aurelia", the browser will load with /products/scripts/app-bundle.js. As you can notice, this path doesn't exist.

* **What is the expected behavior?**
The expected behavior should be at the root "/scripts/app-bundle.js".
Note that there is a "/" at the beginning of scripts here.

* **What is the motivation / use case for changing the behavior?**
It should be good to have a wellknown documentation for this because to solve this, below is the line of code to able to have the / at the beginning: https://github.com/aurelia/cli/blob/master/lib/build/bundle.js#L199
As you see, there is a property "useAbsolutePath" that need to be true.
However, as we can see here, it's in a variable "platform". So, guess that there is no documentation about the schema of aurelia.json, on the top, there is a section "platform", so we added useAbsolutePath on it but we still have the issue. After debug, it appears that "useAbsolutePath" should be declared under "builds/targets" section. 
I don't know if this is a bug but the variable spelling is complety wrong.

Hope this will help people when scripts/app-bundle.js and vendor-bundle.js are not correctly loaded to the right path.

**Comment by aidesigner** [comment]
I went down a similar path and tried to fix things with useAbsolutePath.  However, I then added the code below to my index.html and the bundle paths were no longer relative (Success).  Note my app is configured to use pushstate if that is relevant.
`
  <head>
    <title>Aurelia</title>
    **<base href="/">**
  </head>
`

**Comment by EisenbergEffect** [comment]
Yes, using the `base` tag is necessary when using push state.
