### ISSUE TITLE
ASP.NET Core - Typescript: Missing modules

### ISSUE THREAD

**Issue by deliberaligiacomo** [aurelia/cli#285]
- Windows 10
- Node 6.4.0
- NPM 3.10.6
- Typescript

I've just created a new ASP NET Core application with Visual Studio 2015 Update 3.
After that I've typed in the .xproj folder:
`au new --here`
and followed all the steps. It gives me no errors.

Now reloading code from VS and looking into, for example, `run.js` all the modules import are missing: `Cannot find module ...`.

If I try to execute `au run` i got no errors, but the default address `localhost:9000` says `cannot /GET`.

How can i resolve the imports errors? Am I missing some .d.ts or something else?

**Comment by EisenbergEffect** [comment]
You can ignore anything in the aurelia_project folder. That is all handles by the Aurelia CLI itself.

**Comment by deliberaligiacomo** [comment]
I cannot ignore the aurelia_project because the file `aurelia.json` is used by the cli during the build and run tasks. 

We found the solution to resolve the `cannot /GET` issue: just modify in `task/run.ts` the prop `baseDir` from `.` to `./wwwroot`.

Now we are trying to migrate from JSPM to aurelia-cli to reach the Edge support, but all the references are broken. Is there a good way to update quickly (and maybe not by hand) the `aurelia.json`? Or have we got to go reference by reference and update manually the file? Thank you

**Comment by madrus** [comment]
I am afraid I have to agree with @deliberaligiacomo, @EisenbergEffect. Because of these build errors I am always forced to run the latest successful build for my backend .NET Core Web API. On the other hand, I have found a tip on the Internet that it is possible to temporary suppress the TypeScript build by adding this property to the first `PropertyGroup` in the `.csproj` or `.xproj` file:

```xml
<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
```

So, my workaround here is to set it to `true` when I want to build the rest of the solution (to create a new "last successful build") and to `false` when I want to see the TypeScript errors.

Alternatively, I could have chosen to separate my backend solution and Aurelia project.

**Comment by dkent600** [comment]
Changing  baseDir  from  .  to  ./wwwroot works for me to make the app come up without the "GET" error.

It is not clear to me how @EisenbergEffect's suggestion fixes this.  I'm not even sure what is meant by "ignore anything in the aurelia_project folder".  Does that mean add that folder to the 'exclude' section in 'tsconfig.json'?

**Comment by madrus** [comment]
@dkent600 I don't think you have to 'exclude' this section. When you run 'au run', gulp takes care of all the necessary steps, including compiling .ts files. Everything just works out of the box.

**Comment by dkent600** [comment]
@madrus OK, maybe @EisenbergEffect didn't understand the problem.  But clearly without changing baseDir from . to ./wwwroot , things don't just "work out of the box".

**Comment by madrus** [comment]
Yes, you are right. I have also had to make this change. I would imagine that `./wwwroot` is necessary when using Visual Studio, otherwise just `/`.

**Comment by LarsKemmann** [comment]
@madrus, I think @EisenbergEffect meant to add the following to your `tsconfig.json` file:

    "exclude": [
      ...
      "aurelia_project" // <--- Exclude just this folder from TypeScript builds
    ],

This works for me. I then added the following to my `project.json` file to build the front-end code together with my back-end code:

    "scripts": {
      "precompile": [ "au build" ], // <--- Run 'au build' when the ASP.NET Core project is compiled
      ...
    }

**Comment by EisenbergEffect** [comment]
Bingo! Sorry if I didn't provide the specifics.

**Comment by LarsKemmann** [comment]
It would also be nice if I could figure out how to hook up the Aurelia Gulp tasks directly and hopefully cut down on the build times... 15 seconds for a default project right now. :/
