### ISSUE TITLE
Revision in path

### ISSUE THREAD

**Issue by hadrienl** [aurelia/cli#286]
**I'm submitting a feature request**

* **Library Version:**
1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When I deploy a new version on Cloudfront, the previous stays in my users browser cache.

**Expected/desired behavior:**
 I'd like the path to the scripts to be changed with a revision suffix or a querystring to be forced to reload.

**Comment by hadrienl** [comment]
I've added this ugly task in my deploy serie:

```
function killCache(version) {
  const index = fs.readFileSync('./index.html');
  fs.writeFileSync('./index.html', index.toString().replace(
    /(scripts\/vendor-bundle.js)(\?.*)?"/,
    `$1?v=${release}"`
  ));

  const vendorbundle = fs.readFileSync('./scripts/vendor-bundle.js');
  fs.writeFileSync('./scripts/vendor-bundle.js', vendorbundle.toString().replace(
    /(requirejs\.config\(\{)/,
    `$1"urlArgs": "v=${release}",`
  ));
}
```

Maybe someone would write it better…

**Comment by AStoker** [comment]
I believe this is related: https://github.com/aurelia/cli/issues/205
I'm going to start working on this issue, so I'll be discussing there.

**Comment by EisenbergEffect** [comment]
Implemented and released thanks to @AStoker !
