### ISSUE TITLE
require from of css fails without proper logging making it hard to diagnose

### ISSUE THREAD

**Issue by corneliutusnea** [aurelia/cli#287]
**I'm submitting a bug report**
- **Library Version:**
  0.18.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.3.7
- **NPM Version:**
  3.10.7
- **Browser:**
  Chrome
- **Language:**
  TypeScript

**Current behavior:**

**Expected/desired behavior:**

In your html do a require that has an invalid name/path
`<require from="./aurelia-grid.css"></require>`
The load fails with a crash 
vendor-bundle.js:formatted:4098 Uncaught TypeError: h.load is not a function
Which makes it impossible to figure out what the error is.

The problem is in this line:
https://github.com/aurelia/cli/blob/b02946c6b45262781f85ebc3ff1ae18e8102669f/lib/build/amodro-trace/lib/loader/require.js#L1092
map.name in that line has the exact path you are trying to load e.g. "./aurelia-grid.css".

A quick check for `if (!plugin.load) { .. }` throw error that it could not find file map.name "./aurelia-grid.css" and maybe the context would save lots of hours of debugging.
- **What is the expected behavior?**
  Throw a proper error that can point to the problem.
- **What is the motivation / use case for changing the behavior?**
  Simplify diagnosing.

**Comment by EisenbergEffect** [comment]
This is a great opportunity to PR an improvement :)

**Comment by nexbit** [comment]
It's true that the `h.load` error is too cryptic, but in Chrome I see the following error, after the RequireJS timeout:
`Unhandled rejection Error: Failed loading required CSS file: path/to/the/resource`

This only works if you haven't handled the `unhandledrejection` event in some custom way...

**Comment by JayDi85** [comment]
Firefox console show: "TypeError: plugin.load is not a function" when aurelia attempt load css-resources (that's why error "Failed loading required CSS file" raise).

After some research I [found that SO post about that error](http://stackoverflow.com/questions/39399772/unhandled-rejection-error-load-timeout-for-modules-template-registry-entry).

Author found solution in comments to first post:
28 Jul, to dynamically require text requires setting stub:false in the text plugin at aurelia.json > build.loader.plugins.

After change `stub` value to `false` in `aurelia.json` -- work fine for me. Bug is gone and app work correct.

**Comment by nexbit** [comment]
@JayDi85 I'm glad you found a solution to your problem, but this issue thread proposes a better reporting message for errors like yours, not a solution to these errors (that are always a kind of 404 error)... 
What's interesting, though, is that even in your case and in Firefox you received an `Unhandled rejection error` with the actual path of the resource that failed to load. Can you confirm that?

I suppose that all the failures originating from the `text` plugin lead to unhandled rejections with the full path of the resource, in that case the severity of this issue (better error reporting) is lower than expected.

**Comment by JayDi85** [comment]
@nexbit no, it's not a resource path problem. All data have write correct in `vendor-bundle.js` by `text!name_of_css` index. Sometimes, you can fix it by change module position in `aurelia.json` config file -- like add new library with css before or after bootstrap v4 library.

Here is firefox log:

![shot_161004_203508](https://cloud.githubusercontent.com/assets/8344157/19083155/1f17d064-8a72-11e6-833a-8d462c2135b6.png)

After that I found that line of code in `\scripts\require.js` and add `console.log(plugin) before load. And that `plugin` param was empty object. Other resources (not CSS) loads good.

**Comment by AbraaoAlves** [comment]
Its a transpile problem, the same error don't happen in javascript project.

Here, two branchs with the same code:
[[works] In Javascript](https://github.com/AbraaoAlves/new-aurelia-sample/tree/js)
[[fail]     In Typescript](https://github.com/AbraaoAlves/new-aurelia-sample/tree/ts)


And typescript project build output:
`au build`
```
Starting 'buildTypeScript'...
{ uid: 9,
  name: 'buildTypeScript',
  branch: false,
  error:
   { Error: Debug Failure. False expression: File C:/sources/aurelia/samples/new-aurelia-sample/node_modules/milligram/dist/milligram.css has unknown extension.
       at Object.assert (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:3177:23)
       at Object.fail (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:3182:19)
       at Object.extensionFromPath (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:3324:15)
       at resolvedFromAnyFile (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:23415:44)
       at loadNodeModuleFromDirectory (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:23977:28)
       at loadModuleFromNodeModulesFolder (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:24007:13)
       at loadModuleFromNodeModulesOneLevel (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:24026:53)
       at C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:24019:24
       at forEachAncestorDirectory (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:24086:26)
       at loadModuleFromNodeModulesWorker (C:\sources\aurelia\samples\new-aurelia-sample\node_modules\typescript\lib\typescript.js:24017:16)
     domain:
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: true },
  duration: [ 0, 46914158 ],
  time: 1482283715384 }
```

Remember, all this is just to add a single css vendor.

**Comment by avrahamcool** [comment]
@EisenbergEffect 
considering that the tracer was completely re-written - I think this one is safe to close.
