### ISSUE TITLE
Require search into wrong folder during bundle

### ISSUE THREAD

**Issue by federico-galfione** [aurelia/cli#288]
- Windows 10
- Node 6.4.0
- NPM 3.10.6
- Typescript

I'm trying to implement the google-maps-api package. It require scriptjs and promise packages. I installed and wrote them into aurelia.json, but when I try to run bundling I get this error:

`Error: ENOENT: no such file or directory, open 'C:\code\tfs\af\ibv-website-cli\IbvSolutionsCli\src\IbvSolutionsCli.Web\lib\core.js'`

'lib/core.js' is inside 'promise' package and it's required from 'node_modules/promise/index.js'

What could be causing this problem?

**Comment by federico-galfione** [comment]
I was forgetting resources in promise definition in aurelia.json.
Now my code is:
```
{
            "name": "promise",
            "path": "../node_modules/promise",
            "main": "index",
            "resources": [
              "lib/core.js"
            ]
          }
```

but I still get the same error: 

`Error: ENOENT: no such file or directory, open 'C:\code\tfs\af\ibv-website-cli\IbvSolutionsCli\src\IbvSolutionsCli.Web\promise\lib\core.js'`

node_modules seems to be ignored.

**Comment by XuJinNet** [comment]
The same problem.

**Comment by XuJinNet** [comment]
@federico-galfione 
maybe the reason is
`require('./core.js');`

you can try modify to
`require('./core');`
