### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined when using async/await syntax

### ISSUE THREAD

**Issue by snicky** [aurelia/cli#291]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

* **Browser:**
all

* **Language:**
ESNext

* **Babel configuration (standard)**
```
"presets": [ "es2015-loose", "stage-1"],
  "plugins": [
    "syntax-flow",
    "transform-decorators-legacy",
    "transform-flow-strip-types"
  ]
```

**Current behavior:**
Using async/await in an app generated with the aurelia-cli results in getting `ERROR [app-router] ReferenceError: regeneratorRuntime is not defined`

**Reproducing**
Just try to use async/await in any ViewModel.

**Comment by EisenbergEffect** [comment]
This doesn't have anything to do with the CLI. If you want to use async/await in a Babel project, you have to configure Babel to transpile it and then add the necessary generator runtime library to your app.

**Comment by Leonidnei** [comment]
How to add "necessary generator runtime library to your app"? Currently we have babel and babel-runtime in config.js, how to deal with this going to aurelia-cli?

**Comment by snicky** [comment]
Hi @Leonidnei. I managed to make things work by requiring babel-polyfill at the top of my `main.js` file and commenting out the Bluebird promises configuration, although this is probably not the best thing to do :) The bluebird package is there for a reason, but I didn't really have time to dive into this. Well, at least you know the quick'n'dirty workaround.

My `main.js` file looks like this:

```
require('node_modules/babel-polyfill/dist/polyfill.js')

// other imports here

//Configure Bluebird Promises.
//Note: You may want to use environment-specific configuration.
// Promise.config({
//   warnings: {
//     wForgottenReturn: false
//   }
// });
```

Obviously, you'll have to manually install the `babel-polyfill` package as well.

**Comment by lpj145** [comment]
`"prepend": [
          "node_modules/babel-polyfill/dist/polyfill.min.js",
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "node_modules/tether/dist/js/tether.min.js",
          "scripts/require.js"
        ]`


And uncomment Promise.config.

**Comment by lpj145** [comment]
you can include after bluebird.
