### ISSUE TITLE
Cannot import json file with text plugin or json plugin

### ISSUE THREAD

**Issue by salminio** [aurelia/cli#296]
**I'm submitting a bug report**
- **Library Version:** 
  0.18.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  5.10.1
  
  
- **NPM Version:**
  3.8.6
  
  
- **Browser:**
  Chrome 52.0
- **Language:**
  ESNext

**Current behavior:**
We have several json files that we import into the client. With SystemJS we were doing 
`import _defaults from './entity-default-definitions.json!json';`

I've tried switching to 
`import _defaults from 'json!./entity-default-definitions.json';`
which produces
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error:
   { [Error: ENOENT: no such file or directory, open 'D:\Users\kminio\src2\tw-composer\thingworx-ui-platform\src\json.js
']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'D:\Users\kminio\src2\tw-composer\thingworx-ui-platform\src\json.js',
     moduleTree: [ 'entity/entity-defaults' ],
     fileName: 'D:/Users/kminio/src2/tw-composer/thingworx-ui-platform/src/entity/entity-defaults.js' },
  duration: [ 5, 603011213 ],
  time: 1472497970464 }

and also 
`import _defaults from 'text!./entity-default-definitions.json';`
closer but produces:
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error: [TypeError: Path must be a string. Received undefined],
  duration: [ 5, 706117176 ],
  time: 1472498084764 }

**Expected/desired behavior:**

- **What is the expected behavior?**
  If I could load directly using requirejs json plugin that would be ideal. I could load as text and do a JSON.parse to achieve as well.
- **What is the motivation / use case for changing the behavior?**
  Migrating to CLI from JSPM/SystemJS

**Comment by salminio** [comment]
Should also mention I did tinker with aurelia.json as well... Trying to add json as valid text extension as well as define a json plugin - neither had any affect. Below is the json to text
```
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css",
            ".json"
          ],
          "stub": true
        }
      ]
    },

```

**Comment by EisenbergEffect** [comment]
We have this working in production with svg. I'm not sure why it would be different for json.

**Comment by salminio** [comment]
Not sure either but I tried 3 flavors with trying to import the json file.

`import ViewServiceMetaModel2 from 'json!services/view-service.json';`

'import ViewServiceMetaModel2 from 'services/view-service.json';`

both of these produce errors which I can probably understand and maybe I need some special plugin to handle json... but importing as a text should work.

`import ViewServiceMetaModel2 from 'text!services/view-service.json';`

but this fails as well - silently - Tracing/writing the bundles. 

I was able to work around this issue by dynamically 'requiring in file as text'
```
    static importJson(filepath) {
        return new Promise(resolve => {
            require(['text!' + filepath], res => {
                resolve(JSON.parse(res));
            });
        });
    }
```

**Comment by brunto** [comment]
Hi, I have a similar issue with json file
`import config from 'text!./config.json'`
and same error: `TypeError: Path must be a string. Received undefined`

**Comment by RenathoAzevedo** [comment]
Any news about it ?  I have to import a json file and I'm receiving the same error :  TypeError: Path must be a string. Received undefined

**Comment by JeroenVinke** [comment]
No news yet. I'll try and take a stab at this soon (i'm working through the issue list). A PR would be very welcome as well

**Comment by fabioluz** [comment]
I can import a json file by creating a `textProcessor` step. 

**aurelia.json**

```
"textProcessor": {
    "displayName": "Text",
    "source": "src/**/*.json"
  },
```

**process-text.js**

```
import gulp from 'gulp';
import changedInPlace from 'gulp-changed-in-place';
import project from '../aurelia.json';
import {build} from 'aurelia-cli';

export default function processText() {
  return gulp.src(project.textProcessor.source)
    .pipe(changedInPlace({firstPass: true}))
    .pipe(build.bundle());
}

```
And finally
```
import Routes from 'text!../routes.json';
JSON.parse(Routes.app);
```

**Comment by RenathoAzevedo** [comment]
I tried this method, but I couldn't be able to import, I was still receiving the same error: TypeError: Path must be a string. Received undefined.

**Comment by fabioluz** [comment]
@RenathoAzevedo That's odd. Could you show me your json file?

**Comment by RenathoAzevedo** [comment]
@fabioluz it's nothing special, just a basic json. 
`{
	"title": "Person",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
`
Putting the json file inside of the src folder it seems to load the json but the aurelia-cli dies on : 
Tracing app...
Tracing main...

**Comment by fabioluz** [comment]
Have you added `processText` in the build.js/ts? 

```
export default gulp.series(
  readProjectConfiguration,
  gulp.parallel(
    transpile,
    processMarkup,
    processCSS,
    processText,
    processLocales,
    copyFiles
  ),
  writeBundles
);

```

**Comment by RenathoAzevedo** [comment]
@fabioluz  yes,  I did the `import processText from './process-text';` and add it on : 
`export default gulp.series(
  readProjectConfiguration,
  gulp.parallel(
    transpile,
    processMarkup,
    processCSS,
    processText
  ),
  writeBundles
);`

I also tried what the @graemechristie did on: https://github.com/aurelia/cli/issues/300; 
What is strange is that when json is outside src folder it gives me the error:  TypeError: Path must be a string. Received undefined.  Inside src folder no error is given but the aurelia-cli dies on tracing main...

**Comment by JeroenVinke** [comment]
Unfortunately I can't seem to reproduce this issue. Using a new aurelia app (0.26.1), I did this:

- in aurelia.json add ".json" to the text plugin extensions
- create `test.json`
- import the JSON file from app.js:
  ```
  import myJSON from 'text!./test.json';
  console.log(JSON.parse(myJSON));
  ```

Repository is [here](https://github.com/JeroenVinke/aurelia-cli-296-insidesrc). When I moved `test.json` up one folder (so to the root folder) and changed the import statement accordingly, it also worked. So please provide steps to reproduce this issue and i'll take another look

**Comment by RenathoAzevedo** [comment]
@JeroenVinke Thank you man, I got it. Sorry for not providing my environment. My global dependencies were updated but in my local package.json my dependencies weren't.  So I was with aurelia-cli 0.26.1 in the global environment but in my local project it was with the 0.24.0 version, so in the 0.24.0 cli version the problem occurs, I updated my dependencies and with the 0.26.1 the problem disappears. I can load my JSON files with no problems.
The only thing that upset me now is that it not accept the dynamic load, meaning I have to restart the project to load any update on my JSON file, even using --watch flag.

**Comment by JeroenVinke** [comment]
Thanks for the quick response @RenathoAzevedo. Regarding it not doing dynamic loads, try and bundle all JSON files by changing [this line](https://github.com/JeroenVinke/aurelia-cli-296-insidesrc/blob/master/aurelia_project/aurelia.json#L88) to `"**/*.{css,html,json}"` 

I did have an issue when I instruct the bundler to update JSON files whenever one changes (using a similar setup as @fabioluz), for which I opened an issue: https://github.com/aurelia/cli/issues/544.

I believe this issue has been resolved now so I'll close this one
