### ISSUE TITLE
ReferenceError: Can't find variable: IntlPolyfill

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#297]
I bundle the polyfill intl, get the error when running:
`ReferenceError: Can't find variable: IntlPolyfill`

``` json
{
  "name": "intl",
  "path": "../node_modules/intl/dist",
  "main": "Intl.complete"
}
```
- Framework Version:
  1.0.2
- aurelia-i18n Version:
  1.1.1
- intl Version:
  1.2.4
- Operating System:
  OSX 10.11.6
- Node Version:
  6.3.1
- NPM Version:
  3.10.3
- Aurelia-CLI:
  0.18.0
- Browser:
  Chrome 52.0 | Firefox 48.0 | Safari 9.1.2
- Language:
  ESNext

**Comment by XuJinNet** [comment]
A temporary solution:
```json
"prepend": [
    "node_modules/bluebird/js/browser/bluebird.core.js",
     "node_modules/intl/dist/Intl.min.js",
     "node_modules/intl/locale-data/jsonp/zh.js",
     "scripts/require.js"
],
```

**Comment by JeroenVinke** [comment]
I don't think we can do anything here, it should be fixed in the Intl.js library: https://github.com/andyearnshaw/Intl.js/issues/218.
