### ISSUE TITLE
App.bundle.js 404's When Adding Multiple Paths to URL

### ISSUE THREAD

**Issue by jasonbiondo** [aurelia/cli#299]
**I'm submitting a bug report**

* **Library Version:**
0.17.0

* **Operating System:**
OSX 10.11.5

* **Node Version:**
4.4.3

* **NPM Version:**
3.10.5

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
my app.bundle.js url goes to:
http://localhost:9001/account-recovery/scripts/app-bundle.js 404 (Not Found)
When I configure my route as:
{ route: 'account-recovery/email',       name: 'accountRecoveryEmail',       moduleId: './authentication/email/email',    title: 'Account Recovery' },

Another example is if I switch pages from a url like /treks and go to /treks/create there is no problem, but if I hard load the page on /treks/create is when I get the error

**Expected/desired behavior:**
When doing a hard page refresh the app-bundle should load from...
http://localhost:9001/scripts/app-bundle.js 

* **What is the expected behavior?**
app-bundle.js loading should not be dependent on the route. 

* **What is the motivation / use case for changing the behavior?**
You can't build pages with multiple paths until this is fixed.

**Comment by Jenselme** [comment]
I add the same problem. I opened a pr #243 to solve this. It has been merged. Setting `build.targets[0].useAbsolutePath` to `true` in your `aurelia.json` file should solve it.

See [here](https://bitbucket.org/arenaoftitans/arena-of-titans/src/739925e9fd903d2412dc0eb0ec773bff901d5faa/aurelia_project/aurelia.json?at=master&fileviewer=file-view-default#aurelia.json-55) for an example.
