### ISSUE TITLE
Failed to execute Aurelia Bundle.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/cli#3]
I copied the Aureliafile from the readme and ran `aurelia bundle`.  This was the output:

```
> aurelia bundle

Would you like jspm to prefix the jspm package.json properties under jspm?:Yes
Enter server baseURL (public folder path):./
Enter jspm packages folder:.\jspm_packages
Enter config file path:.\config.js
Configuration file config.js doesn't exist, create it?:Yes
Enter client baseURL (public folder URL):/
Which ES6 transpiler would you like to use, Traceur or Babel?:traceur
Potentially unhandled rejection [6] Error: Error loading "aurelia-bootstrapper" at file:C:/Users/MyName/Source/MyName.MyProject/aurelia-bootstrapper.js
ENOENT, open 'C:\Users\MyName\Source\MyName.MyProject\aurelia-bootstrapper.js'
    at Error (native)
```

**Comment by ahmedshuhel** [comment]
Looks like you didn't setup a project before using the cli. You got to have an `aurelia` project setup with a valid configuration in `Aureliafile.js` for cli bundling to work.

**Comment by Zoltu** [comment]
The CLI should either setup the project for me or provide a better error message.  As a novice user, the error message as it is does not provide enough information to resolve the problem on my own.

**Comment by EisenbergEffect** [comment]
@ahmedshuhel @Zoltu Has good feedback on this. Can we create an issue for that to provide an auto-gen default config file? (asking the user if they want one first)
