### ISSUE TITLE
Not possible to import *.json files inside TypeScript. 

### ISSUE THREAD

**Issue by sislex** [aurelia/cli#300]
I am using aurelia-cli - typescript version. I need to import .json file inside typescript file f.e.` import config from "../config/app.json"`.
When I try to build project I am getting an error can't find file {path to file}/config/app.json.js
I tried to add require js json plugin to aurelia.json file and change my code to `import config fom "json!../config/app.json"`(https://github.com/millermedeiros/requirejs-plugins). But without any success. Error:
 uid: 9,
  name: 'writeBundles',
  branch: false,
  error: [TypeError: Path must be a string. Received undefined],
  duration: [ 6, 499384178 ],
  time: 1472563256344 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: [TypeError: Path must be a string. Received undefined],
  duration: [ 13, 649611809 ],
  time: 1472563256359 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: [TypeError: Path must be a string. Received undefined],
  duration: [ 13, 650647973 ],
  time: 1472563256360 }
[TypeError: Path must be a string. Received undefined]

Is there any way to import .json?

Could you please provide me aurelia.json example or other solution to resolve this issue?

**Comment by AntonChyrko** [comment]
Looks like you have typo in your import. Also please check the path, it cannot parse it to string for some reason.

**Comment by sislex** [comment]
I think it's "aurelia-cli" bug and I will be glad if I will get answer from aurelia developers.

**Comment by wmkleuver** [comment]
Have you tried `import * as config from "../config/app.json!json"`?
You need to have the `!type` part at the end of an import statement. An import is not the same as a define (like the example in your link).
Also, you cannot import it as a regular module (like `import config ..` or `import {config} ..`) because there is no module export in the json file. This is why you need to alias it as `import * as config ...`

**Comment by sislex** [comment]
Issue stay the same. 
Screen this issue here [http://screencast.com/t/WpByu5Xw2Mh](http://screencast.com/t/WpByu5Xw2Mh)
Someone will offer more ideas?

**Comment by aviplayer** [comment]
I have the same issue. Made changes in aurelia.json and added json plugin. Tried several plugins to `import config from "json!app.json"`. But still no result. Seems a bug. Because it possible to import json in webpack sceleton using json-loader plugin and also in system js config using system js json loader. But I can't find a way how to import .json using aurelia-cli.

**Comment by alpox** [comment]
The Aurelia-CLI is based on requirejs so i guess you can use additional loaders for it as well. You most likely will need one when trying to import json. Another possibility would maybe be to use the `text` loader plugin which should be already integrated with aurelia, get the json file as text and then JSON.parse it.

Take a look at http://stackoverflow.com/questions/15314019/requirejs-load-static-json-file for the json plugin.

**Comment by EugeneShpuriaka** [comment]
I have the same issue and can't find any solution using aurelia-cli.

**Comment by sislex** [comment]
**alpox**: Could you give example your aurelia.json config. May be I did mistake.

**Comment by alpox** [comment]
@sislex I'm not using the CLI anymore, i switched to Webpack some days ago but i didn't try it with the json loading anyway. I just tried to give some hints which could lead to a solution :-)

**Comment by aviplayer** [comment]
> I would try it with import * as jsonConfig from 'text!app.json"; And then do a let jsonConfig = JSON.parse(json); at first.
This solution is not working.
Compilation error:```
 { uid: 1,
  name: '<series>',
  branch: true,
  error: [TypeError: Path must be a string. Received undefined],
  duration: [ 2, 824574798 ],
  time: 1472743279163 }
```
Seems there is the same issue: https://github.com/aurelia/cli/issues/296

**Comment by EisenbergEffect** [comment]
Here's an example of how we load the Aurelia SVG logo inside our Hub.

```
import desktoplogoSVG from 'text!resources/aurelia-logo/aurelia-logo-beta.svg';
```

You could use the same approach for json. You would get the text so you would need to parse it afterward.

**Comment by graemechristie** [comment]
I'm not sure this should have been closed, seems like a bug in aurelia-cli to me. If importing, even using the text plugin without json, I am getting the same error as @sislex..``` TypeError: Path must be a string. Received undefined
       at assertPath (path.js:7:11)
       at Object.normalize (path.js:1179:5)
       at normalizeKey (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundler.js:187:15)
       at getItemByPath (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundler.js:87:28)
       at amodroTrace.then.traceResult (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundled-source.js:109:28)
       at process._tickDomainCallback (internal/process/next_tick.js:129:7),
```

If I put a Console.writeline in aurelia-cli/lib/build/bundled-source.js, e.g.

```
    ).then(traceResult => {

      let traced = traceResult.traced;

      for (let i = 0, ii = traced.length; i < ii; ++i) {
        let result = traceResult.traced[i];
        console.log("TraceResult::::", result);
        let item = bundler.getItemByPath(result.path);

```

We can see that there is no path defined for the object with the id "text!config.json", hence the error.

```TraceResult:::: { id: 'text',
  path: '/Users/gchristie/dev/octane/scripts/text.js',
  contents: 'define(\'text\',{load: function(id){throw new Error("Dynamic load not allowed: " + id);}});',
  dependents: [ 'text!config.json' ] }
TraceResult:::: { id: 'text!config.json', dependents: [ 'app' ] }
{ uid: 9,
  name: 'writeBundles',
  branch: false,
  error:
   TypeError: Path must be a string. Received undefined
       at assertPath (path.js:7:11)
       at Object.normalize (path.js:1179:5)
       at normalizeKey (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundler.js:187:15)
       at getItemByPath (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundler.js:87:28)
       at amodroTrace.then.traceResult (/Users/gchristie/dev/octane/node_modules/aurelia-cli/lib/build/bundled-source.js:109:28)
       at process._tickDomainCallback (internal/process/next_tick.js:129:7),
  duration: [ 0, 828796626 ],
  time: 1475489034272 }
```
 
I'll have a bit more of a look tonight and see if I can find more info as to why there is no path populated for text! imports ...

**Comment by MeirionHughes** [comment]
you might need to define a loader for typescript i.e. 
`text.d.ts`
```
declare module 'text!*' {
    var _: string;
    export default  _;
}
```

**Comment by graemechristie** [comment]
Okay, I got this working. I'm not sure if this is as-designed, maybe @EisenbergEffect can comment.

It looks like that in order for the tracer to find a file, it must already be added to the bundler by the build process. It does not seem that modifying the bundles.source section of the aurelia.json project configuration does this. e.g.

```
    "bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[**/*.js]",
          "**/*.{css,html}",          
          "**/*.json"
```

does not cause any json files in the src dir to be added to the bundler.

It appears that any files need to have been passed into `build.bundle` from gulp at some previous point in the build process, such as via the processMarkup or processCss functions that the generator creates under aurelia_project.

 The quick and dirty fix would be to replace ` `['**/*.json' ]` to the markupProcessor.source setting of aurelia.json, however to be a bit more succint I created a new setting in aurelia.json for a textProcessor`

```
....
 },
  "textProcessor": {
    "displayName": "Text",
    "source": "src/**/*.json"
  },
...
```

Then added a new file, `process-text.ts`, in the `aurelia-project` dir with the following:

```
import * as gulp from 'gulp';
import * as changedInPlace from 'gulp-changed-in-place';
import * as project from '../aurelia.json';
import {build} from 'aurelia-cli';

export default function processText() {
  return gulp.src(project.textProcessor.source)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(build.bundle());
}
```

Then I modified the build.ts script to include the new processText function. It looks something like the following:

```
import * as gulp from 'gulp';
import transpile from './transpile';
import processMarkup from './process-markup';
import processText from './process-text';
import processCSS from './process-css';
import processFontAwesome from './process-font-awesome';
import {build} from 'aurelia-cli';
import * as project from '../aurelia.json';
import * as del from 'del';

export default gulp.series(
  readProjectConfiguration,
  gulp.parallel(
    transpile,
    processMarkup,
    processCSS,
    processFontAwesome,
    processText
  ),
  writeBundles
);

function readProjectConfiguration() {
  return build.src(project);
}

function writeBundles() {
  return build.dest();
}
```






```
gulp.src(project.markupProcessor.source)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(build.bundle());
```

**Comment by EisenbergEffect** [comment]
Did you add the `.json` file extension to the aurelia.json file's text plugin settings?

```
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        { "name": "text", "extensions": [".html", ".css", ".json"], "stub": false }
      ]
    }
```

That is how the build system knows that it should handle json files with the text plugin. You also need to make sure that the .json files get selected into the bundle. So, you need to probably add a task that globs over the json files and pushes them into the bundle the same way that the markup task does.

**Comment by MeirionHughes** [comment]
Yes, but the only difference was `"stub": true`

**Comment by EisenbergEffect** [comment]
@graemechristie That's pretty much it. The idea is that the tasks feed files into the bundler. Then the globs in the aurelia.json file are used to take the incoming files and push them into the correct bundles. In this case, you've go an extra file type of .json that adds a bit of complication. Perhaps in the future we can just add another tasks that makes it easy to push random files into the system based on extensions or globs.

**Comment by graemechristie** [comment]
@EisenbergEffect That's what I had originally assumed the bundles.source setting from auelia.json was doing .. e.g. 

```
    "bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[**/*.js]",
          "**/*.{css,html}",          
          "**/*.json"
        ]
      }
```

Would it be fair to say that the source setting doesn't actually do anything currently ? Should it be removed in favour of some other mechanism of including non-processed files such as text/svg/json files in the bundler output ?

**Comment by EisenbergEffect** [comment]
The source is critical. That is what selects from the incoming stream.

**Comment by mttmccb** [comment]
I'd be interesting in seeing this being supported more easily, using i18n with translation json files seems like the obvious way you'd want to include those files.

**Comment by hozn** [comment]
I've gotten the above pattern from @graemechristie to work -- well, mostly.  I am using aurelia-cli.  I am trying to inject a "StaticStore" that has some Map objects initialized from JSON files.  The `au run` command always dies silently as soon as it tries to trace through a VM class's file, which in turn imports my `StaticStore` (for injection).  Removing the json import ultimately fixes the problem.   Is this an issue with order of files being bundled?

Here are some abbreviated versions.
```javascript
import codes from 'text!assets/country-codes.json';

export class StaticStore {
  constructor() {
    this.countrycodeMap = new Map( JSON.parse(codes));
  }
}
```

```javascript
import {inject} from 'aurelia-framework';
import {StaticStore} from 'stores/static-store';

@inject(StaticStore)
export class Summary {
  constructor(staticStore) {
    this.staticStore = staticStore;
  }
}
```

And my `aurelia.json` diff:
```diff
diff --git a/aurelia_project/aurelia.json b/aurelia_project/aurelia.json
index d5cbb69..cb8ebb9 100644
--- a/aurelia_project/aurelia.json
+++ b/aurelia_project/aurelia.json
@@ -30,6 +30,12 @@
     "fileExtension": ".css",
     "source": "src/**/*.css"
   },
+  "textProcessor": {
+    "id": "none",
+    "displayName": "Text",
+    "fileExtension": ".json",
+    "source": "src/**/*.json"
+  },
   "editor": {
     "id": "webstorm",
     "displayName": "WebStorm"
@@ -69,7 +75,8 @@
           "name": "text",
           "extensions": [
             ".html",
-            ".css"
+            ".css",
+            ".json"
           ],
           "stub": true
         }
@@ -84,7 +91,8 @@
         "name": "app-bundle.js",
         "source": [
           "[**/*.js]",
-          "**/*.{css,html}"
+          "**/*.{css,html}",
+          "**/*.json"
         ]
       },
```

Anyone have any ideas why the trace just dies?

```
➜  my-app git:(master) ✗ au run --watch
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'prepareFontAwesome'...
Starting 'processText'...
Starting 'configureEnvironment'...
Finished 'processCSS'
Finished 'processText'
Finished 'configureEnvironment'
Starting 'buildJavaScript'...
Finished 'prepareFontAwesome'
Finished 'processMarkup'
Finished 'buildJavaScript'
Starting 'writeBundles'...
Tracing app...
Tracing environment...
Tracing main...
Tracing public...
Tracing resources/index...
Tracing routes/dashboard...
Tracing routes/login...
Tracing services/autobahn-service...
Tracing stores/static-store...
Tracing resources/form/bootstrap-form-renderer...
Tracing resources/view-widgets/confirm...
Tracing routes/admin/admin...
Tracing routes/admin/roles...
Tracing routes/admin/user-form...
Tracing routes/admin/users...
Tracing routes/products/products...
Tracing routes/usage/summary...
➜  my-app git:(master) ✗
```

**Comment by mika76** [comment]
I can't get this to work. Added in all the code from @graemechristie 's post but I still get  ```gulp-notify: [Error running Gulp] Error: src\static-page.ts(2,23): error TS2307: Cannot find module 'text!data.json'.```

**Comment by johot** [comment]
We managed to fix this in our aurelia-cli project.

To import use the following syntax:
`import * as config from 'text!./folder/config.json';`

This should work right away, try writing `alert(config)` for example.

Now you will probably see a typescript compilation error in your command line window. To fix this create a file with a `d.ts` extension in your `custom_typings` folder. The file title doesn't matter. In this file write:

<pre>
declare module "text!*" {
    const value: any;
    export default value;
}
</pre>

We also wrote a blog post about this here:
http://www.curbitssoftware.com/2017/04/04/importing-json-files-aurelia-cli-project/

**Comment by mostafa7240** [comment]
Use `export` before functions in the foo.js file:
```
export function someFunction(input){
    ...
    return output;
}

```
in the ts.config :
```
{
  "compilerOptions": {
    "allowJs": true,
    ...
    }
}
```
Now you can import and call that in the ts file:
`
import someName from '../JS/json_xml.js';  //path to the js file
`

At last in the class of the ts use what you want:
`
this.data = someName.someFunction(input);
`

**Comment by meta-pratap-ranawat** [comment]
Hi @EisenbergEffect ,

 I facing issue regard imprt for svg file in component

**`import logo from 'text!resources/aurelia-logo.svg';`**

This is not working for me. Is that i am missing any step for it.

I am working with typescript&webpack    

 @EisenbergEffect 

Thanks in Advance

**Comment by EisenbergEffect** [comment]
@meta-pratap-ranawat You may be using a require.js or system.js specific syntax in your import, which wouldn't work with Webpack. You probably want to look up how Webpack handles bundled svg resources. My guess is that you should start by just trying to import `resources/aurelia-logo.svg` and make sure the webpack config is setup to bundle svg correctly.

**Comment by sachingaurs** [comment]
111
