### ISSUE TITLE
Conflicting type definitions : angular-protractor and jquery

### ISSUE THREAD

**Issue by geleto** [aurelia/cli#301]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli@0.17.0

* **Operating System:**
Windows 10

* **Node Version:**
v6.3.1

* **NPM Version:**
3.10.3

* **Browser:**
Chrome 52.0.2743.116 m (64-bit)

* **Language:**
 TypeScript 

Hello, when using aurelia-cli TypeSript install with testing tools and after installing jquery:
```
npm install jquery --save
typings install jquery=dt~jquery -G --save
```
When building I get this error:
`typings\globals\jquery\index.d.ts(3218,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.`

This is a [known issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734) when using both libraries and can be frustrating for anyone who wants to use jquery with Typescript and the testing tools.

**Comment by NimaAra** [comment]
For completeness I have added the following two files resolve the above issue _for now_:

### adhoc_interfaces.d.ts
```javascript
interface URLSearchParams {}
```
### aurelia-protractor.d.ts
```javascript 
// Extend existing interfaces with additional functionality from Aurelia Protractor Extender (aurelia.protractor.js)
declare module protractor {
  interface IBrowser extends protractor.Protractor {
    loadAndWaitForAureliaPage(url: string): protractor.Protractor;
    waitForRouterComplete();
  }

  interface IProtractorLocatorStrategy {
    valueBind(bindTarget: string): webdriver.Locator;
  }
}
```
