### ISSUE TITLE
Bundle dependency resources not including all files matching a file mask

### ISSUE THREAD

**Issue by salminio** [aurelia/cli#302]
**I'm submitting a bug report**
- **Library Version:**
  0.18.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  5.10.1
  
  
- **NPM Version:**
  3.8.6
  
  
- **Browser:**
  Chrome 52
- **Language:**
  ESNext

**Current behavior:**
I have about 50 html files that I'm trying to include in a named bundle... Using a wildcard it includes the first 12-13 depending on size. These html files are in various subfolders and if I start to add addtional entries to include the subfolders but not necessarily all of them. If I list out each individual entry - then they all get included.
`
            {
                "name": "thingworx-ui-bundle.js",
                "dependencies": [
                    {
                        "name": "my-lib",
                        "path": "../node_modules/my-lib/dist",
                        "main": "index",
                        "resources": [
                            "**/*.html"
                        ]
                    }
                ]
            }
`

**Expected/desired behavior:**

- **What is the expected behavior?**
  I expect all files in the mask to be included.
- **What is the motivation / use case for changing the behavior?**
  Migrating to CLI from JSPM/SystemJS

**Comment by EisenbergEffect** [comment]
I'm having a little bit of trouble following the explanation. My apologies. Can you provide some more details and expand the explanation.

**Comment by salminio** [comment]
Using a wildcard in the resources section of a cli bundle definition (aurelia.json) to bundle my html files does NOT include all the html files. It only includes ~13 out of 50. If instead of using a wildcard I list out each one specifically, then I get the bundle in. All 50 files are NOT in one directory - they are separated into many different sub directories. 

To work around this I had to build a separate function to build the aurelia.json on the fly which explicitely lists out all the html files.

**Comment by AStoker** [comment]
@salminio, not entirely sure of the solution, just digging for some clarifying answers.  
Are the ~13 html files that are included in the bundle the same files consistently? In other words, if you run the build a few times, are the files that are put in the bundle the same ones, or are different html files being included on each re-build?

**Comment by salminio** [comment]
The files were consistent (same set each time).

**Comment by AStoker** [comment]
@salminio, are you able to provide the names of those html files, and their paths? As well as your configuration? And can you also post the output of your build command?  
If I were to venture a wild guess, I have a feeling that maybe during the bundling process, it's getting to one of those html files (the 14th) and something is causing the bundling to fail, so it ignores the rest... I'd imagine something like that to throw an error though.

**Comment by JeroenVinke** [comment]
This sounds related to https://github.com/aurelia/cli/issues/368 which was fixed a while ago. Due to https://github.com/aurelia/cli/issues/368 not all resources were traced and specifying all files individually resolved the issue as well. @salminio do you still encounter this issue, or can we close this one?

**Comment by Thanood** [comment]
Materialize bridge (has a lot of files and) is at least bundled correctly. 😃

**Comment by JeroenVinke** [comment]
I tried this with the latest version of the bridge and it works as expected now
