### ISSUE TITLE
Time required to build and/or run a project is seemingly excessive

### ISSUE THREAD

**Issue by emcga** [aurelia/cli#303]
**I'm submitting a performance request**
- **Library Version:**
  0.17.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11
- **Node Version:**
  6.4.0
  
  
- **NPM Version:**
  3.10.6
  
  
- **Browser:**
  Chrome 52.0.2743.116
- **Language:**
  TypeScript

**Current behavior:**
When executing au run, or au build it takes considerably longer to build my project than it did with gulp. The longest part of the build process is when it traces my src directory. Is there a configuration param that will speed things up a bit?

**Expected/desired behavior:**

- **What is the expected behavior?**
  For au run to start up faster than it currently does. Preferably as fast as gulp did.
- **What is the motivation / use case for changing the behavior?**
  Speeding up workflow. The bigger my project gets, the longer it takes. As of right now I have 15 small files in my src directory and it takes 30+ seconds before I can run my app.

**Comment by EisenbergEffect** [comment]
Gulp only built your code before. It didn't trace dependencies and create deployable bundles. That's why it takes longer. It shouldn't take 30 seconds for 15 files though. I'm not sure what is going on there. We do have some plans to improve performance but some other features and fixes are higher priority at the moment.

**Comment by emcga** [comment]
@EisenbergEffect Thanks for the quick reply. It may even be something on my end with my current configuration. It just seems like tracing takes forever, but it's responsive once built. And the --watch flag is responsive when modifying existing code. Overall I do really like aurelia-cli and think it makes life much easier, and makes using the framework even more enjoyable. Just thought I would express my concern with the speed issue I'm experiencing on my end. I will try to build the project on my Linux machine to see if OSX, or my current config is the problem. Thanks again.

**Comment by emcga** [comment]
Just so you have my stats. 

au run time: 43 sec
17 src files with 300 lines of code max per file

My system is a 2.7 Ghz i7 with 8GB RAM and a Samsung SSD

**Comment by djedi** [comment]
au build  82.51s user 2.37s system 102% cpu 1:22.89 total

2.3 GHz i7 with 16 GB RAM & SSD

I'm thinking I may go back to jspm until this improves or there is some way to skip tracing. Build time is killing me and this project is only going to get bigger.

**Comment by LarsKemmann** [comment]
I'm wondering along similar lines whether there's some overhead going on in our case. I've got an ASP.NET Core project where in the `project.json` `scripts` section I'm calling `au build` as a pre-compile step. That adds 15 seconds to my otherwise 1-2 second build time for the project.

I'd like to try a test first that just calls the actual Gulp tasks, to see if that reduces the performance impact noticeably. That would be `aurelia_project/tasks/build.ts`, correct? How might I go about calling that from e.g. a `gulpfile.js` in the root of the project?

**Comment by EisenbergEffect** [comment]
The standard use scenario is to run `au run --watch` and to keep that running while you develop. This allows the CLI to incrementally build only the changed files and update the bundles quickly with the changes, rather than having to build and bundle everything over and over again.

**Comment by jadrake75** [comment]
I would be all for improvements in compile time, however the compiled output and the development process with the --watch has been stellar.  We have a growing larger and larger app and soon I suspect we'll need to do some creative generation of the bundles (maybe even some sort of vendor then multiple app bundles in parallel or something) as it can take a while.  Still I think it is the right direction.  Just need some tweaking on the path.

**Comment by EisenbergEffect** [comment]
I think there are probably a lot of perf things we can do, including some smarter caching and updating of bundles, even across executes of the commands.

**Comment by ggrimbert** [comment]
I hope you'll work on this, with my project (about 300 files), build takes more than 6 minutes...

**Comment by AStoker** [comment]
@ggrimbert, how many vendor files are you pulling in? We have about the same amount of source code, maybe a bit less, but it only takes upwards of 1 minute tops.

**Comment by ggrimbert** [comment]
I have 50 dependencies

**Comment by AStoker** [comment]
What size does your `vendor-bundle` get up to? Trying to identify what the bottleneck is with what's causing the time to be so large.

**Comment by ggrimbert** [comment]
The vendor-bundle size is 3.3Mo, 95852 lines.

I don't think the problem comes from the vendor bundle, I see aurelia-cli taking 3-4 sec for each of my file. The app-bundle file size is 7.7Mo...

But after my files are processed, dependencies are done very fast (about 3 sec) for one dependency and all of its files.

**Comment by AStoker** [comment]
So you say you have about 300 files... How big are those files if your app bundle is 7.7Mb? 😝  
There is definitely some optimization of files that can take place, but it might sound like for your setup the big problem is just the sheer number/size of your files.  
We have to trace each of the app files for their dependencies, and it's quite possible that the trace is what's taking so long.

**Comment by ggrimbert** [comment]
Files obviously have a different size, I'd say that the average line number is 300. 

But in those 300 files, nearly 40% are html files, so the only process for them is to take the code and put it in the app-bundle so the time for processing them is ridiculous. 
Maybe the problem for all js files might be the inheritance, every viewmodel extends a 'base-viewmodel'. Can it be a start of explanation ?

**Comment by AStoker** [comment]
I can't say for sure, maybe... But most source files have some kind of source files included, so it shouldn't be too big of a surprise. Does the base-viewmodel go crazy with dependencies? If each file depends on the base view model, and the base view model has a bunch of deps, then for each file, you would have to trace all the same deps, every time (which could slow it down if there are many).

**Comment by ggrimbert** [comment]
The base-viewmodel has 9 dependencies, 5 are ours and they depend on other files too.

But don't you have a kind of cache to prevent this from happening ? I think this is an important thing in this kind of project.

**Comment by AStoker** [comment]
We use Amodro Trace (https://github.com/amodrojs/amodro-trace). Didn't personally write the tracing part of the CLI, so I'm not sure if the tracer does the caching like that or not (I would hope it would!)

**Comment by djedi** [comment]
Is the tracing step really necessary? Could a flag be passed to skip the tracing when we're confident it doesn't need to be done?

**Comment by AStoker** [comment]
How else would you properly find your dependencies @djedi?

**Comment by ggrimbert** [comment]
I posted an issue on amodro-trace, a caching system is on reflection, feel free to post there if you have an idea of the way to process. https://github.com/amodrojs/amodro-trace/issues/5

**Comment by huochunpeng** [comment]
I waited too long for this to be fixed, so I spent some hours today and got a working fix!

Try this in your big project package.json to see if this solve your problem.

```
"devDependencies": {
    "aurelia-cli": "git://github.com/huochunpeng/cli.git#trace_cache",
    // ...
}
```

Surprisingly, the slowest part is not repeated parsing (to find out deps), it's writeTransform. I did a profile, writeTransform consumes 85s of 110s (my project build time).

My fix includes:

1. uses amodro-trace's [issue5-trace-cache](https://github.com/amodrojs/amodro-trace/compare/issue5-trace-cache) branch (it caches deps), patch cli to use it, it reduces my build time from 125s to 110s on a project with 144 js files.
2. patch amodro to use cached contents, it reduces build time to 32s.

@EisenbergEffect could someone from Aurelia try this before I submit a PR?

**Comment by EisenbergEffect** [comment]
Woohoo! This sounds awesome! @AStoker Can you check this out and see if we can bring it in?

**Comment by ggrimbert** [comment]
Hi,

I tried and this works perfectly !

The only negative point I found is the version of NodeJS required for this to work. I first tried with Node 5.0.0 and it has a problem with ```const {id, deps, contents} = item;``` in bundled-source.js.

But with node 6.7.0 it works as expected.

Thanks a lot for this work, it will save my days

**Comment by huochunpeng** [comment]
I will refactor my code to use es5 syntax.

**Comment by tdamir** [comment]
I'm getting an Object.values is not a function in bundled-source.js:17:17
NodeJS v6.5.0 and v6.9.1.

**Comment by huochunpeng** [comment]
@tdamir I am using latest v6.9.1. Did you has a special nodejs configuration somewhere that disabled some es6 features?

**Comment by huochunpeng** [comment]
@tdamir I refactored the code to avoid Object.values. Have a try.

**Comment by tdamir** [comment]
It works now. Perfect. Thanks!
According to these: http://node.green/ and https://nodejs.org/en/docs/es6/ for the usage of Object.values a --harmony runtime flag is needed.

**Comment by huochunpeng** [comment]
@tdamir interesting. Something on my Mac must turned on harmony mode. Object.values works even in v4.6.1 on my machine. My node is installed through nodenv.

**Comment by tdamir** [comment]
@huochunpeng Could be. Honestly, I'm still noob for the nodejs. I'm working in Windows environment and installed it from the executable provided on the nodejs site.

**Comment by AStoker** [comment]
@huochunpeng, thanks so much for spending time making a PR for this issue! Seriously, it goes a long way. In regards to node versions, I'm pretty sure (I'm ready to be corrected) that the CLI only supports the v4 LTS, v6 LTS, and the latest...  
@EisenbergEffect, I'll try and take a look at it today.

**Comment by AStoker** [comment]
@huochunpeng, if you could make a PR so we can discuss fixes there, I'd greatly appreciate it. I just tried to use your fix in my production setup, and it seems to silently fail and not write out the files. On the plus side though, the tracing step was _significantly_ faster :)

**Comment by huochunpeng** [comment]
Removing tracing works. #431 
Please help to test it and report your issue there. Thanks very much.
Beware of aurelia.json change.

**Comment by EisenbergEffect** [comment]
Fixed.
