### ISSUE TITLE
Cli don't support jquery-ui

### ISSUE THREAD

**Issue by behel33** [aurelia/cli#306]
I have do 
```
npm install jquery
npm install jquery-ui
```

and I write in aurelia.json :     
```
       .... build.bundle : {     
       "jquery",
          {
          	"name": "jquery-ui",
          	"path": "../node_modules/jquery-ui",
          	"main": "ui/widget.js",
         	"deps": ["jquery"],
         	"exports": "$"
          },
```

But when I want use sortable of jquery-ui I get:
` jQuery().sortable` is not a function
What is wrong ?

**Comment by icegnome** [comment]
I believe you just need to drop the .js from widget.js,  the extension is implied
For example bootstrap:
`
          "jquery",
          {
              "name": "bootstrap",
              "path": "../node_modules/bootstrap/dist",
              "main": "js/bootstrap.min",
              "deps": ["jquery"],
              "exports": "$"
          },
`

**Comment by behel33** [comment]
I want use jquery-ui and not bootsrap (which is very slow on firefox/IE).
the tree of jquery-ui is :
```
build
demos/
external/
tests/
themes/
ui/
ui/effects/
ui/i18n/
ui/widgets/
```
It is not common to bootstrap.
Any idea how insert jquery-ui ?

**Comment by behel33** [comment]
I had find the solutions.
To include jquery-ui not use "jquery-ui" but use "jquery-ui-dist" by :
`npm install jquery-ui-dist`
then add in aurelia.json :+1: 
```
 {
          	"name": "jquery-ui",
          	"path": "../node_modules/jquery-ui-dist",
          	"main": "jquery-ui",
         	"deps": ["jquery"],
         	"resources": ["jquery-ui.css"],
         	"exports": "$"
 },
```

**Comment by pkozul** [comment]
behel33, thanks for that. It works fine. I didn't realize there was "jquery-ui-dist".
