### ISSUE TITLE
au new failed on install project dependencies

### ISSUE THREAD

**Issue by cgi49** [aurelia/cli#308]
**I'm submitting a bug report**

* **Library Version:**
0.19-0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.6

* **Browser:**
all
* **Language:**
all

**Current behavior:**

C:\ProjetsTS>au new

Project Configuration

    Name: contact-manager
    Platform: Web
    Transpiler: TypeScript
    CSS Processor: None
    Unit Test Runner: Karma
    Editor: Visual Studio Code

Would you like to create this project?

1. Yes (Default)
   Creates the project structure based on your selections.
2. Restart
   Restarts the wizard, allowing you to make different selections.
3. Abort
   Aborts the new project wizard.

[Yes]>
Project structure created and configured.

Would you like to install the project dependencies?

1. Yes (Default)
   Installs all server, client and tooling dependencies needed to build the project.
2. No
   Completes the new project wizard without installing dependencies.

[Yes]>

Installing project dependencies.
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-ecf98f08: undefined
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-ecf98f08: undefined
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-4-0-4b46db44: undefined
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-4-0-4b46db44: undefined
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: undefined
**npm ERR!** git clone --template=C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\cgincheleau\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: undefined

**Comment by EisenbergEffect** [comment]
Make sure you have git installed and that it is working properly. That seems to be the problem.

**Comment by cgi49** [comment]
Thank you very much, actually GitHub for Windows does indeed install its own version of Git, but it doesn't add it to the PATH variable : Solution =>http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows
