### ISSUE TITLE
issues with node v. 6.5 and npm v. 3.10.3

### ISSUE THREAD

**Issue by krzysiek009** [aurelia/cli#311]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Mint)

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **Browser:**
none

* **Language:**
all

**Current behavior:**
The module installed with no trouble, the project creation ran flawlessly. Afterwards none of the commands from the documentation worked.
"au run", "au test", even "au help".
All commands result in ASCII art logo and basic help message. After downgrading to node v4.5.0, cleaning npm cache, and reinstalling the module, the same steps led to a working app.

**Expected/desired behavior:**

The CLI should respond to commands described in the docs.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by AStoker** [comment]
Try running the following commands:
`npm uninstall aurelia-cli au -g` //Removes any instance of aurelia-cli
`npm cache clean` //Cleans out any cached version of the install
`npm install aurelia-cli -g` //Globally installs aurelia-cli (will be v.0.19.0)
`npm install aurelia-cli` //Locally updates aurelia-cli (to version v.0.19.0)
And then try those commands (`au run`...) again.

**Comment by EisenbergEffect** [comment]
Closing due to no response from the OP.
