### ISSUE TITLE
some bundled imports behave differently in aurelia-karma vs. browser

### ISSUE THREAD

**Issue by fkleuver** [aurelia/cli#312]
**I'm submitting a bug report**
- **Library Version:**
  0.19.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.5.0
  
  
- **NPM Version:**
  3.10.6
  
  
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.2

**Current behavior:**
CodeMirror underlying imports work fine with `au run` but with `au test` they error out with "Uncaught ReferenceError: CodeMirror is not defined". This prevents the test runner from starting.

It's this piece of code where it goes wrong:

```
if (typeof exports == "object" && typeof module == "object")
    mod(require("../../lib/codemirror"));
else if (typeof define == "function" && define.amd)
    define(["../../lib/codemirror"], mod);
else // **it enters here when running test, and it crashes**
    mod(CodeMirror);
```

When running in the browser, it enters the second statement `define(["../../lib/codemirror"], mod);` and it works.
When running the test, it enters the third statement `mod(CodeMirror);` and errors out.

For some reason `define` or `define.amd` is not defined (or not of the correct type) in the scope of those imports in the test runner, causing it to fall through to the third statement which does not work.

Manually replacing the piece of code above with simply this line directly in the bundle, fixes the problem:
`define(["../../lib/codemirror"], mod);`

**Expected/desired behavior:**

I expect my imports to behave the same way with `au run` as they do with `au test`. This particular scenario should either work with `au test`, or fail completely in both cases.
Probably `define` and `define.amd` should be defined so the test runner works.

Or alternatively - if I'm missing something obvious here - the docs need to include the piece of information that would allow me to properly configure my aurelia.json and/or tests.
- **Steps to reproduce:**

I have attached a minimal project that illustrates the problem:
[aurelia-testing-test.zip](https://github.com/aurelia/cli/files/465671/aurelia-testing-test.zip)
1. npm install
2. au run --env dev
3. open it in the browser -> the editor will display, no script errors occur
4. au test -> crashes
- **What is the motivation / use case for changing the behavior?**

The ability to have tests work out-of-the-box in more scenarios when aurelia.json is properly configured and works in the browser.

**Comment by EisenbergEffect** [comment]
If you have a recommendation for how we can improve the Karma configuration, that would certainly help. I'm not sure off-hand why this would be happening.

**Comment by freddykleuver** [comment]
`define.amd` is not defined when app-bundle.js runs from au test.
I'm not even sure where `define` is coming from.

scripts/require.js does this right after defining `define`:
`define.amd={jQuery:!0}`

So it doesn't look like the test runner is using scripts/require.js. Is this perhaps what needs to be fixed?

The only way I've been able to "fix" it so far is by adding the following to the top of app-bundle.js.

```
if (typeof define === "function" && (typeof define.amd === "undefined" || define.amd === null)) {
  define.amd = {};
}
```

**Comment by JeroenVinke** [comment]
[updated.zip](https://github.com/aurelia/cli/files/1777801/updated.zip)

This seems to be resolved in the current version of the CLI
