### ISSUE TITLE
au new creates package.json with previous version of aurelia-cli

### ISSUE THREAD

**Issue by guidorice** [aurelia/cli#314]
**I'm submitting a bug report**

**Library Version:**
 au --version
0.19.0

**Please tell us about your environment:**
* **Operating System:**
freebsd 9.3

* **Node Version:**
v6.2.2

* **NPM Version:**
3.9.2

* **Browser:**
all

* **Language:**
all

**Current behavior:**

```
$ au --version
0.19.0
$ au new test-proj

Project Configuration

    Name: test-prj
    Platform: Web
    Transpiler: Babel
    CSS Processor: None
    Unit Test Runner: None
    Editor: Atom

$ cd test-proj
$ au --version
0.18.0

$ grep aurelia-cli package.json 
    "aurelia-cli": "^0.18.0",
```

**Expected/desired behavior:**
aurelia-cli should create package.json with the latest same of aurelia-cli.

If this is not actually bug, it is confusing to see this when trying to figure out if the current version of aurelia-cli is installed or not, and how to update it to latest.

**Comment by guidorice** [comment]
Seeing same problem with 0.20.0

**Comment by guidorice** [comment]
Reproduced on OS X npm 3.10.5 and on Freebsd npm 3.9.2

**Comment by AStoker** [comment]
What happens if you run `npm cache clean` and then those steps again?

**Comment by EisenbergEffect** [comment]
This is a bug. It's completly my fault. I'll get it sorted soon.

**Comment by guidorice** [comment]
Hi guys, thanks so much for looking into this. Andrew btw I did try the `npm cache clean` but got  same results.

**Comment by EisenbergEffect** [comment]
Fixed.

**Comment by guidorice** [comment]
Rob, this is still occurring in 0.20.2

**Comment by AStoker** [comment]
Did you clean out your npm cache and re-install the cli?

**Comment by guidorice** [comment]
Ah no, I did not realized we need to uninstall and reinstall aurelia-cli for each release.

**Comment by AStoker** [comment]
What _**might**_ have happened was that npm cached a previous version of the cli, and that's what is actually running. Just wanted to confirm if that was the issue.

**Comment by guidorice** [comment]
I think that matches what I am seeing now. npm is weird! :) sorry for the noise

**Comment by AStoker** [comment]
No problem! Hope we can get some of this stabilized so we have less of these kinds of issues :)
