### ISSUE TITLE
support output.publicPath or similar config, for loading app-bundle.js

### ISSUE THREAD

**Issue by guidorice** [aurelia/cli#315]
**I'm submitting a feature request**
- **Library Version:**
  au --version
  0.19.0

**Please tell us about your environment:**
- **Operating System:**
  freebsd 9.3
- **Node Version:**
  v6.2.2
- **NPM Version:**
  3.9.2
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**

Hey all, I keep running into this roadblock trying to use aurelia-cli for anything except a single page application! In the web framework on the server side (php/drupal), I output a script tag tag in a template like this:

`<script src="/sites/all/modules/tripal/tripal_phylogeny/theme/js/aurelia/scripts/vendor-bundle.js" data-main="aurelia-bootstrapper"></script>`

The vendor-bundle.js then tries to load app-bundle.js based on the URL of the page, which happens to be: `http://localhost:8081/chado_phylotree/scripts/app-bundle.js` which is a path that does not exist.

As far as I can tell from the aurelia-cli docs, there is no way to adjust the public path of the loader.

**Expected/desired behavior:**

IIRC, webpack has an option to specify the public path for where it's chunk loader / lazy loader will source the child scripts. Making it more flexible in this respect.

https://github.com/webpack/docs/wiki/Configuration

> output.publicPath  The publicPath specifies the public URL address of the output files when referenced in a browser.

Just to be sure, I tried the `output : { path: '', publicPath: '' }` but it does not seem to be supported by aurelia-cli.
- **What is the motivation / use case for changing the behavior?**

Currently it is inflexible, and is going to cause problems in many usage scenarios for aurelia  integrating into an existing site, or non-SPA context, where one does not have full control over the document root path, or for CDN usage. 

I also ran into this issue when build a site served by a Flask/Python web framework. In that case I was able to solve it because I had full permissions over the paths, but I had to do some symlinking of directories to make stuff exist where aurelia-cli expected it should be. Need to be able to just configure aurelia-cli to "load stuff from here", whether it is a CDN, or static/ or assets/ directory.

**Comment by magnusdanielson** [comment]
On the last line in vendor-bundle.js you have the following line:
`function _aureliaConfigureModuleLoader(){requirejs.config({"baseUrl":"src/"`

If you manually (or with gulp ) update the baseUrl you can load from different source.

**Comment by AshleyGrant** [comment]
@JeroenVinke it looks like I found this old bug. Hope this bug report can help!
