### ISSUE TITLE
http connection to github.com not only the SSH connection

### ISSUE THREAD

**Issue by bootrider** [aurelia/cli#316]
**I'm submitting a feature request**

* **Library Version:**
0.19

**Please tell us about your environment:**
* **Operating System:**
Windows 7
* **Node Version:**
6.3.1

* **NPM Version:**
3.10.5

* **Browser:**
all

* **Language:**
all 

**Current behavior:**
Trying to perform the command **au new --here** but at the end of the wizard due to security issues I got:

```
Installing project dependencies.
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: Cloning into bare repository 'C:\Users\XXXX\AppData\R
oaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801'...
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: ssh_exchange_identification: read: Connection reset by pee
r
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801:
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\XXXX\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-7c06e801: and the repository exists.

```

**Expected/desired behavior:**

* **What is the expected behavior?**
it would be nice to have an option to use http connection to github.com not only the SSH connection

* **What is the motivation / use case for changing the behavior?**
some companies have its development teams behind firewalls and security policies, and are not able to proceed to use this tool

**Comment by EisenbergEffect** [comment]
That is all handled by npm. All the cli does is run an `npm install`.

**Comment by bootrider** [comment]
But the links to the packages are hardcoded in aurelia-cli\package.json

Line 59:     "url": "https://github.com/aurelia/cli/issues"
Line 100:     "url": "git+https://github.com/aurelia/cli.git"

**Comment by bootrider** [comment]
Also after the wizard  has finished, the gulp dependency in the package.json file states:

gulp": "github:gulpjs/gulp#4.0",
