### ISSUE TITLE
Coverage for test execution

### ISSUE THREAD

**Issue by bootrider** [aurelia/cli#318]
**I'm submitting a bug report**

* **Library Version:**
0.19

**Please tell us about your environment:**
* **Operating System:**
Windows7

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.5

* **Browser:**
Chrome | PhantomJs

* **Language:**
TypeScript

**Current behavior:**
Perform the command au new --here , create the new project, and try to execute the test included, it ran with out issues, but then I feel keen to know the coverage of that test, I configure karma to generate coverage:

```
"use strict";
const path = require('path');
const project = require('./aurelia_project/aurelia.json');
const tsconfig = require('./tsconfig.json');

let testSrc = [
  { pattern: project.unitTestRunner.source, included: false },
  'test/unit/setup.js',
  'test/aurelia-karma.js'
];

let output = project.platform.output;
let appSrc = project.build.bundles.map(x => path.join(output, x.name));
let entryIndex = appSrc.indexOf(path.join(output, project.build.loader.configTarget));
let entryBundle = appSrc.splice(entryIndex, 1)[0];
let files = [entryBundle].concat(testSrc).concat(appSrc);
console.log(files);

module.exports = function(config) {
  config.set({
    basePath: './',
    frameworks: [project.testFramework.id],
    files: files,
    exclude: [],
    preprocessors: {
      [project.unitTestRunner.source]: [project.transpiler.id],
        'src/**/*.js':['coverage']
    },
    typescriptPreprocessor: {
      typescript: require('typescript'),
      options: tsconfig.compilerOptions
    },

    reporters: ['progress','coverage'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false,

    coverageReporter: {
        reporters: [
            { type: 'json', subdir: '.', file: 'coverage-final.json', dir: 'coverage/' },
            {
                type: 'lcov', subdir: '.', dir: 'coverage/'
            }
        ]
    },

    plugins: [
                'karma-jasmine',
                'karma-coverage',
                'karma-phantomjs-launcher',
    ],   

  });
};
```
Neither running the test from Karma Start command nor au test, the run successfully. I got:

```
C:\T\Unity_Plot\Main\XXXX\XXXX.UnityPlot.Web>karma start
[ 'wwwroot\\scripts\\vendor-bundle.js',
  { pattern: 'test\\unit\\**\\*.ts', included: false },
  'test/unit/setup.js',
  'test/aurelia-karma.js',
  'wwwroot\\scripts\\app-bundle.js' ]
14 09 2016 17:44:25.965:WARN [preprocess]: Can not load "typescript", it is not registered!
  Perhaps you are missing some plugin?
14 09 2016 17:44:26.029:WARN [karma]: No captured browser, open http://localhost:9876/
14 09 2016 17:44:26.037:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
14 09 2016 17:44:26.045:INFO [launcher]: Starting browser PhantomJS
14 09 2016 17:44:27.661:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#Zba6VI3viR0nvlnSAAAA with id 614176
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Error: Mismatched anonymous define() module: function (require, exports, aurelia_pal_browser_1) {
      "use strict";
      aurelia_pal_browser_1.initialize();
  }
  http://requirejs.org/docs/errors.html#mismatch
  at C:/T/Unity_Plot/Main/XXXX/XXXX.UnityPlot.Web/wwwroot/scripts/vendor-bundle.js:3763


Terminate batch job (Y/N)? y

C:\T\Unity_Plot\Main\XXXX\XXXX.UnityPlot.Web>au test
Starting 'unit'...
[ 'wwwroot\\scripts\\vendor-bundle.js',
  { pattern: 'test\\unit\\**\\*.ts', included: false },
  'test/unit/setup.js',
  'test/aurelia-karma.js',
  'wwwroot\\scripts\\app-bundle.js' ]
14 09 2016 17:44:57.610:WARN [preprocess]: Can not load "typescript", it is not registered!
  Perhaps you are missing some plugin?
14 09 2016 17:44:57.673:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
14 09 2016 17:44:57.681:INFO [launcher]: Starting browser PhantomJS
14 09 2016 17:44:59.357:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#4xXwG6IuSex1s-vqAAAA with id 75393093
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Error: Mismatched anonymous define() module: function (require, exports, aurelia_pal_browser_1) {
      "use strict";
      aurelia_pal_browser_1.initialize();
  }
  http://requirejs.org/docs/errors.html#mismatch
  at C:/T/Unity_Plot/Main/XXXX/XXXX.UnityPlot.Web/wwwroot/scripts/vendor-bundle.js:3763


{ uid: 0,
  name: 'unit',
  error: 1,
  duration: [ 5, 343706445 ],
  time: 1473893102523 }
1
```

**Expected/desired behavior:**

* **What is the expected behavior?**

the tests run and generates the coverage info

**Comment by AStoker** [comment]
Does the coverage reporter work when using a different launcher other than phantom? Do the errors look any different?

**Comment by bootrider** [comment]
I try to use it with the Chrome launcher for Karma, reporter did not work

**Comment by AStoker** [comment]
Can you reproduce this error in the skeleton project without typescript (e.g. ESNext)?

**Comment by Jenselme** [comment]
It looks like you are missing a plugin like [this one](https://www.npmjs.com/package/karma-typescript-preprocessor) to make it work.

Using ES6, I am able to get coverage on the generated files in dist with [this karma file](https://github.com/arenaoftitans/arena-of-titans/blob/299ff3d20075ab918d72d7847e0333dc125f95d1/karma.conf.js). It is not optimum, I'd prefer to have the coverage of the source code instead.

I also managed to get coverage on the source with [karma-remap-istanbul](https://www.npmjs.com/package/karma-remap-istanbul) which uses source maps to generate the report on the sources. However, I don't have colors and I get the reports per file in the source folder which is annoying in my opinion. You can view the associated karma file [here](https://github.com/arenaoftitans/arena-of-titans/blob/a738f0c350e3a8e24316baf6e1cd2e14d86019e6/karma.conf.js).

I tried to configure karma to use requirejs and babel to use directly the source files without success so far. You can look at my non working karma conf [here](https://github.com/arenaoftitans/arena-of-titans/blob/68e71245ee065a700c71696bb13b0d09d17025dc/karma.conf.js).

I think it would be a huge plus to be able to configure code coverage for the source (and not the transpiled files) with the cli.

**Comment by fragsalat** [comment]
I got a very nice and simple solution based on babel-plugin-instanbul. It generates a coverage report based on the source files and the setup is super easy.
@EisenbergEffect  This might be an option behind a flag for the cli setup with babel.

Install karma-coverage for report generation and babel istanbul plugin to track coverage on source files
```bash
npm i -D babel-plugin-istanbul karma-coverage
```

Add coverage reporter and reporter config in aurelia_project/tasks/test.js
```js
new Karma({
  configFile: path.join(__dirname, '/../../karma.conf.js'),
  singleRun: !CLIOptions.hasFlag('watch'),
  reporters: ['spec', 'coverage', 'junit'],
  junitReporter: {
    outputDir: project.paths.reports,
    outputFile: 'junit-report.xml',
    useBrowserName: false
  },
  coverageReporter: {
    dir: project.paths.reports,
    includeAllSources: true,
    reporters: [
      {type: 'cobertura', subdir: '.'},
      {type: 'html', subdir: '.'},
      {type: 'text'}
    ]
  }
}, done).start();
```

Add istanbul plugin to test babel config in aurelia_project/aurelia.json
```json
  "transpiler": {
    "id": "babel",
    "displayName": "Babel",
    "fileExtension": ".js",
    "options": {
      "plugins": [
        "transform-es2015-modules-amd",
        "istanbul"
      ]
    },
    "source": "src/app/**/*.js"
  },
```

**Comment by stevies** [comment]
@fragsalat - with your solution, do you get the instrumented code included in your final build app-bundle.js file?  The istanbul plugin appears to always be enabled when transpiling.  You'd need some way of turning it off when doing a full build.

**Comment by fragsalat** [comment]
Yeah thats true. It would require two different configs.

**Comment by stevies** [comment]
Thanks.  I was seeing that happen, and wasn't sure I was missing something.  I worked around it by using a different configuration when running coverage and when building for the final output.
