### ISSUE TITLE
Respect editorconfig settings

### ISSUE THREAD

**Issue by zewa666** [aurelia/cli#32]
Our code currently seems to follow different code-styles. It'd be nice if we could setup the file editorconfig as we need it and rely on those formats. Currently it says e.g. intends of 2 yet most of the files have 4 spaces.

**Comment by PWKad** [comment]
Definitely agree there was also a line spacing issue before.  We need to have a `fix everything commit to fix all of the spacing issues and review all PRs going forward for consistency.  Can github help us enforce the spacing issue?
