### ISSUE TITLE
Aurelia CLI template for ASP.NET Core doesn't serve files with au run

### ISSUE THREAD

**Issue by jcarrascal** [aurelia/cli#322]
**I'm submitting a bug report**
- **Library Version:**
  au --version
  0.18.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  node -v
  v6.3.1
- **NPM Version:**
  npm -v
  3.10.5
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**
After creating a project with au new --here on an ASP.NET Core project, and runing with au run the server returns the string "Cannot GET /" to the server

**Expected/desired behavior:**
The server returns index.html. The browser displays "Hello, world!"
On ASP.NET Core projects the statics files are served from the wwwroot folder. I found that the template for ASP.NET Core projects create a gulp task called run that configures the browserSync server with is baseDir as ["."]. Changing it to baseDir: ['./wwwroot'] fixes the problem.

**Sugested**
On the ASP.NET Core templates change the baseDir property of browserSync to point to ['./wwwroot'] by default. Maybe also show a message with the name of the file to change (aurelia_project\tasks\run.ts) in case that the wwwroot folder has been renamed.

**Comment by rsuter** [comment]
@jcarrascal how did you create a .NET Core based project with "au new"? I don't have this option...

**Comment by kodeek** [comment]
I still needed to change baseDir in aurelia_project\tasks\run.ts in version 0.23.0.

**Comment by bgardner87** [comment]
@kodeek I'm having the same issue and updated the baseDir in the run task. In my case, the page loads but gets a 404 when trying to load the vendor-bundle.js from the /scripts directory.

This looks like a similar relative path issue, are you seeing the same thing?

**Comment by kodeek** [comment]
Hi @bgardner87, I think your issue is related to this issue - https://github.com/aurelia/cli/issues/173. I hope that will help you.

**Comment by bgardner87** [comment]
@kodeek Thanks for the link, looks like you ended up in the same place I did by changing the build=>targets=>output property. From then on it seems to be working perfectly.

**Comment by reft** [comment]
How did you manage to get the browser sync to work in .net core? I can only get it to work in port:9000, (not 5000).

http://stackoverflow.com/questions/42040786/aurelia-net-core-browser-sync-not-working-on-net-core

**Comment by JeroenVinke** [comment]
Lets continue in https://github.com/aurelia/cli/issues/531 which is the same issue
