### ISSUE TITLE
Allow for multiple source folders

### ISSUE THREAD

**Issue by derkork** [aurelia/cli#323]
In my project I experiment with code generation. In an ideal world one would have the generated sources outside of the handwritten sources. So I set up a project like this:

- src
  -  [handwritten sources here]
- target
  - generated-sources
    - [generated sources here]

Then in aurelia.json i modify 

```
  "transpiler" : {
    ...
    "source": ["src/**/*.js", "target/**/*.js"],
   }
```
This works, the new files are picked up and being transpiled and added as modules to `app-bundle.js` by the aurelia cli build system. However the modules get strange relative names assigned to them. While the things from the `src` folder look like this:

```
define('resources/pages/edit-user-profile', ....)
```

The things from the `generated-sources` folder look like this:

```
define('../target/generated-sources/resources/...', ....)
```

So they seem to get a module name that starts with a relative path, which makes them impossible to import in a component.  I tried to set up a second root in `aurelia.json` like this:

```
"paths": {
    "root": ["src", "target/generated-sources"]
```

But this property is required to be a plain string. As a workaround I currently generate my stuff directly into the `src` folder, but this is less than ideal as one needs to make sure not to commit generated sources. It would be nice if aurelia-cli would support multiple source roots in a future release.

**Comment by AStoker** [comment]
Could this be resolved by creating a different bundle that references your generated code outside the `src` folder?

**Comment by derkork** [comment]
Maybe. As far as I can see the `aurelia.json` allows you to specify bundles in the bundles section but how would I create such a bundle in the first place using only one project file?

**Comment by AStoker** [comment]
You're project file (the `aurelia.json` file I'm guessing you mean) should exist in your project root. If you're talking about bundling code from different projects, what would be the use case for that? It seems a bit more dangerous to do that, or at least less optimized?  
Theoretically (I haven't tried this), you could make bundles like this:
```
      {
        "name": "app-bundle.js",
        "source": {
          "include": [
            "[**/*.js]",
            "**/*.{css,html}"
          ]
        }
      },
      {
        "name": "secondary-bundle.js",
        "source": {
          "include": [
            "[../second-source/**/*.js]",
          ]
        }
      },
```
