### ISSUE TITLE
Aurelia runs locally but fails when I upload to the server

### ISSUE THREAD

**Issue by paulolvac** [aurelia/cli#324]
#I have an installation of Aurelia in my local machine that runs fine. When I upload to the server, I get errors like this

`Unhandled rejection ReferenceError: configureHtmlResourcePlugin is not defined
    at Object.configure (http://lvacdevicetrkserver.lvac.com/paulo/deviceTrkWebA/scripts/vendor-bundle.js:25228:9)
    at http://lvacdevicetrkserver.lvac.com/paulo/deviceTrkWebA/scripts/vendor-bundle.js:11141:36`

I also notice that the vendor-bundle.js on the server is much longer, and this line does not even show up on my localhost. What can be done to make sure it runs the same way on the server?

**Comment by EisenbergEffect** [comment]
Please ask questions in the gitter.

**Comment by paulolvac** [comment]
Sorry. Just posted there.
