### ISSUE TITLE
Bundling firebase and exporting it does not work

### ISSUE THREAD

**Issue by rclaes1995** [aurelia/cli#325]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.0

* **NPM Version:**
3.8.2

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
firebase is undefined

**Expected/desired behavior:**

* **What is the expected behavior?**

firebase should be globally available through the exports name

-- 

When using an aurelia-cli project to import firebase (obtained through `npm install firebase --save`, I'm adding the following code to my vendors bundle in aurelia.json

    
          {
            "name": "firebase",
            "path": "../node_modules/firebase",
            "main":"firebase",
            "exports": "firebase"
          }

firebase however, is not globally available.

**Comment by EisenbergEffect** [comment]
The purpose of bundling it that way is to make it available non-globally, through the module system. If you want it to function as a normal global script, add it to the prepend section.
