### ISSUE TITLE
Warning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by AndreiBelokopytov** [aurelia/cli#329]
**I'm submitting a bug report**

* **Library Version:**
0.19.0

* **Operating System:**
Windows 10

* **Node Version:**
6.4.0

* **NPM Version:**
3.10.3

**Current behavior:**
I am trying to setup new aurelia project with aurelia cli tool. I select default TypeScript configuration:

 Name: au-contact-manager
    Platform: Web
    Transpiler: TypeScript
    CSS Processor: None
    Unit Test Runner: Karma
    Editor: Visual Studio Code

After that i choose option "Install project dependencies". Seems that all works fine, but i always see repeated message in command output (i use git bash for Windows):

> Warning: Possible EventEmitter memory leak detected

![2016-09-22_10-19-23](https://cloud.githubusercontent.com/assets/5220147/18740424/46fe0c20-80b2-11e6-87c2-b7fda2210fe5.png)

I also tried to setup my project without this option and install dependencies later with npm install command. In this case there are no warnings in console.

* **What is the expected behavior?**
Do not display warning about potential memory leak in command output.

* **What is the motivation / use case for changing the behavior?**
Developers may be confused with this behaviour

**Comment by AStoker** [comment]
We noticed this a bit ago. It comes from npm itself I believe, and can be resolved by updating npm to the latest `npm install npm -g`. That should put you at version 3.10.8

**Comment by AndreiBelokopytov** [comment]
@AStoker thanks for response. I followed you advice and updated npm to version 3.10.8, but unfortunately it did not solve problem for me.

**Comment by AStoker** [comment]
`npm -v` comes out with 3.10.8? Strange... Try also upgrade node to the latest, v6.6.0.

**Comment by AndreiBelokopytov** [comment]
Warnings still apear with node 6.6.0 and npm 3.10.8

**Comment by AStoker** [comment]
And this is with a base cli project?

**Comment by AndreiBelokopytov** [comment]
If you mean that configs may be changed by me, than no. This is a cli project created from scratch.

**Comment by EisenbergEffect** [comment]
@AStoker The CLI itself has npm referenced so it might be that we need to update the cli dependencies version.

**Comment by EisenbergEffect** [comment]
I've updated the cli dep version.
