### ISSUE TITLE
[Feature] CLI Test Coverage

### ISSUE THREAD

**Issue by AStoker** [aurelia/cli#330]
**I'm submitting a feature request**
- **Library Version:**
  0.19.0

**Please tell us about your environment:**
- **Operating System:**
  All
- **Node Version:**
  6.6.0
  
  
- **NPM Version:**
  3.10.3
  
  
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**
No test coverage of Aurelia CLI behaviors and functions

**Expected/desired behavior:**

- **What is the expected behavior?**
  Test coverage should exist for the CLI to protect from regression issues and ensure good code quality
- **What is the motivation / use case for changing the behavior?**
  Adding new features to the CLI can cause regression issues, among other things. To protect against regression issues, and to ensure that the CLI is behaving as expected, tests should exist.

**Comment by AStoker** [comment]
Thoughts from: https://github.com/aurelia/cli/pull/326

>My initial thoughts for some basic tests would be to have a few difference "scenarios" represented by various aurelia.json files. From that, we might be able to at least do some basic test cases to make sure that functions will execute correctly given various scenarios, and are returning the expected data.  
https://github.com/aurelia/cli/pull/326#issuecomment-248945529

>That makes sense. Ultimately you end up building a little mini-framework for testing, based on scenario definitions. The trick is the assertions I suppose. Lets just keep brainstorming about this. In the mean time, I'll get this merged in. Thanks for working on it!
https://github.com/aurelia/cli/pull/326#issuecomment-248947941

**Comment by MeirionHughes** [comment]
this should be priority, unfortunately I couldn't mock `fs` properly and a few things broke (namely the tracing lib that is embedded in this repo).

**Comment by EisenbergEffect** [comment]
We could refactor that to enable instancing a file system implementation if that would help. Let me know.

**Comment by MeirionHughes** [comment]
if all the libs and utils could be made to use an instance of the FileSystem class, rather than use `require("fs")`, that probably would do it. could then put in a mock file system during testing.

**Comment by s-hoff** [comment]
I just managed to get a test running on the `file-system.js` using [mock-fs](https://github.com/tschaub/mock-fs) and [jasmine-node](https://github.com/mhevery/jasmine-node). I tried all the functions on `file-system` and `fs` that are being called on the code according to a search all 'fs' with vscode. The only limitation I hit was that the (deprecated) [exists()](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) function did not work at all. These functions are use a total of 6 times in the code, all in the cli's own files. If we replace these with [fs.stat()](https://nodejs.org/api/fs.html#fs_fs_stat_path_callback) and [fs.access()](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback), it should work with mock-fs.

**Comment by EisenbergEffect** [comment]
I'd take a PR for that if you are interested.

**Comment by s-hoff** [comment]
I'm definitely interested and working on it now.

**Comment by MeirionHughes** [comment]
I assume this can be closed now
