### ISSUE TITLE
[Feature Request] the property "rev" can support value "dev" and "prod"

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#333]
the reversion feature is very useful, but in general not use "rev" in developing, use "rev" in production, so holp the feature can be able to adapt the different environment, thanks !!!!

**Comment by EisenbergEffect** [comment]
@AStoker We should definitely support this. I think it should already work the same way as minify, etc. work which allow you to specify environments. Can you check on that?

**Comment by AStoker** [comment]
I'm on it

**Comment by AStoker** [comment]
To clarify @EisenbergEffect, the desired implementation/result would be as follows.
Setting `rev` to true would result in it _always_ using build revisions.  
Setting `rev` to be `"dev"` would make build revisions only happen with the `dev` flag, and so forth with the other options.  
Sound about right? @XuJinNet, that match what you're expecting?

**Comment by AStoker** [comment]
Works exactly as expected with that. I'll make a PR to the docs to document how to set up the flags for different environments.

**Comment by XuJinNet** [comment]
@AStoker yes, awesome, thank you !!!!
but we have other problems:
1. it not clear the bundles of the previous build when building.
2. it not change the every bundle file`s references in index.html
aurelia.json
```javascritp
        "options": {
            "minify": "stage & prod",
            "sourcemaps": "dev & stage",
            "rev": "stage & prod"
        },
        "bundles": [
            {
                "name": "app-bundle.js",
                "source": [
                    "[**/*.js]",
                    "**/*.{css,html}"
                ]
            },
            {
                "name": "actorjs-bundle.js",
                "prepend": [
                    "node_modules/actor-js/actor.js"
                ]
            },
            {
                "name": "vendor-bundle.js",
                "prepend": [
                    "node_modules/bluebird/js/browser/bluebird.core.js",
                    "scripts/require.js"
                ],
                "dependencies": [
                // ...
                ]
            }
        ]
```
i have three bundles, reference two bundles within index.html, but only changed one bundle file`s reference(vendor-bundle) after build, not change all.
index.html
```html
<body aurelia-app="main">
    <script src="scripts/actorjs-bundle.js"></script>
    <script src="scripts/vendor-bundle-1fe58c37e0.js" data-main="aurelia-bootstrapper"></script>
</body>
```

**Comment by EisenbergEffect** [comment]
Closing this since the feature is implemented. If there are other features or bugs, please create new issues for those.

**Comment by AStoker** [comment]
@XuJinNet, yes, we only update the vendor bundle reference (the one that contains the RequireJS config). I haven't come across a use case where I've needed to import anything other than the vendor bundle in the index file. Can you explain why you are doing what you are?
