### ISSUE TITLE
app-bundle.js fails to build when project path contains hidden folder

### ISSUE THREAD

**Issue by leiavoia** [aurelia/cli#335]
**I'm submitting a bug report**
- **Library Version:**
  0.20.0

**Please tell us about your environment:**
- **Operating System:**
  Linux (Kubuntu 14.04 LTS)
- **Node Version:**
  6.6.0
- **NPM Version:**
  3.10.8
- **Browser:**
  all 
- **Language:**
  all

**Current behavior:**
When building a new project with the CLI, /scripts/app-bundle.js fails to build when any hidden directory ("dot folder") is in the path of the project folder. Running `au build` will finish running all steps but will produce an app-bundle.js file that has zero bytes. Building fails if the project is located anywhere inside of a hidden folder, regardless of depth.

Example project path that works:
/home/yourname/visible/project

Example project path that fails:
/home/yourname/.hidden/project

**Expected/desired behavior:**
- **What is the expected behavior?**
  Expected an app-bundle.js of non-zero bytes ;-)
- **What is the motivation / use case for changing the behavior?**
  My main working project directory is actually a link to a hidden directory.

**Steps to reproduce:**

```
cd ~
mkdir .hidden
cd .hidden
au new x
cd x
au build
ls -l scripts/
```

**Comment by guidorice** [comment]
Dot hidden directories are intended to hide the directory from filesystem utilities by default. I would not expect a build process to work on hidden folders.

**Comment by leiavoia** [comment]
I would not expect utilities to work _directly_ with hidden folders either. However, in this case it fails if there is a hidden folder at any point in the path. This would even include something totally sane like `/home/username/.hidden/www/projects/whatever/my-project` where neither the project folder, its contents, or its containing folder are hidden. It's a perfectly valid path and should function as such.

It's also worth noting that other node-based tools are working fine for me in this setup. It's only the Aurelia CLI that has this hiccup.

**Comment by EisenbergEffect** [comment]
This isn't a common use case in the community. That doesn't mean we can't do it but it's going to take a lower priority than other issues. If you want it handled sooner than later, the best path is going to be to submit a PR to fix it.

**Comment by leiavoia** [comment]
If anyone has a hint of where to start looking, I'm willing to poke at it a bit. I am unfamiliar with the CLI internals.

**Comment by fjfeijoo** [comment]
I have had issues with this too. In my case I was trying to build an Aurelia project using Jenkins on Mac. By default Jenkins creates the workspace folder inside a hidden folder like $HOME/.jenkins/jobs

The main problem is that there are no warnings or errors at all when you build the project. The app-bundle.js is empty, that's all.

**Comment by fjfeijoo** [comment]
See PR https://github.com/aurelia/cli/pull/666
