### ISSUE TITLE
Improve the out of the box-Browsersync setup to support pushstate debugging

### ISSUE THREAD

**Issue by MikaelPorttila** [aurelia/cli#337]
**I'm submitting a feature request**
- **Library Version:**
  0.20.0 

**Current behavior:**
The current au run and the built-in browsersync setup, router pushState (config.options.pushState = true;) doesn't support navigation straight to a child-view. Instead browsersync tries to GET static file on the given URL and it will return 404.

**Expected/desired behavior:**
For a SPA-solution with pushstate activated, the desired behavior would be to redirect the first page-request to the default index-file.
- **What is the expected behavior?**
  That Aurelia-cli supports pushstate-debugging by modifying the Browsersync config.
- **What is the motivation / use case for changing the behavior?**
  Improve the debugging of applications with pushstate activated.

**Comment by EisenbergEffect** [comment]
Is there some reason you can't modify the run task yourself to support this scenario? We've had other people do it? Is it that you just need guidance/documentation on how to do this?

**Comment by MikaelPorttila** [comment]
Hi!

Sure I could modify the browsersync-config (and has already done so for some edge-scenarios) but I believe pushstate is more common for projects and I think it would be neat to have the support for pushstate-debugging out of the box so every project wouln't need to their own hack.

As you mentioned this doesn't need to be a change in the code - extended documentation in the configuration-topic would be just fine.

**Comment by tmmunro** [comment]
Yep, battling to get this working nicely, a working example would be much appreciated, e.g, is a custom middleware in the browserSync the way to go? Sample would very helpful, thanks.

**Comment by reft** [comment]
What is the status on this? 
Can you provide documentation for how to modify the task if this is not to be patched?
I have implementat a .net core backend fix for PushState but I'm unable to make it work with browsersync while develoing, as MikaelPorttila describes it.

**Comment by reft** [comment]
@MikaelPorttila @EisenbergEffect @tmmunro Do you have any examples of a modified run task that I can take a look at or does it actually exist documentation for this? Would really appreciate some help..

I'm using latest cli with ts.

Thanks :)

**Comment by Alexander-Taran** [comment]
I believe, that this is what you are looking for
config sample  
https://gist.github.com/kcmr/eba67564af1a72baa19c
for middleware  
https://github.com/bripkens/connect-history-api-fallback

**Comment by Alexander-Taran** [comment]
@JeroenVinke  & @EisenbergEffect 
 we can add commented out lines to task
would it hurt?

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can we put this in for the next CLI release?

**Comment by Alexander-Taran** [comment]
@JeroenVinke ping (-:

**Comment by Alexander-Taran** [comment]
@3cp how are we on the front of pushstate with server?

**Comment by 3cp** [comment]
It's been working for few years. browser-sync is also removed from latest skeleton.
