### ISSUE TITLE
[Feature Request] when using "rev", only changed one bundle file`s reference(vendor-bundle) within index.html after build, not change all

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#338]
i have three bundles, reference two bundles within index.html, but only changed one bundle file`s reference(vendor-bundle) after build, not change all.
aurelia.json

``` javascritp
        "options": {
            "minify": "stage & prod",
            "sourcemaps": "dev & stage",
            "rev": "stage & prod"
        },
        "bundles": [
            {
                "name": "app-bundle.js",
                "source": [
                    "[**/*.js]",
                    "**/*.{css,html}"
                ]
            },
            {
                "name": "actorjs-bundle.js",
                "prepend": [
                    "node_modules/actor-js/actor.js"
                ]
            },
            {
                "name": "vendor-bundle.js",
                "prepend": [
                    "node_modules/bluebird/js/browser/bluebird.core.js",
                    "scripts/require.js"
                ],
                "dependencies": [
                // ...
                ]
            }
        ]
```

index.html

``` html
<body aurelia-app="main">
    <script src="scripts/actorjs-bundle.js"></script>
    <script src="scripts/vendor-bundle-1fe58c37e0.js" data-main="aurelia-bootstrapper"></script>
</body>
```

Operating System: OSX 10.11.6
Node Version: 6.3.1
NPM Version: 3.10.3
CLI Version: 0.20.0

**Comment by EisenbergEffect** [comment]
Why are you referencing multiple bundles from within the index.html? The module loader should handle auto-loading the other bundles as needed.

**Comment by AStoker** [comment]
@XuJinNet, it looks like you're trying to prepend a node module (actor-js). If this is correct, then simply add it to the prepend section of the vendor bundle like this:
```
 "options": {
            "minify": "stage & prod",
            "sourcemaps": "dev & stage",
            "rev": "stage & prod"
        },
        "bundles": [
            {
                "name": "app-bundle.js",
                "source": [
                    "[**/*.js]",
                    "**/*.{css,html}"
                ]
            },    
            {
                "name": "vendor-bundle.js",
                "prepend": [
                    "node_modules/actor-js/actor.js",
                    "node_modules/bluebird/js/browser/bluebird.core.js",
                    "scripts/require.js"
                ],
                "dependencies": [
                // ...
                ]
            }
        ]
```
The `prepend` section of your options will prepend anything you put in there at the top of the bundle. And they'll be prepended in order. So if you needed `actor-js` before bluebird or requirejs, just place it first in the list. Otherwise, if it's just another module that needs to be loaded, place it in the `dependencies` section normally.

**Comment by XuJinNet** [comment]
@EisenbergEffect @AStoker Thanks for you are reply!
There are two reasons:
1. the `actor-js` loading through the module loader is not supported, otherwise it will not work;
2. the `actor-js` file size is very big (1M+), so i want it to be separate from the `vendor-bundle.js`.

**Comment by AStoker** [comment]
@XuJinNet have you tried configuring it as described in the [CLI Docs](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/6), in particular the section titled "A Very Stubborn Legacy Library"? That should take care of the situation you're talking about. 
And in regards to size, you're going to have to download that file anyway, what does separating it out help?

**Comment by XuJinNet** [comment]
@AStoker yes, i using the way of "A Very Stubborn Legacy Library" for `actor-js` , but don`t want bundle it within vendor-bundle.js (vendor-bundle.js is already contain enough libraries).
if bundle it in vendor-bundle.js, when the user's network environment is not very good, it may lead to download failure (e.g. timeout), so i want bundle it to a separate file.

Thanks for you are reply!

**Comment by AStoker** [comment]
@XuJinNet, in that case, simply make a separate bundle that contains "non startup essential libraries". That way you'll have your application code in a bundle, your vendor bundle that contains the startup specific needed code, and your non startup essential code bundle. That will help with your slow startup times on a bad network.

**Comment by XuJinNet** [comment]
@AStoker Thanks for you are reply!
But in my case, the library `actor-js` loading through the module loader is not supported,  it will not work:
`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

**Comment by AStoker** [comment]
If that's the error you're getting @XuJinNet, after some quick searching I found this SO [post](http://stackoverflow.com/questions/24297829/execute-write-on-doc-it-isnt-possible-to-write-into-a-document-from-an-asynchr). That leads me to believe that somewhere in `actor-js` you're trying to use `document.write`. The answer to the question explains why that can't work. So in your case, it sounds like you **must** load `actor-js` before the application loads, which means you need to include it in the `<head>` of your page.

**Comment by XuJinNet** [comment]
@AStoker Thanks for you are reply!
Yes, you are right. The library `actor-js` is thirdparty, i can`t modify it, so i hope the feature `rev` can support this case.

**Comment by AStoker** [comment]
@XuJinNet, I'm not entirely sure that's a case that can/should be solved by the CLI (I could be wrong). Your particular library needs to be loaded up before the document is loaded up. With that being the case, it's being loaded up before any Aurelia files are even loaded, so the developer must insert it.

**Comment by XuJinNet** [comment]
@AStoker Thanks for you are reply!
If `CLI` can support this case, it would be unified way of development, improve development experience (through the `NPM` manage dependencies, through the `CLI` bundle it), developers only need to add the "bundles of Legacy Library" to the `index.html`.

**Comment by AStoker** [comment]
Perhaps in the future there could be some way via configuration in the `aurelia.json` file to load dependencies before the application starts (before app start would be before the document is completely loaded, aka load files in the `<head>`). If you think that is a solid case, you could make a feature request for that and give a detailed explanation of the reasons why it would be helpful.

**Comment by XuJinNet** [comment]
@AStoker Thank you very much !
