### ISSUE TITLE
[Bug] when using "rev", it not clear the bundles of the previous build when building

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#339]
the reversion feature is very useful, but have a problem, it not clear the bundles of the previous build when every building.

Operating System: OSX 10.11.6
Node Version: 6.3.1
NPM Version: 3.10.3
CLI Version: 0.20.0

**Comment by EisenbergEffect** [comment]
This is meant to be used as part of a CI build process where the bundles would be cleared out as part of the deploy process. It's not meant to be used in development mode.

**Comment by AStoker** [comment]
@XuJinNet, if you're adamant about using revisions for development (not a good idea as Eisenberg said), make your clean task with gulp remove any files that match the regex for a revision build.

**Comment by XuJinNet** [comment]
@EisenbergEffect @AStoker You are right, thanks.

**Comment by XuJinNet** [comment]
@EisenbergEffect @AStoker  Understood, thanks for you are reply!

**Comment by JeroenVinke** [comment]
@AStoker can we close this one?
