### ISSUE TITLE
rev and run --watch: regenerating the vendor-bundle on app-bundle change

### ISSUE THREAD

**Issue by tdamir** [aurelia/cli#340]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.7

* **Browser:**
all

* **Language:**
TypeScript 2.0

**Current behavior:**
While in watch mode (au run --watch) and revision enabled, if app file changes the vendor-bundle is not re-generated (ie: the reference for app-bundle-xxxxx is same like before the change). 

**Expected/desired behavior:**

The vendor-bundle should be also regenerated and should reference the newly created app-bundle.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
Please do not use ref for development mode. It is designed for deploy. If we were to regenerate both bundles on any change that would probably cause a serious performance issue and hinder your development.

**Comment by tdamir** [comment]
I understand the decision to not use the rev in development mode. I would like to notice that I'm using the modified version of revisioning described in [this](https://github.com/aurelia/cli/issues/205#issuecomment-229705109) issue. I'm generating the vendor-bundle on every change and didn't noticed any performance issues. The project is 'au new' generated with two bundles (app-bundle and vendor-bundle) and is relatively small. Of course there could be issues with big projects and custom configurations.

**Comment by AStoker** [comment]
@tdamir, check out this comment: https://github.com/aurelia/cli/issues/339#issuecomment-249592371

**Comment by tdamir** [comment]
@AStoker all good. My modified rev task is already removing the old files.
