### ISSUE TITLE
"rev": true breaks bundling with au run --watch

### ISSUE THREAD

**Issue by guidorice** [aurelia/cli#344]
**I'm submitting a bug report**

* **Library Version:**
$ au --version
0.20.0

**Please tell us about your environment:**
* **Operating System:**
freebsd 9.3

* **Node Version:**
v6.2.2

* **NPM Version:**
3.9.2
 
* **Browser:**
chrome

* **Language:**
ESNext

**Current behavior:**

in my aurelia.json revision hash naming is enable like so:
```
 "options": {
      "minify": "stage & prod",
      "sourcemaps": "dev & stage",
      "rev": true
    },
```
When using the revision hash setting, and developing with `au run --watch` the loading process gets broken.

**Expected/desired behavior:**

When using with revision hash and `au run --watch` the loading process should not be broken.

Here is an example repro
```
$ au run --watch
...
Writing app-bundle-646361e219.js...
Writing vendor-bundle-7291916a92.js...
Finished 'writeBundles'
Application Available At: http://localhost:9000
BrowserSync Available At: http://localhost:3001
Starting 'watch'...
# ... time passes ...
# edit a file 
File Changed: src/resources/elements/msa.js
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
Finished 'configureEnvironment'
Starting 'buildJavaScript'...
Finished 'processCSS'
Finished 'processMarkup'
Finished 'buildJavaScript'
Starting 'writeBundles'...
Tracing resources/elements/msa...
Writing app-bundle-e176624cf0.js...
Finished 'writeBundles'
Starting 'reload'...
Finished 'reload'
```
Now the app-bundle has been updated, but the original vendor-bundle has not been updated. Reloading my index.html the browser, the browser loads the 
vendor-bundle-7291916a92.js which loads OLD app-bundle-646361e219.js, not the NEW *app-bundle-e176624cf0.js...*

Note I am not using http://localhost:9000. Rather, I am loading the index.html via a web app framework template on the server side. (not sure if this matters for the bug, I suspect not)

As a side note, perhaps there should be some feature for cleanup of old hash revisions files, because as is demonstrated here, aurelia-cli is perfectly happy to load defunct revisions of the code. Not sure if this helps, but in webpack land, this can be accomplished by:

```
var WebpackCleanupPlugin = require('webpack-cleanup-plugin');
#...
module.exports = {
#...
plugins: [
    new WebpackCleanupPlugin()
  ]
}
```

**Comment by AStoker** [comment]
Yes, right now unless you have a process to change your references live during tests, using revisions will break this. However, **you shouldn't be using revisions for testing**, as it's more for production than development.  
Change your `rev` option to be `"stage & prod"` so that when you run tests normally, you're not dealing with revision numbers.

**Comment by guidorice** [comment]
Thanks Andrew, that works well. Closing - cheers
