### ISSUE TITLE
Build fails when adding an NPM scoped package dependency

### ISSUE THREAD

**Issue by nexbit** [aurelia/cli#345]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.8

* **Browser:**
all

* **Language:**
all

**Current behavior:**
If you add a private package published to the `npmjs` registry, the CLI fails to locate the root directory of the package.
When you install a private package from the `npmjs` registry, you do it with a command like:
```
npm install --save @nexbit/yourpackagename
```
The package is then installed under the dir `node_modules/@nexbit`. Every private package is scoped under a directory named after your username.
Then you add the dependency in `aurelia.json`:
```
{
      "name": "yourpackagename",
      "path": "../node_modules/@nexbit/yourpackagename/dist/amd",
      "main": "yourpackagename"
}
```
If you try to `au build`:
```
{ uid: 1,
  name: 'readProjectConfiguration',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open 'node_modules/@nexbit/package.json'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/@nexbit/package.json' },
  duration: [ 0, 10762335 ],
  time: 1475061605517 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open 'node_modules/@nexbit/package.json'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: 'node_modules/@nexbit/package.json' },
  duration: [ 0, 21608811 ],
  time: 1475061605527 }
{ Error: ENOENT: no such file or directory, open 'node_modules/@nexbit/package.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/@nexbit/package.json' }
```

The error is in `package-analyzer.js`, in the `getPackageFolder` function:
```
...
    if (stopOnNext) {
      break;
    } else if (part === 'node_modules') {
      stopOnNext = true;
    }
...
```
should be changed in:
```
...
    if (stopOnNext && !part.startsWith('@')) {
      break;
    } else if (part === 'node_modules') {
      stopOnNext = true;
    }
...
```
and everything works as expected.

**Expected/desired behavior:**

* **What is the expected behavior?**
The private dependency is bundled successfully.

* **What is the motivation / use case for changing the behavior?**
You should be able to use private packages as well as public ones.

**Comment by AStoker** [comment]
Curious, is that behavior (the `@` symbol for private repos) standard? Are there any other cases like this that we should address too?

**Comment by nexbit** [comment]
@AStoker Well, that's the way npmjs.com private packages work. See https://docs.npmjs.com/private-modules/intro

Unfortunately I can't speak for other hosted solutions, so I don't know how many other edge cases like this are to be considered...
In addition, there some other issues with the package name. Now that I patched the CLI like above, the build succeed, but tsc gives me errors on import statements. It seems it cannot find the d.ts file that the `typings` directive points to. Even vscode complains on that imports.

**Comment by nexbit** [comment]
Just looked at Sinopia docs: https://www.npmjs.com/package/sinopia#using-private-packages

They do not use any hard namespacing, they only suggest to use a prefix for you private packages' name (like `nexbit-yourpackagename`).
So it seems this is unique to npmjs.com, but that's the major player out there, so... ;)

**Comment by EisenbergEffect** [comment]
@nexbit Would you be willing to submit a PR with the above fix. We could probably get it in and out within 24 hours.

**Comment by nexbit** [comment]
@EisenbergEffect I need to investigate the typescript typings issue, just to be sure that the above fix will suffice.. Then I'll open a PR for this.

**Comment by EisenbergEffect** [comment]
Sounds good. Thanks!

**Comment by EisenbergEffect** [comment]
@nexbit I hope you don't mind..I assigned the issue to you. If you are unable to submit a PR with a fix then if you can just report back here to us your findings, we can move the issue along. Thanks!

**Comment by EisenbergEffect** [comment]
@jdanyow This is a test. Ignore this.

**Comment by nexbit** [comment]
@EisenbergEffect No prob! As soon as I have a free time slot, I'll report back here what I found on typings issue, and then I'll submit a proper PR...

**Comment by nexbit** [comment]
The bug is more subtle, I fear..
What I found so far:

The correct way to import a private module dependency (at least in Typescript) is:
```
import { SomeClass } from '@nexbit/some-module';
```
This is the only way to have `moduleResolution: "node"` to work. Otherwise TSC complains about a missing definition.
This is really awkward, because if you plan to publish that package in the public registry someday, you'll have to change all your imports!

With that import in place, the `au build` command fails, unless you declare your dependency in `aurelia.json` in this way:
```
{
      "name": "@nexbit/some-module",
      "path": "../node_modules/@nexbit/some-module/dist/amd",
      "main": "some-module"
}
```
The build succeed, but the generated bundles are broken... The browser complains at that import with the following error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/src/some-module.js 
```
I suspect that during the bundle the dependency is found, but it is included with an incorrect path, and thus RequireJS fails to load it when the first import is encountered.

I need some help on this from someone that has deep knowledge of the CLI codebase. I looked into the generated bundles, and the `define` calls seem ok to me, but obviously they aren't ...

**Comment by nexbit** [comment]
**ADDENDUM**

It could be an incorrect tracing by amodo-trace, I suspect the import style is causing it to fail.
But at least the dependency is bundled (**incorrectly**, the bug we are tracing in https://github.com/aurelia/cli/issues/342 still applies).
I strongly believe that a first static analysis pass on the `dependencies` is needed to avoid all of these amodo-trace nuances... See my other comment [here](https://github.com/aurelia/cli/issues/342#issuecomment-250496098)

**Comment by nexbit** [comment]
Spoke too soon... ;)
It was my fault, when loading the plugin in my `main` file, I need to reference it with the `@nexbit` prefix, and that makes perfectly sense.
So, for future readers' reference, you need to load your private plugin with:
```
aurelia.use.standardConfiguration().plugin('@nexbit/module-name');
```

All of this nuances should be documented in the hub, I think in a `Using npmjs.com private packages` paragraph under this topic: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/6

**Comment by jdanyow** [comment]
These are called [scoped packages](https://docs.npmjs.com/misc/scope). The package name is `@scopeName/name` and are installed in the `node_modules` folder using the following directory structure:
```shell
node_modules
  - @scopeName
    - name
```

**Comment by nexbit** [comment]
Well good to know they are somewhat standard.
They remain awkward though... I understand it's a safe way to namespace private packages from public ones, but they lead to ugly imports! ;)

Anyway, apart from the fix, the docs need to mention them IMHO

**Comment by EisenbergEffect** [comment]
Is there a PR we need to merge? Also, @nexbit, would you be interested in PRing the docs?

**Comment by nexbit** [comment]
> Is there a PR we need to merge?

Yes, you found it attached to this issue, it's number #348 . Merging that will auto close this. It touches only one file with the aforementioned fix, no version bump etc.

> Also, @nexbit, would you be interested in PRing the docs?

Sure, but never looked at your doc hub, maybe point me at the right repo to clone.

**Comment by EisenbergEffect** [comment]
Wow. Not sure how I missed the PR ref. Sorry about that!
