### ISSUE TITLE
[Bug] when using `rev` on Windows, `src` of <script> uses backslashes as directory delimiters

### ISSUE THREAD

**Issue by Flatta** [aurelia/cli#346]
**Library Version:** 0.20.0
**Operating System:** Windows 10, probably on other Windows
**Node Version:** 6.7.0 
**NPM Version:** 3.10.5

**Current behavior:**
index.html shows as follows: 
`<script src="scripts\vendor-bundle-f2b6a92e9b.js" ...></script>`

**Expected/desired behavior:**
it should be like this: 
`<script src="scripts/vendor-bundle-f2b6a92e9b.js" ...></script>`

**Comment by Flatta** [comment]
I am sorry, I opened the issue by mistake

**Comment by Flatta** [comment]
I corrected the issue so reopened it.

**Comment by AStoker** [comment]
Most likely related to this: https://github.com/aurelia/cli/issues/332

**Comment by Flatta** [comment]
I overlooked that issue.
No doubt this issue is duplicate by that one.

I'm sorry and thank you for telling me.
