### ISSUE TITLE
imports a named export but doesn't use a relative path

### ISSUE THREAD

**Issue by MMJM** [aurelia/cli#347]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.2

* **NPM Version:**
3.10.3

* **Language:**
 TypeScript 2.0

**Current behavior:**
Cannot bundle Auth0-Lock

au build reports this error:
no such file or directory ..... /src/events.js

The line in auth0-lock that is referencing this file is
import { EventEmitter } from 'events';

**Expected/desired behavior:**
To be able to bundle Auth0. @PWKad suggested posting the problem here.
Thoughts on how the CLI should reference a third-party module that imports a named export but doesn't use a relative path? 
import { EventEmitter } from 'events';

* **What is the expected behavior?**
Adding a combination of settings in aurelia.json will create a bundle.

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
I'm not 100% convinced this is a cli issue. It could be an issue of library configuration or usage. Can you show me what you added to the aurelia.json file?

**Comment by AStoker** [comment]
@MMJM, pretty sure you're missing a configuration to include `events` in your project. Since it's not defined in your bundle, when you try to import it, it tries to find a file in the source directory called `events`, instead of the aliased location that would have been created if it were defined.

**Comment by PWKad** [comment]
@astoker do the docs on cli configuration show aliasing?

**Comment by AStoker** [comment]
I used the word "aliased", but whether or not that's the actual word I should have used or not, I don't know. What I meant was that a dependency was needed for a module defined with the name `events`. If another module requires that module (and it didn't have it defined in the deps section), that's the error we're seeing. So a module must be _defined_ to be `events`, and `events` is really a short name for the long path name for the location of the file. Nothing real special there, and that is the standard configuration that's in the docs, @PWKad.

**Comment by MMJM** [comment]
@EisenbergEffect @AStoker @PWKad 
Turns out that `events` is part of Node Core. It seems that Browserify when it encounters this it uses a set of replacement browser-specific shims. I used one of their replacements and this seems to bundle now. Is there any plan to do the same as Browserify and include a set of browser-specific shims for bundling with the CLI?

See the `Compatibility` sections mentioned in this link
https://github.com/substack/node-browserify#usage

**Comment by EisenbergEffect** [comment]
Yes, we would like to do that. Any interest in helping out with that? Perhaps a start a looking into what would be involved to just do that automatically.

**Comment by MMJM** [comment]
@EisenbergEffect I'd love to help out with Aurelia. I'm quite limited on time but I can have a look when I get a chance.

**Comment by EisenbergEffect** [comment]
Everyone is welcome to contribute in any way they desire :)
