### ISSUE TITLE
Unable to import node module with ".js" in name

### ISSUE THREAD

**Issue by powerbuoy** [aurelia/cli#349]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.7.0

* **NPM Version:**
3.10.3

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When I `npm install --save-dev jump.js` and later add it ("jump.js" literaly - its main property points to its only JS file) to aurelia.json `build.bundles[].dependencies` I get **Error: ENOENT: no such file or directory, open '/home/powerbuoy/.../src/main/resources/static/jump.js'**

If I do the same with say "moment" everything works fine.

**Expected/desired behavior:**

That I don't get an error.

**Comment by EisenbergEffect** [comment]
Try using a different name in your js and in the aurelia.json mapping. Here's an example for chart.js which has a similar problem:

```json
         {
            "name": "chartjs",
            "path": "../node_modules/chart.js/Chart.min",
            "exports": "Chart"
          }
```

**Comment by powerbuoy** [comment]
@EisenbergEffect Is this a limitation in Aurelia CLI or should one avoid naming packages with a "." regardless?

If it's an issue with Aurelia CLI only, is there any plan to fix it?

**Comment by JeroenVinke** [comment]
@powerbuoy could you provide more info so I can reproduce the issue with the chartjs plugin?

**Comment by powerbuoy** [comment]
@JeroenVinke All I did was create a new Aurelia CLI project, `npm install chart.js` then add `chart.js` to my dependencies in `aurelia_project/aurelia.json`. The project won't build because the name contains a period.

Thanks to https://github.com/chartjs/chartjs-plugin-deferred/issues/2 I did notice though that as long as I supply a path I can still name the package with a period which makes it all work.

Would still be nice if we didn't have to supply the path manually.

**Comment by zewa666** [comment]
@powerbuoy I dont really think that is feasible as the path is made exactly for this kind of scenarios. @JeroenVinke we could though try to through a better error message, so the users get better instructions how to switch to using the path property.

**Comment by powerbuoy** [comment]
Ok I see, well as long as I can keep the period in the name everything works at least.
