### ISSUE TITLE
Add a "None of the above" option for the Editor step

### ISSUE THREAD

**Issue by emilniklas** [aurelia/cli#350]
**I'm submitting a feature request**
- **Library Version:**
  0.2.1

**Please tell us about your environment:**
- **Operating System:**
  macOS 10.12
- **Node Version:**
  6.6.0
  
  
- **NPM Version:**
  3.10.7
  
  
- **Language:**
  all

**Current behavior:**
At step 6 of the `au new` wizard, you get these options:
1. VS Code
2. Atom
3. Sublime
4. WebStorm

I use Vim. But I don't particularly need a Vim option here. In fact, I don't really know what this option does, other than to add specific folders or files like `.vscode/`.

However, it bugs me that I cannot just opt out of choosing at this point.

**Expected/desired behavior:**
1. VS Code
2. Atom
3. Sublime
4. WebStorm
5. None of the above

**Comment by EisenbergEffect** [comment]
That sounds reasonable :) Would you be interested in creating a PR to add it?

**Comment by emilniklas** [comment]
Sure, I'll give it a shot!

**Comment by emilniklas** [comment]
#351

**Comment by mttmccb** [comment]
This can probably be closed as it has been merged.
