### ISSUE TITLE
Tracing fails for indexes

### ISSUE THREAD

**Issue by sensedeep** [aurelia/cli#352]
**I'm submitting a bug report**
- **Library Version:**
  0.20.1
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  v5.11.0
- **NPM Version:**
  3.8.6
- **Browser:**
  N/A
- **Language:**
  Babel ES6

**Current behavior:**

When using an import with a relative path, _au build_ works fine. But if the import uses a definition in aurelia.json:loader.config.paths, then the build works, but tracing fails.

The use case is a directory with an index which re-exports services. E.g.

```
export { Account } from './account.js'
export { Alert } from './alert.js'
export { Audit } from './audit.js'
export { Channel } from './channel.js'
```
## Simplified Test Case:

main.js:

```
import {B} from 'paks/a/index'
```

paks/a/index.js

```
export {B} from './b'
```

paks/a/b.js

```
export class B {}
```

In this scenario **au build** completes successfully both building and tracing.

However, when importing a module ID that is defined via loader.config.paths, the tracing fails to resolve. Change main.js to:

   import {B} from 'a'

Add a definition to aurelia.json to resolve 'a'

```
"loader": {
      "config": {
        "paths": {
            "a": "paks/a/index"
        }
      }
```

Then the tracing step fails on "main". It seems the config.paths are not being considered and tracing is trying to find "b.js" in the top level directory instead of under "paks/a".

```
{ uid: 7,
  name: 'writeBundles',
  branch: false,
  error:
   { [Error: ENOENT: no such file or directory, open '/Users/mob/dev/ab.1/src/b.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/mob/dev/ab.1/src/b.js',
     moduleTree: [ 'a' ],
     fileName: '/Users/mob/dev/ab.1/src/paks/a/index.js' },
  duration: [ 0, 18755216 ],
  time: 1475530351775 }
```

**Expected/desired behavior:**

Expect that config.paths should be uses when creating the module ID path for the import.
- **What is the motivation / use case for changing the behavior?**

Have a large code base being refactored to use the CLI.

**Comment by sensedeep** [comment]
A bit more info and a question:

Should this work?

````
import {Admin, User} from './models'
````

Where models/index.js exports these symbols?
````
export {Admin} from './admin'
export {User} from './user'
````

This fails similarly without any loader.config.paths definition. It looks for models in the top directory. However, this work:

````
import {Admin, User} from 'models/index'

FYI: this all worked either way with jspm/systemjs.

````
{ uid: 7,
  name: 'writeBundles',
  branch: false,
  error:
   { [Error: ENOENT: no such file or directory, open '/Users/mob/dev/ab.1/src/models.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/mob/dev/ab.1/src/models.js',
     moduleTree: [ 'main' ],
     fileName: '/Users/mob/dev/ab.1/src/main.js' },
  duration: [ 0, 21767091 ],
  time: 1475535281616 }
````

**Comment by EisenbergEffect** [comment]
I don't believe that should have worked with jspm. That doesn't seem to be standard behavior for the browser loader. It makes sense for npm, but not the browser.

**Comment by sensedeep** [comment]
We've been using this syntax in our app with JSPM for months. Works well, but has other unrelated JSPM issues.

The import syntax and re-export is ES6 standard and it should translate into standard amd / cjs primitives.

Why do you say it isn't standard?  A module can import and re-export symbols, and destructuring syntax is part of the standard on the import.

**Comment by EisenbergEffect** [comment]
The syntax is standard but only npm has the behavior of translating a folder into a call to the index.js file inside that folder.

**Comment by sensedeep** [comment]
Okay, but that is where the loader.config paths comes in.  In JSPM we create map entries like this:

````
    "js-id": "paks/js-id/index",
    "js-json": "paks/js-json/index",
````

and then wanted to do the same in loader.config.paths. It works for the transpile phase, but then trips in the tracing. 

Thanks for clarifying. We can work around by adding "/index" to all our imports. 

BTW, some feedback on the CLI so far:

- Slow on the first build compared to JSPM
- Much faster in dev mode when watching
- Compiled bundles look smaller
- Would love to expose some of the inner steps in the CLI as gulp-able tasks. That way it could be integrated into an existing build system.  Currently we are shell invoking "au build" which is an all or nothing approach

Keep up the good work. I think the CLI direction is the way to go.
