### ISSUE TITLE
Some dependencies are being excluded from package.json

### ISSUE THREAD

**Issue by DamnedScholar** [aurelia/cli#355]
I set up an app using the CLI. Everything worked fabulously. I mucked about and broke things, as I am wont to do, and my app would no longer build. I got things shaped up, deleted my `node_modules/` folder and went to use `npm install` to re-download the dependencies at the recommended versions (because part of the mucking about included reckless upgrades). When I tried to build the app, it turned out that `aurelia-binding`, `aurelia-dependency-injection`, `aurelia-event-aggregator`, `aurelia-framework`, `aurelia-history`, `aurelia-history-browser`, `aurelia-loader`, `aurelia-loader-default`, `aurelia-logging`, `aurelia-logging-console`, `aurelia-metadata`, `aurelia-pal`, `aurelia-pal-browser`, `aurelia-path`, `aurelia-polyfills`, `aurelia-route-recognizer`, `aurelia-router`, `aurelia-task-queue`, `aurelia-templating`, `aurelia-templating-binding`, `aurelia-templating-resources`, `aurelia-templating-router`, `jquery`, and `source-map` had not been added to my project's dependencies. Now that I have replaced them all, `au run` executes perfectly.

It seems to me that the CLI should certainly create a `package.json` that refers to *all* of the important components.

**Comment by EisenbergEffect** [comment]
Make sure that you are using NPM 3 or above. That is a requirement. It sounds like you have an older version of npm on your system.
