### ISSUE TITLE
Highlighting bundle errors

### ISSUE THREAD

**Issue by CasiOo** [aurelia/cli#356]
**I'm submitting a feature request**
- **Library Version:**
  0.20.1

**Please tell us about your environment:**
Windows 10
- **Node Version:**
  6.3.0
- **NPM Version:**
  3.8.6

**Current behavior:**
Bundle errors (transpile task) are very difficult to notice when they are written to the console.
The errors are written with the same color and size as successful tasks.
Spot the error (took me 40 min of debugging the bundle section not noticing the console error):
![image](https://cloud.githubusercontent.com/assets/5333676/19129178/9c073e0a-8b46-11e6-8a7c-5269469fc437.png)

**Expected/desired behavior:**
Highlight the error like was it a transpile error.
![image](https://cloud.githubusercontent.com/assets/5333676/19129206/b3d63806-8b46-11e6-9e0c-cf7c59462a2b.png)

**Comment by CasiOo** [comment]
Also the error isn't very descriptive. `error c:\privat\tower-defence\not-existing-path\not-existing.js`
If it isn't able to find the file, then maybe it should tell so.
```
{
  "name": "not-existing",
  "path": "../not-existing-path/not-existing"
}
```

**Comment by EisenbergEffect** [comment]
Sounds reasonable.

**Comment by Alexander-Taran** [comment]
@3cp aren't we there yet?

**Comment by 3cp** [comment]
<img width="521" alt="Screen Shot 2022-05-26 at 8 37 09 am" src="https://user-images.githubusercontent.com/1188806/170380970-9d448e64-ccdc-41d1-8348-fb0def7e5528.png">

It does highlight.
