### ISSUE TITLE
'au build' is complaining about missing html file when installed via cli for .net core

### ISSUE THREAD

**Issue by 4imble** [aurelia/cli#357]
**I'm submitting a bug report**

* **Library Version:**
0.20.1

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
4.4.4

* **NPM Version:**
3.10.5

* **Language:**
TypeScript

**Current behavior:**

'au build' is erroring for new .net core site.

**Expected/desired behavior:**

- Create a new Asp.net Core website. (C:/Projects/AureliaTest)
- Open cmd line, nav to root folder where the wwwroot exists (C:/Projects/AureliaTest/src/AureliaTest)
- **Run 'au new --here' <---- important**
- Choose 2 (ASP.NET Core)
- Choose 2 (Typescript)
- Choose 2 (Less)
- Choose 2 (No unit testing)
- Choose 1 (Yes, create project)
- Choose 1 (Yes, Install Dependencies)
=Wait to finish=
- Type 'au build'
It will error stating 'Error: No index file found at "index.html"'

* **What is the expected behavior?**
It should not complain about a missing index file.
This does not happen when creating project via the 'au new [name]' command

**Comment by 4imble** [comment]
Changing the aurelia.json file build section from:
```
 "build": {
    "targets": [
      {
        "id": "aspnetcore",
        "displayName": "ASP.NET Core",
        "output": "wwwroot\\scripts",
        "index": "index.html", <---
        "baseUrl": "scripts"
      }
    ],
```
to this:
```
 "build": {
    "targets": [
      {
        "id": "aspnetcore",
        "displayName": "ASP.NET Core",
        "output": "wwwroot\\scripts",
        "index": "wwwroot\\index.html", <----
        "baseUrl": "scripts"
      }
    ],
```
Fixes this error it seems.

**Comment by EisenbergEffect** [comment]
We have this tracked as a bug and will work to get it fixes. Thanks!

**Comment by JamesFenton** [comment]
Hi, I can't seem to find an open issue regarding this, and this bug is still happening as of v0.22.0

**Comment by WillTartak** [comment]
Today the fix from @4imble was still required for a new project created with cli v0.22.0 as @JamesFenton stated.

**Comment by cornillemichiel** [comment]
How would one configure this  when there is no index at all? use case: I replaced index.html with a razor view.

**Comment by JeroenVinke** [comment]
Yep, thats the way!
