### ISSUE TITLE
[Feature] Custom Loader Config Generators

### ISSUE THREAD

**Issue by AStoker** [aurelia/cli#360]
**I'm submitting a feature request**
It would be nice to have the ability to create our own loader config generator so that custom configs for the application (whether it's RequireJS, SystemJS, or any other module loader) can be created. This would allow a user to generate their own config for their own setup without having to rely on the CLI to provide one itself.  

Additionally, having the ability to create you own loader config comes with the benefits of creating custom configs that are needed for testing frameworks like Karma and Wallaby.  

What we could do is provide the basic configuration setups (currently just RequireJS, and hopefully soon SystemJS and Webpack), but allow the user to define their own in the `aurelia.json` file. I'm thinking that we could make use of the `build.loader.type` option to do this. The CLI could look at the type and if it matches one of the prebuilt ones (require, system, webpack) then it would simply use the one it had. But if it didn't match a prebuilt generator, then we could read it as a path to load the custom generator.  

For example. A default configuration looks like this for the loader:

``` javascript
"loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": true
        }
      ]
    },
```

Using that setup, we would simply use the prebuilt requirejs config generator. But the user could also do something like this:  

```
"loader": {
      "type": "configGenerators/awesome-loader",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": true
        }
      ]
    },
```

This setup would not match any prebuilt generator, and instead would now look to the file path listed to load up the generator and create the module loader configuration.  

Thoughts, ideas?  
The immediate use we would have for this would be to create custom configurations for Karma and Wallaby test runners.

**Comment by EisenbergEffect** [comment]
Yes please :)

**Comment by AStoker** [comment]
@EisenbergEffect, let me know what you think. Initially I was thinking about making use of the `loader.type` option to use a custom loader config generator. However, I didn't realize the depth that the loader type is used. It's also used in the loader-plugin for defining modules and how they're compiled. Would we want a two part thing going on here? We could keep using the loader.type for the module loader, but provide an optional option for defining how the config gets generated? 
At that point, it's really only good for situations where you want to repeatedly create a custom config while keeping with your current module loader... What are your thoughts?

**Comment by EisenbergEffect** [comment]
Ultimately, we need to come up with a model for loaders so that we can extract all uses throughout the codebase, including the loader-plugin piece. That code should ultimately also defer to the configured loader implementation.

**Comment by Alexander-Taran** [comment]
@AStoker thoughts?

**Comment by 3cp** [comment]
I think it's already implemented.
