### ISSUE TITLE
[Feature Request] Support some way via configuration in the aurelia.json file to load dependencies before the application starts (before app start would be before the document is completely loaded, aka load files in the <head> or load before vendor-bundle.js)

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#366]
The origin of this issue: #338 

i have three bundles, reference two bundles within index.html, but only changed one bundle file`s reference(vendor-bundle) after build, not change all.
aurelia.json
```javascritp
        "options": {
            "minify": "stage & prod",
            "sourcemaps": "dev & stage",
            "rev": "stage & prod"
        },
        "bundles": [
            {
                "name": "app-bundle.js",
                "source": [
                    "[**/*.js]",
                    "**/*.{css,html}"
                ]
            },
            {
                "name": "actorjs-bundle.js",
                "prepend": [
                    "node_modules/actor-js/actor.js"
                ]
            },
            {
                "name": "vendor-bundle.js",
                "prepend": [
                    "node_modules/bluebird/js/browser/bluebird.core.js",
                    "scripts/require.js"
                ],
                "dependencies": [
                // ...
                ]
            }
        ]
```
index.html
```html
<body aurelia-app="main">
    <script src="scripts/actorjs-bundle.js"></script>
    <script src="scripts/vendor-bundle-1fe58c37e0.js" data-main="aurelia-bootstrapper"></script>
</body>
```

There are two reasons:
1. the dependency `actor-js` loading through the module loader is not supported, otherwise it will not work:
｀Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.｀

2. the actor-js file size is very big (1M+), so i want it to be separate from the vendor-bundle.js:
vendor-bundle.js is already contain enough libraries, if bundle it in vendor-bundle.js, when the user's network environment is not very good, it may lead to download failure (e.g. timeout), so i want bundle it to a separate file.

If `CLI` can support this case, it would be unified way of development, improve development experience (using the `NPM` manage dependencies, using the `CLI` bundle it), developers only need to add the "bundles of Legacy Library" to the `index.html`.

Operating System: OSX 10.11.6
Node Version: 6.3.1
NPM Version: 3.10.3
CLI Version: 0.20.0

**Comment by EisenbergEffect** [comment]
This seems like an extreme edge case and I would recommend you solve this by writing some simple JS code to load that library itself and then afterwards load Aurelia.
