### ISSUE TITLE
Plugin with many components does not bundle correctly

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#368]
**I'm submitting a bug report**

* **Library Version:**
0.20.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.7

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When using the `resources` property for a dependency that has many files, not all files are traced and added to the bundle. 

I have made an aurelia-cli project that demonstrates this: https://github.com/JeroenVinke/aurelia-cli-dependency-inclusion. There is a folder `large-plugin` that contains 20 box components (view/view-model pairs). This `large-plugin` is referenced as dependency from `aurelia.json`:

```
{
    "name": "large-plugin",
    "path": "../large-plugin/dist/amd",
    "main": "index",
    "resources": [
        "**/**.js",
        "**/**.html"
    ]
},
```

Running this app results in:

![image](https://cloud.githubusercontent.com/assets/2189477/19211664/1ff16da6-8d42-11e6-9308-a41cb6dedb8f.png)

Note that not all 20 boxes were traced.

In the browser the following error is shown:
![image](https://cloud.githubusercontent.com/assets/2189477/19211682/7a4f3f58-8d42-11e6-8c52-850a47bb6b77.png)

If I change the amount of boxes to two it works fine. This can be done by changing the resources property in aurelia.json to:
```
          {
            "name": "large-plugin",
            "path": "../large-plugin/dist/amd",
            "main": "index",
            "resources": [
              "**/box1.js",
              "**/box1.html",
              "**/box2.js",
              "**/box2.html"
            ]
          },
```

And by changing main.js to: `.plugin('large-plugin', (builder) => builder.boxes(2));`

Both files are traced:
![image](https://cloud.githubusercontent.com/assets/2189477/19211711/187e72f2-8d43-11e6-8c1e-74ee5c7deba8.png)

And the app works fine:
![image](https://cloud.githubusercontent.com/assets/2189477/19211710/0fce2332-8d43-11e6-97e4-57e95f37dc6c.png)

**Expected/desired behavior:**

Aurelia-cli should wait until all dependency files are processed

* **What is the motivation / use case for changing the behavior?**

So that the user can use the `resources` property for large plugins such as aurelia-kendoui-bridge and aurelia-materialize-bridge

**Comment by JeroenVinke** [comment]
I think that the cause may be [here](https://github.com/aurelia/cli/blob/a07181e10a4a0318be7b06419cc532a793b186b7/lib/build/bundle.js#L35-L40).

[addDependency](https://github.com/aurelia/cli/blob/a07181e10a4a0318be7b06419cc532a793b186b7/lib/build/bundle.js#L47-L50) does not return a promise. This function creates a `[DependencyInclusion](https://github.com/aurelia/cli/blob/master/lib/build/dependency-inclusion.js)` instance. In the constructor of [DependencyInclusion](https://github.com/aurelia/cli/blob/master/lib/build/dependency-inclusion.js#L21) it calls [addAllMatchingResources](https://github.com/aurelia/cli/blob/master/lib/build/source-inclusion.js#L49-L70) which apparently does not get enough time to process many plugins (like the plugin referenced in the issue report)

**Comment by EisenbergEffect** [comment]
@JeroenVinke Thanks for looking into this. Would you be able to submit a PR to fix that?
