### ISSUE TITLE
au test --watch should just build & write bundles with changes

### ISSUE THREAD

**Issue by cResults** [aurelia/cli#370]
**I'm submitting a feature enhancement request**

**Library Version: 0.19.0**
Please tell us about your environment:

**Operating System:**
All

**Node Version:**
6.6.0

**NPM Version:**
3.10.3

**Browser:**
all

**Language:**
all

**Current behavior:**
in the default set up generated by aurelia cli, au test --watch configures karma to watch test files and source bundles.  Saving a test file causes tests to run very quickly against the bundles.  Changes to source files will not trigger tests to run.  au build must be called which rebuilds all bundles including vendor bundle (which takes > 60 second on a relatively small app) and then run au test or au test --watch in order to get updated test run.  This is a totally impractical work flow.

**Expected/desired behavior:**
In my ideal world, au test --watch would set up file watchers for each au configured bundle. Upon saving files, just the bundles that have changes would be built and published to the dist folder (compiled output folder). karma would then respond the updated source bundle and re-run tests.
- **What is the motivation / use case for changing the behavior?**
  This change coupled with the improved tracing performance that the aurelia cli team is working on will give this Instant Feedback Junky quite a TDD fix.

**Comment by s-hoff** [comment]
Until this is built in, there is a workaround you CAN use: Have `au run --watch` going in the background. That way, the run task will watch the `src` files and create the bundles, causing the tests to run. Its should by no means be necessary but also gives near instant feedback.

**Comment by AStoker** [comment]
Also, in case you were wondering, you can configure the testing to work with TDD. I made a repo to demonstrate this here: https://github.com/AStoker/Aurelia-TDD
