### ISSUE TITLE
Include requirejs and requirejs/text via NPM.

### ISSUE THREAD

**Issue by shaunluttin** [aurelia/cli#371]
Right now these are included in the `scripts` directory instead of letting NPM install them. 

In the aurelia.json, please move from this:

```
"prepend": [                                                   
  "scripts/require.js"                                         
],                                                             
"dependencies": [                                              
{                                                            
  "name": "text",                                            
  "path": "../scripts/text"                                  
},                                                           
```

to this: 

```
"prepend": [                                                   
  "node_modules/requirejs/require.js"                          
],                                                             
"dependencies": [                                              
  "text",                                                      
```

And add this to the package.json dependencies

```
"requirejs": "^2.3.2",
"text": "github:requirejs/text"
```

**Comment by EisenbergEffect** [comment]
Sounds reasonable :) Is it not possible to get require.js from npm?

**Comment by shaunluttin** [comment]
Yes. It is possible to get requirejs from NPM. It is also possible to get `requirejs/text` from there too. The problem is that the `aurelia-cli` scaffolding does not do that, so we have to manually make the above changes.

**Comment by Gheoan** [comment]
Note that the `text` plugin is not in the npm registry, but can be obtained from github via npm.

**Comment by AStoker** [comment]
Many of the people I've talked to have already replaced the included require and text loaders with the ones from npm. It seems simple enough to do and probably worth doing. Just have to modify the default aurelia.json file to load up those files, and include them in the default package.json

**Comment by shaunluttin** [comment]
@AStoker That's what I do too. For one, it's a pain. For two, it's an inconsistent message to people learning Aureila; i.e. why are some libraries pulled from NPM but others installed into `scripts`?

**Comment by EisenbergEffect** [comment]
I think we should fix this. It shouldn't be hard.

**Comment by AStoker** [comment]
@EisenbergEffect, how does this look: https://github.com/aurelia/cli/pull/391
