### ISSUE TITLE
Export interpreted build options

### ISSUE THREAD

**Issue by CasiOo** [aurelia/cli#372]
**I'm submitting a feature request**
- **Library Version:**
  0.20.0

**Current behavior:**
Implementing certain custom build tasks sometimes require you have access to the interpreted build options, such as minify and sourcemaps.

Currently the build options are locally interpreted in the bundler https://github.com/aurelia/cli/blob/master/lib/build/bundler.js#L23

**Expected/desired behavior:**
Export the interpreted build options for use in custom build tasks.
- **What is the motivation / use case for changing the behavior?**
  Ideally I can use the interpreted build options like so:

```
import {build} from 'aurelia-cli';

function buildSass() {
    let sassOptions = {};

    if (build.buildOptions.minify) {
        sassOptions.outputStyle = 'compress';
    }

    return gulp.src('./sass/**/*.scss')
               .pipe(sass(sassOptions);
}
```

Either the options should be on `CLIOptions` or the `build` export.

With this enhancement, we can easily modify the current CSS build tasks to minify the source. Should be an easy PR for sass at least as shown above.

**Comment by EisenbergEffect** [comment]
It is important to note that these options are per bundle usually...

**Comment by stsje** [comment]
@EisenbergEffect Is that feature coming in a later release? I haven't seen anyone use per bundle build options, is that even an option right now? Currently the build options are added to the `build` object, at the same level as the bundles.
```
"build": {
  "options": {
    "minify": "stage & prod"
  },
  "bundles": []
}
```

**Comment by EisenbergEffect** [comment]
I believe it is implemented. I'll check into it.

**Comment by Alexander-Taran** [comment]
It works on bundle level.
Should we mention it in the docs?

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can you comment? Is there a good place to put this in the CLI docs?

**Comment by Alexander-Taran** [comment]
http://aurelia.io/docs/build-systems/aurelia-cli#javascript-minification
In my opinion

**Comment by Alexander-Taran** [comment]
@3cp I believe in my words from 4 years ago.. although I can't remember how to use them options.. per bundle..
Can you confirm?
I'll draft a PR to docs after

**Comment by 3cp** [comment]
This is essentially same as #652. See the comments there.
