### ISSUE TITLE
JS_Parse_Error from aurelia-cli when Typescript targets ES6

### ISSUE THREAD

**Issue by jutxle** [aurelia/cli#373]
**I'm submitting a bug report**
- **Library Version:**
  0.20.2

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  6.2.1
- **NPM Version:**
  3.9.3
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.3

**Current behavior:**
tsconfig.json target = "es2015"
aurelia-cli builds properly but fails to minify when the --env prod/stage flag is applied

Stacktrace : 

> { uid: 8,  
>   name: 'writeBundles',  
>   branch: false,  
>   error:  
>    JS_Parse_Error {  
>      message: 'SyntaxError: Unexpected token: name (AccessNotificationRemote)',  
>      filename: 0,  
>      line: 3,  
>      col: 10,  
>      pos: 108,  
>      stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\Projects\project-name\apps\
> \app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2092:9)\n    at token_e
> rror (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2100:9)\n    at unexpected (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\t
> ools\node.js:28:1), <anonymous>:2106:9)\n    at semicolon (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2126:56)\n    at simple_statement (eval at <anonymous> (C:\
> Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2317:73)\n    at eval (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:218
> 6:19)\n    at eval (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2139:24)\n    at block_ (eval at <anonymous> (C:\Projects\project-name\apps\app-name\node_modules\u
> glify-js\tools\node.js:28:1), <anonymous>:2432:20)' },  
>   duration: [ 4, 158831512 ],  
>   time: 1476208823281 }

**Comment by AStoker** [comment]
Are you able to identify the file that the build is failing on?

**Comment by jutxle** [comment]
It appears to error in my App.ts at line 3, the first import statement that loads a module within my src.

Line 1-3 are as follows
```
declare var x;
import { inject } from 'aurelia-framework';
import { y } from './y';
```

**Comment by AStoker** [comment]
@jutxle, what are the contents of file `y.js`?
Could be that you're not exporting the named module `y`?

**Comment by jutxle** [comment]
Y.js is being exported.  You can reproduce this bug with a bare aurelia-cli Typescript project, with the Typescript target set to es6

**Comment by AStoker** [comment]
I don't use typescript, but I'm just trying to help where I can.
Did you mean that `y` is being exported (as a named export) from `y.js`? Because that's what your code is assuming.

**Comment by Ullfis** [comment]
I believe it's because UglifyJS does not support es6 yet. See progress [here](https://github.com/mishoo/UglifyJS2/issues/448).

Use typescript and target es5 in cli projects. To get the latest typescript goodies like async/await, use latest releases (like `npm i typescript@2.1.0-dev.20161014 –save-dev`).

Example project [here](https://github.com/Ullfis/au-cli-skel)

**Comment by jutxle** [comment]
Thanks Ullfis, that does appear to be the issue and your resolution is a suitable workaround as  Typescript 2.1 supports async/await in es5

**Comment by JeroenVinke** [comment]
@jutxle can we close this one?

**Comment by gheoan** [comment]
This is not fixed, however it could be solved with https://github.com/aurelia/cli/issues/490.
