### ISSUE TITLE
Creating a separate bundle and requiring css before importing js fails

### ISSUE THREAD

**Issue by Thanood** [aurelia/cli#379]
**I'm submitting a bug report**
- **Library Version:**
  0.21.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 8
- **Node Version:**
  6.2.2
  
  
- **NPM Version:**
  3.20.5
  
  
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**

I'm trying to bundle a 3rd party library which contains css and js - `material-design-lite` to be precise.
I tried to `<require from="material.css">` before any JS is imported.

If I do that, I'm getting the following error:

```
vendor-bundle.js:4102 GET http://localhost:9000/scripts/mdl-bundle.css 404 (Not Found)
```

When I `import 'material-design-lite'` before that, everything is okay.
I will add my `aurelia.json` configuration as an answer to this issue for readability.

**Expected/desired behavior:**

> If the current behavior is a bug, please provide the steps to reproduce.

I will add this information in my first answer to this issue.
- **What is the expected behavior?**

Being able to `require` a css file from a bundle before anything else.
- **What is the motivation / use case for changing the behavior?**

Personally, I don't have a problem with importing js first, but I think this could become a problem in lazy loading scenarios when you use "common chunks" in separate bundles.

**Comment by Thanood** [comment]
## Steps to reproduce:

`npm install --save material-design-lite`

aurelia.json bundle config:

```json
      {
        "name": "mdl-bundle.js",
        "dependencies": [
          {
            "name": "material-design-lite",
            "path": "../node_modules/material-design-lite/dist",
            "main": "material",
            "exports": "componentHandler",
            "resources": [
              "material.css",
              "material.teal-orange.min.css"
            ]
          }
        ]
      },
```

app.html:

```html
<require from="material-design-lite/material.css"></require>
```

## Making it work

main.js:

```javascript
import 'material-design-lite';
``´

Importing JS before the `require` loads the bundle and css will be loaded.

**Comment by AStoker** [comment]
@Thanood, when we bundle CSS, you can see it defined in the vendor bundle. This seems strange that it would happen. Can you look in your vendor bundle for the module definition that corresponds to your material css file?

**Comment by Thanood** [comment]
I see..

```json
"mdl-bundle":["material-design-lite","material-design-lite/material","material-design-lite/material.teal-orange.min"]
```

So this is maybe because the name of the css file without the extension is the same as the JS file (`material-design-lite/material`).

It works with the `material.teal-orange.min.css` now (different name).
Although I'm pretty sure that it didn't when I first looked at this. Anyway, I cannot reproduce that.

**Comment by AStoker** [comment]
That's from the require config I suppose? Not quite what I was looking for.
If you look at the `vendor-bundle.js`, that's where all your vendor code exists, both modules and regular prepended (non amd) code. CSS is supposed to be converted into a module, so you should see a module defined as `material-design-light/material.css` (based off your config). Especially because you say that importing that works when you import the base js, I'm thinking that there's definitely a module defined as that in there. If not, then the problem is not what I think it is, and requires some more digging :P

**Comment by AStoker** [comment]
My bad, don't look in your vendor bundle, you have it defined in your material bundle.

**Comment by Thanood** [comment]
Alright, thanks! :+1: 
I thought you meant the reference to `mdl-bundle` in `vendor-bundle`. :smiley: 

Btw.: When you actually put this into `vendor-bundle` it works, since `vendor-bundle` is required anyway.

**Comment by Alexander-Taran** [comment]
@3cp does this affect dumber & friends?

**Comment by 3cp** [comment]
There is no such issue in dumber bundler.
Also this issue doesn't exist on latest aurelia-cli bundler which is totally different from the one in v0.21.0.

The bundler setup for latest aurelia-cli:
```
{
  "name": "mdl-bundle.js",
  "dependencies": [
    "material-design-lite"
  ]
},
```

If you only want to require css without automatically bundle js main file:
```
{
  "name": "mdl-bundle.js",
  "dependencies": [
    {
      "name": "material-design-lite",
      "lazyMain": true
    }
  ]
},
```
As long as you didn't explicitly import js file, the bundle will only contain that css file.

**Comment by 3cp** [comment]
FYI, in latest cli bundler, the explicit "path", "main" are optional, the bundler will try to find from the common place if it's not set. The "resources" is totally obsolete, the bundler traces files without that "resources" hint.
