### ISSUE TITLE
Aureliafile.js is not extensible

### ISSUE THREAD

**Issue by PWKad** [aurelia/cli#38]
Currently by relying on a JavaScript file as the configuration for the CLI it prevents the ability to 'extend' the functionality of the CLI or make it able to work when upgrading versions.  If the CLI is not upgraded it will throw errors for methods not being implemented.

I think the Aureliafile.js should be converted into a file that is of JSON format so that it is more extensible.

**Comment by zewa666** [comment]
Hmm makes sense. But besides that how about offering a `sanitze` task to fix the Config-file, whatever it's called?

**Comment by joelcoxokc** [comment]
I say we do both!

**Comment by joelcoxokc** [comment]
I actually like the idea of sticking with a JSON file. I will handle this, and make a PR.

**Comment by Aaike** [comment]
i like the sanitize idea also, json is nice and solid , but a js file allows me to comment out lines and make the configuration more dynamic if needed.

**Comment by joelcoxokc** [comment]
Hmm, Good observation. I am going to take a dive into JSPM and see how they are using the config.js. I think it is possible to keep a js file. The only concern I have is speed. It shouldn't affect us for more than a couple milliseconds... However, Let me take a look anyway!

**Comment by joelcoxokc** [comment]
OK I found a solution to using a JS file. I am going to create a PR with a module that contains the functionality to save, read , and write to this config file.
