### ISSUE TITLE
au run --watch detects but does not render HTML changes when rev is true.

### ISSUE THREAD

**Issue by shaunluttin** [aurelia/cli#380]
**I'm submitting a bug report**

* **Library Version:**
0.20.2

**Please tell us about your environment:**
* **Operating System:** Windows 10
* **Node Version:** v6.3.0
* **NPM Version:** 3.10.3
* **Browser:** all
* **Language:** TypeScript

**Current behavior:**
0. Set `build.options.rev = true`
1. `au run --watch`
2. Open any browser at localhost:9000
3. Change the HTML of the current template. 
4. The watcher detects the change and reloads the page albeit without the change. 

**Expected/desired behavior:**
0. Set `build.options.rev = true`
1. `au run --watch`
2. Open any browser at localhost:9000
3. Change the HTML of the current template. 
4. The watcher detects the change and reloads with the change. 

**What is the motivation / use case for changing the behavior?**
Ease development by having the watcher not only detect but also render changes.

**Comment by shaunluttin** [comment]
Related: http://stackoverflow.com/questions/40114963/the-watcher-detects-the-change-and-reloads-the-page-without-including-the-change/40115194

**Comment by AStoker** [comment]
Revisions are used for production and should not be used in a testing environment (aka when using `--watch`).

**Comment by shaunluttin** [comment]
It sounds like the use case for `rev` does not include my expected behavior. Is that right?

**Comment by EisenbergEffect** [comment]
That is correct.
