### ISSUE TITLE
Using postcss with imports does not pick up changes correctly on au run --watch

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/cli#381]
**I'm submitting a bug report**
- **Library Version:** 0.21.0

**Please tell us about your environment:**
- **Operating System:** Windows 10
- **Node Version:** 4.4.7
- **NPM Version:** 3.10.5
- **Browser:** all 
- **Language:** TypeScript 2.0.3

**Current behavior:**
When I use PostCSS with [postcss-import](https://github.com/postcss/postcss-import) and two files:
a.css and _b.css, where in a.css I **@import variables** from _b.css.
When I run `au run --watch` and change _b.css, the CLI picks up the changes, runs the build and refreshes the site.
But the changes are not applyed in the styles.

I managed to solve the problem by changing aurelia_project/tasks/process_css.ts:

``` typescript
//...

return gulp.src([
        project.cssProcessor.source,
        // do not bundle files that are imported 
        "!src/**/_*.css"
    ])
        // do not only use changed files or files that import other files will not be picked up 
        // .pipe(changedInPlace({ firstPass: true }))
        .pipe(sourcemaps.init())
        .pipe(postcss(processors))
        .pipe(build.bundle());
```

**Expected/desired behavior:**
The CLI should pick up changes when I change imported files.

Do you think that my workaround is the way to go or can this be solved in another way?

**Comment by EisenbergEffect** [comment]
That seems reasonable to me for now. We might be able to come up with something better in the future.

**Comment by thomas-darling** [comment]
We ran into the same problem - there's a couple of gulp plugins that try to solve it, but in our testing, they all failed.

I tried to see if we could help fix them, but eventually gave up on them, and built one that actually works myself:

https://www.npmjs.com/package/gulp-dependents

We've been using it on a large code base for about a year now, and it's been working great :-)

**Comment by Alexander-Taran** [comment]
The only solution that worked for me is to rebuild all on any change
there is a gulp-sass-watch plugin or something.. that adds files that import the one changed to streams..
but it is not compatible with logging and all.

**Comment by 3cp** [comment]
Latest skeleton does push through all sass/less files on watch, for fixing the same issue.
