### ISSUE TITLE
Bluebird config not allowed when promises already in use

### ISSUE THREAD

**Issue by stsje** [aurelia/cli#385]
**I'm submitting a bug report**

* **Library Version:**
0.21.0

* **Browser:**
Firefox, Edge, IE 11

**Current behavior:**
An error is thrown if you enable bluebird's cancellation option: `cannot enable cancellation after promises are in use`. The error doesn't occur in Chrome.

A newly created CLI project has the bluebird configuration in `main.js`.

Example configuration in `main.js` that fails at startup:
```
import environment from './environment';

//Configure Bluebird Promises.
//Note: You may want to use environment-specific configuration.
Promise.config({
  warnings: {
    wForgottenReturn: false
  },
  cancellation: true
});

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('resources');

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  aurelia.start().then(() => aurelia.setRoot());
}
```

**Expected/desired behavior:**
A newly setup project should allow any bluebird configuration options without failing.

The `aurelia-bootstrapper` module seems to be using promises in any other browser than Chrome before `main.js` is loaded. 

One option is to change the bootstrapper, so it doesn't use promises. This will allow us to use the current clean setup, that is easy for people to understand.

Another option, which is our current fix, is to configure bluebird in `index.html`. Our index file is then changed to:
```
<!--<script src="dist\vendor-bundle.js" data-main="aurelia-bootstrapper"></script>-->
<script src="dist\vendor-bundle.js"></script>
<script>
  requirejs.config({
    skipDataMain: true
  });

  // Configure Bluebird Promises.
  Promise.config({
    warnings: {
      wForgottenReturn: false
    },
    cancellation: true
  });

  require(['aurelia-bootstrapper']);
</script>
```
Note that the requirejs config isn't actually needed, but it still might be a good idea to tell it not to look for `data-main`.

**Comment by EisenbergEffect** [comment]
It's not possible to remove promise use from the bootstrapper.

**Comment by stsje** [comment]
Could we then change the default CLI project setup, so it configures bluebird before requiring bootstrapper?

**Comment by EisenbergEffect** [comment]
It's possible. That's more complicated though because it would involve leaking module loader details into the index.html, which is something we would rather not do.

**Comment by EisenbergEffect** [comment]
PRs are welcome if we can find a good solution.

**Comment by stsje** [comment]
I'm not sure if the `data-main` attributes qualifies as a module loader dependency, since it wouldn't hinter other module loaders from working.
An abstraction will be needed in the CLI if `data-main` is seen as a module loader dependency.

How about doing the following, where you don't find any requirejs specific code in index.
```
    <script src="dist\vendor-bundle.js" data-main="aurelia-bootstrapper"></script>
    <script>
      // Configure Bluebird Promises.
      Promise.config({
        warnings: {
          wForgottenReturn: false
        },
        cancellation: true
      });
    </script>
```

I really don't like adding a pre-configuration step before aurelia-bootstrapper. It seems cleaner to have your configuration inside `main.js`. Right now I don't see any other way for bluebird promises.

**Comment by EisenbergEffect** [comment]
Will the code you show above work, without needing to use require.js directly?

**Comment by stsje** [comment]
Yes the above code does work. Will have to investigate futher if there are any race conditions though.
Also you don't have the option to use the environment variables in the configuration which makes it kind of a less ideal solution.

**Comment by EisenbergEffect** [comment]
Good point.

**Comment by AshleyGrant** [comment]
I just had an idea of how to fix this. I'm going to submit a PR for it momentarily
