### ISSUE TITLE
[Feature Request] Add shorthands for importing resources

### ISSUE THREAD

**Issue by CasiOo** [aurelia/cli#388]
**I'm submitting a feature request**
- **Library Version:**
  0.21.0

**Expected/desired behavior:**
It would be nice with a shorthand for importing modules in the resources directory. All module loaders should support defining aliases for module sub paths or whatever they are called.

I would like to have the following config as part of the default CLI setup for a new requirejs project.
The config will make you able to import non-global value-converters like so:

```
// Require import before change
<require from="resources/value-converters/currency-value-converters"></require>
// Require after feature change
<require from="value-converters/currency-value-converters"></require>
```

The above is possible using requirejs's map feature http://requirejs.org/docs/api.html#config-map .
With Systemjs you would define it in the config using paths.

I would like the following requirejs setup. Sorry for not opening a pull request, but I have no idea how to test any CLI changes. If you could add it to the readme it would be great.

```
"loader": {
    "type": "require",
    "configTarget": "vendor-bundle.js",
    "includeBundleMetadataInConfig": "auto",
    "plugins": [
        { "name": "text", "extensions": [".html", ".css"], "stub": true }
    ],
    "config": {
        "map": {
            "*": {
                "elements": "resources/elements",
                "attributes": "resources/attributes",
                "value-converters": "resources/value-converters",
                "binding-behaviors": "binding-behaviors"
            }
        }
    }
}
```

**Comment by AStoker** [comment]
Unfortunately we don't have full tests on the CLI yet, so any changes need to be tested manually (and thoroughly). 
If you could do me a favor and prepend this issue name with something like "[Feature Request]", that would help with sorting. 
Right now, we only support RequireJS as the module loader, but later we want to support SystemJS and Webpack. So any kind of configuration that is created should probably have a syntax that could be used to interpret configuration for the desired module loader.
If you have an idea for a PR, it might be helpful to have that as the starting point for any future fixes/additions for this feature.

**Comment by Alexander-Taran** [comment]
Stale since 2016

**Comment by JeroenVinke** [comment]
I believe you can do this now by using the loaderConfig property ([it's picked up here](https://github.com/aurelia/cli/blob/master/lib/build/loader.js#L51)). Let me know if this is not the case

**Comment by Alexander-Taran** [comment]
shipt it (-:
