### ISSUE TITLE
Unable to "require" a supporting class within a unit test, given the generated code from aurelia-cli.

### ISSUE THREAD

**Issue by ChrisMancini** [aurelia/cli#392]
**I'm submitting a bug report**

* **Library Version:**
0.21.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x/Windows 7

* **Node Version:**
4.4.3/5.4.0

* **NPM Version:**
3.10.9/3.9.1

* **Browser:**
Only targeting Chrome at this time, however I suspect this will fail in other browsers.

* **Language:**
all 

**Current behavior:**

Unable to "require" a supporting class within a unit test, given the generated code from aurelia-cli.

The steps below have been applied to this [repository](https://github.com/ChrisMancini/aurelia-app)

Following these steps I am unable to execute a test within the new aurelia cli framework.

* run `au new`
    - Accept all defaults except choose Typescript (however this fails with ESNext as well)
* Add new folder under `test` called `utils` as a sibling to `unit`
* Create a new file within `utils` called `testHelper.ts`
```
export TestHelper {
  Name : string;
}
```
* Modify `app.spec.ts` to include the new utility class and use it within the test

```
import {App} from '../../src/app';
import {TestHelper} from "../utils/testHelper";

describe('the app', () => {
  it('says hello', () => {

    let h = new TestHelper();

    h.Name = "John";

    expect(h.Name).toBe("John");
    expect(new App().message).toBe('Hello World!');
  });
});
```

* Add the utils folder to the files configuration object of karma within `karma.config.js`

```
let testSrc = [
  { pattern: 'test/utils/**/*.ts', included: false},
  { pattern: project.unitTestRunner.source, included: false },
  'test/aurelia-karma.js'
];
```

* Add the utils folder to the preprocessors configuration object of karma within `karma.config.js`
```
    preprocessors: {
      [project.unitTestRunner.source]: [project.transpiler.id],
      ['test/utils/**/*.ts']: [project.transpiler.id]
    },
```

* run `au build`
* run `au test`

* You will receive the following error:

```
λ au test
Starting 'unit'...
24 10 2016 15:11:42.954:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
24 10 2016 15:11:42.971:INFO [launcher]: Starting browser Chrome
24 10 2016 15:11:43.969:INFO [Chrome 53.0.2785 (Windows 7 0.0.0)]: Connected on socket -rw81aF6Glx1RWjVAAAA with id 8644146
24 10 2016 15:11:44.149:WARN [web-server]: 404: /base/test/utils/helper
Chrome 53.0.2785 (Windows 7 0.0.0) ERROR
  Uncaught Error: Script error for "C:/git/aurelia-app/test/utils/helper", needed by: C:/git/aurelia-app/test/unit/app.spec.js
  http://requirejs.org/docs/errors.html#scripterror
  at C:/git/aurelia-app/scripts/vendor-bundle.js:3763


{ uid: 0,
  name: 'unit',
  branch: false,
  error: 1,
  duration: [ 2, -497867396 ],
  time: 1477336304256 }
1
```

**Comment by AStoker** [comment]
@ChrisMancini, I just tried to reproduce this with ESNext, and didn't get your error. Can you try to create a clean project with ESNext and see if it does the same thing? I wonder if it's something with the babel typescript transpiler not creating the file correctly.

**Comment by ChrisMancini** [comment]
@AStoker I just walked through the same procedure selecting all defaults (ESNext) during 'au new'.

I received the error listed above.;

**Comment by AStoker** [comment]
Interesting. Let me try it again and see if maybe I missed something...

**Comment by ChrisMancini** [comment]
@AStoker Could you create a repo with your attempt?  I could then compare it to mine.

**Comment by AStoker** [comment]
BTW, my `testHelper.js` is as follows (since I'm on ESNext)
```
export default class TestHelper{
    Name = 'test';
}
```

**Comment by AStoker** [comment]
@ChrisMancini, I got your issue to be reproducible (I had some changes in my files that caused it to work). 
The reason this is happening is because the tests are being compiled into AMD, and RequireJS won't automatically add the `.js` extension to files that are requested that have certain criteria ([Load Javascript Files](http://requirejs.org/docs/api.html#jsfiles))
> Ends in ".js".
> Starts with a "/".
> Contains an URL protocol, like "http:" or "https:".  

Now you might think, "Hey, but I'm pulling in the app code just fine!". Well, it turns out that the app module is already defined based off the baseURL, so it know's how to get it's jam on.  
For you, you have to options.  
1. You can add the `.js` extension to the import (`import {TestHelper} from '../utils/testHelper.js';`)
2. You can modify the `aurelia-karma.js` `normalizePath` function to automatically insert the `.js` extension. That can be done by adding the following lines just after the for-loop in `normalizePath` on line 31:
``` javascript
//Use case of testing source code. RequireJS doesn't add .js extension to files asked via sibling selector
//If normalized path doesn't include some type of extension, add the .js to it
    if(normalized.length > 0 && normalized[normalized.length-1].indexOf('.') < 0){
      normalized[normalized.length-1] = normalized[normalized.length-1] + '.js';
    }
```
This will add the `.js` extension to _any_ file that doesn't have an extension in the request. See how I've set this case up over [here](https://github.com/AStoker/Aurelia-TDD/blob/master/test/aurelia-karma.js#L37)

**Comment by ChrisMancini** [comment]
@AStoker yes I was able to proceed with the first option when I first encountered the problem.  I will try the second option.  Thanks!

**Comment by ChrisMancini** [comment]
@AStoker Worked like a charm.  Thank you very, very much!

**Comment by AStoker** [comment]
Glad you got it working! Happy to help
