### ISSUE TITLE
Update typings to @types

### ISSUE THREAD

**Issue by con-ssc** [aurelia/cli#395]
**I'm submitting a feature request**
- **Library Version:**
  0.21.0
- **Operating System:**
  Windows 10
- **Node Version:**
  6.6.0
- **NPM Version:**
  3.10.8
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.3

**Current behavior:**
The "au new" command puts "typings" npm module in place.

**Expected/desired behavior:**
The "au new"command should use "@types" npm module for typings instead if possible
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
  The DefinatelyTyped definition files are now maintained in @types. MS supports this package as well.

**Comment by AStoker** [comment]
Could you do me a favor and format this according to the [Issue Template](https://github.com/aurelia/cli/blob/master/ISSUE_TEMPLATE.md)?

**Comment by con-ssc** [comment]
Here you go.

**Comment by EisenbergEffect** [comment]
This sounds like a nice idea. @con-ssc Any interest in making a PR to do this?

**Comment by con-ssc** [comment]
Puhh I can have a look into it, but I haven't looked at the cli source at all yet.

**Comment by con-ssc** [comment]
Are all of those typings needed?
angular-protractor
jasmine
selenium-webdriver
node

**Comment by con-ssc** [comment]
@EisenbergEffect PR #397

**Comment by milkshakeuk** [comment]
excellent I was going to raise an issue about this myself 😄

**Comment by milkshakeuk** [comment]
@EisenbergEffect with #457 being merged can this be closed?

**Comment by EisenbergEffect** [comment]
@milkshakeuk Yes sir :)
