### ISSUE TITLE
au test and npm test

### ISSUE THREAD

**Issue by hadrienl** [aurelia/cli#396]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Language:**
ESNext

**Current behavior:**

My test failed. When I launch `au test`, I get a `1` exit code. I set `npm test` in my `package.json` to exec `au test`. When I exec `npm test` my test fails, but the exit code is `0`.

**Expected/desired behavior:**
I want `npm test` to return the same exit code that the command it refers to.

I need to modify test.js to
```
new Karma({
      configFile: __dirname + '/../../karma.conf.js',
      singleRun: true
    }, err => {
      if (err) {
        process.exit(err);
      }
    }).start();
```

to have a exit code `1` with `npm test`.

**Comment by AStoker** [comment]
Just curious, if you update to the latest version of Aurelia CLI (0.21.0), do you still experience this issue?

**Comment by hadrienl** [comment]
Oh yeah, it's fixed… sorry…
