### ISSUE TITLE
Support for PWA

### ISSUE THREAD

**Issue by jmvtrinidad** [aurelia/cli#399]
**I'm submitting a feature request**

**Please tell us about your environment:**
- **Operating System:**
  Windows 8.1
- **Node Version:**
  6.2.0
  
  
- **NPM Version:**
  3.8.9
  
  
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**
N/A

- **What is the expected behavior?**
  `au new --mobile`
- **What is the motivation?**
  Allow creating template for Progressive Web App while following the recommended structure.

**Comment by AStoker** [comment]
Could you put a little bit more details about Progressive Web App and what you would expect exactly?

**Comment by jmvtrinidad** [comment]
Upon executing `au new --mobile`, `au-cli` should be able to generate files needed to get started developing [Progressive Web App](https://developers.google.com/web/progressive-web-apps/)(PWA). It also should be based on [Material Design](https://material.google.com) or maybe (just maybe) based on [Bootstrap](getbootstrap.com/). Building, adding page, elements, components, etc. should be the same.

More about [PWA](https://addyosmani.com/blog/getting-started-with-progressive-web-apps/).
Thanks for great work.

**Comment by AStoker** [comment]
It sounds like you're wanting something that builds a setup specifically for Material/Bootstrap. I'm not sure that's the direction that the CLI is going, @EisenbergEffect can confirm that. The CLI sets up a skeleton project that needs just bare bones stuff.  
Adding to the CLI a build setup for a specific library might start opening the doors to making a build setup for other libraries, and before you know it you have 100 different flags for different frameworks that nobody can manage.  
It's probably a better idea for those individual projects to set up their own project according to how they need it.

**Comment by jmvtrinidad** [comment]
For clarification, its not about libraries, its more about the structure that will generate to get started developing Progressive Web App. 
Sorry for confusion.

**Comment by EisenbergEffect** [comment]
Specifically, what about the default setup is a problem for PWA?  I don't see any real issues.

**Comment by jmvtrinidad** [comment]
Sorry, what do you mean by this?

> Specifically, what about the default setup is a problem for PWA?

**Comment by Ganbin** [comment]
With the default setup you can already build a PWA. It is depending the way you create your application and not the setup made by the CLI.

The CLI provide the setup to develop your project. You can go any direction you want. Mobile, SPA, full desktop, PWA, etc...

**Comment by jmvtrinidad** [comment]
Maybe its more suitable in [skeleton-navigation](https://github.com/aurelia/skeleton-navigation/) repository.
Thanks for great support.

**Comment by andreabaldin-LIC** [comment]
Future looks at PWAs.  Providing a PWA template would increase dramatically the Aurelia distribution.  
Personally I'm looking for production ready template: Aurelia + .NETCore + PWA + Webpack3 + TypeScript with Implicit Flow auth (OpenIddict/IdentityServer4) and I don't want to spend months in setting and sorting configuration problems.  
Sorry, no time to spend in infrastructure challenges and several projects waiting for a productive starting point.  Any ideas ?
Thx in advance

**Comment by diegohb** [comment]
yes, let's avoid 100 switches for cli and any implementation specifics!! 👍 supporting all the library package loaders and bundlers is a big task enough for this project...

@andreabaldin-LIC  - this following is somewhat what you're looking for... i needed the same sort of thing to be able to have a decent jump-off point without spending too much time (again) figuring out node and au tooling specifics..

It is Aurelia CLI (aurelia.json) + SystemJS (instead of Webpack) + DotNetCore 1.1 + TypeScript + Bootstrap + JQuery. It is "F5-able" (ready to run) from *both* VSCode and VS2017. It's also setup with an opinionated approach at handling multi-SPAs within single MVC Web App that is structured to allow standard ASPNET MVC pages as well.

https://github.com/diegohb/samples-aurelia-vanilla_cli

**Comment by andreabaldin-LIC** [comment]
I also tested that coming with the .NET SPA templates (https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/) .
It also includes Webpack and Typescript !

However it can be challenging configuring the Webpack PWA starting point, then the authentication…

I wouldn’t like to invest on something not ready for prod and after a while have to move to another framework.

However thanks for your quick response.


Andrea Baldin
Senior Software Developer

[cid:LIC_automation_signature_logo_jpg]
LIC Automation
PO Box 20306 (119 Maui St, Pukete)
Hamilton 3241 NEW ZEALAND

Web: www.lic.co.nz
Our vision at LIC Automation: To improve the prosperity and productivity of our farmers through automation and information
________________________________
This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. LIC reserves the right to monitor all e-mail communications through its networks. Although LIC regularly scans its computer systems for viruses using anti-virus software, LIC is not responsible for the consequences of any viruses, data corruption, interception or unauthorised amendment to this email. The recipient should check this email and any attachments for viruses and defects. This email does not designate an information system for the purposes of section 11(a) of the NZ Electronic Transactions Act 2002.

**Comment by JeroenVinke** [comment]
@andreabaldin-LIC PWA support is now tracked here: https://github.com/aurelia/cli/issues/535. It's something we really like to get in, but there are other things we need to get done first.

**Comment by andreabaldin-LIC** [comment]
Ok, thanks.
In the meantime I’ll have a look at other frameworks waiting for the Aurelia one.
Cheers


Andrea Baldin
Senior Software Developer

[cid:LIC_automation_signature_logo_jpg]
LIC Automation
PO Box 20306 (119 Maui St, Pukete)
Hamilton 3241 NEW ZEALAND

Web: www.lic.co.nz
Our vision at LIC Automation: To improve the prosperity and productivity of our farmers through automation and information
________________________________
This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. LIC reserves the right to monitor all e-mail communications through its networks. Although LIC regularly scans its computer systems for viruses using anti-virus software, LIC is not responsible for the consequences of any viruses, data corruption, interception or unauthorised amendment to this email. The recipient should check this email and any attachments for viruses and defects. This email does not designate an information system for the purposes of section 11(a) of the NZ Electronic Transactions Act 2002.
