### ISSUE TITLE
Packaging sometimes is incorrectly building the vendor-bundle.js

### ISSUE THREAD

**Issue by corneliutusnea** [aurelia/cli#401]
**I'm submitting a bug report**
- **Library Version:**
  0.21.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.5.0
- **NPM Version:**
  3.10.7
- **Browser:**
  all
- **Language:**
  TypeScript

**Current behavior:**
Building the prod bundle using `au build --env prod` sometimes creates an unusable bundle.
When I try to load the app the bundle tries to load some module from node_modules folder directly instead of the bundle.
I basically get this error:

```
https://localhost/admin/node_modules/aurelia-templating-resources/dist/amd/aurelia-templating-resources.js Failed to load resource: the server responded with a status of 404 (Not Found)
vendor-bundle.js?v=2016.1031.2059.0:1 Unhandled rejection Error: Script error for "aurelia-templating-resources/aurelia-templating-resources"
http://requirejs.org/docs/errors.html#scripterror
    at F (https://localhost/admin/scripts/vendor-bundle.js?v=2016.1031.2059.0:3:2530)
```

The name of the module that fails is generally different at every build.

If I look inside the bundle I can see the file there however the `define` for it.
If I rebuild the bundle generally second rebuild yields a different bundle that works.

I'm quite sure this is related to #378

**Comment by AStoker** [comment]
Not sure why using the production flag would cause a different outcome here... 
Could you post your `aurelia.json` file? Can you also reproduce this on a clean project?

**Comment by alpox** [comment]
This should also be fixed with https://github.com/aurelia/cli/pull/427
