### ISSUE TITLE
[feature] loader config by environment

### ISSUE THREAD

**Issue by Thanood** [aurelia/cli#402]
**I'm submitting a feature request**

* **Library Version:**
0.21.0

**Expected/desired behavior:**

We can create bundles depending on environment and we can configure the loader (currently requirejs).
I have a setup where it would be beneficial to have several `paths` overrides while in development but the same `paths` as module names inside of a bundle when going production.

This actually works but I have to comment out the `paths` overrides when creating bundles.
I did it this way because Aurelia-CLI only ever updates the `app-bundle` and not any other bundles during `--watch`.

I'd like to be able to use different loader configs in dev/stage/prod environments.
This way I could tag the `paths` overrides for `dev` and have the loader ignore them when the `prod` bundle is created/used.

Of course the "real" feature here would be the CLI refreshing any bundles which changed but I think there's already an issue for that and maybe this feature request is useful anyway. :smiley:

**Comment by JeroenVinke** [comment]
Closing in favor of https://github.com/aurelia/cli/issues/627
