### ISSUE TITLE
Trying to call the app from a different host server using useAbsolutePath

### ISSUE THREAD

**Issue by alecb67** [aurelia/cli#403]
I'm slightly unsure as to whether this is a bug or whether i'm after a separate enhancement. We have our aurelia-cli project deployed and working on our internal production server (IntranetApps.domain.com) and this is where we would like to keep our code. However our Intranet is hosted from our Umbraco CMS sevrer. What we need to be able to do is host the aurelia code on IntranetApps.domain.com/aurelia and call the bundle file from the umbraco server (umbracoprod.domain.com).

* **Library Version:**
^0.20.2

* **Operating System:**
Windows 8.1

* **Node Version:**
v5.5.0

* **NPM Version:**
3.3.12

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I have my umbraco template calling the aurelia app as such:
<script src='@Umbraco.Field("aureliaSystemUrl")' data-main="aurelia-bootstrapper"></script>
which works fine.

I altered my aurelia.json file to look like the following:

"build": {
    "targets": [
      {
        "id": "web",
        "displayName": "Web",
        "output": "scripts",
        "useAbsolutePath": true,
        "baseUrl": "http://intranetApps.domain.com/aurelia"
      }
    ]

When the vendor bundle is called from the umbracoprod server, the vendor bundle file attempts to call the app-bundle file. However this fails with a 404, as its trying to find the file:

"http://umbracoprod.domain.com/http://intranetApps.domain.com/aurelia/scripts/app-bundle.js"

Which obviously isn't right for what i want. I believe this was because of the behaviour in the aurelia-cli bundle.js file, notably in the "createRequireJSConfig(platform)" function, after seeing what was discussed in this previous issue, https://github.com/aurelia/cli/issues/173.

    let location = platform.baseUrl || platform.output;

    if (platform.useAbsolutePath) {
      location = '/' + location;
    } else {
      location = '../' + location;
    }

As you can see in the function above, if i use the absolutePath flag, it's adding in a / before my provided baseUrl, which is adding in the host URL.

* **What is the expected behavior?**
Once I had removed the slash and left the bundle.js code like:

```
    let location = platform.baseUrl || platform.output;

    if (platform.useAbsolutePath) {
      location = location;
    } else {
      location = '../' + location;
    }
```

The app-bundle file was called correctly and the app worked perfectly from our umbracoprod server.

* **What is the motivation / use case for changing the behavior?**
We'd like to be able to make changes to our web applications without having to do a whole push from our umbraco servers, and using aurelia as a js framework and hosting js apps from a different location helps us achieve this.

I'm not sure if the above code is actually doing what it's expected and what I'm actually after is an added flag called something lie "useRealAbsolutePath" which avoids the preceding host '/', or whether it is a bug. I have been chatting with @AshleyGrant over the past few weekes and he has asked me to raise this as an issue.

Thanks

**Comment by EisenbergEffect** [comment]
This seems like a bug.

**Comment by EisenbergEffect** [comment]
Would you be interested in submitting a PR to fix it? @AStoker Thoughts on this?

**Comment by AStoker** [comment]
So I think I'm tracking with what's going on. Let me just re-iterate, so I can make sure I'm following the issue correctly.  
You're trying to reference a different location for your script files, since they don't exist in the same location as your `index` file. So you're using the absolute path flag, and a base url, which _should_ be making every request from your baseUrl location, instead of your "current" location, slash, and then your base url, e.g. `http://currentLocation.com/http://baseUrlLocation.com`  
The `location` bug you're working around would cause that problem, but I don't think we can just blanket say `location = location` in this example, since if we're not using a different url location, I believe the desired location would still be `location = '/' + location`.   
_Instead_, what might work is a regex to see if your `baseUrl` is an address (as opposed to a location reference), and if it is an address (contains `http`, `www.` or whatever regex is appropriate), then set `location = location`, and if it isn't, then leave `location = '/' + location`.  

That's all just what I'm thinking off my head, I haven't tested any of that... I imagine that you'd only have to fix it in that location line you're at @alecb67. Something across the lines of 
``` javascript
let location = platform.baseUrl || platform.output;

if (platform.useAbsolutePath) {
  if (locationHasSameBaseUrl(location)){ //some regex tester to confirm location is at the same base address
    location = '/' + location;
  }  
} else {
  location = '../' + location;
}
```

Does that sound about right @EisenbergEffect ?

**Comment by AshleyGrant** [comment]
We're still early enough in the development of the CLI, that a breaking change could be a responsible fix for this. Is there a better configuration setup we could use? Maybe add a `useAbsoluteUrlBase` or something that acts differently than `useAbsolutePath`? Or maybe change `baseUrl` to `basePath` and then make `baseUrl` be a full url?

**Comment by alecb67** [comment]
Yeah you've got the gist of it Andrew. I initially was going to write a separate flag similar to what Ashley has just explained, but i just went with the quick fix of getting rid of the slash. Either a new flag or a regex would work great for us. Happy to submit a pull request if it's still necessary.

**Comment by AStoker** [comment]
If we can create a consistent regex to catch this case, I feel that that would probably make more sense, since it would mean _less_ configuration for the user to get the use case they want. Too many flags to get stuff working, and you have users getting paralyzed by options.

**Comment by AshleyGrant** [comment]
@AStoker has there been any work on this issue?

**Comment by AStoker** [comment]
@AshleyGrant, I've not worked on this, I have too many other things on my plate right now. I was hoping someone would take that code snippet, make the regex to catch the case, and make a PR.

**Comment by codeflowee** [comment]
In the end user can write anything to ´baseUrl` so this means it's not giving in the proper conf. How about quick fix for this?

```
let location = platform.baseUrl || platform.output;

if (platform.useAbsolutePath) {
  location = platform.baseUrl ? location : '/' + location;
} else {
  location = '../' + location;
}
```

**Comment by AStoker** [comment]
@codeflowee, could you make a PR for us to look at?
