### ISSUE TITLE
vendor-bundle.js Does not work with electron or nwjs 

### ISSUE THREAD

**Issue by hamidabdulmalik** [aurelia/cli#406]
Everything works fine in browser, but when I run with electon or nwjs, it gives this error. Any help?

![aurelia](https://cloud.githubusercontent.com/assets/340532/20161992/127e9d12-a703-11e6-952b-b1bf0acd97ff.png)

**Comment by AStoker** [comment]
Can you show the code that is breaking on the `vendor-bundle` file?  
Also, the error seems to be coming/thrown from from a chrome extension? Does this happen on any other browser?

**Comment by EisenbergEffect** [comment]
Closing since OP didn't provide additional info and we know that there are working Electron+Aurelia apps.
