### ISSUE TITLE
[Feature Request] Export static files

### ISSUE THREAD

**Issue by fabioluz** [aurelia/cli#407]
I've been developing an aurelia-plugin for a legacy library. This library loads some static files asynchronously, which means that these files must be "exported" to the dist folder.  

After a long conversation with @AStoker, we came to the conclusion that aurelia-cli needs a feature to export files, like the one that SystemJS Skeleton has. It's good to emphasize that this feature is different from "resources" key in aurelia.json, that includes files in the bundle.  

This feature would be very helpful for handling libraries that weren't build for modular systems, and it will also solve some others problems like https://github.com/aurelia/cli/issues/248 

We were thinking in something like this: 
``` 
{ 
   “name”: “ckeditor”, 
   “path”: “../node_modules/ckeditor”, 
   “main”:”main”, 
    “resources”: [ 
    ], 
   “exports”: { 
      “editor.js”:”exportLocation/editor.js”, 
      “config.js”:”exportLocation/config.js” 
   } 
} 
``` 

However, we have to find anohter name because the key "exports" is being used for other things: 

``` 
{  
   "name": "bootstrap",  
    "path": "../node_modules/bootstrap/dist",  
    "main": "js/bootstrap.min",  
    "deps": ["jquery"],  
    "exports": "$",  
    "resources": [ "css/bootstrap.css" ]  
} 
``` 
 I can make the PR if I get the right direction.

What the rest of the team think about this?

**Comment by AStoker** [comment]
Other name options (not sure of any of them, just throwing ideas):  
- Copy
- Export (no 's', but could easily cause confusion)  
- Move (could be confusion because you're not really _moving_ files)

**Comment by Thanood** [comment]
How about `externals` because these files are "external" to the bundle..
Hmm, not perfect but I'll leave it here. 😃

**Comment by AStoker** [comment]
I kind of like that. Could it be confused with thinking external to the project though? Like CDN's and things external to the build folder? Or is that overthinking it?

**Comment by Thanood** [comment]
Maybe you're right.. Not sure if that's overthinking. I looked at my proposal for too long that I'm overthinking it myself right now. 😂 

- `static`
- `lazyLoad` (anything "lazy" actually)
- still like the `external`-ish direction somehow

**Comment by fabioluz** [comment]
I think that `copy` and `copyToDist` are the best so far.

**Comment by AStoker** [comment]
@fabioluz, for the sake of moving forward, I'd `copy`. If you're able to code it up in a way that makes renaming easy down the road, that'd be helpful.
