### ISSUE TITLE
HTML Source Maps not being created correctly

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/cli#409]
**I'm submitting a bug report**

* **Library Version:**
0.22.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**

Source maps for HTML files are not being added to `app-bundle.js.map` correctly. There are two issues. 

- HTML file paths in the `sources` array are being given as full absolute drive paths, e.g. `C:/foo/src/app.html`
- The `sourcesContent` array has `null` being placed in it for HTML files.

This issue affects both TypeScript and JavaScript applications.

**Comment by EisenbergEffect** [comment]
@AshleyGrant Seems like you figured out what was going wrong. Is the fix pretty straight forward? Any chance of a PR?

**Comment by AshleyGrant** [comment]
The only thing I've figured out so far is that I'm not exactly sure how source maps worked in the first place. The two lines here: https://github.com/aurelia/cli/blob/master/lib/build/concat-with-sourcemaps/index.js#L2 require from a module called `source-map`, but that doesn't seem to be a dependency of the CLI. 

Any idea how this is working? `source-map` is in my `node_modules` folder, but I need to figure out what is causing it to be installed.

**Comment by AshleyGrant** [comment]
Well, nevermind. I figured that out. It is a dependency of `gulp-sourcemaps` which is a dev dep of an Aurelia CLI project, so that explains how that works.

**Comment by EisenbergEffect** [comment]
It's coming in from another dependency. I can't remember which one though. It might be coming from gulp-sourcemaps or something like that.
