### ISSUE TITLE
Need to add release note regarding sourcemaps

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/cli#411]
I have figured out that the changes made regarding windows path separators in the `0.22` release fix some issues with source maps in both ESNext and TypeScript projects.

Unfortunately, these issues will persist until a developer updates their `aurelia.json` file. They'll need to replace all instances of `\\` with `/` to get the fixed behavior. 

Also, the path to `requirejs` was updated from `"scripts/require.js"` to `"node_modules/requirejs/require.js"` in the `prepend` section. And finally, the `text` dependency was fixed and changed from:
```javascript
{
   "text",
   "name": "text",		
   "path": "../scripts/text"		
}
```
to simply just `"text"`. 

It wouldn't hurt to add release notes regarding this for the next release of the CLI.

**Comment by EisenbergEffect** [comment]
We've got a change log for the cli but it didn't include this. If you want to PR the changelog directly, I can add that info to the next blog post.
