### ISSUE TITLE
Please add abbreviation for au generate <generator> CLI command and new generators

### ISSUE THREAD

**Issue by rajajhansi** [aurelia/cli#412]
**I'm submitting a feature request**

Please add abbreviation 'g' for generate like this:
`au generate` -> `au g`

Please add the following generators:
1.
`au g class <className>` - should generate a plain .js or .ts file under **src** folder with the source code:
```
export class className {
}
```

2.
`au g test <className>` - should generate a className.spec.js or className..ts file under **test\unit** folder with the source code:
```
import {className} from ../../src/className;

describe('the className', () => {
  it('should', () => {
  });
});
```
3.
`au g view <viewName>` - should generate a viewName.html file under **resources\elements** folder with the source code:
```
<template>
   ${}
</template>
``` 
Please add the switches --lang <language> and -y to "au new":
--lang <language> - possible values should be 'es6' (ECMAScript 6/2015) and 'ts' (TypeScript)
-y - takes default options for the remaining 2 steps in 3 step project creation i.e. , for Step 2: 1. Yes - Creates the project structure based on your selections. and for Step 3: 1. Yes - Installs all server, client and tooling dependencies needed to build the project.
For e.g., to create a TypeScript Aurelia project, I would use:
```au new projectName --lang ts -y```
I don't have to answer 3 options.

**Comment by EisenbergEffect** [comment]
No need to add a language flag because the CLI knows what language you are using. For the generators, you can write your own by simply dropping code into the folder. If you want these out of the box, please consider PRing them to the CLI. Be sure to PR them in both languages.

**Comment by rajajhansi** [comment]
@EisenbergEffect My bad. I meant to request to add switches --lang <language> and -y to "au new" and not to "au generate" command. I've edited my comment. I'd be happy to PR the generators.

**Comment by fabioluz** [comment]
But when you run `au new` you can choose which language you want. Also, you can choose among css pre processors and module loaders (in the future). 

So, adding switches to avoid answering questions could be confusing. Some users may never know about the options because someone told them to run `au new projectName --lang ts -y`.
