### ISSUE TITLE
Watcher crashes due to esprima parse errors

### ISSUE THREAD

**Issue by llicht** [aurelia/cli#413]
**I'm submitting a bug report**

* **Library Version:**
0.22.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.1 LTS

* **NPM Version:**
3.10.9

* **Language:**
TypeScript 

**Current behavior:**
Often, when I make changes to typescript sources and save while a syntax error still exists (I save very often), the au watcher crashes with the following attached errors:
[report.txt](https://github.com/aurelia/cli/files/594577/report.txt)
After this, I have to restart the watcher, which consumes unneeded time.

**Expected/desired behavior:**
The watcher should avoid crashing and continue watching.

**Comment by EisenbergEffect** [comment]
I'm closing this as a duplicate. We've got a fix coming shortly.
