### ISSUE TITLE
Introduction path to Aurelia and state of CLI and Skeleton project

### ISSUE THREAD

**Issue by xdvarpunen** [aurelia/cli#416]
**I'm submitting a feature request**
The Aurelia documentation introduces first how to use premade project and later on introduces to use aurelia-cli. Neither is production ready; CLI is in Alpha and premade project is actually just reference to make it easier to start working on Aurelia. In the nutshell Aurelia needs "production ready" development guide/introduction. 

-XDVarpunen

**Comment by xdvarpunen** [comment]
Skeleton projects seem to be the production ready starting packs

**Comment by EisenbergEffect** [comment]
The Skeletons are production ready. The CLI is in alpha but the project it generates is production quality.

**Comment by xdvarpunen** [comment]
What's difference between production quality and production ready? I am trying to decide whether to use CLI or Skeleton Projects
