### ISSUE TITLE
No sourcemaps in karma

### ISSUE THREAD

**Issue by tlenczyk** [aurelia/cli#420]
Hi, 
When debugging my test code I don't see sourcemaps in chrome console (http://localhost:9876/debug.html)

After modifications in karma.conf.js sources appears

```
let sourceMapsApp = [{pattern: 'scripts/app-bundle.js.map', included: false}]; // I'm adding this map file 
let files = [entryBundle].concat(testSrc).concat(appSrc).concat(sourceMapsApp);
```

I don't know what I should change to attach also sourcemaps for test sources. 
Do you have any ideas?

aurelia-cli 0.22.0

**Comment by EisenbergEffect** [comment]
Interesting. We need to look into this. Please update us with any other findings or experiments that yield your expected output. We can use this to improve what our CLI generates.

**Comment by AStoker** [comment]
We've included sourcemaps for our project the same way you have done. For test sources you need to tell babel that you want sourcemaps included, and make them inline, so that way you don't have to bring in external files (they're embedded in the transpiled file).
