### ISSUE TITLE
project built with aurelia-cli WITHOUT requirejs/text loader. How does this work?!

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/cli#422]
**I'm submitting a bug report**

* **Library Version:**
0.22.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Surprise!
remove "text" from package.json,
remove "text" from aurelia.json dependencies,
create an empty file "text.js" in src/ folder.
now run `au run`, everything works, all html templates are working!

Here is a repo to approve it.
https://github.com/huochunpeng/au-without-requirejs-text

**Expected/desired behavior:**
How does this ever work?!?!

* **What is the expected behavior?**
Since everything works, should we remove requirejs/text??

* **What is the motivation / use case for changing the behavior?**
When I study the compiled js bundle, I found the text.js file content was not in there, there is only one empty defintion `define('text', {});`.
Then I found out aurelia-cli does NOT actually use requirejs/text source code to load html/css files. I am confident it is not used as my debug line `throw new Error(...)` was never ever triggered.

Could someone explain what's going on here? This hurts my brain.

**Comment by EisenbergEffect** [comment]
The bundling process, using the default coniguration, inlines all the text content, so that a plugin is no longer needed. As a result, it can just stub the text plugin with a fake version. If you look in the aurelia.json file, you'll see some configuration for stubbing that.

**Comment by huochunpeng** [comment]
Thanks! yes they are all inline.

**Comment by huochunpeng** [comment]
because cli stubs it anyway, should we remove "text" from package.json?

**Comment by EisenbergEffect** [comment]
We don't want to remove it because some people turn stubbing off. If they need to dynamically require text, they will need to include that. I'd prefer for it to still be there.
