### ISSUE TITLE
Support for adding sass paths

### ISSUE THREAD

**Issue by krokofant** [aurelia/cli#430]
Is there a existing way of adding paths to the sass/css processor?

Adding a framework like Foundation was not so easy. Either use weird imports or include paths into sass.

I added this so one can paths via the `cssProcessor` object in `aurelia.json`
```js
import gulp from 'gulp';
import sourcemaps from 'gulp-sourcemaps';
import sass from 'gulp-sass';
import project from '../aurelia.json';
import { build } from 'aurelia-cli';
import path from 'path';

export default function processCSS() {
  return gulp.src(project.cssProcessor.source)
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: project.cssProcessor.paths.map(p => path.join(__dirname, "../../", p))
    }).on('error', sass.logError))
    .pipe(build.bundle());
}
```

Is this a valid solution? Could something like this be added by default?

**Comment by AStoker** [comment]
For our situation, we had a bunch of custom css files that we wanted to have included, as well as some sass files that we wanted separate so it'd load up before the application started (sounds like what you'd want Foundation to do).   

I'm not terribly familiar with Foundation. But I'm assuming that it's a module that you downloaded and sits in the Node Modules folder, and doesn't have a root/main javascript file? If that's the case, you could probably do something similar to what you're doing here. You can add a property to your json file that describes external sass libraries to be compiled and imported, and then simply bring them in by doing your `build.bundle`, or gulp them to a destination file to include in your `index.html`.  

There's an existing issue (don't have it on me right now) for being able to identify CSS frameworks and bundle them appropriately via the `aurelia.json` bundle's dependencies (right now, the dependencies require a `main.js`, which CSS frameworks don't have).  

Does that help?

**Comment by krokofant** [comment]
I'm not looking to solve a specific problem as much as I'm trying to find the optimal solution.

In the example with the Foundation framework there are scss files which are preferably imported from the path and the imported files may also import things assumed to be in the path. This forced me to modify a part of the code created by aurelia-cli to be able to include stuff in the scss/sass path.

So for importing scss/sass modules it would be great if a way, similar to the one i wrote, to be included in the aurela-cli generator.

**Comment by AStoker** [comment]
Modifying the tasks that the Aurelia CLI sets up is perfectly fine (and what you should do). The CLI sets you up for an initial case, but you can customize it all you want. Once the project is set up once with the CLI, it's not going to touch those tasks it created again.
