### ISSUE TITLE
Specify test folder or allow test to be in the same folder as components

### ISSUE THREAD

**Issue by mttmccb** [aurelia/cli#433]
**I'm submitting a feature request**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.1

* **Node Version:**
6.8.1

* **NPM Version:**
3.10.8

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Unit tests are configured to be in a separate folder

**Expected/desired behavior:**
Unit test can be configured to be in the either in the separate folder or in the same folder as the component under test.

* **What is the expected behavior?**
An option in the CLI which gives a few options, [test], [specify folder], [in place]

* **What is the motivation / use case for changing the behavior?**
This would make the unit test paths simpler and also make it easier to do testing as the files you need would be in the same folder.

This isn't the way everyone wants to work but it would nice to be an option.

I'm going to try and do this for a build I'm generating using the CLI, I don't know how easy this would be to implement as an option.

**Comment by mttmccb** [comment]
I managed to get this working by making a few small changes (definitely a hacky way to do it!)

In aurelia.json I updated transpiler settings to exclude spec files

```
  "transpiler": {
    "id": "typescript",
    "displayName": "TypeScript",
    "fileExtension": ".ts",
    "dtsSource": [
      "./typings/**/*.d.ts",
      "./custom_typings/**/*.d.ts"
    ],
    "source": "src/**/!(*.spec).ts"
  },
```

and the test runner source to look for spec files in the new location

```
  "unitTestRunner": {
    "id": "karma",
    "displayName": "Karma",
    "source": "src/**/*.spec.ts"
  },
```

This means the setup file isn't included so in karma.conf.js I included it in testSrc

```
let testSrc = [
  { pattern: 'test/unit/setup.ts', included: false },
  { pattern: project.unitTestRunner.source, included: false },
  'test/aurelia-karma.js',
];
```

and in the preprocessors I added the setup file too.

```
    preprocessors: {
      ['test/unit/setup.ts']: [project.transpiler.id],
      [project.unitTestRunner.source]: [project.transpiler.id]
    },
```

**Comment by JeroenVinke** [comment]
Looks like a nice solution to me. Thanks for returning to post the solution
