### ISSUE TITLE
Change the main property in a dependency configuration to be optional

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#435]
**I'm submitting a bug report**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.7

* **Browser:**
all

* **Language:**
all 

**Current behavior:**
Kendo-UI has a bunch of controls that are exported as individual files. There is no specific "main" file, so in dependencies section of aurelia.json we do not need to configure the "main" property either:

```
{
    "name": "kendo-ui-core",
    "path": "../node_modules/kendo-ui-core"
},
```

However, this results in the following error:

![image](https://cloud.githubusercontent.com/assets/2189477/21074754/f4d0b74e-bf00-11e6-8e5a-49eaaf03bfbc.png)

Luckily the application still runs and it works as it should (the mapping works fine).

**Expected/desired behavior:**

* **What is the expected behavior?**
The main property should be optional, so that simple path mappings can be declared as well.

* **What is the motivation / use case for changing the behavior?**
To be able to use libraries that do not have a specific main file.

Assuming that there is no other way to configure packages without main files, I can create a PR to resolve this error

original issue: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/660
repro: https://github.com/JeroenVinke/aurelia-app-optional-main

**Comment by EisenbergEffect** [comment]
@JeroenVinke Please feel free to submit a PR for this.

**Comment by zedL** [comment]
Any news here?

**Comment by JeroenVinke** [comment]
@zedL I will take a look at this shortly

**Comment by StrahilKazlachev** [comment]
What about being explicit, setting it to `false` - `"main": false`, or something? My idea is to show intention.

**Comment by JeroenVinke** [comment]
That's probably a better solution. Right now `main` is optional, but then it assumes that the `path` is pointing to an existing file. I'll update the PR

**Comment by zewa666** [comment]
This would be great in order to create a minimal import of Rx.js. I like the `main: false` approach as it is very descriptive :+1:

**Comment by JeroenVinke** [comment]
:+1:

I have updated the PR: https://github.com/aurelia/cli/pull/673
