### ISSUE TITLE
[Feature Request] Add markup minification option during project setup

### ISSUE THREAD

**Issue by bigopon** [aurelia/cli#440]
**I'm submitting a feature request**

* **Library Version:**
latest

**Please tell us about your environment:**
* **Operating System:**
all

* **Language:**
all

* **Current behavior:**
HTML minifying is something everyone eventually does, but has to add to gulp tasks themselves every time, maybe consider offering an option during project setup to turn this task on. Options could be:

    - None (default) -> No markup minification used
    - Basic -> Remove only whitespace between block elements
    - Aggressive -> Remove all whitespace between elements, also remove attribute quotes where possible

* **Expected/desired behavior:**
Out of the box support for `gulp-html-minifier`

* **What is the motivation / use case for changing the behavior?**
Having to set this up every project does not seem right

**Comment by EisenbergEffect** [comment]
Would you be interested in making a PR to the CLI's generated html task?

**Comment by bigopon** [comment]
Im not familar with the repo but ill give it a go.
Where you want the step position be ? After transpiler step ?

**Comment by EisenbergEffect** [comment]
Consider adding it right into the html task.

**Comment by bigopon** [comment]
The PR is here #441 
The step name is `markupProcessor` making it feel uncomfortable to put those configs in though

**Comment by Gheoan** [comment]
Thanks @bigopon for the PR. Should this issue be closed now?
Related: https://github.com/aurelia/cli/issues/191.

**Comment by bigopon** [comment]
@gheoan definitely. I assumed it was repo maintainer job but i guess ill saved everyone time. Tks.
