### ISSUE TITLE
Loading resources from a bundle not loaded/required at page-load fails.

### ISSUE THREAD

**Issue by bellstrand** [aurelia/cli#445]
**I'm submitting a bug report**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.2

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.8

* **Browser:**
Chrome 55.0.2883.95 (64-bit)

* **Language:**
ESNext

**Current behavior:**
Loading a page that requires nothing from bundle X and then navigating to a page that requires a package from bundle X results in this error:
```bash
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
Loading the page that requires something from bundle X directly works as expected.

Package used when testing: https://www.npmjs.com/package/highcharts

**How to reproduce:**
npm install highcharts --save

In aurelia.json add a 3'd bundle, my config is below.
```json
{
	"name": "highcharts-bundle.js",
	"dependencies": [
		{
			"name": "highcharts",
			"path": "../node_modules/highcharts",
			"main": "highcharts.src",
			"resources": [
				"highcharts-more.src.js"
			]
		}
	]
}
```

Create a aurelia application with at least 2 routes, and import highcharts in one of them.
```javascript
import Hightcharts from 'highcharts';
```

Load the route that doesn't require highcharts, then navigate to the route that does and the error should appear.

* **What is the expected behavior?**
I expect the bundle to be loaded "ad-hoc" when it's needed in my application.

* **What is the motivation / use case for changing the behavior?**
I have a few pages that requires libraries that are big and I don't want them to load during a normal page-load, just when they are needed.

**Comment by tbnovaes** [comment]
I needed to use the highcharts-more module too, so what I did was to import it as a different module. Than in the main.js I imported like that:

import 'highcharts';
import 'highcharts-more';

This way both are available in for my entire application, once I'm using it in many places.

**Comment by bellstrand** [comment]
@tbnovaes I think you are missing my point now, the problem is not importing the library.
I want to put the library in a separate bundle that is only loaded on certain routes to minify the bundle size that is always loaded.

**Comment by 3cp** [comment]
This now behaves as expected in latest cli-bundler.
The config is simpler.

```
{
  "name": "highcharts-bundle.js",
  "dependencies": [
    "highcharts"
  ]
}
```
