### ISSUE TITLE
Feature Request: Allow modules to be ignored or stubbed at bundle time

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/cli#448]
**I'm submitting a feature request**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.9

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
There seems to be no way to ignore specific module names while bundling in the CLI. In the codebase, there is a check for `build.loader.config.stubModules` (https://github.com/aurelia/cli/blob/master/lib/build/bundler.js#L33); adding modules to this array seems to allow the trace feature to stub the module definition (https://github.com/aurelia/cli/blob/master/lib/build/amodro-trace/write/stubs.js).

The current problem is that whether or not modules are defined in this configuration key, the CLI will always check whether or not the filename exists on disk (in package-analyzer.js), breaking the build.

**Expected/desired behavior:**

* **What is the expected behavior?**
When calling `bundle.create`, the package analyzer should repect the `stubModules` property in `loader.config` and choose not to attempt to resolve the module.

* **What is the motivation / use case for changing the behavior?**
I'm migrating from a JSPM/SystemJS project which used `System.newModule` to generate Javascript modules based on server data at page render time (dotnet MVC). This worked natively with SystemJS and the import statements, but it doesn't seem to work with the bundler in this case because the bundler isn't expecting dynamic module load at runtime.

**Comment by EisenbergEffect** [comment]
This should already be possible through the excludes option.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect Looking further at this, I'm not sure if this solves the issue. The `excludes` option takes a list of filenames or file paths - but not a list of module names. As such, the module resolution will still fail at bundle time, even if the files are excluded. I'm not sure if there's a good solution to this.
