### ISSUE TITLE
dependent file not being transpiled when read before depending class

### ISSUE THREAD

**Issue by torgeirhansen** [aurelia/cli#450]
**I'm submitting a bug report**

* **Library Version:**
0.23.0

* **Operating System:**
Windows 10

* **Node Version:**
6.9.2
* **NPM Version:**
3.10.9

* **Browser:**
Chrome 55 | IE 11 (tested, I assume this is really All.)

* **Language:**
ESNext

**Current behavior:**
.js class files that are discovered before the .js file that imports them are not transpiled.
This causes the web app to not load.

**Expected/desired behavior:**
Transpiling should occur :)

To reproduce:
au new somethingsomething, using ESNext and default options.
In src, create folders a,b,c.
Create these files:

- a/controller1.js
```
import { Model1 } from 'src/b/model1.js';

export class Controller1 {
    model = new Model1();
}
```
- a/controller1.html
```
<template>
<h1>Controller 1</h1>
Model1 result: <b>${model.getSomeValue()}</b>
</template>
```
- b/model1.js
```
import { ValidationRules } from 'aurelia-validation';

export class Model1 {
    getSomeValue(){
        return "Hello from model1";
    }
}
```
- b/model2.js
```
export class Model2 {
    getSomeValue(){
        return "Hello from model2";
    }
}
```
- c/controller2.js
```
import { Model2 } from 'src/b/model2.js';

export class Controller2 {
    model = new Model2();
}
```
- c/controller2.html
```
<template>
<h1>Controller 2</h1>
Model2 result: <b>${model.getSomeValue()}</b>
</template>
```

Then change app.html to this:
```
<template>
  <h1>Bundle test</h1>
  <hr>
  <require from='a/controller1'></require>
  <require from='c/controller2'></require>

  <controller1></controller1>
  <hr>
  <controller2></controller2>
  
</template>
```

It'll fail to load, saying this (the unexpected token export is the hint that no transpiling occured):
```
INFO [aurelia] Aurelia Started
vendor-bundle.js:14205 DEBUG [templating] importing resources for app.html ["a/controller1", "c/controller2"]0: "a/controller1"1: "c/controller2"length: 2__proto__: Array[0]
model2.js:1 Uncaught SyntaxError: Unexpected token export
vendor-bundle.js:14205 DEBUG [templating] importing resources for a/controller1.html []
vendor-bundle.js:14205 DEBUG [templating] importing resources for c/controller2.html []
vendor-bundle.js:1395 Unhandled rejection Error: Error invoking Controller2. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot read property 'Model2' of undefined
Inner Error Stack:
TypeError: Cannot read property 'Model2' of undefined
```
(I've cut away all the stack tracing at the end).

Then you can try to move b/model2.js to a new directory, d.
Change the import in controller2.js to point to d/model2.js, stop au run and start it again. 
Now it'll work just fine.

* **What is the expected behavior?**
The expectation is for the transpiling to occur, also for files that have names (or are in folders with names) that sort before the scripts that import them are read.

* **What is the motivation / use case for changing the behavior?**
The motivation whould be a happy user that can have his model classes in a models directory rather than xmodels - which is my current workaround :(

**Comment by 3cp** [comment]
The importing path is not correct.
`import { Model1 } from 'src/b/model1.js';`

Either use relative path `from '../b/model1.js`;`,

or absolute path `from 'b/model1.js` (in requirejs context, the root is `src/`, not the project's root folder).

Furthermore, latest cli-bundler will gave you error at build time. The error shows it tries to load a npm package named after "src" (similar to the case of import from `"foo/b/c.js"`).
```
ERROR [Bundler] Failed to add Nodejs module src/b/model1
INFO [Bundler] Error: Unable to find package metadata (package.json) of src
```
