### ISSUE TITLE
Testing changes during cli development

### ISSUE THREAD

**Issue by s-hoff** [aurelia/cli#451]
**I'm submitting a feature request**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When making changes to the cli, in order to test it, one must either

1. Edit the node_modules/aurelia-cli folder in a test project, or
2. edit the files in the global installation when making changes that affect e.g. the new command.

When trying to do an `npm link` on the dev directory, npm will complain about esprima not being installed:

```
Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /home/shoff/aurelia/aurelia/cli/lib/build/amodro-trace/lib/parse.js:5:62
    at Array.map (native)
    at define (/home/shoff/aurelia/aurelia/cli/lib/build/amodro-trace/lib/parse.js:5:36)
    at Object.<anonymous> (/home/shoff/aurelia/aurelia/cli/lib/build/amodro-trace/lib/parse.js:10:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Expected/desired behavior:**

* **What is the expected behavior?**
Using `npm link`, `npm install ./cli` or `node bin/aurelia-cli.js`, the cli should work as normal, but with the local changes. Installing esprima as a dependeny or devDependency solves this.
For some reason, using `npm i -g aurelia-cli` does not produce the same error, even although esprima cannot be found anywhere in the global installation. Adding the dependency might in fact save from future trouble as it becomes clear where it comes from.
amodro-trace, which requires this module, has esprima in its dependencies. Therefore, I assume this would also be a good place for it in the cli.

* **What is the motivation / use case for changing the behavior?**
Testing changes to the cli should be easy and not involve having to potentially even edit the global installation manually.

**Comment by s-hoff** [comment]
After this, it would also be good to add documentation on how to manually test ones changes to the readme or wiki, so new cli developers can quickly get set up.

**Comment by JeroenVinke** [comment]
@s-hoff since your PR has been merged, can this been closed?

**Comment by s-hoff** [comment]
@JeroenVinke I would like to address adding some form of documentation to this to avoid future 'how do I test the cli?' kind of questions. Even although now all it takes is an `npm link`, I feel like a line on it in the README or CONTRIBUTING would be appropriate.

**Comment by EisenbergEffect** [comment]
If you could put something in the readme file, that would be amazing. You can add it to this PR even. Please ❤️

**Comment by sbolel** [comment]
I actually didn't experience this issue while working on #499 just now. 

[Here's a Gist](https://gist.github.com/sbolel/ef766756af567b261b069315c9b9d032) of how I've been doing development for that PR.

**Comment by s-hoff** [comment]
So seems like there is only one issue here: When, on top of the `npm link`, I do an `npm link aurelia-cli` in the test project's directory in order to bind my changes for e.g. the `build` command, somehow the devDependencies of the tasks go missing.

@sbolel That's because the dependency was already declared by then ;)
I was, however, also unable to test changes from my work copy for the on-project commands such as `au build` with your method (tested it by deliberately putting some broken code and logs in areas that would have to be touched there).

**Comment by JeroenVinke** [comment]
@s-hoff 

> So seems like there is only one issue here: When, on top of the npm link, I do an npm link aurelia-cli in the test project's directory in order to bind my changes for e.g. the build command, somehow the devDependencies of the tasks go missing.

I noticed this as well. Weird

**Comment by ghidello** [comment]
Same here, linking my CLI fork in a test project returns me some devDependencies errors that I've not been able to solve. 
I'm trying to handle the Subresource Integrity attributes for the bundles so, in order to be able to test my updates, I ended up developing directly in  my test project node_modules subfolder.
How do you normally develop end test cli commands like build or generate?

**Comment by s-hoff** [comment]
Make the changes in the `aurelia_project` folder of a fresh project or one without any previous changes to the cli, then copy then to your clone. Even if we fix the `npm link` part, this will stay as one is supposed to be able to customize the `aurelia_project` parts.

**Comment by ghidello** [comment]
I wasn't referring to the code in the aurelia_project folder, sorry if I wasn't clear, but to the actual CLI logic like [bundle.js](https://github.com/aurelia/cli/blob/master/lib/build/bundle.js): that's why I would need to link my fork.

**Comment by JeroenVinke** [comment]
I have created a PR with the commands I use to work on the CLI: https://github.com/aurelia/cli/pull/616. Let me know if you have issues when running these commands

**Comment by ghidello** [comment]
Worked like a charm and sorry for answering so late.
