### ISSUE TITLE
[Feature Request] Add default tslint setup

### ISSUE THREAD

**Issue by s-hoff** [aurelia/cli#452]
**I'm submitting a feature request**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
There is a tslint.json for TypeScript projects and an eslintrc.json for babel. The eslint has no configuration in it, while the eslintrc is extending the aurelia tools setup.

**Expected/desired behavior:**

* **What is the expected behavior?**
The tslint.json should prodive some kind of default. We could base it on the eslint setup from aurelia-tools or maybe aurelia-ux (as it is the only TS project I know of among the official projects).

* **What is the motivation / use case for changing the behavior?**
Linting provides good code quality. It should be ready to go for both ESNext and TypeScript projects, and have similiar defaults.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/pull/718
