### ISSUE TITLE
[Feature Request] Add linting to build tasks

### ISSUE THREAD

**Issue by s-hoff** [aurelia/cli#453]
**I'm submitting a feature request**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
During build, any linting rules are ignored.

**Expected/desired behavior:**

* **What is the expected behavior?**
Linting should either be done in the build process, the transpile task, or there shoud be a task set up do run the tools manually.

* **What is the motivation / use case for changing the behavior?**
There are already linting rules in the default projects, so it makes sense to use and enforce them. With this set up, one does not have to manually set it up when creating a new project.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/pull/718
