### ISSUE TITLE
Aurelia new - command does not exist

### ISSUE THREAD

**Issue by zewa666** [aurelia/cli#46]
seems the latest fix to how Command loads the necessary command files has introduced execution errors with the init phase commands `new` and `init`. @joelcoxokc guess we should revert to first check for the folder/index.js file and then afterwards try to find the file. If both fail then throw the error.

**Comment by ahmedshuhel** [comment]
@zewa666 I guess this code in `commands/index` creates the problem. It certainly does for me.
```javascript
cmd = (__dirname + '/' + cmd );
  // Checking for whether the files exists at this point, should only be for development
  // Otherwise, we know the files exists, so this just becomes an extra function call
  // Once fully deployed, we shouldn't be checking whether the command file exists.
  isArg = exists(cmd);
```
Changing this to: `  cmd = (__dirname + path.sep + cmd + '.js' );` works for me. Can you confirm?

**Comment by zewa666** [comment]
yes, thats right, the problem though is that we need to check for both commands within the commands folder and those in subfolders. So doing both checks should fix the issue

**Comment by zewa666** [comment]
should be fixed with the merged PR
