### ISSUE TITLE
Aurelia CLI version 0.24.0 - Task script process-markup causing two issues

### ISSUE THREAD

**Issue by abemeister** [aurelia/cli#464]
I'm submitting a bug report

Library Version:
0.24.0
Please tell us about your environment:

Operating System:
Windows 7

Node Version:
6.9.2

NPM Version:
3.10.9
JSPM OR Webpack AND Version
JSPM 0.16.32 | webpack 2.1.0-beta.17
Not using JSPM or Webpack - using Aurelia CLI - Node packages

Browser:
Chrome, Firefox & Internet Explorer

Language:
all | TypeScript X.X | ESNext
Typescript

Current behavior:

First bug

In the process-markup.ts script, was working for version 0.23.0 but broken for 0.24.0
First bug cause not finding the custom tags because it can't parse the require paths in the HTML. This work for 0.23.0 but broken for 0.24.0

When set the flag to firstPass: false to avoid the error

Second bug

The gulp htmlmin cause a runtime error:
Failed to load resource: the server responded with a status of 404 (Not Found)
vendor-bundle.js:1395 Unhandled rejection Error: src/../scripts/app-bundle.html HTTP status: 404
at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9000/scripts/vendor-bundle.js:62891:31)
From previous event:
at DefaultLoader._import (http://localhost:9000/scripts/vendor-bundle.js:36671:14)
at DefaultLoader.loadText (http://localhost:9000/scripts/vendor-bundle.js:36642:19)
at TextTemplateLoader.loadTemplate (http://localhost:9000/scripts/vendor-bundle.js:36566:21)
at Object.fetch (http://localhost:9000/scripts/vendor-bundle.js:36615:71)
at Object.load (http://localhost:9000/scripts/vendor-bundle.js:36710:39)

It's complaining can't find the app-bundle.html. It working when take off the script code:
.pipe(htmlmin({
removeComments: true,
collapseWhitespace: true,
collapseInlineTagWhitespace: true,
collapseBooleanAttributes: true,
removeAttributeQuotes: true,
minifyCSS: true,
minifyJS: true,
removeScriptTypeAttributes: true,
removeStyleLinkTypeAttributes: true
}))

and run it again...

Expected/desired behavior:

The process-markup.ts script for the htmlmin should work without affecting the HTML require paths and working at runtime

What is the expected behavior?

What is the motivation / use case for changing the behavior?
If using the task script from 0.23.0 version for process-markup.ts it works
When introduce the htmlmin, it causing the desired two issues:

Complain about not finding the custom element because not interpreting the require paths anymore.
The runtime issue in regards to not finding the app-bundle.html

**Comment by Alexander-Taran** [comment]
Probably can be closed

**Comment by Alexander-Taran** [comment]
Either fixed or OP lost interest.
