### ISSUE TITLE
Support browser field spec

### ISSUE THREAD

**Issue by unional** [aurelia/cli#467]
**I'm submitting a bug report**
* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Windows [8]

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

I wrote `aurelia-logging-color` and want to use it in my project.
It uses the `browser` field to skip the node specific "os" module.
https://github.com/unional/aurelia-logging-color/blob/master/package.json#L6-L8

It seems like the aurelia project does not support reading the browser field
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/6

Currently, I specify a replacement module to get around it:

```js
// aurelia_project/aurelia.json

          {
            "name": "aurelia-logging-color",
            "path": "../node_modules/aurelia-logging-color/dist/es5",
            "main": "index"
          },
          {
            "name": "os",
            "path": "../node_modules/os-browserify",
            "main": "browser"
          },
```

**Comment by EisenbergEffect** [comment]
I believe we have support coming for this in a PR already :)

**Comment by unional** [comment]
Nice! Thanks, Rob.

**Comment by JeroenVinke** [comment]
Closing this one as we have another issue tracking this: https://github.com/aurelia/cli/issues/581. A fix is ready, just need to test a few more things
