### ISSUE TITLE
collapseInlineTagWhitespace

### ISSUE THREAD

**Issue by rquast** [aurelia/cli#473]
I'm submitting a bug report.

CLI Version 0.24.0

option ...
collapseInlineTagWhitespace: true

The process markup task for maximum minification incorrectly removes whitespace for the following scenario when turned on:

```
<p>This is some text <a href="#">with a link</a> that should have spacing around it</p>
```

The collapseInlineTagWhitespace option will do this to the html..

```
<p>This is some text<a href="#">with a link</a>that should have spacing around it</p>
```

Should not remove the whitespace before and after the anchor tag.

**Comment by EisenbergEffect** [comment]
I think this bug should be submitted to the underlying library that handles the minification probably. Can you submit this here? https://github.com/jonschlinkert/gulp-htmlmin

**Comment by rquast** [comment]
Just got shut down by the repo maintainer for submitting the issue. Oh well.

**Comment by rquast** [comment]
@bigopon I gathered that too. The reply seemed so curt, so I lost interest.
