### ISSUE TITLE
Generate element creates unnecessary empty dirs

### ISSUE THREAD

**Issue by depsypher** [aurelia/cli#475]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

* **Operating System:**
OSX 10.x

* **Node Version:**
v7.4.0

* **NPM Version:**
4.0.5

**Current behavior:**
Running a command such as `au generate element foo` creates several empty directories.
```
attributes
binding-behaviors
value-converters
```

**Expected/desired behavior:**
I'd prefer no empty dirs to be created.

* **What is the expected behavior?**
Just an `elements` dir with new files in it is created.

* **What is the motivation / use case for changing the behavior?**
Given that there are separate generators for each of these things, it is confusing that `generate element` does anything related to attributes, binding-behaviors or value-converters. Empty dirs don't get tracked in git, so different team members can have different directory structures, and it's just visual noise to see a dir that's empty.

**Comment by Alexander-Taran** [comment]
Stale since may 2017

**Comment by Alexander-Taran** [comment]
@3cp what do you think?

**Comment by 3cp** [comment]
Will fix this.
