### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by arvadevy** [aurelia/cli#478]
**I'm submitting a bug report**

* **Library CLI Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **Browser:**
Google Chrome

* **Language:**
TypeScript 2.1.5

**Issue**
Most of the times when i build my application i get this error in my console.
![image](https://cloud.githubusercontent.com/assets/24693253/22506872/05a2725a-e883-11e6-804c-015b633b719d.png)

I have multiple node modules that depend on jquery so i can't use it like this:
```
"jquery",
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": [
              "jquery"
            ],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
            ]
          }
```
but i have to use it like this:
```
 {
            "name":"jquery",
            "path":"../node_modules/jquery/dist",
            "main":"jquery.min",
            "export": "$"
          },
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "resources": [
              "css/bootstrap.css"
            ]
          },
{
            "name": "toastr",
            "path": "../node_modules/toastr",
            "main": "toastr",
            "resources": [
              "build/toastr.min.css"
            ],
            "deps": [
              "jquery"
            ]
          }

```
Any ideas?

**Comment by arvadevy** [comment]
Of sometimes this one 
![image](https://cloud.githubusercontent.com/assets/24693253/22512591/da02d088-e899-11e6-905a-5fa598cf3204.png)

**Comment by jedd-ahyoung** [comment]
I've run into this a few times as well and can confirm this behavior.

**Comment by fabioluz** [comment]
A temporary solution is putting jquery in the `preprend` intead of in the `dependencies`.

**Comment by sbolel** [comment]
Do you have `import 'bootstrap';` at the top of _main.js_ as suggested in [this answer](http://stackoverflow.com/documentation/aurelia/1916/aurelia-cli/6256/adding-bootstrap-to-a-cli-application#t=201702042308227454478) on StackOverflow?

**Comment by rahulmeharkar** [comment]
send proper anser

**Comment by vedprakash289** [comment]
Uncaught Error: Bootstrap's JavaScript requires jQuery
To resloved these issue in angular 2,4,6
first just install in window os
1. npm install jquery --save
2. stop the ng server if running by ctr+c then press y for yes

3. again type  ng serve
