### ISSUE TITLE
Contributing to the CLI

### ISSUE THREAD

**Issue by mttmccb** [aurelia/cli#479]
I was looking at a few issues but there are some blockers that are making difficult to get started with closing them off

* I don't know how to build the CLI project, there are no instructions.
* I don't know if the changes I make would break something, there are no tests.
* I don't know what the desired behaviour of all the elements of the CLI is so I'm not sure if my changes would do something unexpected, there are no specs.

I want to contribute as I like the experience of using the CLI and want to help improve it, rather than just raise more issues.

Please let me know how I (and others) can help.

**Comment by EisenbergEffect** [comment]
* There's no need to build the CLI project.
* It's extremely difficult to find a way to write tests for the CLI. If you are looking for a way to contribute, helping us work that out would be great. The tests can then form a set of specs.

**Comment by mttmccb** [comment]
Ok, I just looked at the bin folder and assumed that was where it built to but I see that isn't the case.

The starting point would be adding tests for the lib directory, probably mocking creating files, etc..

I'll give it a go and see how far I get.
