### ISSUE TITLE
@inject not supported

### ISSUE THREAD

**Issue by altus34** [aurelia/cli#480]
**I'm submitting a bug report**

* **Library CLI Version:**
0.24.0

* **Operating System:**
Linux (Ubuntu 16.10)

* **Node Version:**
v4.2.6

* **NPM Version:**
3.5.2

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**
I try to use @inject([Router]) annotation in my project created in ESNext.
I've got this error in my node console:

`
gulp-notify: [Error running Gulp] Error: /myfile.js: Unexpected token (3:0)
`

So I need to use this syntax:

`
static inject() { return [Router]; }
`

**Expected/desired behavior:**
I expect to be able to use the inject annotation. The babel plugin is provided by the default Aurelia CLI (the package babel-plugin-transform-decorators-legacy is here).

I take a look on the Aurelia.js and add the transform-decorators as babel plugin:

`
"plugins": [
        "transform-es2015-modules-amd",
        "transform-decorators"
      ]
`

Now I've this issue:

Error: /myfile.js: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:
`
{
  "plugins": ["transform-decorators-legacy"]
}
`
The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

Thanks

**Comment by mttmccb** [comment]
You don't need the square brackets, try this

```
@inject(Router)
```

or for multiple dependencies

```
@inject(Router, Element)
```

Hopefully that resolves your issue.

**Comment by altus34** [comment]
Same issue

**Comment by EisenbergEffect** [comment]
Is your transpiler configured to use decorators? It's definitely supported or else Aurelia would have died two years ago....
