### ISSUE TITLE
ENOENT error is repeated even after removing bad dependency reference from aurelia.json

### ISSUE THREAD

**Issue by samuelmolinski** [aurelia/cli#484]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora)

* **Node Version:**
6.8.0

* **NPM Version:**
3.10.8

* **Language:**
ESNext

**Current behavior:**
After a typo in the aurelia.json in an attempt to add a legacy library to the dependencies, I added a duplicate string entry like this, where "json-editor" was the typo:
```
"dependencies": [
  ... ,
  {
    "name": "aurelia-testing",
    "path": "../node_modules/aurelia-testing/dist/amd",
    "main": "aurelia-testing",
    "env": "dev"
  },
  "json-editor",
  {
    "name": "jsoneditor",
    "path": "../vendor",
    "main": "jsoneditor",
    "exports": "JSONEditor"
  }
]
```
After running `au run --watch` I started to receive this error:

> Error: ENOENT: no such file or directory, open '/home/sjmolinski/PhpstormProjects/sis-skis/node_modules/json-editor/package.json'

To which I immediately removed all of the new code: 
```
  "json-editor",
  {
    "name": "jsoneditor",
    "path": "../vendor",
    "main": "jsoneditor",
    "exports": "JSONEditor"
  }
```
I still get the same error regardless of changes to the dependencies.

**Expected/desired behavior:**
I expect it to reset and compile the code as it was before the typo.  Is there some kind of cache on my local machine that needs to be cleared, either something from Aurelia, gulp or even node?

**Comment by EisenbergEffect** [comment]
Do you have a reference to that module somewhere in your code?
