### ISSUE TITLE
au run : Invalid Command

### ISSUE THREAD

**Issue by code-recipes** [aurelia/cli#485]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
WIndows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.1.2

* **Browser:**
Edge

* **Language:**
ESNext

**Current behavior:**
When following the "contact-manager" tutorial instructions "au run --watch" outputs "Invalid Command: run"

**Comment by code-recipes** [comment]
Update: Keeps doing it after the uninstall and npm-cache clean.

**Comment by sbolel** [comment]
Is `aurelia-cli` included both in the project `devDependencies` and also installed globally? 

```sh
npm i -g aurelia-cli
npm i --save-dev aurelia-cli
```

**Comment by code-recipes** [comment]
Hi @sbolel. Thanks for that. Problem fixed after installing the local dev package.

**Comment by Mobe91** [comment]
I am experiencing the same issue even after running
```
npm i -g aurelia-cli
npm i --save-dev aurelia-cli
```
I am using
* aurelia-cli 0.31.3 
* npm 3.10.10
* node 6.11.4

**Comment by JeroenVinke** [comment]
Hmm. Perhaps try and remove the node_modules foldrr and `npm install` again?

If that doesn't help please include the project (without node modules) as a zip to this issue, if possible

**Comment by Mobe91** [comment]
Removing node_modules did not help, here is the project:
[aurelia-test.zip](https://github.com/aurelia/cli/files/1407109/aurelia-test.zip)

**Comment by JeroenVinke** [comment]
@Mobe91 I see, thank you for sending me the ZIP.

There seems to be a mix of typescript and babel in the project, e.g. `.ts` files in the src folder and typescript also mentioned as the `transpiler` in `aurelia_project/aurelia.json`. But typescript isn't installed (in package.json there's no `typescript` entry), but babel is.

When I change the `transpiler` section in aurelia.json to:

```
  "transpiler": {
    "id": "babel",
    "displayName": "Babel",
    "fileExtension": ".js",
    "source": "src/**/*.js"
  },
```

the app runs, although there's an error in the browser related to a CSS file
