### ISSUE TITLE
Feature request: displayCompleted LifeCycle Method

### ISSUE THREAD

**Issue by lstarky** [aurelia/cli#487]
**I'm submitting a feature request**

* **Library Version:** 0.24
* **Operating System:** Windows 10
* **Node Version:** 6.7.0
* **NPM Version:** 3.10.3
* **Browser:** Chrome 56.0.2924.87 (64-bit)
* **Language:** all

**Current behavior:**
I've seen many users, including myself, run into difficulty because there's no clean way to determine when the DOM binding has completed for things like `repeat.for` loops and other display items that take more than 1ms.  Most recent example here:

http://stackoverflow.com/questions/42241091/execute-function-after-content-has-been-dynamically-loaded-in-aurelia
http://stackoverflow.com/questions/41697495/using-jquery-datatables-with-aurelia

The workaround solution is to add a task at the bottom of the queue, which theoretically will run after all binding jobs have completed.  However, this is not a clean approach.

**Expected/desired behavior:**
I believe that Aurelia should implement a lifecycle method like `displayCompleted` or `bindingCompleted` or something else along these lines.  This is something that would be useful in many scenarios and would alleviate frustrations for designers.

This might even be a very easy solution to implement if the `taskQueue.queueMicroTask()` approach doesn't have any fatal flaws.  You could simply always insert a task in the queue to call the lifecycle hook if it exists.

**Comment by JeroenVinke** [comment]
The templating repository seems the best place for this one, so I moved it there: https://github.com/aurelia/templating/issues/534
