### ISSUE TITLE
Create plugin install command to pull from aurelia-registry

### ISSUE THREAD

**Issue by PWKad** [aurelia/cli#49]
The interface is already defined in the help command, but for reference again - 

```sh
aurelia plugin [p] [-list, -l]                     List all installed plugins
  plugin [-h]                                      Show help for plugins
  plugin -a --add {plugin-name}                         Add plugin from Aurelia plugin repo
  plugin -r --remove {plugin-name}                      Disable plugin from project
  plugin -c --clear {plugin-name}               Completely remove plugin and files
```

This compliments the corresponding issue in the registry

**Comment by PWKad** [comment]
This should also install the plugins' CLI libs.  I would assume that they would be placed in the lib file along side the others, but how can we add the commands without modifying the cli source so it can still be updated?  Any thoughts @joelcoxokc @ahmedshuhel @zewa666 ?

**Comment by joelcoxokc** [comment]
I think I have some ideas. I say we have them install the plugins locally. and we can just require them from their local dir. Let me play around with it.

**Comment by PWKad** [comment]
@joelcoxokc I think you have a lot of issues already, I'm taking this one back for now since I've been working on it.  In the future please let me know before you reassign.

**Comment by joelcoxokc** [comment]
I apologize. I think I did this by mistake.

**Comment by PWKad** [comment]
I'm unassigning myself from this now as I don't have time to salvage the work I've done right now.  In a nutshell, if you pick this one up, this is what I would suggest - 

User input
```js
$ aurelia -a i18next
```

1. Check the [registry](https://github.com/aurelia/registry/blob/master/plugin-registry.json) for a matching named entry named 'i18next'
2. Use the endpoint and location to construct the `jspm install` message (ex. `jspm install github:zewa666/i18next`)
3. Add aurelia section to package.json if it doesn't exist.
4. Add key/value entry for the plugin under the `aurelia: { plugins: [] }` section

For this to still work the way I planned it would mean that we need a helper function added to the main.js to dynamically add the plugins listed there.  The alternative is to manually edit the main.js but that feels fragile.

**Comment by joelcoxokc** [comment]
I'll take it off your hands !

**Comment by ahmedshuhel** [comment]
The feature is in and released already

**Comment by PWKad** [comment]
@ahmedshuhel wow that's awesome! Is there some documentation we can read on how to install a plugin through the CLI?

**Comment by ahmedshuhel** [comment]
@PWKad credit goes to @zewa666. https://github.com/aurelia/cli#plugin
