### ISSUE TITLE
Linter error within transpile.ts

### ISSUE THREAD

**Issue by suamikim** [aurelia/cli#495]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Not Browser related

* **Language:**
TypeScript 2.1.5

**Current behavior:**
My linter complains about the use of `var` instead of `let` on the line `var typescriptCompiler = typescriptCompiler || null;` within a fresh CLI TypeScript project in `transpile.ts`.

Simply changing it to `let` leads to the TypeScript error `TS2448:Block-scoped variable 'typescriptCompiler' used before its declaration.`.

**Solution/Question**
I've managed to solve this by replacing the whole line with `let typescriptCompiler = null;` which works at first glance and doesn't cause any obvious problems.

Is it save to do so or am I missing something here?

**Comment by EisenbergEffect** [comment]
Honestly, I can't remember why this code as like that. I think it was some edge case. If it's not giving you any problems, you should be ok though.
