### ISSUE TITLE
Unable to partially add multiple modules from 1 package

### ISSUE THREAD

**Issue by suamikim** [aurelia/cli#502]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Not browser related

* **Language:**
TypeScript 2.1.5

**Current behavior:**
It doesn't seem to be possible to partially add 2 or more modules from 1 package whilst not including all modules of the package in the `vendor-bundle`.

E.g. I'd like to use the modules `crypto-js/aes` & `crypto-js/sha256` from the package [crypto-js](https://www.npmjs.com/package/crypto-js) whilst not including the complete package.

So far I tried the following approaches:

*(1) Explicitly add both modules to `package.json`*

`package.json`

```
{
    // ...
    "bundles": [
        {
            // app-bundle
        },{
            // vendor-bundle
            // ...
            "dependencies": {
                // ...
                {
                    // Use some custom name and point it explicitly to a module. Doesn't work...
                    "name": "crypto-js-aes",
                    "path": "../node_modules/crypto-js",
                    "main": "aes"
                },{
                    // Use some custom name and point it explicitly to a module. Doesn't work...
                    "name": "crypto-js-sha256",
                    "path": "../node_modules/crypto-js",
                    "main": "sha256"
                }
            }
        }
    ]
}
```

`foo/bar/code.ts`
```javascript
import * as aes from 'crypto-js-aes';
import * as sha256 from 'crypto-js-sha256';
```

This leads to the following problems:

* Typescript tells me `TS2307:Cannot find module 'crypto-js-aes'.` where I try to import the modules (`foo/bar/code.ts`)
* The CLI process started with `au run --watch` stops execution after the output `Tracing foo/bar/code...` without any additional error.

*(2) Add the complete package to `package.json` but only require the modules which are actually used*

`aurelia.json`
```
{
    "name": "crypto-js",
    "path": "../node_modules/crypto-js",
    "main": "index"
}
```

Which is basically equal to only including the package name as a simple string instead of the object above.

`foo/bar/code.ts`
```javascript
import * as aes from 'crypto-js/aes';
import * as sha256 from 'crypto-js/sha256';
```

Whilst this is working, the CLI includes the complete `crypo-js` package in the built `vendor-bundle` instead of only the 2 mentioned modules.

**What is the motivation / use case for changing the behavior?**
Only include the modules which are actually used to keep the `vendor-bundle` as small as possible.

**Additional note**
I've also asked this question [on stackoverflow](http://stackoverflow.com/questions/42340582/how-to-add-multiple-modules-from-1-package) but didn't get no solution there and since I consider partial adding of modules as a must have for the build/bundling process, I'm also reporting it as an issue here...

**Comment by AStoker** [comment]
Can you see if in the bundle the packages are individual modules and what their names are? This sounds like a reasonable use case, and I want to say that we've dealt with similar things with jQuery-UI packages...

**Comment by suamikim** [comment]
Using option (2) from my first post, it seems like the complete package is bundled into `vendor-bundles.js`. Here's an excerpt from my built `vendor-bundle.js`:

```
// ...

;(function (root, factory) {
	if (typeof exports === "object") {
		// CommonJS
		module.exports = exports = factory();
	}
	else if (typeof define === "function" && define.amd) {
		// AMD
		define('crypto-js/crypto-js',[], factory);
	}
	else {
		// Global (browser)
		root.CryptoJS = factory();
	}
}(this, function () {

	/**
	 * CryptoJS core components.
	 */
	var CryptoJS = CryptoJS || (function (Math, undefined) {
		// ...
	}

	// All modules of CryptoJS follow here, even the ones which are not used anywhere...

}));;define('crypto-js', ['crypto-js/crypto-js'], function (main) { return main; });

// ...
```

The code within the excerpt above from `vendor-bundle.js` is completely identical to the code within my locally installed `node_modules/crypto-js/crypto-js.js`

**Comment by arabsight** [comment]
@suamikim check SO, I updated my answer to include crypro-js. this isn't a bug.

**Comment by suamikim** [comment]
@arabsight Perfect, this is exactly what I was looking for!
