### ISSUE TITLE
Poor debug experience due to broken source maps

### ISSUE THREAD

**Issue by suamikim** [aurelia/cli#503]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Chrome 56 but I guess it's browser independent

* **Language:**
TypeScript 2.1.5

**Current behavior:**
Breakpoints in Chrome Dev Tools don't show the correct mapped source code. This seems to be mostly the case when debugging 3rd party dependencies which can most of the time be considered as an inconvenience but also happens when debugging application code itself which is more of a show stopper:

![debug issues](https://cloud.githubusercontent.com/assets/2870365/23355826/d0b97a8e-fcd7-11e6-919b-dc61a9728566.gif)

I've already described the issue in detail [on stackoverflow](http://stackoverflow.com/questions/41815351/debugging-3rd-party-scripts-with-aurelia) and therefore don't duplicate the reproduction steps etc. here but am happy to do so if required ;)

Also when writing the stackoverflow question I was under the impression, that this only happens for 3rd party scripts but realized later, that this also happens for application code. If necessary I can try to create a simple test application with reproduction steps etc.

This is possibly a consequence of https://github.com/aurelia/cli/issues/342 but I believe that it should still be a dedicated issue...

**Comment by AStoker** [comment]
I'm not sure (can't recall right now) if we're actually bundling/including source maps for vendor files. It's possible that if a vendor has a source map, that it's being screwed up in the bundle process because it's looking for files that don't exist... 
If it's related to the bundling issue, we'd appreciate any help with that.
If you're able to read out the sourcemaps somewhat and maybe find out where it's erroneously pointing to the wrong file, that'd be great. Otherwise, if you could set up a repo that we could pull down and look at, that would be helpful as well.

**Comment by EisenbergEffect** [comment]
I believe the fix for some of this is coming in the next release. We had some improvements related to source maps.

**Comment by suamikim** [comment]
@EisenbergEffect Good to hear! Do you have any idea on when the next release will be published?

@AStoker Actually I'm currently not able to reproduce the mentioned behavior but I'll try to create a repo with reproduction steps as soon as I experience it the next time!

**Comment by EisenbergEffect** [comment]
Next release very soon. This week, even if it kills me.

**Comment by suamikim** [comment]
Haha, good to hear (that it's coming soon, not that it's troublesome...)

**Comment by EisenbergEffect** [comment]
It's not troublesome. I've just got a bit behind on releases and I'm determined to get that all sorted this week.

**Comment by JeroenVinke** [comment]
@suamikim can you confirm whether or not aurelia-cli 0.25.0 fixed this issue? Thanks

**Comment by suamikim** [comment]
Since I can't even reproduce the issues in version `0.24.0` with my current code base I can't reliably confirm that they're fixed with `0.25.0` or later.

Therefore I'm closing this issue and simply reopen it if I'll ever experience them again.
