### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#504]
**I'm submitting a feature request**
This purpose of this issue is to track all instances where errors during the bundling/tracing phase are silenced

**Current behavior:**
Some tracing/bundling related errors are currently silenced. Some examples mentioned in:

- https://github.com/aurelia/cli/issues/502
- https://github.com/aurelia/cli/pull/419
- https://github.com/aurelia/cli/issues/190

**Expected/desired behavior:**
All errors to be reported

**Comment by AStoker** [comment]
My name is Andrew Stoker, and I approve of this issue. ;)
Some thoughts I had in addition to this were having optional flags to log out various levels of verbosity. e.g. `au build --verbose` would be _verbose_ in it's messages, helping out with debugging, while `au build --silent` would output only errors...
