### ISSUE TITLE
Error in either CLI or Contact-Manager tutorial

### ISSUE THREAD

**Issue by MarkStega** [aurelia/cli#508]
**I'm submitting a bug report**
* **Library Version:**
1.0.0

* **CLI Version**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.5.0

* **NPM Version:**
4.2.0

* **Browser:**
Chrome 56.0.2924.87
Firefox 51.0.1

* **Language:**
TypeScript 2.2.1

**Current behavior:**

As soon as I add   'require from="bootstrap/css/bootstrap.css' to the contact manager tutorial app.html the app fails to load (this is after I added bootstrap & jquery to the installed node modules and updated aurelia.json.

**FF trace:**

POST http://localhost:9001/browser-sync/socket.io/?EIO...sport=polling&t=Lg5Owd8&sid=paDTgOFZLjAxDtc_AAAJ
	
200 OK
		2ms	
browser...=2.18.8 (line 2)
GET http://localhost:9001/browser-sync/socket.io/?EIO...sport=polling&t=Lg5OwdL&sid=paDTgOFZLjAxDtc_AAAJ
	
200 OK
		6ms	
browser...=2.18.8 (line 2)
POST http://localhost:9001/browser-sync/socket.io/?EIO...sport=polling&t=Lg5OwfE&sid=paDTgOFZLjAxDtc_AAAJ
	
200 OK
		1ms	
browser...=2.18.8 (line 2)
GET http://localhost:9001/browser-sync/socket.io/?EIO...sport=polling&t=Lg5OwfK&sid=paDTgOFZLjAxDtc_AAAJ
	
200 OK
		158ms	
browser...=2.18.8 (line 2)
TypeError: plugin.load is not a function
	

vendor-bundle.js (line 4834, col 21)

**Chrome trace:**

DEBUG [aurelia] Loading plugin aurelia-templating-binding.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-templating-binding.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin aurelia-templating-resources.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-templating-resources.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin aurelia-event-aggregator.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-event-aggregator.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin aurelia-history-browser.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-history-browser.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin aurelia-templating-router.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-templating-router.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin resources/index.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin resources/index.
vendor-bundle.js:13935 DEBUG [aurelia] Loading plugin aurelia-testing.
vendor-bundle.js:13935 DEBUG [aurelia] Configured plugin aurelia-testing.
vendor-bundle.js:13935 DEBUG [templating] importing resources for aurelia-templating-resources/compose []
vendor-bundle.js:13935 DEBUG [templating] importing resources for aurelia-templating-router/router-view []
vendor-bundle.js:13945 INFO [aurelia] Aurelia Started
vendor-bundle.js:13935 DEBUG [templating] importing resources for app.html ["bootstrap/css/bootstrap.css", "styles.css"]
vendor-bundle.js:4834 Uncaught TypeError: plugin.load is not a function
    at Module.<anonymous> (vendor-bundle.js:4834)
    at vendor-bundle.js:3873
    at on (vendor-bundle.js:4256)
    at Module.callPlugin (vendor-bundle.js:4694)
    at Module.fetch (vendor-bundle.js:4563)
    at Module.check (vendor-bundle.js:4595)
    at Module.enable (vendor-bundle.js:4915)
    at Object.enable (vendor-bundle.js:5296)
    at Module.<anonymous> (vendor-bundle.js:4900)
    at vendor-bundle.js:3873
    at each (vendor-bundle.js:3798)
    at Module.enable (vendor-bundle.js:4852)
    at Module.init (vendor-bundle.js:4527)
    at vendor-bundle.js:5199

**Expected/desired behavior:**

* **What is the expected behavior?**
Expect tutorial app to load properly.

** Steps to reproduce **
Follow the Contact Manager tutorial through the complete router configuration steps

* **What is the motivation / use case for changing the behavior?**
Having a functional tutorial is useful for new users.

**Comment by MarkStega** [comment]
As soon as I add   <require from="bootstrap/css/bootstrap.css"></require>
to app.html; Not sure what happened in original submission.

**Comment by JeroenVinke** [comment]
I saw a similar issue on SO: http://stackoverflow.com/questions/42489212/aurelia-application-startup-issue-in-contact-manager-tutorial/42494327#42494327

**Comment by MarkStega** [comment]
That was me also - I had gone ahead and finished the tutorial without the CSS. When I started down the path to set the stub property to false I first added the require line back in. On saving app.html the application now loads correctly. I am going to start the tutorial again and see when continuing pasty the router mysteriously makes things work.

**Comment by AStoker** [comment]
It's most likely an error in the tutorial, since we're able to do this now.

**Comment by MarkStega** [comment]
I started the tutorial from scratch and again at the completion of 'Building out the default route' the initial error state is reproduced. Continuing the tutorial it is not until you complete 'Adding a loading indicator' that the load of bootstrap.css succeeds.

**Comment by AStoker** [comment]
Sounds like a documentation change needs to be made to fix the tutorial. Mind making a PR with the change, since you're familiar with the correct order?

**Comment by MarkStega** [comment]
I would do the PR but I truly don't understand why the break occurs and what actually fixes the issue. I think that someone who understands the CLI and Webpack needs to look at this. I will happily help them get to the error state...

**Comment by AStoker** [comment]
I got a few other things on my plate before I can look at it, personally. However, if you were to make a repo of the state that shows it breaking, and where specifically in the steps of the tutorial you're at, I'll do my best to take a look.

**Comment by MarkStega** [comment]
I created a public GitHub repository at MarkStega/Contact-Manager-1; This corresponds to the completion of the step "Building out the default route". I don't think this is a documentation issue, but instead one of either the CLI, WebPack, or Aurelia-Loader. Whatever it is, I'd love to understand the issue even if it does turn out to be documentation.

**Comment by JeroenVinke** [comment]
Thanks @MarkStega, I got the plugin.load error in your repository. It mentioned `no-selection.html` in a subsequent error. I noticed you had `no-Selection.html` (capital S), and after renaming it to `no-selection.html` the app worked.

**Comment by MarkStega** [comment]
@JeroenVinke Thanks; I corrected the filename case and had other errors. I brought down a copy of my repository, fixed the filename, and everything does work. I went back and put the wrong case filename in place. The logging of the bootstrap process could be clearer..

**Comment by JeroenVinke** [comment]
Thanks for trying it out. What do you mean by logging of the bootstrap process, and how would you like to see it improved?

**Comment by MarkStega** [comment]
@JeroenVinke BY logging of the bootstrap process I mean a more coherent line by line of something like "Loaded 'no-selection.html'" for success and a line like "Failed to load 'no-selection.html'" rather than the spurious plugin.load error and then the two screen stack trace.

**Comment by JeroenVinke** [comment]
I agree. We have an issue tracking this: https://github.com/aurelia/cli/issues/287. I'll close this issue now, as this problem seems to be resolved

**Comment by codedbypaul** [comment]
As per the answer [here](http://stackoverflow.com/questions/38026255/including-bootstrap-css-in-aurelia) I had to restart the app after modifying the aurelia.json file to get it find the bootstrap files.

**Comment by JeroenVinke** [comment]
Thanks @codedbypaul! I will make sure that this gets mentioned in the tutorial
