### ISSUE TITLE
Crash in CLI on syntax error

### ISSUE THREAD

**Issue by jugglingthebits** [aurelia/cli#510]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.6.0

* **NPM Version:**
4.1.2

* **Language:**
TypeScript 2.2.1

**Current behavior:**
`au build` crashes when compiling typescript with invalid syntax in application code. Not all cases of invalid syntax crash. The resulting error message contains way too much information and is confusing ([example](https://gist.github.com/jugglingthebits/6157e97ce41560cc76a16df190d21cfd)).
My main issue is that `au run --watch` also crashes which makes using the watcher much less useful.
Repro:

    git clone https://github.com/jugglingthebits/au-ts-syntax-error
    cd au-ts-syntax-error
    npm install
    au build *or* au run --watch

**Expected/desired behavior:**
`au build` should inform about the syntax error - not crash.
`au run --watch` should not crash on syntax error and ignore that file.

* **What is the motivation / use case for changing the behavior?**
`au run --watch` should not crash when application code is currently not in a valid state: Code editors may save at any point and a background watcher shouldn't just stop due to syntax errors.

**Comment by AStoker** [comment]
@jugglingthebits, could you test this again with the latest CLI? We've made a few improvements that might solve your issue.
Links to relevant issues/PR's to have everything referenced:
https://github.com/aurelia/cli/pull/511
https://github.com/aurelia/cli/issues/504
https://github.com/aurelia/cli/pull/498

**Comment by jugglingthebits** [comment]
Just tested with 0.26.1. `au run --watch` doesn't crash on these syntax errors any more - nice!

Now, it doesn't start the build-run-watch-loop either but just stops with the same really long error message. IMHO, it should should enter the loop and print the same nice error messages as if those error hat been introduced after it was started correctly.

`au build` displays the same error message as above now, which could be improved. IMHO. this isn't a huge problem though.

I think this issue can be closed, although the error messages are by far not as nice as they should be yet.

**Comment by AStoker** [comment]
If you have some ideas on improving the logging, PR's are more than welcome! :)
