### ISSUE TITLE
Importing interface with absolute path to a module with interface brakes compilation

### ISSUE THREAD

**Issue by goldiner** [aurelia/cli#513]
**I'm submitting a bug report**

* **Aurelia CLI Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.4

* **Browser:**
all

* **Language:**
TypeScript 2.1.6

**Current behavior:**
Importing an interface with absolute path to a module with single interface causing wrong compilation:

1. `au run --watch` tracing missing a lot of files
2. there is no app-bundle.js.map at scripts folder
3. error 404 for main.js when browsing to the site

Problematic code:
```
import {IModel} from 'Model/Interface/IModel'
export interface SomeInterface
...
```

Import with relative path works perfectly:

```
import {IModel} from '../../Model/Interface/IModel'
export interface SomeInterface
...
```

tsconfig.json:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
     "*": ["./src/*"]
    },
    "sourceMap": true,
    "target": "es5",
    "module": "amd", //amd
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "lib": ["es2015", "dom"]
  },
  "exclude": [
    "node_modules"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
}

```

**Comment by AStoker** [comment]
Could you take a look and see if this PR would solve your issue? Just want to see if it's related. https://github.com/aurelia/cli/pull/499

**Comment by goldiner** [comment]
Yes, it is solved my issue. Thanks!

**Comment by AStoker** [comment]
@goldiner, it's not merged yet, so once it's merged, ensure it's working for you. If it isn't, feel free to reopen :)
