### ISSUE TITLE
rev issue: index.html not updated

### ISSUE THREAD

**Issue by tdamir** [aurelia/cli#514]
**I'm submitting a bug report**

* **Library Version:**
0.25.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.9.2

* **NPM Version:**
4.3.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
If rev is enabled in aurelia.json, the bindle revisions are generated but index.html is not updated according to that.

**Expected/desired behavior:**
It should replace the index.html like in previous version.
I've looked at the source and it looks like index is replaced before the revisioned filename is generated. If I change the order, it works fine.

Original bundle.js (line: 182)
```javascript

      if (loaderOptions.configTarget === this.config.name) {
        //Add to the config bundle the loader config and change the "index.html" to reference the appropriate config bundle
        concat.add(undefined, this.writeLoaderCode(platform));
        contents = concat.content;
        let outputDir = platform.baseUrl || platform.output; //If we have a baseUrl, then the files are served from there, else it's the output
        if (platform.index) {
          this.setIndexFileConfigTarget(platform, path.posix.join(outputDir, bundleFileName));
        }
      }

      if (buildOptions.rev) {
        //Generate a unique hash based off of the bundle contents
        this.hash = generateHash(concat.content);
        bundleFileName = generateHashedPath(this.config.name, this.hash);
      }

```
Modified version working as expected:

```javascript
      if (buildOptions.rev) {
        //Generate a unique hash based off of the bundle contents
        this.hash = generateHash(concat.content);
        bundleFileName = generateHashedPath(this.config.name, this.hash);
      }

      if (loaderOptions.configTarget === this.config.name) {
        //Add to the config bundle the loader config and change the "index.html" to reference the appropriate config bundle
        concat.add(undefined, this.writeLoaderCode(platform));
        contents = concat.content;
        let outputDir = platform.baseUrl || platform.output; //If we have a baseUrl, then the files are served from there, else it's the output
        if (platform.index) {
          this.setIndexFileConfigTarget(platform, path.posix.join(outputDir, bundleFileName));
        }
      }
```

**Comment by AStoker** [comment]
Dangit... This is why we need to get those tests in there. When I tested out my "fix", it must have been using a cached version, so I didn't test everything out like I thought I did. Essentially, we moved the hashing function up to solve a different bug, but failed to modify when the updated hash is written to the .html file. I'll have to get the fix in real quick

**Comment by AStoker** [comment]
I'll try and get it in real quick @tdamir. The reason your fix won't work directly is because if a single bundle changes which causes a bundle to have a different hash, but the vendor bundle didn't update, then the vendor bundle's hash would remain the same, even though the other bundle now has a different reference (and is shown in the vendor bundle). This causes browsers to cache the previous vendor bundle (with the same name, but different file contents), and you suddenly have a request for a file that no longer exists.

**Comment by tdamir** [comment]
@AStoker You are right. I was just looking at the code more carefully and figured that my code is also not working in every situation.

**Comment by AStoker** [comment]
What you had as your "fix" was actually how it was previously :) So you weren't far off. In fact, it wasn't until we ran into a very strange cache issue at work that finally brought that issue to light. It's not a common issue though, but it did need to be fixed.

**Comment by tdamir** [comment]
This could do the job (not tested): 
```javascript
      if (loaderOptions.configTarget === this.config.name) {
        //Add to the config bundle the loader config 
        concat.add(undefined, this.writeLoaderCode(platform));
        contents = concat.content;
      }

      if (buildOptions.rev) {
        //Generate a unique hash based off of the bundle contents
        this.hash = generateHash(concat.content);
        bundleFileName = generateHashedPath(this.config.name, this.hash);
      }

      if (loaderOptions.configTarget === this.config.name) {
        //Change the "index.html" to reference the appropriate config bundle
        let outputDir = platform.baseUrl || platform.output; //If we have a baseUrl, then the files are served from there, else it's the output
        if (platform.index) {
          this.setIndexFileConfigTarget(platform, path.posix.join(outputDir, bundleFileName));
        }
      }


```

**Comment by AStoker** [comment]
That's pretty much what I did (slightly modified). Check out the PR referenced: https://github.com/aurelia/cli/issues/515

**Comment by tdamir** [comment]
@AStoker Thanks for the fix!
