### ISSUE TITLE
Inline source maps cause build to fail

### ISSUE THREAD

**Issue by s-hoff** [aurelia/cli#517]
**I'm submitting a bug report**

* **Library Version:**
0.25.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When generating or obtaining source maps from the vendor files, inline source maps get treated as file references. This results in the cli trying to load an impossible path like `/home/shoff/workspaces/tests/cli-26/node_modules/dragula/dist/data:application/json;charset:utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5v(...)`. That again causes the build to fail and abort.

**Expected/desired behavior:**

```
au new inline-sourcemaps
cd inline-sourcemaps
npm i --save dragula
```
Add dragula in aurelia.json
```
{
    "name": "dragula",
    "path": "../node_modules/dragula/dist",
    "main": "dragula"
}
```
then build
`au build`

* **What is the expected behavior?**
Inline source maps should be ignored. They are already in the file and need no extra work.

* **What is the motivation / use case for changing the behavior?**
The current behavior would break several libraries, or at least dragula.

**Comment by fabioluz** [comment]
The temporary solution is using the minified version:

```
{
    "name": "dragula",
    "path": "../node_modules/dragula/dist",
    "main": "dragula"
}
```

**Comment by EisenbergEffect** [comment]
@AStoker or @JeroenVinke Can you look at this?
