### ISSUE TITLE
Set environment variable using command line arguments

### ISSUE THREAD

**Issue by suamikim** [aurelia/cli#522]
**I'm submitting a feature request**

* **Library Version:**
CLI `0.26.0`
Framework `1.0.8`

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Chrome 56 but it's not browser related

* **Language:**
TypeScript 2.1.5

I'd sometimes need the possibility to set the value of a specific environment variable using a command line argument.

E.g. I'd like to set a version number which is generated by my build server:

`aurelia_project/environments/prod.ts`

```
export default {
    debug: false,
    testing: false,
    // $buildVersion$ should be replaced during build with the actual value
    buildVersion: $buildVersion$
};
```

Imaginary command: `au build --env prod --buildVersion 1.1.1`

**Comment by AStoker** [comment]
Nothing stopping you from doing this inside of a gulp task during your build. You can look at the existing tasks and see how it pulls down the cli flags. You can do the same thing to pull/make any flag you want and modify your environments file any way you want, and pretty much do whatever you'd like 😃  Let me know if you need any tips for that.

**Comment by suamikim** [comment]
@AStoker Thanks for the suggestion, I've already had that in mind as a fallback option. At least to me it feels like this should be built into the CLI so the feature request persists :wink:

Nonetheless I need some advice now for implementing this manually:

I tried to manually update the `src/environment.ts` file which is a simple copy of the appropriate `aurelia_project/environments/${env}.ts` file and assumed/hoped that the CLI bundles this file into my `app-bundle` which seems to wrong.

Here's what I tried:

**aurelia_project/environments/${env}.ts**
```ts
export default {
    debug: false,
    testing: false,
    buildVersion: {buildVersion} // <-- The placeholder which should be replaced during build
};
```

**aurelia_project/tasks/build.ts**
```ts
// ...
import processEnvironment from './process-environment';

export default gulp.series(
	readProjectConfiguration,
	gulp.parallel(
		gulp.series(
			transpile,
			// Process this in series with "transpile" which copies the
			// appropriate env file to "src/environment"
			processEnvironment // <-- The replacement happens here
		),
		processCSS,
		// ...
	),
	writeBundles
);
// ...
```

**aurelia_project/tasks/process-environment.ts**
```ts
// ...
export default function processEnvironment() {
	const buildVersion = CLIOptions.getFlagValue('buildVersion') || '0.0.0';
	
	return gulp.src(`${project.paths.root}/environment.ts`)
		.pipe(replace('{buildVersion}', buildVersion))
		.pipe(gulp.dest(project.paths.root));
}
```

This seems to work as expected and the `{buildVersion}` placeholder within `src/environments.ts` is replaced as expected.

However, the replacement is not reflected by my built `app-bundle.js`:

```ts
define('environment',["require", "exports"], function (require, exports) {
    // ...
    exports.default = {
        buildVersion: '{buildVersion}',
        // ...
    };
});
// ...
```

It seems like the bundler doesn't take the info from `src/environments` but directly from `aurelia_project/environments/${env}.ts`?

I see multiple options right now:
1. Perform the replacement after bundling directly within `app-bundle`.
    * **(-)** I'd need to perform the replacement on `app-bundle` & `src/environment.ts` in order to keep everything "in sync"
2. Perform the replacement before all other steps within `aurelia_project/environments/${env}.ts` using some regex instead of the `{buildVersion}` placeholder
    * **(-)** I'd lose the explicit information from the `{buildVersion}` placeholder which lets everybody know from looking at the code that this is subject to replacement in some build step
    * **(-)** Changing content of dev files in a build step simply doesn't feel right to me...

What are your thoughts on this? Do you see any superior alternatives?

**Comment by AStoker** [comment]
Quick note, the `src/environtment.ts` file is modified at build time to reflect how you are trying to run. If you run with the dev environment, the file will have the options that represent that (as configured by the `aurelia.json` file). So if you manually modified it, and then ran, then that file would have been updated with your build instructions.  

Now, the `src/environments` should be what is pulled down when you ask for it, as you can see this in the `main.js` of the skeleton project. The reason you're not getting your updated file contents is because of the order in which you are processing your files. If you look at the `transpile` task, that is where the environment variables are read in and the appropriate file copied. But also inside here is where we transpile/build the code. Which means your replacement function is happening after the code is transpiled, and therefore not being brought into your bundle.  

To solve your problem, simply do your replace function inside the `transpile.js` `configureEnvironment` function, since that is where you should be doing this kind of configuration. 

So, your `configureEnvironment` function simply is modified to look like this (this is for ES, fyi, but the solution is identical).
``` javascript	
function configureEnvironment() {
  let env = CLIOptions.getEnvironment();
  let buildVersion = CLIOptions.getFlagValue('buildVersion') || '0.0.0'; //Added this to get buildVersion
  return gulp.src(`aurelia_project/environments/${env}.js`)
    .pipe(changedInPlace({firstPass:true}))
    .pipe(replace('{buildVersion}', buildVersion)) //Replace your text with the build version
    .pipe(rename('environment.js'))
    .pipe(gulp.dest(project.paths.root));
}
```

That's it, that's all it takes :) Let me know if this still doesn't work, or if you have any more questions.

**Comment by suamikim** [comment]
Perfect, this is exactly the hook I was looking for. Thanks for the tip!

**Comment by suamikim** [comment]
Here's a follow up question:

How can I dynamically set the locations of my `vendor-bundle.js` & `app-bundle.js` which are referenced within `index.html` & `vendor-bundle.js` during build based on the chosen environment?

Right now, those are always referenced with a **relative** URL which is working perfectly fine in development but doesn't in my production scenario which looks something like this:

* `index.html` is served over www.mydomain.com
* `vendor-bundle.js` & `app-bundle.js` are served by an external source (CDN etc.). So they are coming from https://my.cdn.com/vendor-bundle.js & https://my.cdn.com/app-bundle.js

Those locations need to be adjusted dynamically using the environment files:

**aurelia_project/environments/dev.ts**
```js
export default {
    // ...
    resPath: 'res/'
};
```

**aurelia_project/environments/stage.ts**
```js
export default {
    // ...
    resPath: 'https://mystaging.cdn.com/'
};
```

**aurelia_project/environments/prod.ts**
```js
export default {
    // ...
    resPath: 'https://my.cdn.com/'
};
```

As you can see, the `resPath` can be a **relative** link to `index.html` when working locally but needs to be an **absolute** path when deployed. Also it needs to use different URLs in staging & production environment.

I've already managed to do this using some custom tasks which look something like this:

**aurelia_project/tasks/process-index**
```js
// ...
export default function processIndex() {
	// We have to manually parse the actual value of the "resUrl" param from the
	// appropriate environment file since there's currently no way to access environment
	// variable values during the build with the CLI which I'm aware of...
	// See http://stackoverflow.com/q/42682253/1273551
	const env = CLIOptions.getEnvironment();
	const envContent = fs.readFileSync(`aurelia_project/environments/${env}.ts`, 'utf8');
	const resUrl = /resUrl: '(.*)'/ig.exec(envContent)[1];
	
	// Actually adjust the paths in our index.html.
	// Very naive approach, not very "future prove"...
	return gulp.src('index.html')
		.pipe(replace('build/res', resUrl))
		// ...
}
```

**aurelia_project/tasks/process-bundles**
```js
// !!! Needs to be executed after `writeBundles` since it replaces code inside the fully processed `vendor-bundle.js`
// ...
export default function processVendorBundle() {
	// ... same parsing of env variable values as in the above processIndex...
	
	return gulp.src(`${project.platform.output}/vendor-bundle.js`)
		.pipe(replace('../res', resUrl))
		// ...
}
```

Whilst this works for now, there are a few things I don't like about it:

* The whole part of manually parsing data from the appropriate env file is quite cumbersome and possibly error prone. See leading comments inside `processIndex` and/or http://stackoverflow.com/q/42682253/1273551
* Manually replacing stuff inside `index.html` & the fully processed `vendor-bundle.js` doesn't feel right since the CLI is already doing its parts. Also my naive replace-approaches above may work now but are definitely error prone.

Is there another hook in the CLI or existing build process which I'm not aware of which I could use for my described scenario?

I've already stumbled across some places in `aurelia.json` which allow me to adjust those paths but I'm not quite sure which parts I actually have to edit (`build.targets[].output` & `baseUrl`?) and ultimately don't know how to make them conditional based on the actual build environment...

**Comment by AStoker** [comment]
Try checking out this issue for how to use an absolute url for your starting location (https://github.com/aurelia/cli/issues/403)   
At first glance, it looks like you're trying to take too much control over the output of the files :P I'd try to not control the output of the files, but rather look to see if there's some way you can influence the building itself so the output is what you're expecting.  

I'm not sure what else you'd have to do there besides use that option.

**Comment by suamikim** [comment]
Thanks for the hint with `useAbsolutePath`. Do you have any suggestions according different URLs for different environments?

**Comment by AStoker** [comment]
It would depend on what needs to be changed. If you're just hosting your files in different locations, then you only need to modify the index page, which is simple enough with a gulp task.
