### ISSUE TITLE
Library Upgrade Command

### ISSUE THREAD

**Issue by cosmoKenney** [aurelia/cli#526]
**I'm submitting a feature request**

Can we add command to au that upgrades the library and all dependencies? I've spent hours trying to update to the latest cli and others that were released last night. But it's a big jumbled mess.

**Comment by EisenbergEffect** [comment]
Is there some reason that npm won't work?

**Comment by Thanood** [comment]
Maybe it would be useful to be able to automate upgrade tasks as mentioned in [0.23.0](https://github.com/aurelia/cli/releases/tag/0.23.0) and [0.25.0](https://github.com/aurelia/cli/releases/tag/0.25.0).

**Comment by cosmoKenney** [comment]
NPM only seems to do one at a time. And doesn't keep all related packages like all the bits of aurelia at the most recent release. 

For instance, lots of people were having problems yesterday with npm install aurelia-cli@latest. It was  installing the broken 0.26.1. 

My proposal would be for the cli to bring all packages to the latest working release so you know that all the packages on your system will work together. That doesn't necessarily always mean all packages should be at their latest version. It should also update the package.json version numbers. And also either modify files, like we had to do in the prepend entry in aurelia.json for the cli 0.25.0 upgrade, or emit instructions.

**Comment by JeroenVinke** [comment]
@cosmoKenney thanks for the info.

> For instance, lots of people were having problems yesterday with npm install aurelia-cli@latest. It was installing the broken 0.26.1.

Since 0.26.1 is the current version of the CLI, could you elaborate on what is broken?

**Comment by JeroenVinke** [comment]
Lets continue in https://github.com/aurelia/cli/issues/231 where some more ideas were shared as well
