### ISSUE TITLE
npm install aurelia-cli -g installs 26 not 25 and neither 25 nor 26 are working on Ubuntu

### ISSUE THREAD

**Issue by TonySpegel** [aurelia/cli#527]
**I'm submitting a bug report**

* **Library Version:**
25.0.0  
26.0.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04 LTS)

* **Node Version:**
4.2.6

* **NPM Version:**
3.10.9

**Current behavior:**
- After using npm install aurelia-cli -g it installed, 0.26.0 not 0.25.0 (I had 0.24.0 before and thought it will install 0.25.0 as it was [mentioned](http://blog.aurelia.io/2017/03/07/early-march-mega-release/) as the latest version
- I'm not able to use any 'au'-commands
- when installing either 0.25.0 or 0.26.0 globally and running for example 'au -v', I'm getting this:

```
au -v
/usr/local/lib/node_modules/aurelia-cli/lib/file-system.js:70
exports.join = function(...segments) {
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/aurelia-cli/lib/cli.js:4:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

- In both cases I did used a fresh install by using ```npm uninstall aurelia-cli@0.25.0 -g```

**Expected/desired behavior:**
- Being able to use any 'au'-commands at all
- Installing Version 0.25.0 while using npm install aurelia-cli -g (why am I on a different release channel?)

Thanks for helping me

**Comment by EisenbergEffect** [comment]
This looks like a node version issue. @JeroenVinke Thoughts?

**Comment by AshleyGrant** [comment]
Are we still supporting Node v4? I thought our support policy for Node is to support the current Node LTS release (6.x). I just checked Node's own LTS policy, it looks like Node 4 enters maintenance mode on April 1, 2017 (beginning of next month). 

Given that the CLI is still in Alpha, I'm of the mind that we should only support the current Node LTS release, not the older one.

Thoughts?

**Comment by JeroenVinke** [comment]
Take a look at [this page](http://node.green/).. Node v6 is quite a lot better.

**Comment by AStoker** [comment]
@TonySpegel, you _will_ get that issue if you're not running higher than node 5 (pretty sure it needs to be the LTS or greater, or at least around 6). Something about being able to use ES6 features (like the `...` spread operator).  
Upgrade your node version first. _Then_, try these following commands (exactly, just copy paste) to ensure that you've cleaned and re-installed the latest aurelia cli
`npm uninstall -g aurelia-cli au`
`npm cache clean`
`npm install -g aurelia-cli`

**Comment by adamskopl** [comment]
(just want to inform, that @AStoker 's comment works)

**Comment by AStoker** [comment]
I'm going to go ahead and close this issue for now, as the CLI has needed to be running >=6 for a while. If we need to support previous versions, let's make that a separate issue.
