### ISSUE TITLE
cli build issue

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/cli#528]
Hi experts.  This is more a question/request for help than an issue with the cli.

I have performed a build using `au build --env prod`, however, when I run my application I am getting a couple of errors; namely
`GET http://localhost:8080/node_modules/font-awesome/css/font-awesome.min.css
GET http://localhost:8080/styles/styles.css 
Uncaught SyntaxError: Invalid left-hand side in for-loop`

I can overcome the second error by copying over the folder to the web site as well, but I thought everything was supposed to be bundled up.

This works fine using `au run --watch`.

Does anyone have any ideas what I am doing incorrectly?

Thanking you all in advance

**Comment by JeroenVinke** [comment]
Hey @stuartbloom 

It seems that there are multiple issues with some of the last releases of uglify-js. Take a look at [my comment](https://github.com/aurelia/cli/issues/524#issuecomment-284862285). I recommend locking the version of uglify-js to 2.8.5 until we can get in touch with the uglify-js folks.

**Comment by stuartbloom** [comment]
Thanks @JeroenVinke 

So are you saying i need to `npm uninstall uglify-js` and then `npm install uglify-js@2.8.7`?

**Comment by JeroenVinke** [comment]
I think that `npm install uglify-js@2.8.5` should do the trick

**Comment by stuartbloom** [comment]
thanks, got an eye test now, will try when I get back and let you know 👍

**Comment by stuartbloom** [comment]
@JeroenVinke that works fine; just need to figure out how to the the font-awesome and styles.css included in the bundle :(

**Comment by stuartbloom** [comment]
again, thankyou @JeroenVinke , all working now :)
