### ISSUE TITLE
au install should also set up a package's dependencies in the aurelia.json file

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/cli#530]
**I'm submitting a feature request**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When installing an npm package that has dependencies, those dependencies are not properly set up by the aurelia cli in `aurelia.json`.

* **What is the expected behavior?**
Running `au install` should properly the entire dependency tree for a package to the aurelia.json file based on reading the `"dependencies"` section of a package's `package.json` file.

* **What is the motivation / use case for changing the behavior?**
Make Aurelia great again.

**Comment by JeroenVinke** [comment]
[This SO post](http://stackoverflow.com/questions/42656021/error-from-aurelia-cli-command-au-run-watch-when-importing-3rd-party-library) is quite a good example of what can be improved

**Comment by JeroenVinke** [comment]
I have seen this issue quite a lot. We can certainly modify `au install` to have it add sub dependencies to the aurelia.json file as well. This would make the aurelia.json file larger though.

@AStoker shouldn't subdependencies be traced already? Take [this require statement](https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L1) for example  Shouldn't the build step trace this require statement and pull `raf` into the bundle?

**Comment by fabioluz** [comment]
@JeroenVinke I've always had to add sub dependencies to aurelia.json. Based on my experience as CLI user, I don't think the current tracing algorithm automatically pulls dependencies into the bundle. Take aurelia-i18n for example, we currently have to add `i18next` to aurelia.json. 

This enhancement would allow the improvement of `aurelia-i18n` installation. I am right @zewa666 ?

**Comment by zewa666** [comment]
Yes that should be doable and I even had an example of autofixing the deps section of Aurelia.json. will try to dig it up

**Comment by zewa666** [comment]
ahh now I remember why I left the script abandoned, its the same like this issue here https://github.com/aurelia/cli/issues/533 where we would be forced to second guess where the location of the umd/amd compatible build artifacts is. Honestly I really have no idea how to make this universally work. As long as we could expect the build folder to be named `dist` we could try to locate either `amd` or `umd` and take either the `[package-name`].js` or `index.js` as the `main` property. But those are a lot of ifs.

The targeted section in CLI would be this:
https://github.com/aurelia/cli/blob/master/lib/importer/package.js

**Comment by AshleyGrant** [comment]
We're never gonna be able to make it universally work.

That's okay though. Plenty of people are happy with JSPM and it doesn't universally work.

**Comment by AStoker** [comment]
☝️ https://github.com/aurelia/cli/issues/530#issuecomment-285127835
@JeroenVinke, the tracing might trace dependencies to pull in what it needs, but to create the appropriate loader config, I'm pretty sure we need to have a properly defined `aurelia.json` file, which means we should probably be loading up our `dependencies` into the json file when we run the install command.

**Comment by JeroenVinke** [comment]
A good test case for this is https://github.com/aurelia/cli/issues/579#issuecomment-292660994

**Comment by jwx** [comment]
I'm working on a PR for this.

**Comment by jamesond** [comment]
What is the work around on this? Do we included sub dependencies like regular ones?

**Comment by JeroenVinke** [comment]
@jamesond that's the way to go

**Comment by f3lang** [comment]
I'll go and pick this up, since this is quite a drawback in using 3rd party modules. Usually there is a chain of dependencies in almost any npm package. Some get quite big and it is very time consuming and annoying to resolve and include them manually.

@jwx do you have a WIP on this?

**Comment by AshleyGrant** [comment]
I've been using the CLI with webpack recently, and I have to say I enjoy not having to configure this stuff. I'm excited to see what you all create to solve this though!

**Comment by jwx** [comment]
I thought this would become less relevant once webpack was supported by the CLI so I've got to admit I stopped working on my PR before it was finished. Is this still wanted? If so, I could pick up the work again.

**Comment by Alexander-Taran** [comment]
I think there was an import command introduced.. and install calls import by default.
Maybe can be closed

**Comment by huochunpeng** [comment]
This is irrelevant now because `au import` and `au install` commands were removed in v1 beta.

**Comment by Alexander-Taran** [comment]
Can be closed then?
