### ISSUE TITLE
Either documentation or CLI precludes a successful .Net Core based application

### ISSUE THREAD

**Issue by MarkStega** [aurelia/cli#531]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.5.0

* **NPM Version:**
4.3.0

* **Browser:**
Chrome 56.0.2924.87 | Firefox 51.0.1

* **Language:**
TypeScript 2.2.1

**Current behavior:**

If you follow the CLI documentation to produce an ASP.Net Core based Aurelia project the resulting Aurelia application is not properly served.

**Expected/desired behavior:**

Expect to see "Hello World" when browsing to localhost:9001

**If the current behavior is a bug, please provide the steps to reproduce.**

* Use VS2017 to create an ASP.Net Core Web Application (I also chose Web API as the variant)
* Add "[TypeScriptCompileBlocked]true[/TypeScriptCompileBlocked]" to the PropertyGroup the the project's .csproj file using less than/greater than delimiters(Note that the CLI documentation doesn't have the closing tag on the directions for adding and still references .xproj)
* Use "AU new --here" to create the Aurelia application
* Use "AU run --watch"
* Browse to 'localhost:9001'
* Observe this in the browser window: "Cannot GET /"
* If you create a 'standard web application (ie, not a .Net Core based app) then you see appropriate output

**What is the expected behavior?**
Expect to see "Hello world!"

**What is the motivation / use case for changing the behavior?**
Need to be able to create cooperating .Net Core App and Aurelia App

**Comment by EisenbergEffect** [comment]
@AshleyGrant Can you look into this?

**Comment by chaskim** [comment]
In `run.ts`, the `baseDir` entry needs to be changed from `'.'`to `'./wwwroot'` for a .NET Core app. 

Like this:

`baseDir: ['./wwwroot']`

Tested with CLI 0.26.1.

**Comment by AshleyGrant** [comment]
It'll be next week before I can look at it. I'm going to be taking a few days off after South Florida Code Camp.

**Comment by MarkStega** [comment]
@chaskim has the correct fix; Now is it a documentation or CLI enhancement that is needed?

**Comment by JeroenVinke** [comment]
A CLI enhancement seems best I think. When you select "ASP.NET Core" in the wizard you should get a working project, if that is not the case we should fix it in the CLI.

One way to solve this would be to add a new property to the aurelia.json for this (in the platform section seems best). If you add one around [here](https://github.com/aurelia/cli/blob/a88bbf19754f146320ebf50a6d5d1d4e98822e94/lib/commands/new/project-template.js#L260), you should be able to retrieve it from the `project ` variable in the [run task](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.ts) and use that as the baseDir. You'd have to update the [ESNext version](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.js) of the same task as well.

Does anyone want to create a PR for this change?

**Comment by chaskim** [comment]
@JeroenVinke I'd like to create a PR for this. I made the changes on my end based on your guidance and it's working okay on my local repo. I'll do some final testing with the various `au new` scenarios and will submit it as a PR very soon (most likely tomorrow).

**Comment by JamesFenton** [comment]
@MarkStega is correct about the documentation - http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/2 shows `<typescriptcompileblocked>true` instead of `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` which is very important. The markdown is correct: https://github.com/aurelia/framework/blob/master/doc/article/en-US/the-aurelia-cli.md#aspnet-core so it seems to be an issue with the docs website.

**Comment by mobilemancer** [comment]
Regarding the documentation, it refers to xproj, which now has been replaced with csproj in the latest .NET Core version.
