### ISSUE TITLE
Multiple instances of sourceMappingUrl cause issues in Edge/IE

### ISSUE THREAD

**Issue by devingoble** [aurelia/cli#532]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.3.0

* **Browser:**
Edge 25.10568.672.0/IE 11.713.10568.0/possibly others

* **Language:**
TypeScript 2.2.1

**Current behavior:**
If third party libraries contain an instance of `sourceMappingUrl`, they will be preserved in the final vendor-bundle.js file along with the one added by the CLI. Edge and IE don't seem to like having multiple instances of 'sourceMappingUrl' in a single file. I can work around it by removing the offending lines from the final bundle or from the installed library.

**Expected/desired behavior:**
* `au new` up an application.
* `npm install` something that has it's own sourcemap. `aurelia-configuration` is what messed me up.
* Build the app and take a look at vendor-bundle.js

**What is the expected behavior?**
There should only be a single `sourceMappingUrl` instance at the bottom of vendor-bundle.js

**What is the motivation / use case for changing the behavior?**
I couldn't find anywhere that says this for sure, but Jonathan Sampson in [this](http://stackoverflow.com/questions/34687049/how-to-debug-why-ms-edge-ie11-does-not-load-sourcemap) SO question seems to think it's not standard. At the very least, it would fix Edge and IE.

**Comment by AStoker** [comment]
Sourcemaps are typically saved in the form of a comment if they're being brought down into the vendor bundle. I'd imagine that when you minify your code, it would strip out those sourcemaps and therefore they wouldn't be an issue... We'd have to do some special regex to handle inlined sourcemaps (which sounds like your problem) to combine them.

**Comment by JeroenVinke** [comment]
Tracking all sourcemap related issues in https://github.com/aurelia/cli/issues/624.
