### ISSUE TITLE
Unnecessary Bluebird config in main.[js|ts]?

### ISSUE THREAD

**Issue by trydis** [aurelia/cli#534]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.2.0

* **NPM Version:**
4.1.2

* **Browser:**
N/A

* **Language:**
all

**Current behavior:**
In https://github.com/aurelia/cli/pull/505 Bluebird config was moved to prepended file.

The upgrade notes say: 
>We have removed the code for configuring Bluebird from main.[js|ts]

When i create a new project using the CLI, it still contains the config in `main.[js|ts]`, as well as prepending it.

**Expected/desired behavior:**

* **What is the expected behavior?**
I expected `main.[js|ts]` to not contain the config.

* **What is the motivation / use case for changing the behavior?**
If my understanding is correct, the config in `main.[js|ts]` is unnecessary. If not, just close this.

**Comment by fabioluz** [comment]
It seems that @AshleyGrant forgot to remove bluebird configuration from the **.ts** file 

1 day in the dungeon with no food for him 😄 

@trydis Could make a PR to correct this? What you'd have to do is the same #505 but for typescript.

**Comment by AshleyGrant** [comment]
Aww maaannnnn
