### ISSUE TITLE
Source maps broken after moving from 0.23.0 to 0.26.1

### ISSUE THREAD

**Issue by llicht** [aurelia/cli#539]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.9

* **Language:**
Typescript 2.1.6

**Previous behavior**
In 0.23.0, sources (files in src dir) were correctly loaded both when using Chrome's debugger and when using VSCode with the chrome debugger extension.

**Current behavior:**
In 0.26.1, sources are not correctly loaded when debugging - Chrome shows my sources as empty and vscode doesn't let me put breakpoints in them.

**Cause**
It looks like the source map files generated by 0.26.1 have a sourceRoot of ".." while those of 0.23.0 have a sourceRoot of "../src"
Since the generated scripts sit in "./scripts" and the sources in "./src", it makes sense to me that "../src" (the old value) would work while ".." (the new value) wouldn't.

I've checked an auto-generated 0.26.1 aurelia-cli app and it seems to have the same problem, except it embeds the sources into the source maps which makes Chrome show them anyway - but vscode breakpoints still don't work since it still can't find the sources (and having the sources embedded in the source map doesn't help with that).

**Comment by JeroenVinke** [comment]
**Sourcemap as `..`**
![image](https://cloud.githubusercontent.com/assets/2189477/23895363/bfa3cba8-08a5-11e7-8cfa-37bdb7dd10d9.png)

**Sourcemap as `../src`**
![image](https://cloud.githubusercontent.com/assets/2189477/23895359/bcd0f81a-08a5-11e7-8fe2-b9e267655fc9.png)

I believe `../src` is the correct one since the `src` folder is at the same level of `scripts` on disk

**Comment by k2s** [comment]
please fix this issue, it is critical problem

**Comment by JeroenVinke** [comment]
@k2s are you also debugging from visual code or are you having issues in chrome for example?

**Comment by BringerOD** [comment]
I have not been able to figure out how do configure VS Code debugger.

I am using the latest CLI with typescript.  

Does anyone have a launch.json example on how this should look?

Bryan

**Comment by JeroenVinke** [comment]
If you make [these changes](https://github.com/aurelia/cli/pull/584/commits/87ca276216ba5c1be09e1dba6735f5f46bfe9c87) it will fix the issue. However, I did encounter what looks to be an issue in VSCode: https://github.com/Microsoft/vscode/issues/22711
