### ISSUE TITLE
Serve in development over HTTPS not http

### ISSUE THREAD

**Issue by KernowCode** [aurelia/cli#542]
Windows 10 using Microsoft Code

How to perform 'au run --watch' over HTTPS and not http in development environment.

**Comment by KernowCode** [comment]
Answer is to add https: true to browserSync: aurelia_project/tasks/run.js

Perhaps this should be easier to find in Aurelia.io Doc HUB documentation

**Comment by JeroenVinke** [comment]
@KernowCode thanks, added this suggestion to https://github.com/aurelia/cli/issues/393
