### ISSUE TITLE
Rebuilding files that are loaded through plugins does not work as it should

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#544]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.4.0

* **NPM Version:**
4.1.1

**Current behavior:**
When you have a JSON file watcher which instructs the bundler to update JSON files whenever one changes, then the resulting moduleId of the file gets messed up.

In the first run everything is OK:
`define('text!test.json',[],function () { return '{\r\n  "foo": "bar1234"\r\n}';});`

Whenever a JSON file is changed and the bundler is instructed to update the JSON file the moduleId is incorrect:
`define('text!text!test.json.json', ['module'], function(module) { module.exports = "{\r\n  \"foo\": \"bar1234\"\r\n}"; });`

Reproduced in the [json-watch](https://github.com/JeroenVinke/aurelia-cli-296-insidesrc/tree/json-watch) branch.

**Comment by RenathoAzevedo** [comment]
Hi there, even adding this:  "**/*.{css,html,json}" to aurelia.json file, It doesn't load. if you change the name of the JSON file or put it in another folder and change the path where you're importing under --watch flag, it throws the follow error:

![selecao_021](https://cloud.githubusercontent.com/assets/16307350/23961161/d3cdd3b0-0988-11e7-9e21-34a03a2fb72a.png)

By the way, it's not related, but I'm concerned I'm using aurelia-mask, and somehow it overrided vendor-bundle.js on console log, as the above image shows. It happend after updating aurelia-cli to latest version.

**Comment by schmarre** [comment]
Any news on this issue? Having the same problem.

**Comment by JeroenVinke** [comment]
@schmarre no news yet

**Comment by 3cp** [comment]
Fixed in latest cli-bundler.
