### ISSUE TITLE
Add support for `--watch` argument on `au build` command

### ISSUE THREAD

**Issue by nawijn** [aurelia/cli#553]
**I'm submitting a feature request**
Add support for `--watch` argument on `au build` command.

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Fedora 25

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
all 

**Current behavior:**
Automatic project rebuilding is not supported for the `au build` command.

**Expected/desired behavior:**
Project is rebuild when one or more of the underlying resource files changes.

* **What is the expected behavior?**
The same behaviour as for `au run --watch`

* **What is the motivation / use case for changing the behavior?**
Automatic rebuilding of the project is very useful and increases developer productivity. Currently, in the context of the `aurelia-cli`, this behaviour is only supported when using the `node` backend. When this behaviour is also added as an option to the `au build` command, developers using other backends can also benefit.

**Comment by JeroenVinke** [comment]
This is definitely something we are going to add. Since we already have an issue tracking this feature request, lets continue there: https://github.com/aurelia/cli/issues/265
