### ISSUE TITLE
Add support to create new project non-interactively

### ISSUE THREAD

**Issue by nawijn** [aurelia/cli#557]
**I'm submitting a feature request**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Linux Fedora

* **Node Version:**
v6.10.0

* **NPM Version:**
3.10.10

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**
New Aurelia projects have to be created by answering a set of interactive questions.

**Expected/desired behavior:**
By providing one or more flags to the `au new` a new Aurelia project can be created non-interactively. 

* **What is the expected behavior?**
Given a set of defaults, a new Aurelia project can be created non-interactively where either the defaults are used or a separate flag overrides the default. For example:
`au new --non-interactive --name MyProject --transpiler babel --language typescript`

* **What is the motivation / use case for changing the behavior?**
Once a developer is past the novice stage, I believe, answering interactive questions becomes annoying. Further, when automating setting up a development environment for new projects, having the need to answer interactive questions in the process can be cumbersome. One scenario, the I use myself is that I setup a new Aurelia development environment inside a Docker container. 

The Dockerfile for this looks something like this:
```
FROM alpine:3.5

MAINTAINER Marco.Nawijn@colosso.nl
ARG PROJECT=MyProject

# Arguments that can be overruled by the --build-args commandline flag               
ARG USER=webapp                                                                      
# Mode should be one of {dev, stage, prod}                                           
ARG MODE=dev                                                                          
                                                                                     
RUN apk add --update \                                                               
    bash \                                                                           
    git \                                                                            
    nodejs \                                                                         
    && rm -rf /var/cache/apk/* \
    # Aurelia installation
    && npm install aurelia-cli -g \
    # Create group/user
    && addgroup -S ${USER} \
    && adduser -h /home/${USER} -G ${USER} -D -S ${USER}

# Switch to normal user
USER ${USER}

# Set working directory
WORKDIR /home/${USER}

RUN mkdir -p devel \
    && chown -R ${USER}:${USER}

# This does not work
RUN au new --name ${PROJECT} --transpiler babel

# This works with new versions of Aurelia CLI
RUN au install tether \
  && au install jquery \
  && au install bootstrap \
  && au install d3

# --watch flag not supported yet on the build command
CMD au build --env ${MODE} --watch
```

Because of the added support for the `au install` command, configuring project dependencies is pretty well supported in the above scenario. However creating a new project, still requires answering interactive questions. Another option could be to first create a new project and than copy resulting files into the container, however, the drawback is that everytime a new feature is added to the Aurelia CLI, you must repeat the step to first interactively create a project.

This is just one scenario, that supports the feature request, but I believe there are more. Additionally, I would really love to see the Aurelia CLI grow towards the 'only' commandline interface needed to create, configure, build and deploy applications. The first steps are already taken (adding the `au install` command).

I am more than happy to assist, but I would need some guidance into how the code is organized. I am not that experienced yet in the npm/node/aurelia/js eco-system.

**Comment by 3cp** [comment]
@EisenbergEffect this can be closed. Current cli has unattended mode.
