### ISSUE TITLE
Repo of valid aurelia.json client library entries

### ISSUE THREAD

**Issue by sp00ky** [aurelia/cli#561]
It would be nice to be able to lookup the correct aurelia.json entries for popular client libraries, rather than trying to figure them out by trial and error.  

It obviously wouldn't be comprehensive but I imagine most questions about how to configure them could be answered.

Just a thought :)

**Comment by EisenbergEffect** [comment]
Have you tried the new install feature? @JeroenVinke may have some thoughts on this and how we can further eliminate the need for you to think at all about looking up config.

**Comment by sp00ky** [comment]
I hadn't seen it until you mentioned it.  Can't wait to try it!

**Comment by Gheoan** [comment]
You could try using github search: https://github.com/search?utf8=%E2%9C%93&q=path%3Aaurelia_project+extension%3Ajson+jquery&type=Code.

**Comment by JeroenVinke** [comment]
@sp00ky yep, try out `au install <packagename>` (documentation of this feature is on the way). If it doesn't configure the package correctly in your aurelia.json, let us know so we can make the importer smarter, or (in the worst case) add a working configuration to our [configuration registry](https://github.com/aurelia/cli/tree/master/lib/importer/registry) so `au install <packagename>` will work in the future.

**Comment by JeroenVinke** [comment]
The above is the way to go for now
