### ISSUE TITLE
Ability to specify Uglify options

### ISSUE THREAD

**Issue by zedL** [aurelia/cli#562]
**I'm submitting a feature request**

* **Library Version:**
aurelia-cli@0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.7.2

* **NPM Version:**
4.3

* **Language:**
TypeScript 2.2.1

**Current behavior:**
I use uglify-js@2.8.14 and get following error when I build with `au build --env stage`
```
Writing mdl-bundle.js...
WARN: Output exceeds 32000 characters
Writing vendor-bundle.js...
```
My options in aurelia.json are
```
"options": {
      "minify": "stage & prod",
      "sourcemaps": "dev & stage",
      "rev": "prod"
    },
```
Because uglify write the warning in err output my CI build give up with an error.

With uglify-js@2.7.5 it works like expected.

Under the [Beautifier-Options](https://www.npmjs.com/package/uglify-js#beautifier-options)
is a `max-line-len` option that points to this problem.

But how can I set the uglify options when I use aurelia CLI? There is no way of doing it.
I found out that it is hard coded [here](https://github.com/aurelia/cli/blob/45255cb692d4669d7690541eed19251265401fb4/lib/build/bundle.js#L239)

**Expected/desired behavior:**
-- higher default warning level or disabled option ([set to zero](https://github.com/mishoo/UglifyJS/tree/2bc1d02363db3798d5df41fb5059a19edca9b7eb#usage))
-- ability to set uglify option

**What is the motivation / use case for changing the behavior?**
I want to use continiouse integration without warnings/errors.

**Comment by ariovistus** [comment]
for the sake of anyone stumbling on this from google, the way to turn off the warning (at least on 0.30.1 with uglifyjs 2.8.29) is

```
"options": {
  "minify": {
    "prod": {
      "output": {
        "max_line_len": 1000000
      }
    }
  }
}
```

**Comment by diegohb** [comment]
@ariovistus - thanks for summing it up.. 

replacing "stage & prod" with this object with options.. im wondering how to still enable minify for stage per the original setting "stage & prod"... I don't see anywhere in the cli code that it parses those into configured environments..

is it maybe an empty object? 
```
 "minify": {
                "prod": {
                  "output": {
                    "max_line_len": 1000000
                  }
                },
               "stage": { }
         }
```

**Comment by JeroenVinke** [comment]
@diegohb I believe you can set `"stage": false`. Documentation is written and will go out with the next release of the docs: https://github.com/aurelia/framework/blob/master/doc/article/en-US/the-aurelia-cli.md#javascript-minification.

**Comment by diegohb** [comment]
thanks! thats correct.. for reference, specs show different options: https://github.com/aurelia/cli/blob/f4862398620e8247232698e1259111046b7a09d4/spec/lib/configuration.spec.js
