### ISSUE TITLE
Ability to create separate deployable bundles and not touch source code

### ISSUE THREAD

**Issue by stevies** [aurelia/cli#563]
**Current behavior:**
When versioning is switched on -  "rev": true - the CLI bundling process modifies 
    index.html 
    /src/environment.js

(which would normally be under source control) and leaves the files in place to be manually copied for deployment. 
 
For deploying the app, the docs say:

```
Then copy the file index.html and the folder /scripts to the main deployment folder on your server.
```
  

**Desired behavior:**
Means of creating fully deployable bundles that keeps the original source code from being touched. eg 

    /dev/
    /dev/index.html
    /dev/scripts/
    /dev/scripts/app-bundle-xxxx.js
    etc...

    /prod/
    /prod/index.html
    /prod/scripts/
    /prod/scripts/app-bundle-xxxx.js 
   etc...

Nice and clean.  You just copy the output folder when deploying.  No need to revert modified files or undo the bundling.  A bit like what happens with a Webpack build.  

Assume run commands would also need to pick up from the various output directories.

**Comment by jwx** [comment]
I'm working on a PR that would also cover this. Here's what I currently have:
In aurelia.json, the `build.targets` would change from
```
    [
      {
        "id": "web",
        "displayName": "Web",
        "output": "scripts",
        "index": "index.html",
        "baseDir": ".",
        "baseUrl": "http://localhost:9000/scripts"
      }
    ]
```
to
```
    [
      {
        "id": "default",
        "root": "build",
        "output": "scripts",
        "index": "index.html",
        "baseDir": ".",
        "baseUrl": "http://localhost:9000/scripts",
        "resources": [
          "favicon.ico",
          "images/**",
          "styles/**"
        ]
      },
      {
        "id": "dev",
        "root": "build/dev"
      },
      {
        "id": "prod",
        "root": "build/prod",
        "baseUrl": "http://prod-server.domain.com/scripts"
      }
    ]
```
and so on. Would this work for you? Any comments?

**Comment by stevies** [comment]
I've not really been using Aurelia for a while, but that could be good.  

Not sure if having the prod baseURL hard-coded would be ideal - but I guess that could be overridden at build time somehow. The way I see it is that I might want to run a "production" level build locally out of localhost or on a build box just to test it works, then deploy the built bundle without touching it again.

**Comment by jwx** [comment]
@stevies The baseUrl isn't necessary (and wouldn't normally be used). I did a copy-paste from a different post that included baseUrl and forgot to remove it. Sorry for the confusion. Also, it'll most likely end up being
```
    "targets": {
      "default": {
        "root": "build",
        "output": "scripts",
        "index": "index.html",
        "baseDir": ".",
        "resources": [
          "favicon.ico",
          "images/**",
          "styles/**"
        ]
      },
      "dev": {
        "root": "build/dev"
      },
      "prod": {
        "root": "build/prod"
      }
    }
```

**Comment by stevies** [comment]
Looks good.

**Comment by jpravetz** [comment]
What are the dependencies on getting this accepted? It would be nice to clean this up. 

As well, I've been working on a way to get the build number and date into the target build. Currently I'm generating an about.json that is written into src, from where it is bundled, and of course that's not optimal. It might have been easier to write this into index.html, but I don't know of safe hooks to do that. At least with about.json, I don't need to include it in source control.

**Comment by JeroenVinke** [comment]
@jpravetz I want to make sure we're not introducing breaking changes

@jwx I wonder, how would build targets allow you to have different environment.js files per build? As I see it the `environment.js` file is imported from `main.js` which means that the `environment.js` file needs to be there during build. The distribution folders only come into play after the build has completed, right?

**Comment by stevies** [comment]
Any progress on this?

**Comment by JeroenVinke** [comment]
Not yet. We're planning on adding build targets (cordova, phonegap, electron) to the CLI. For that work we might end up changing the folder structure of the dist folder. I'll keep this issue in mind so that hopefully we can implement it together with the different build targets
