### ISSUE TITLE
issue with building.

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/cli#566]
Hi

I am able to perform an `au run` and the application works perfectly.

When i perform a `au build --env prod`, the build runs, I then copy the files to my IIS folder, but when i browse to it I am getting the following error:

![image](https://cloud.githubusercontent.com/assets/7871566/24397639/d360c142-139e-11e7-9171-fee501a58054.png)

I assume there is something missing in my aurelia.json file, but I am not sure what.

Can someone point me in the right direction?

Thanks in advance

**Comment by JeroenVinke** [comment]
Hi, could you provide the steps necessary to reproduce the issue?

**Comment by stuartbloom** [comment]
@JeroenVinke I have a project that makes use of the i18n plugin.  In my main.ts file I have this:
`import * as Backend from "i18next-xhr-backend";`.

In my aurelia.json file I also have this:
```
          {
            "name": "i18next",
            "path": "../node_modules/i18next/dist/umd",
            "main": "i18next"
          },
          {
            "name": "aurelia-i18n",
            "path": "../node_modules/aurelia-i18n/dist/amd",
            "main": "aurelia-i18n"
          },
          {
            "name": "i18next-xhr-backend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },
````

Thanks again

**Comment by stuartbloom** [comment]
as an addition, if I create a node_modules folder and then add the path and file for i18nextXHRBackend.js it works fine

**Comment by JeroenVinke** [comment]
i'm unable to reproduce the issue. After following the installation instructions of aurelia-i18n in the docs, running `au run --env prod` worked as expected. To make sure I copied everything to a `deployed_app` folder and ran `http-server` (the http-server module on NPM) in that folder, and it also worked as it should. I have pushed the app here: https://github.com/JeroenVinke/aurelia-cli-566. This is with aurelia-cli 0.27.0.

Can you please compare your setup to https://github.com/JeroenVinke/aurelia-cli-566 and provide the steps I need to take to get to the point where you're at? Also, can you fill in the [issue template](https://github.com/aurelia/cli/blob/master/ISSUE_TEMPLATE.md)?

**Comment by stuartbloom** [comment]
I have built a new application from the start and it works fine.

I must have something wrong with my current app.  I will go back and rebuild it.

Thanks for your time :)
