### ISSUE TITLE
[Request] Add to CLI : ASP.NET Core 1.1 (VS 2017 or VSCode) + Webpack 2 + Typescript 2 + Aurelia 1?

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/cli#568]
I need a simple sample that configured with ASP.NET MVC Core 1.1 + Typescript 2.2 + Webpack 2 + Aurelia 1 .

Can anyone add it to CLI as an item ? (with easywebpack and without it - pure webpack)

based on this article [Jspm vs Webpack - I Like Kill Nerds](https://ilikekillnerds.com/2015/07/jspm-vs-webpack/) I think someone prefer to use webpack 2 against jspm so it would be great if CLI support it.

**Comment by ghidello** [comment]
I read somewhere that a webpack option was in the future roadmap for the CLI. In the meantime you can check one of the [samples](https://github.com/jods4/aurelia-webpack-build/tree/master/demos/06-ASPNET) for the new [webpack plugin](https://github.com/aurelia/webpack-plugin) (currently in RC stage) which uses also some SpaServices middlewares

**Comment by JeroenVinke** [comment]
Yep, support for webpack is tracked in this issue: https://github.com/aurelia/cli/issues/260.

**Comment by HamedFathi** [comment]
@JeroenVinke 

Is there a release time for supporting webpack 2 via CLI ?

**Comment by JeroenVinke** [comment]
Not at the moment. We first need to stabilize the CLI, then put in an abstraction so we can add other loaders/bundlers and then hook webpack into that.
