### ISSUE TITLE
au install stripe - build failure

### ISSUE THREAD

**Issue by bawoodruff** [aurelia/cli#570]
**I'm submitting a bug report**
using the CLI to install stripe, results in a build failure

* **Library Version:**
aurelia-cli 0.27.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.7.0

* **NPM Version:**
3.10.7

* **Browser:**
Chrome XX 

* **Language:**
TypeScript 2.2.1

**Current behavior:**
Build fails:

Tracing stripe...
File not found or not accessible: /Users/<redacted>/src/http.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/node_modules/stripe/package.json.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/child_process.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/https.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/object-assign.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/path.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/bluebird.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/qs.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/lodash.isplainobject.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/http.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/node_modules/stripe/package.json.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/child_process.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/https.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/object-assign.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/path.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/bluebird.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/qs.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js
File not found or not accessible: /Users/<redacted>/src/lodash.isplainobject.js. Requested by /Users/<redacted>/node_modules/stripe/lib/stripe.js

**Expected/desired behavior:**
No errors during build

* **What is the motivation / use case for changing the behavior?**
Allow stripe nodejs API to be installed into an Aurelia package

**Comment by JeroenVinke** [comment]
Hi, stripe is a nodejs package meaning that it can't be used in a browser environment
