### ISSUE TITLE
AU Cli failing to install dependencies

### ISSUE THREAD

**Issue by shawty** [aurelia/cli#574]
I'm submitting a bug report

* **Library Version:**
Not sure, which lib and how do I find this out?

* **Operating System:**
Windows 7 (x64)

* **Node Version:**
6.9.4

* **NPM Version:**
4.0.5

* **Browser:**
Not Applicable (Windows command line only)

* **Language:**
all

* **Current behavior:**
au new <name>, goes through the wizard to create an app skeleton, then fails when trying to install project dependencies.

to reproduce:
    au new myapp
    select 1 (ES Next)
    select 1 (Yes)
    select 1 (Yes)

* **Expected/desired behavior:**
Wizard completes, creates project structure and successfully installs all required NPM/JSPM based dependencies needed by the new project.

* **What is the motivation / use case for changing the behavior?**
New projects can no longer be created using au cli tool, rendering it completely ineffective.

* **Additional info**
NPM install on an existing Aurelia based project, created with the au cli tool and previously working, also fails with missing NPM dependencies.

For reference, here's the entire console output:

    H:\*****************\Client Work\*******>au new foolish
                          _ _          ____ _     ___
      __ _ _   _ _ __ ___| (_) __ _   / ___| |   |_ _|
     / _` | | | | '__/ _ \ | |/ _` | | |   | |    | |
    | (_| | |_| | | |  __/ | | (_| | | |___| |___ | |
     \__,_|\__,_|_|  \___|_|_|\__,_|  \____|_____|___|
    
    
    Would you like to use the default setup or customize your choices?
    
    1. Default ESNext (Default)
       A basic web-oriented setup with Babel for modern JavaScript development.
    2. Default TypeScript
       A basic web-oriented setup with TypeScript for modern JavaScript development.
    3. Custom
       Select transpilers, CSS pre-processors and more.
    
    [Default ESNext]> 2
    
    Project Configuration
    
        Name: foolish
        Platform: Web
        Transpiler: TypeScript
        Markup Processor: Minimal Minification
        CSS Processor: None
        Unit Test Runner: Karma
        Editor: Visual Studio Code
    
    
    Would you like to create this project?
    
    1. Yes (Default)
       Creates the project structure based on your selections.
    2. Restart
       Restarts the wizard, allowing you to make different selections.
    3. Abort
       Aborts the new project wizard.
    
    [Yes]> 1
    Project structure created and configured.
    
    Would you like to install the project dependencies?
    
    1. Yes (Default)
       Installs all server, client and tooling dependencies needed to build the project.
    2. No
       Completes the new project wizard without installing dependencies.
    
    [Yes]> 1
    
    Installing project dependencies.
    (node:7904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: no such package available : @gulp-sourcemaps/map-sources
    
    H:\*****************\Client Work\*******>dir
     Volume in drive H is Shawty
     Volume Serial Number is 6D07-A480
    
     Directory of H:\*****************\Client Work\*******
    
    30/03/2017  16:58    <DIR>          .
    30/03/2017  16:58    <DIR>          ..
    30/03/2017  16:58    <DIR>          foolish
    01/03/2017  15:00    <DIR>          *****************
    30/03/2017  14:25    <DIR>          *****************
                   0 File(s)              0 bytes
                   5 Dir(s)  13,841,866,752 bytes free
    
    H:\*****************\Client Work\*******>cd foolish
    
    H:\*****************\Client Work\*******\foolish>dir
     Volume in drive H is Shawty
     Volume Serial Number is 6D07-A480
    
     Directory of H:\*****************\Client Work\*******\foolish
    
    30/03/2017  16:58    <DIR>          .
    30/03/2017  16:58    <DIR>          ..
    30/03/2017  16:58               264 .editorconfig
    30/03/2017  16:58                29 .gitignore
    30/03/2017  16:58    <DIR>          .vscode
    30/03/2017  16:58    <DIR>          aurelia_project
    30/03/2017  16:58    <DIR>          custom_typings
    30/03/2017  16:58             4,127 favicon.ico
    30/03/2017  16:58               229 index.html
    30/03/2017  16:58             1,326 karma.conf.js
    30/03/2017  16:58             1,336 package.json
    30/03/2017  16:58    <DIR>          src
    30/03/2017  16:58    <DIR>          test
    30/03/2017  16:58               547 tsconfig.json
    30/03/2017  16:58                22 tslint.json
    30/03/2017  16:58               332 typings.json
                   9 File(s)          8,212 bytes
                   7 Dir(s)  13,841,866,752 bytes free

**Comment by JeroenVinke** [comment]
That's strange. I have just created a new app and it installs the packages correctly. Can you clear your NPM cache and try again?

**Comment by avrahamcool** [comment]
may not be related to your problem,
but you should update to latest node and npm and try again.

**Comment by shawty** [comment]
@avrahamcool - just done that and everything *appears* to be working correctly again.

What threw me a curve ball, was the failiure on the old code base too.

I spotted it, beacuse whatever happened broke my build server build everythime it tried to do an npm install on the clean sources, so running tests confirmed the failiure on the dev machine, and also showed up when trying a new app too.

For the record, not just AU, but I managed to reproduce it on a few other CLI tools too.

I'm not going to close it right now, I want to try a few tests (Probably tomorrow now, it's getting late here) just to confirm things, then I'll report back once thier done.

**Comment by EisenbergEffect** [comment]
@shawty Thanks for looking into this. Please do report back with your finds. We're pretty curious.

**Comment by shawty** [comment]
Hi Rob,

Happy to help.  I don't contribute as much as I really should, esp to projects that grab my attention such as AU :-)  (I may write a book about it though ;-)  )

anyway....

it turns out, this:
https://www.npmjs.com/package/sinopia

was the root of all my problems.

Beacuse of the sheer number of NPM packages when doing an "npm install" each time my build server re-built things, I'd set up a machine running Ubuntu with this on, then pointed all my NPM clients to it as their NPM source, then just promptly forgotten about it.

Everything had been working fine, building etc without issue, until a couple of days ago when builds started to fail with no apparent reason, I mean just regular "let's trigger a build to make sure things are up to date builds" where no changes where checked in.

At that point, I didn't have the time to dig in deeply, and the surface issue appeared to be the "au cli" that was causing the problems.

Having the time to dig in last night, and working logically back over, after updating stuff left and center, I got to the point where the penny dropped, I re-targeted my NPM clients, and hey presto "au cli" just started to work again.

There was still a few other minor hiccups, but updating node/npm and co to the latest versions fixed that.

I don't see any changes being made to sinopia, so I don't think anything new has been committed there.  In fact there doesn't seem to have been any work on it in 2 years, and the issues for it on github are piling up, so I think it's about time I stopped using it :-)

My guess is that something changed upstream in the NPM environment that sinopia couldn't handle, and that trickled down over, ultimately manifesting itself at "au cli", and making it look like that was the problem.

anyway, as far as I'm concerned for now it's case closed, please keep up the great work you guys are doing on au, and while I'm not actively contributing, I'll definitely continue to sing it's praises.

and please do contact me outside git hub, we'd love to get you or one of the team on a lidnug live online presentation to talk about aurellia, a lot of our members have been asking about it.

Shawty

**Comment by EisenbergEffect** [comment]
Thanks for the update!

**Comment by EisenbergEffect** [comment]
What's the best way to get in contact?

**Comment by shawty** [comment]
you can contact me anumber of ways, but if it's to do with the comment I made about presentations, just drop me an email at:    peter dot shaw at lidnug dot org , or come find lidnug on Linked-in and message me.

Cheers
Shawty
