### ISSUE TITLE
Publishing to iis

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/cli#577]
Hi there, and happy Friday  

I have my application running nicely using `au run --watch`. 

Running `au build --env prod` and copying the relevant files to a separate folder and running `http-server` again works great. 

Now I want to host the application using iis. copying the files to a folder that iis is hosting (for example http://localhost:8080) I get an error:
![image](https://cloud.githubusercontent.com/assets/7871566/24543092/19ef9026-15f6-11e7-8c21-efdd9f5e6592.png)

Browsing to http://localhost:8080/index.html just gives me a white scree, no app, no error.

Googling says I should create some sort of web.config file, but I am still unable to get the app to run under iis. 

Does anyone have any pointers? 

Thanks in advance

**Comment by ghidello** [comment]
Hi, happy friday to you!
Does IIS have the permission to access a folder in your user's Documents subfolder (these subfolders by default should be accessible only to your uid)?

**Comment by stuartbloom** [comment]
@ghidello yes, it does :)

**Comment by stuartbloom** [comment]
Here is something interesting.  If I have a standard router config, the application works fine if I browse to http://localhost:8080/index.html#, however, for one reason or another, my router has the following config:

```
config.options.pushState = true;
config.options.root = "/";
config.options.hashChange = false;
```

and when I have that config I am unable to get the application to run at all

**Comment by stuartbloom** [comment]
just to let folks know, this has been resolved.  I needed to ensure the app pool for my site had its .NET CLR set to "No Managed Code"

**Comment by ttadla** [comment]
Hello All,

As I am new to Aurelia, Can any one please sent me the steps to deploy Aurelia application to IIS which is developed in Visual Studio 2017.
