### ISSUE TITLE
Sub-dependencies are only treated in their short form (no "path", "deps")

### ISSUE THREAD

**Issue by gravsten** [aurelia/cli#582]
**I'm submitting a bug report**

* **Library Version:**
0.27.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

**Current behavior:**
Some libraries have different sub-dependencies depending on their version. npm loads those older packages in a subfolder : ../node_modules/LIB/node_modules/SUBLIB/
In aurelia.json, this would mean:
{
  "name": "sublevel-pouchdb",
  "path": "../node_modules/sublevel-pouchdb/lib",
  "deps": [{
      "name": "level-codec",
      "path": "../node_modules/sublevel-pouchdb/node_modules/level-codec",
      "deps": ["buffer", "through2"],
      "main": "index"
    }]
}
But aurelia-cli in this case looks for "level-codec" in the list of dependencies, not in the above deps. As a result, this fails if there are more than 2 versions of the same library.

**Expected/desired behavior:**
The "deps" section should allow libraries in long form (with "name", "path", "deps" and "main").

Alternatively, one should be able to specify various versions of the same dependency without changing the library code: "level-codec@1.0.33" to be used for require('level-codec'), with the "path" set relative to the library.

* **What is the motivation / use case for changing the behavior?**
The current architecture fails if there are more than 2 versions of the same library with different fields for "path", "deps" and "main". In any large project, this is bound to happen.
If this isn't enough motivation, I don't know what is.

**Comment by Alexander-Taran** [comment]
Is it relevant with new bundler?
