### ISSUE TITLE
au import recepies

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/cli#586]
I've installed some libraries lately, and i've struggled with the way they should be bundled.
I've read somewhere (can't find where) that we can improve the `au import` feature over time by teaching it various package configuration.
I didn't find the appropriate place to do so, so I created this thread.
Hopefully it will grow over time.

here are some of the libraries I recently toyed with.

**Library:** `aurelia-dragula`
**Url:** https://github.com/michaelmalonenz/aurelia-dragula
**Bundle:** `vendor-bundle.js`
**Import:** no import needed
**Configuration:**
```
{
   "name": "aurelia-dragula",
   "path": "../node_modules/aurelia-dragula/dist/amd",
   "main": "index",
   "resources": [
      "dragula-and-drop.js",
      "dragula.css"
   ]
}
```

**Library:** `vis`
**Bundle:** `vendor-bundle.js`
**Url:** https://github.com/almende/vis/tree/develop
**Import:** `import vis from 'vis';`
**Require:** `<require from="vis/vis.min.css"></require>`
**Configuration:**
```
{
   "name": "vis",
   "path": "../node_modules/vis/dist",
   "main": "vis.min",
   "resources": [
      "vis.min.css"
   ]
}
```

**Comment by JeroenVinke** [comment]
Much appreciated!

**Comment by JeroenVinke** [comment]
When we find a suitable place for https://github.com/aurelia/cli/issues/393 I'll make sure to add these there as well
