### ISSUE TITLE
AMD named modules are not supported

### ISSUE THREAD

**Issue by gravsten** [aurelia/cli#587]
**I'm submitting a bug report**

* **Library Version:**
0.27.0

* **Operating System:**
Windows 8.1

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

* **Browser:**
Chrome 57

* **Language:**
TypeScript 2.2.2

**Current behavior:**
If an AMD named module is imported (with require), the result is undefined.

```
import tools = require('../lib/tools');
console.log(tools.is_browser());
```

There is no error emitted by require (on the 1st line of the above example), but obviously the remaining code fails (here on the 2nd line).

Removing the module's name (here in ../lib/tools.js) solves the problem.

**Expected/desired behavior:**
At the very least this should be documented!
aurelia-cli should also attempt to strip the module's name, or even better fully support named modules.

**What is the motivation / use case for changing the behavior?**
Make aurelia-cli work great, save us all time, help prevent baldness among devs...

**Comment by jwx** [comment]
@gravsten Do you know of a library that doesn't work according to the above?

**Comment by gravsten** [comment]
The example library I used above ('../lib/tools') was developped internally and worked fine since 2016 with Aurelia/SystemJS. The problem came to light when we switched to Aurelia/CLI.

So no, I don't know of any public, named AMD module. But it should't be too hard to take any AMD module and add a name to it.

**Comment by Alexander-Taran** [comment]
@gravsten still relevant?
If not, please close the issue..

**Comment by 3cp** [comment]
Named amd module is support, but the name has to match what requirejs expects. This normally is not an issue when the named amd module is from a npm package, for example `require("jquery")` and the jquery has a named module `define("jquery"...`.

Then you are doing relative require like `require('../lib/tools')`, the expected module name depends on the requirejs config. That could be tricky.

What you can do is to clean it up is to not using `../lib/xxx`, but map your local `lib/tools.js` folder as one npm package in `aurelia.json` dependencies.

```
{
  "name": "the-exact-named-module-name-in-lib-tools.js",
  "path": "../lib/tools.js"
},
{
  "name": "do-the-same-for-another",
  "path": "../lib/another.js"
},
```

In code, you can use `require("the-exact-named-module-name-in-lib-tools.js")` as if it's a npm package.
