### ISSUE TITLE
Static json files in dependencies breaks build

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#588]
**I'm submitting a feature request**

* **Library Version:**
0.27.0

**Please tell us about your environment:**

* **Node Version:**
all

* **NPM Version:**
all

**Current behavior:**
When a dependency uses `require('./some-json.json')`, the build produces the following error:

> Error: ENOENT: no such file or directory, open 'C:\Users\Jeroen\Downloads\test-app\src\test.json.js'

**Expected/desired behavior:**

The JSON file to be going through the JSON requirejs plugin and the build not breaking

**Comment by JeroenVinke** [comment]
This one is very tricky mainly because of https://github.com/requirejs/requirejs/issues/674. SystemJS supports this nicely because you can use `meta`:

```
meta: {
  '*.json': { loader: 'json' }
}
```

Then whenever a file with the json extension is loaded, the json loader is used. According to https://github.com/requirejs/requirejs/issues/674, RequireJS does not have such option.

This means that we have to prefix all require calls (that include an extension) with a loader plugin. E.g. `require("some-dir/my-file.json")` becomes `require("json!some-dir/my-file.json")`. This needs to be done in two places: amodrotrace and our bundler.

**Comment by JeroenVinke** [comment]
Another option: all paths that have an extension (other than .js), we set in the `paths` object we path to requirejs. So when `some-package` does `require('./my-file.json')` we set:

```
{
  "paths": {
      "some-package/my-file.json": "json!some-package/my-file.json"
  } 
}
`

**Comment by 3cp** [comment]
json is supported in latest cli-bundler without the need of mapping.
