### ISSUE TITLE
If a library in vendor-bundle has sourcemaps, then chrome gets confused about the origin of console.log's

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#592]
**I'm submitting a bug report**

* **Library Version:**
0.28.0

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
Chrome

**Current behavior:**
When using the `aurelia-mask` library (or any other library that has sourcemaps), chrome gets confused about the origin of console.log calls:

![img](https://files.gitter.im/aurelia/Discuss/pJ22/thumb/Sele__o_031.png)

At the right side you'll see `google-maps.ts` but the same can be observed for aurelia-mask.

**Expected/desired behavior:**

The origin should either be the aurelia library that is doing the logging, or `vendor-bundle.js`

**Comment by RenathoAzevedo** [comment]
The error related to aurelia-mask: https://github.com/ariovistus/aurelia-mask/issues/10

**Comment by JeroenVinke** [comment]
Tracking all sourcemap related issues in https://github.com/aurelia/cli/issues/624.
