### ISSUE TITLE
Unable to Load 'instantsearch.js' library from Algolia

### ISSUE THREAD

**Issue by dnndev** [aurelia/cli#593]
**I'm submitting a bug report**
I'm submitting this at the request of @JeroenVinke after a discussion on Gitter so it can be further researched.

* **Library Version:**
0.28.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.9.1

* **NPM Version:**
4.3.0

* **Browser:**
Google Chrome 57.0.2987.133 (64-bit)

* **Language:**
ESNext

**Current behavior:**
Aurelia does not load the instantsearch JS library from Algolia.

**Expected/desired behavior:**
I expect that if I add the correct entry in `aurelia.json` that the library can be imported and injected into a view model. Reference for the library can be found here: https://community.algolia.com/instantsearch.js/documentation/  

I am adding the following code to aurelia.json:

`...
"bundles": [
  ...
  {
    "name": "vendor-bundle.js",
    "prepend": ...
    "dependencies": [
      ...
      {
        "name": "instantsearch",
        "path": "../node_modules/instantsearch.js/dist-es5-module",
        "main": "instantsearch",
        "resources": [
          "../dist/instantsearch.css"
        ]
      }
    ]`
  ...
  }
]

I'm still new to Aurelia, so I'm still figuring how all the pieces fit together. If I'm just doing it wrong, I'd be happy to know the correct method for getting instantsearch usable in a view model.

Thanks

**Comment by Alexander-Taran** [comment]
Issue on Algolia repo was closed with recomendation to use another more generic library
