### ISSUE TITLE
babel-runtime example

### ISSUE THREAD

**Issue by simonfox** [aurelia/cli#594]
* **Library Version:**
0.27.0

* **Operating System:**
Windows 10

* **Node Version:**
6.2.1

* **NPM Version:**
4.5

* **Language:**
all 

This is a question - sorry to spam issues, but I've tried Gitter and SO (http://stackoverflow.com/questions/43243698/aurelia-cli-babel-runtime-and-async-transforms) and haven't had any bites.

I'm looking for some guidance in getting a CLI app working with `babel-runtime`. See the stackoverflow question above for detail, but basically I can't figure out what is required in the `aurelia.json` bundle dependencies definition to make it work.

**Comment by AStoker** [comment]
I wonder if this is even possible with the CLI?
First off, by transpiling on the fly on the browser, you will increase load times and lower performance as the browser needs to do the transpiling itself, instead of letting it happen at compile time. But that being said, the CLI needs to trace the code in order to build up a proper config. I'm not sure if Amodrotrace (the tracer we use) can work with straight up ES6 code.
Is that what you're trying to do? Or are you just trying to get the library installed so that you can load up other code at runtime?

**Comment by simonfox** [comment]
No I'm not trying to do runtime transpilation. I'm trying to use babel-runtime with the babel-plugin-transform-runtime plugin (see my .babelrc in the SO question).

In the update to the question I have managed to get the build to succeed with a bunch of babel-runtime and core-js dependency definitions. The problem now is at runtime things are failing and it seems to be caused by the order in which things are loaded?

**Comment by AStoker** [comment]
If you have an ordering issue of loading, then confirm the modules you're pulling in are AMD. You want to make sure your modules are able to properly tell the loader what their dependencies are.

**Comment by simonfox** [comment]
I am back on this now and have not had any success....in fact I'm now unsure whether `babel-runtime` and require-js can work at all.

Have switched to `babel-polyfill` for now. Might come back to `babel-runtime` when the aurelia cli gets systemjs support.

**Comment by AStoker** [comment]
Sorry to hear that. We're working on providing additional support for various loaders within the CLI. We'd appreciate any help the community can give!

**Comment by simonfox** [comment]
OK I decided to have one more crack at this and have found the answer....see the [stackoverflow post](http://stackoverflow.com/questions/43243698/aurelia-cli-babel-runtime-and-async-transforms) for details.

@AStoker I'd love to help with SystemJS support, but I'm only just getting used to the CLI and not sure I'd even know where to start (I'm in the middle of a migration from JSPM/SystemJS). Has there been any work started? Has the core team had any design discussions around this and is it documented anywhere public?

**Comment by simonfox** [comment]
One issue I can't get to the bottom of.....looks like there is something still up with bundle config as I'm getting the following requirejs error:
```
Uncaught Error: Mismatched anonymous define() module: function (){return __e}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (vendor-bundle.js:3952)
    at intakeDefines (vendor-bundle.js:5038)
    at vendor-bundle.js:5236
```

Haven't been able to get to the bottom of it, have created a minimal repro @ https://github.com/simonfox/aurelia-cli-issue

just needs `npm i` `au run`

**Comment by JeroenVinke** [comment]
It seems to not like [this anonymous define](https://github.com/zloirock/core-js/blob/9d7db4ad4f59323cfe87516967bc8c054927bcfa/client/core.js#L8262) of core-js. 

I think we'll have to look into using the requirejs optimizer (or something that does the equivalent) in the build, because the [website](http://requirejs.org/docs/errors.html#mismatch) says:

> If you use the loader plugins or anonymous modules (modules that call define() with no string ID) but do not use the RequireJS optimizer to combine files together, this error can occur. The optimizer knows how to name anonymous modules correctly so that they can be combined with other modules in an optimized file.

**Comment by JeroenVinke** [comment]
@simonfox i'm working on webpack integration currently, but if you'd like to work on SystemJS integration, then that would be great. Just shoot me a PM in Gitter and i'll give you some pointers

**Comment by AStoker** [comment]
@JeroenVinke, what do you think about opening up a separate issue for supporting System JS and we can collaborate there? That might open it up for others to be able to contribute as well. @simonfox, does that sound helpful?

**Comment by JeroenVinke** [comment]
@AStoker good idea, will do that!

**Comment by arabsight** [comment]
Hi, It would be nice to have an abstract loader-agnostic core, and have the implementations as plugins or something, so people can create  implementations for specific loaders.

**Comment by AStoker** [comment]
That is the goal @arabsight. Last time I was in there I was trying to take a few steps to accomplish that, but to truly be loader-agnostic requires some more work. Work that I would love to have implemented. Any help from the community is _greatly_ appreciated, as always 😄

**Comment by simonfox** [comment]
systemjs support being tracked at #198
