### ISSUE TITLE
Generators creating files in the wrong folder

### ISSUE THREAD

**Issue by ghidello** [aurelia/cli#596]
**I'm submitting a bug report**

* **Library Version:**
0.28.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.7.2

* **NPM Version:**
4.1.2

* **Browser:**
all

* **Language:**
all 

**Current behavior:**
The command `au genarate element` creates the js/html files in the folder `<root>\resources\element`. 
The same issue affects all the other generators except the **component** one

**Expected/desired behavior:**

* **Steps to reproduce**
Create a new application accepting all the defaults. Execute the command `au genarate element`: there should be a new **resources** folder at the same level of the src folder instead of being in the src folder.

* **What is the expected behavior?**
The command `au genarate element` should create the js/html files in the folder `<root>\src\resources\element`.

**Comment by aleksarias** [comment]
Experiencing the same issue on OSX
