### ISSUE TITLE
aurelia-test in Typescript build: Path module not resolved by TS

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/cli#598]
**I'm submitting a bug report**

* **Library Version:**
0.27.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.8.0

* **NPM Version:**
4.2.0

* **Language:**
TypeScript 2.3

**Current behavior:**
Running `aurelia-test` results in a runtime error because the property `join` cannot be found on `path`, which is resolved incorrectly by Typescript.

**Expected/desired behavior:**

Generate a new Typescript Aurelia project using the Aurelia CLI with "Set Up Unit Testing" set to true. Install the dependencies and run the command `aurelia test`. The command fails because `join` cannot be found on `path` in `aurelia_project/tasks/test.ts`, because the node path module is not found at build time.

* **What is the expected behavior?**
Typescript should build the testing files correctly without any module resolution issues.

* **What is the motivation / use case for changing the behavior?**
Users should be able to scaffold a fully working project in Typescript with testing included.

**Comment by jedd-ahyoung** [comment]
The quick fix on the user side is to alter line 7 in the generated `test.ts` task from `import path from 'path'` to `let path = require('path')`.

**Comment by JeroenVinke** [comment]
This got fixed in 0.28.0
