### ISSUE TITLE
0.28.0 always installs projects from a certain directory no matter which directory I am in

### ISSUE THREAD

**Issue by stephenhuey** [aurelia/cli#604]
**I'm submitting a bug report**

* **Library Version:**
0.28.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.12 

* **Node Version:**
7.9.0

* **NPM Version:**
4.2.0

* **Language:**
ESNext

**Current behavior:**
Just installed node 7.9.0 using nvm and then installed aurelia-cli 0.28.0 (I already had version 0.24 under a different version of node). I have a /code directory in my home directory on my Macbook. After changing directory into /myproject and running

`au new --here`

all the Aurelia files are outputted into /code and not /code/myproject for some reason. I tried to create a temporary directory called /code/holder and changed into that directory and ran au new without the here flag and when it asked for the project name I typed `myproject` and the funny thing is that the current directory ended up being empty but /code/myproject was populated! So the CLI is always defaulting to the /code directory for some reason, not the current directory.

* **What is the expected behavior?**
I was in the /code directory when I installed the latest CLI but I do not want the CLI to always create projects in that directory.

**Comment by JeroenVinke** [comment]
Just tried this on Windows and it uses the right directory:

![image](https://cloud.githubusercontent.com/assets/2189477/25013949/10d59a5a-2076-11e7-9e18-73a191cee827.png)

I'll have to try this on OSX

**Comment by stephenhuey** [comment]
Ok, someone on the Aurelia Gitter channel just tried installing the latest and confirmed that au new --here did not work correctly for them and they're running Windows.

**Comment by JeroenVinke** [comment]
@stephenhuey were you able to reproduce the issue?

**Comment by JeroenVinke** [comment]
Please reopen if you were
