### ISSUE TITLE
Should aurelia-cli be 1.0.0?

### ISSUE THREAD

**Issue by djensen47** [aurelia/cli#614]
I think it would be awesome if aurelia-cli could be set to version 1.x.x based on the semver definition.

It would make our lives as users a little easier to know whether or not a release is breaking. For instance, at first glance 0.28 to 0.29 does not look like a breaking change but based on the semver definition, I should treat it this way.

Thoughts?

**Comment by JeroenVinke** [comment]
We're certainly aiming for it, but it's a bit early for that I think.
