### ISSUE TITLE
Wrong aurelia-cli version for new projects?

### ISSUE THREAD

**Issue by djensen47** [aurelia/cli#615]
**I'm submitting a bug report**

* **Library Version:**
0.29.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu on WSL)

* **Node Version:**
6.10.1

* **NPM Version:**
3.10.10

* **Language:**
all | TypeScript X.X | ESNext

**Steps**
1. Create a new project
2. Open the package.json

**Current behavior:**
The version for aurelia-cli is as follows:
"aurelia-cli": "^0.27.0"

**Expected/desired behavior:**
Shouldn't the version be as follows?
"aurelia-cli": "^0.29.0"

**Comment by JeroenVinke** [comment]
Yes, https://github.com/aurelia/cli/pull/603 will make sure this happens automatically in the future.
