### ISSUE TITLE
0.29.0 html-minifier breaks inline 'less than' ( < ) comparison operator

### ISSUE THREAD

**Issue by BiggAdd** [aurelia/cli#619]
**I'm submitting a bug report**

* **Library Version:**
0.29.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.3.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Inline javascript containing a `<` breaks the html minify build step

`
    <div>${1 < 10 ? 'foo' : 'bar'}</div>
`

Javascript defined inside of an attribute tag compiles correctly.

It seems that the html-minifier node module is the culprit as bypassing this build step fixes the issue.

**Comment by JeroenVinke** [comment]
Thank you for filing this issue @BiggAdd. The changes to the first file in https://github.com/JeroenVinke/cli/commit/860bedee01dee66a183c54b200f831099fa30692 should resolve your issue

**Comment by gheoan** [comment]
Surprisingly, that is not valid HTML. Use `<div>${1 &lt 10 ? 'foo' : 'bar'}</div>` instead. The question is if we should workaround it or not.

**Comment by BiggAdd** [comment]
Its not valid HTML, but the whole point of using the ${} notation is to treat anything inside it as an expression, like ES6 template literals, so in fact ${ 1 < 10 ? ...  } should be supported. 

I've not had a chance to test it, but it looks like JeroenVinke has pushed a fix for it.

**Comment by thomas-darling** [comment]
@JeroenVinke I believe this fix breaks the bundler - please see https://github.com/aurelia/bundler/issues/163
