### ISSUE TITLE
Tests: Support for non-specified browser like angular-cli --browsers

### ISSUE THREAD

**Issue by krokofant** [aurelia/cli#628]
**I'm submitting a feature request**

* **Library Version:**
0.27.0

**Please tell us about your environment:**
* **Operating System:**
macOS Sierra

* **Node Version:**
v7.10.0

* **NPM Version:**
4.5.0

**Current behavior:**
Currently it seems like the CLI targets a specific browser. I don't find it clear how. My setup is that I'm using Chrome Canary as default but have Chrome stable installed.

Chrome stable opens by default when using `au test`.

**Desired behavior and motivation**
Something like angular-cli style `--browsers` switch to be able to open the browser of choice manually. That would make it so that I can use Chrome Canary or any other browser I currently have open and just navigate to the Karma url.

**Comment by JeroenVinke** [comment]
You should be able to modify the gulp task rather easily. In `aurelia_project/tasks/test.js` do the following:

```
let karma = done => {
  new Karma({
    configFile: path.join(__dirname, '/../../karma.conf.js'),
    singleRun: !CLIOptions.hasFlag('watch'),
    browsers: [CLIOptions.hasFlag('browser') ? CLIOptions.getFlagValue('browser') : 'Chrome']
  }, done).start();
};
```

Then you can do `au test --browser firefox` or `au test` if you want to use Chrome.
