### ISSUE TITLE
Is this still Alpha software? Update README?

### ISSUE THREAD

**Issue by netrounds-joakim** [aurelia/cli#630]
Does this big disclaimer in the README still hold:
> Note: The CLI is currently in Alpha and as such may not be suitable for use on all projects yet. In particular, projects that need to make use of extensive 3rd party libraries or Aurelia plugins may not yet work or may require extensive custom configuration or workarounds. We are in the process of addressing these issues.

I read this and immediately didn't consider using this. So if this is no longer true maybe it should be removed?

**Comment by JeroenVinke** [comment]
Even though it's getting better, it's still not very easy to configure some 3rd party libraries. So this disclaimer is still relevant.

**Comment by AStoker** [comment]
I tend to agree with @JeroenVinke. We're still trying to make this awesome, and doing so might at some point require some breaking changes (I hope it doesn't). I think it's best we leave it in alpha until we have some of our major goals taken care of (support for multiple loaders, easy configuration, pluggable build process...)

**Comment by netrounds-joakim** [comment]
Ok sounds like a good approach...

It would be good with documentation on what all the configuration that `aurelia.json` controls. And also, being able to have more fine grained control on what is added in the generated project. As a beginner getting ~100 files or whatever generated is a bit overwhelming. It would be nice to be able to get a very simple project to start with, and then be able to add things on to that once every piece is understood.

If that makes any sense

**Comment by AStoker** [comment]
The goal is for the startup CLI project to have everything you need for a reasonable startup. We don't want the kitchen sink, but we don't want you to have to download 20 other packages every time you create a new project. So there's a balance there, and if you feel the balance is off, we'd love to hear your thoughts about what could be added/removed.
