### ISSUE TITLE
fix/enhancement(cli): add bundle report flag

### ISSUE THREAD

**Issue by Anthony-Mckale** [aurelia/cli#633]
**I'm submitting a feature request**

**Current behavior:**
bundle contents are configured by aurelia json config, but the actual files concat-ed into the build are not shown 

**Expected/desired behavior:**
increase visibility of what each bundle contains 

* **What is the expected behavior?**
by adding a flag say au build --bundle-report=console 

one could have the contents of created bundles outputted in a clear fashion

eg

`
au build --bundle-report=console 
...
>> web-platform.js total size : 1910.34kb, containing 267 files
> 261.76kb (13.70%) -web-platform\node_modules\jquery\dist\jquery.js
> 194.25kb (10.17%) -web-platform\node_modules\highcharts\highcharts.js
> 177.20kb (9.28%) -web-platform\node_modules\aurelia-binding\dist\amd\aurelia-binding.js
> 155.49kb (8.14%) -web-platform\node_modules\aurelia-templating\dist\amd\aurelia-templating.js
> 125.93kb (6.59%) -web-platform\node_modules\moment\moment.js
> 116.86kb (6.12%) - undefined
> 83.34kb (4.36%) -web-platform\node_modules\owl.carousel\dist\owl.carousel.js
> 79.74kb (4.17%) -web-platform\static-assets\js\jquery-ui.js
> 71.16kb (3.73%) -web-platform\node_modules\lodash\lodash.min.js
> 68.12kb (3.57%) -web-platform\node_modules\bootstrap-sass\assets\javascripts\bootstrap.js
> 57.49kb (3.01%) -web-platform\node_modules\aurelia-router\dist\amd\aurelia-router.js
> 26.07kb (1.36%) -web-platform\node_modules\aurelia-templating-binding\dist\amd\aurelia-templating-binding.js
> 25.26kb (1.32%) -web-platform\node_modules\aurelia-polyfills\dist\amd\aurelia-polyfills.js
> 23.24kb (1.22%) -web-platform\node_modules\aurelia-dependency-injection\dist\amd\aurelia-dependency-injection.js
> 17.31kb (0.91%) -web-platform\node_modules\aurelia-framework\dist\amd\aurelia-framework.js
> 15.55kb (0.81%) - undefined
> 14.85kb (0.78%) -web-platform\node_modules\aurelia-pal-browser\dist\amd\aurelia-pal-browser.js
> 13.43kb (0.70%) -web-platform\node_modules\aurelia-route-recognizer\dist\amd\aurelia-route-recognizer.js
> 12.38kb (0.65%) - undefined
> 11.46kb (0.60%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/repeat.js
> 10.90kb (0.57%) -web-platform\node_modules\moment-parseformat\dist\moment-parseformat.js
> 9.72kb (0.51%) -web-platform\node_modules\aurelia-history-browser\dist\amd\aurelia-history-browser.js
> 8.79kb (0.46%) -web-platform/node_modules/aurelia-templating-router/dist/amd/router-view.js
> 8.56kb (0.45%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/array-repeat-strategy.js
> 8.50kb (0.44%) -web-platform\node_modules\aurelia-loader-default\dist\amd\aurelia-loader-default.js
> 7.98kb (0.42%) -web-platform\node_modules\aurelia-fetch-client\dist\amd\aurelia-fetch-client.js
> 7.57kb (0.40%) -web-platform\node_modules\aurelia-metadata\dist\amd\aurelia-metadata.js
> 7.50kb (0.39%) -web-platform\node_modules\responsive-toolkit\src\bootstrap-toolkit.js
> 6.84kb (0.36%) -web-platform\node_modules\redux\dist\redux.min.js
> 6.66kb (0.35%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/compose.js
> 6.10kb (0.32%) -web-platform\node_modules\aurelia-templating-resources\dist\amd\aurelia-templating-resources.js
> 5.93kb (0.31%) -web-platform\node_modules\aurelia-path\dist\amd\aurelia-path.js
> 5.69kb (0.30%) -web-platform\node_modules\aurelia-bootstrapper\dist\amd\aurelia-bootstrapper.js
> 5.58kb (0.29%) -web-platform\node_modules\aurelia-task-queue\dist\amd\aurelia-task-queue.js
> 5.47kb (0.29%) -web-platform/node_modules/lodash/_baseClone.js
> 4.99kb (0.26%) -web-platform/node_modules/aurelia-testing/dist/amd/component-tester.js
> 4.79kb (0.25%) -web-platform\node_modules\aurelia-loader\dist\amd\aurelia-loader.js
> 4.46kb (0.23%) -web-platform\node_modules\attrchange\attrchange.js
> 3.94kb (0.21%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/css-resource.js
> 3.88kb (0.20%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/map-repeat-strategy.js
> 3.84kb (0.20%) -web-platform/node_modules/lodash/_equalByTag.js
> 3.70kb (0.19%) -web-platform\node_modules\aurelia-event-aggregator\dist\amd\aurelia-event-aggregator.js
> 3.36kb (0.18%) -web-platform/node_modules/aurelia-templating-router/dist/amd/route-loader.js
> 3.29kb (0.17%) -web-platform/node_modules/lodash/_baseMergeDeep.js
> 3.27kb (0.17%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/set-repeat-strategy.js
> 3.18kb (0.17%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/repeat-utilities.js
> 3.16kb (0.17%) -web-platform/node_modules/lodash/_baseIsEqualDeep.js
> 3.14kb (0.16%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/if.js
> 2.95kb (0.15%) -web-platform/node_modules/lodash/_equalObjects.js
> 2.68kb (0.14%) -web-platform/node_modules/lodash/_equalArrays.js
> 2.65kb (0.14%) -web-platform\node_modules\aurelia-pal\dist\amd\aurelia-pal.js
> 2.63kb (0.14%) -web-platform/node_modules/aurelia-templating-router/dist/amd/route-href.js
> 2.62kb (0.14%) -web-platform/node_modules/lodash/_initCloneByTag.js
> 2.32kb (0.12%) -web-platform/node_modules/lodash/_baseIsTypedArray.js
> 2.28kb (0.12%) -web-platform/node_modules/lodash/memoize.js
> 2.28kb (0.12%) -web-platform\node_modules\aurelia-logging\dist\amd\aurelia-logging.js
> 2.17kb (0.11%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/focus.js
> 2.10kb (0.11%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/abstract-repeater.js
> 2.06kb (0.11%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/throttle-binding-behavior.js
> 2.06kb (0.11%) -web-platform/node_modules/lodash/_baseUniq.js
> 2.02kb (0.11%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/signal-binding-behavior.js
> 2.00kb (0.10%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/update-trigger-binding-behavior.js
> 1.98kb (0.10%) -web-platform/node_modules/lodash/_getTag.js
> 1.94kb (0.10%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/number-repeat-strategy.js
> 1.93kb (0.10%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/analyze-view-factory.js
> 1.92kb (0.10%) -web-platform/node_modules/lodash/_arrayLikeKeys.js
> 1.86kb (0.10%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/debounce-binding-behavior.js
> 1.85kb (0.10%) -web-platform/node_modules/lodash/_baseIsMatch.js
> 1.82kb (0.10%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/repeat-strategy-locator.js
> 1.77kb (0.09%) -web-platform\node_modules\aurelia-logging-console\dist\amd\aurelia-logging-console.js
> 1.76kb (0.09%) -web-platform/node_modules/lodash/isPlainObject.js
> 1.76kb (0.09%) -web-platform/node_modules/lodash/findIndex.js
> 1.75kb (0.09%) -web-platform/node_modules/aurelia-testing/dist/amd/view-spy.js
> 1.66kb (0.09%) -web-platform/node_modules/lodash/toNumber.js
> 1.62kb (0.09%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/with.js
> 1.54kb (0.08%) -web-platform/node_modules/lodash/_baseIsNative.js
> 1.50kb (0.08%) -web-platform/node_modules/lodash/groupBy.js
> 1.45kb (0.08%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/binding-mode-behaviors.js
> 1.44kb (0.08%) -web-platform/node_modules/lodash/_baseMerge.js
> 1.42kb (0.07%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/show.js
> 1.42kb (0.07%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/hide.js
> 1.39kb (0.07%) -web-platform/node_modules/aurelia-testing/dist/amd/wait.js
> 1.37kb (0.07%) -web-platform/node_modules/lodash/countBy.js
> 1.32kb (0.07%) -web-platform/node_modules/lodash/merge.js
> 1.32kb (0.07%) -web-platform/node_modules/lodash/_baseMatchesProperty.js
> 1.30kb (0.07%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/html-resource-plugin.js
> 1.28kb (0.07%) -web-platform/node_modules/lodash/_baseToString.js
> 1.23kb (0.06%) -web-platform/node_modules/lodash/_hasPath.js
> 1.22kb (0.06%) -web-platform/node_modules/lodash/_getRawTag.js
> 1.22kb (0.06%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/replaceable.js
> 1.21kb (0.06%) -web-platform/node_modules/lodash/isBuffer.js
> 1.18kb (0.06%) -web-platform/node_modules/lodash/_overRest.js
> 1.17kb (0.06%) -web-platform/node_modules/aurelia-testing/dist/amd/compile-spy.js
> 1.16kb (0.06%) -web-platform/node_modules/lodash/_copyObject.js
> 1.15kb (0.06%) -web-platform/node_modules/lodash/_createAssigner.js
> 1.14kb (0.06%) -web-platform/node_modules/lodash/_cloneBuffer.js
> 1.14kb (0.06%) -web-platform/node_modules/lodash/isArguments.js
> 1.13kb (0.06%) -web-platform/node_modules/lodash/_baseIsEqual.js
> 1.12kb (0.06%) -web-platform\node_modules\aurelia-templating-router\dist\amd\aurelia-templating-router.js
> 1.12kb (0.06%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/self-binding-behavior.js
> 1.10kb (0.06%) -web-platform/node_modules/lodash/isFunction.js
> 1.07kb (0.06%) -web-platform/node_modules/lodash/isEqual.js
> 1.06kb (0.06%) -web-platform\node_modules\aurelia-testing\dist\amd\aurelia-testing.js
> 1.05kb (0.06%) -web-platform/node_modules/lodash/_baseIteratee.js
> 1.04kb (0.05%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/sanitize-html.js
> 1.04kb (0.05%) -web-platform/node_modules/lodash/_ListCache.js
> 1.03kb (0.05%) -web-platform/node_modules/lodash/_MapCache.js
> 1.02kb (0.05%) -web-platform/node_modules/lodash/_shortOut.js
> 1.01kb (0.05%) -web-platform/node_modules/lodash/_isIterateeCall.js
> 1.00kb (0.05%) -web-platform/node_modules/lodash/_assignValue.js
> 1.00kb (0.05%) -web-platform/node_modules/lodash/keys.js
> 1.00kb (0.05%) -web-platform/node_modules/lodash/_baseKeysIn.js
> 0.99kb (0.05%) -web-platform/node_modules/lodash/_getSymbols.js
> 0.98kb (0.05%) -web-platform/node_modules/lodash/_createBaseEach.js
> 0.98kb (0.05%) -web-platform/node_modules/lodash/_isKey.js
> 0.97kb (0.05%) -web-platform/node_modules/lodash/get.js
> 0.97kb (0.05%) -web-platform/node_modules/lodash/_stackSet.js
> 0.96kb (0.05%) -web-platform/node_modules/lodash/toFinite.js
> 0.95kb (0.05%) -web-platform/node_modules/lodash/_stringToPath.js
> 0.94kb (0.05%) -web-platform/node_modules/lodash/_createAggregator.js
> 0.94kb (0.05%) -web-platform/node_modules/lodash/isArrayLike.js
> 0.93kb (0.05%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/dynamic-element.js
> 0.93kb (0.05%) -web-platform/node_modules/lodash/property.js
> 0.92kb (0.05%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/aurelia-hide-style.js
> 0.92kb (0.05%) -web-platform/node_modules/lodash/_baseGetTag.js
> 0.92kb (0.05%) -web-platform\node_modules\aurelia-history\dist\amd\aurelia-history.js
> 0.90kb (0.05%) -web-platform/node_modules/lodash/keysIn.js
> 0.90kb (0.05%) -web-platform/node_modules/lodash/_Stack.js
> 0.90kb (0.05%) -web-platform/node_modules/lodash/_getSymbolsIn.js
> 0.89kb (0.05%) -web-platform/node_modules/lodash/_Hash.js
> 0.89kb (0.05%) -web-platform/node_modules/lodash/_baseKeys.js
> 0.88kb (0.05%) -web-platform/node_modules/lodash/isLength.js
> 0.88kb (0.05%) -web-platform/node_modules/lodash/_listCacheDelete.js
> 0.87kb (0.05%) -web-platform/node_modules/lodash/eq.js
> 0.87kb (0.05%) -web-platform/node_modules/lodash/_arrayReduce.js
> 0.87kb (0.05%) -web-platform/node_modules/lodash/_hashGet.js
> 0.86kb (0.05%) -web-platform/node_modules/lodash/isArrayLikeObject.js
> 0.86kb (0.04%) -web-platform/node_modules/lodash/_nodeUtil.js
> 0.86kb (0.04%) -web-platform/node_modules/lodash/hasIn.js
> 0.86kb (0.04%) -web-platform/node_modules/lodash/_baseMatches.js
> 0.85kb (0.04%) -web-platform/node_modules/lodash/toPlainObject.js
> 0.85kb (0.04%) -web-platform/node_modules/lodash/toInteger.js
> 0.85kb (0.04%) -web-platform/node_modules/lodash/_baseGetAllKeys.js
> 0.85kb (0.04%) -web-platform/node_modules/lodash/_baseFindIndex.js
> 0.84kb (0.04%) -web-platform/node_modules/lodash/_baseAggregator.js
> 0.83kb (0.04%) -web-platform/node_modules/lodash/isTypedArray.js
> 0.81kb (0.04%) -web-platform/node_modules/lodash/isObject.js
> 0.81kb (0.04%) -web-platform/node_modules/lodash/_cloneSet.js
> 0.81kb (0.04%) -web-platform/node_modules/lodash/_cloneMap.js
> 0.79kb (0.04%) -web-platform/node_modules/lodash/_baseIndexOf.js
> 0.79kb (0.04%) -web-platform/node_modules/lodash/isSymbol.js
> 0.79kb (0.04%) -web-platform/node_modules/lodash/_apply.js
> 0.79kb (0.04%) -web-platform/node_modules/lodash/_isIndex.js
> 0.78kb (0.04%) -web-platform/node_modules/lodash/_baseCreate.js
> 0.78kb (0.04%) -web-platform/node_modules/lodash/uniq.js
> 0.77kb (0.04%) -web-platform/node_modules/lodash/cloneDeep.js
> 0.77kb (0.04%) -web-platform/node_modules/lodash/_initCloneArray.js
> 0.77kb (0.04%) -web-platform/node_modules/lodash/_baseSetToString.js
> 0.77kb (0.04%) -web-platform/node_modules/lodash/_arrayAggregator.js
> 0.76kb (0.04%) -web-platform/node_modules/lodash/_SetCache.js
> 0.73kb (0.04%) -web-platform/node_modules/lodash/_createBaseFor.js
> 0.73kb (0.04%) -web-platform/node_modules/lodash/_baseAssignValue.js
> 0.73kb (0.04%) -web-platform/node_modules/lodash/_memoizeCapped.js
> 0.72kb (0.04%) -web-platform/node_modules/lodash/_hashHas.js
> 0.72kb (0.04%) -web-platform/node_modules/lodash/_baseGet.js
> 0.72kb (0.04%) -web-platform/node_modules/lodash/_arrayFilter.js
> 0.71kb (0.04%) -web-platform/node_modules/lodash/_arrayIncludesWith.js
> 0.71kb (0.04%) -web-platform/node_modules/lodash/_castPath.js
> 0.70kb (0.04%) -web-platform/node_modules/lodash/_assignMergeValue.js
> 0.70kb (0.04%) -web-platform/node_modules/lodash/isObjectLike.js
> 0.70kb (0.04%) -web-platform/node_modules/lodash/_hashSet.js
> 0.69kb (0.04%) -web-platform/node_modules/lodash/_baseFor.js
> 0.69kb (0.04%) -web-platform/node_modules/lodash/_getMatchData.js
> 0.69kb (0.04%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/attr-binding-behavior.js
> 0.69kb (0.04%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/binding-signaler.js
> 0.69kb (0.04%) -web-platform/node_modules/lodash/_strictIndexOf.js
> 0.69kb (0.04%) -web-platform/node_modules/lodash/_baseRest.js
> 0.68kb (0.04%) -web-platform/node_modules/lodash/toString.js
> 0.68kb (0.04%) -web-platform/node_modules/lodash/_arraySome.js
> 0.67kb (0.04%) -web-platform/node_modules/lodash/_matchesStrictComparable.js
> 0.66kb (0.03%) -web-platform/node_modules/lodash/_isMasked.js
> 0.66kb (0.03%) -web-platform/node_modules/lodash/_listCacheSet.js
> 0.65kb (0.03%) -web-platform/node_modules/lodash/_objectToString.js
> 0.64kb (0.03%) -web-platform/node_modules/lodash/_toSource.js
> 0.64kb (0.03%) -web-platform/node_modules/lodash/_cloneTypedArray.js
> 0.64kb (0.03%) -web-platform/node_modules/lodash/_arrayMap.js
> 0.63kb (0.03%) -web-platform/node_modules/lodash/_arrayIncludes.js
> 0.63kb (0.03%) -web-platform/node_modules/lodash/_initCloneObject.js
> 0.63kb (0.03%) -web-platform/node_modules/lodash/_getAllKeysIn.js
> 0.62kb (0.03%) -web-platform/node_modules/lodash/_cloneSymbol.js
> 0.62kb (0.03%) -web-platform/node_modules/lodash/_arrayEach.js
> 0.62kb (0.03%) -web-platform/node_modules/lodash/_createSet.js
> 0.62kb (0.03%) -web-platform/node_modules/lodash/_cloneDataView.js
> 0.62kb (0.03%) -web-platform/node_modules/lodash/_toKey.js
> 0.61kb (0.03%) -web-platform/node_modules/lodash/_baseIsArguments.js
> 0.61kb (0.03%) -web-platform/node_modules/lodash/constant.js
> 0.60kb (0.03%) -web-platform/node_modules/lodash/_getNative.js
> 0.60kb (0.03%) -web-platform/node_modules/lodash/_baseAssignIn.js
> 0.59kb (0.03%) -web-platform/node_modules/lodash/_copySymbolsIn.js
> 0.59kb (0.03%) -web-platform/node_modules/lodash/_mapCacheSet.js
> 0.59kb (0.03%) -web-platform/node_modules/lodash/_baseTimes.js
> 0.59kb (0.03%) -web-platform/node_modules/lodash/_getAllKeys.js
> 0.59kb (0.03%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/null-repeat-strategy.js
> 0.58kb (0.03%) -web-platform/node_modules/lodash/_assocIndexOf.js
> 0.58kb (0.03%) -web-platform/node_modules/lodash/_baseAssign.js
> 0.58kb (0.03%) -web-platform/node_modules/lodash/_nativeKeysIn.js
> 0.58kb (0.03%) -web-platform/node_modules/lodash/_baseEach.js
> 0.57kb (0.03%) -web-platform/node_modules/lodash/isArray.js
> 0.57kb (0.03%) -web-platform/node_modules/lodash/_isPrototype.js
> 0.57kb (0.03%) -web-platform/node_modules/lodash/_copySymbols.js
> 0.57kb (0.03%) -web-platform/node_modules/lodash/_baseForOwn.js
> 0.56kb (0.03%) -web-platform/node_modules/lodash/_cloneArrayBuffer.js
> 0.56kb (0.03%) -web-platform/node_modules/lodash/_mapCacheDelete.js
> 0.54kb (0.03%) -web-platform/node_modules/lodash/_copyArray.js
> 0.53kb (0.03%) -web-platform/node_modules/lodash/_hashDelete.js
> 0.53kb (0.03%) -web-platform/node_modules/lodash/_cloneRegExp.js
> 0.53kb (0.03%) -web-platform/node_modules/lodash/_listCacheGet.js
> 0.52kb (0.03%) -web-platform/node_modules/lodash/_arrayPush.js
> 0.52kb (0.03%) -web-platform/node_modules/lodash/_isStrictComparable.js
> 0.52kb (0.03%) -web-platform/node_modules/lodash/_mapCacheClear.js
> 0.52kb (0.03%) -web-platform/node_modules/lodash/_isKeyable.js
> 0.52kb (0.03%) -web-platform/node_modules/lodash/_setToString.js
> 0.51kb (0.03%) -web-platform/node_modules/lodash/_setCacheAdd.js
> 0.51kb (0.03%) -web-platform/node_modules/lodash/_listCacheHas.js
> 0.51kb (0.03%) -web-platform/node_modules/aurelia-templating-resources/dist/amd/html-sanitizer.js
> 0.50kb (0.03%) -web-platform/node_modules/lodash/_getMapData.js
> 0.50kb (0.03%) -web-platform/node_modules/lodash/_basePropertyDeep.js
> 0.50kb (0.03%) -web-platform/node_modules/lodash/_stackDelete.js
> 0.49kb (0.03%) -web-platform/node_modules/lodash/_mapCacheHas.js
> 0.48kb (0.02%) -web-platform/node_modules/lodash/stubArray.js
> 0.47kb (0.02%) -web-platform/node_modules/lodash/_overArg.js
> 0.46kb (0.02%) -web-platform/node_modules/lodash/_baseHasIn.js
> 0.46kb (0.02%) -web-platform/node_modules/lodash/identity.js
> 0.46kb (0.02%) -web-platform/node_modules/lodash/_addMapEntry.js
> 0.45kb (0.02%) -web-platform/node_modules/lodash/_mapToArray.js
> 0.45kb (0.02%) -web-platform/node_modules/lodash/_baseProperty.js
> 0.44kb (0.02%) -web-platform/node_modules/lodash/_mapCacheGet.js
> 0.44kb (0.02%) -web-platform/node_modules/lodash/_setToArray.js
> 0.43kb (0.02%) -web-platform/node_modules/lodash/_cacheHas.js
> 0.42kb (0.02%) -web-platform/node_modules/lodash/_addSetEntry.js
> 0.42kb (0.02%) -web-platform/node_modules/lodash/_baseUnary.js
> 0.41kb (0.02%) -web-platform/node_modules/lodash/_getValue.js
> 0.41kb (0.02%) -web-platform/node_modules/lodash/_stackHas.js
> 0.41kb (0.02%) -web-platform/node_modules/lodash/_setCacheHas.js
> 0.40kb (0.02%) -web-platform/node_modules/lodash/_root.js
> 0.39kb (0.02%) -web-platform/node_modules/lodash/_hashClear.js
> 0.39kb (0.02%) -web-platform/node_modules/lodash/_baseIsNaN.js
> 0.37kb (0.02%) -web-platform/node_modules/lodash/stubFalse.js
> 0.36kb (0.02%) -web-platform/node_modules/lodash/_stackClear.js
> 0.36kb (0.02%) -web-platform/node_modules/lodash/_stackGet.js
> 0.34kb (0.02%) -web-platform/node_modules/lodash/_defineProperty.js
> 0.34kb (0.02%) -web-platform/node_modules/lodash/noop.js
> 0.33kb (0.02%) -web-platform/node_modules/lodash/_DataView.js
> 0.32kb (0.02%) -web-platform/node_modules/lodash/_Promise.js
> 0.32kb (0.02%) -web-platform/node_modules/lodash/_WeakMap.js
> 0.32kb (0.02%) -web-platform/node_modules/lodash/_listCacheClear.js
> 0.31kb (0.02%) -web-platform/node_modules/lodash/_nativeKeys.js
> 0.31kb (0.02%) -web-platform/node_modules/lodash/_Set.js
> 0.31kb (0.02%) -web-platform/node_modules/lodash/_Map.js
> 0.30kb (0.02%) -web-platform/node_modules/lodash/_nativeCreate.js
> 0.27kb (0.01%) -web-platform/node_modules/lodash/_getPrototype.js
> 0.27kb (0.01%) -web-platform/node_modules/lodash/_freeGlobal.js
> 0.26kb (0.01%) -web-platform/node_modules/lodash/_coreJsData.js
> 0.24kb (0.01%) -web-platform/node_modules/lodash/_Uint8Array.js
> 0.22kb (0.01%) -web-platform/node_modules/lodash/_Symbol.js
> 0.03kb (0.00%) - undefined
> 0.02kb (0.00%) -web-platform\scripts\text.js
  Writing web-platform.js...
...
`

* **What is the motivation / use case for changing the behavior?**
when building aurelia projects, they get bigger over time and it can be hard to know if all the libraries and files being included are actually necessary 

resulting in slow download time and start up time

* **Limitations**
Would imagine this would need to be pre-minifcation, so the report wouldn't be perfect

**Comment by Anthony-Mckale** [comment]
have some code to do this, will do pull request from here, once i have it cleaned up

https://github.com/Anthony-Mckale/cli-bundler-report-flag

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia/cli/pull/836 (resolve conflicts of https://github.com/aurelia/cli/pull/635) merged

can be closed
