### ISSUE TITLE
'au generate element' creating new 'resource' folder outside the src folder

### ISSUE THREAD

**Issue by TuhinAtha** [aurelia/cli#634]
I created a custom element named as 'header' using **au generate element**.
In result, a new **resource** folder has been created under the root of the project directory. (highlighted with red box)
![aurelia](https://cloud.githubusercontent.com/assets/29048460/26620762/b7aaf356-4601-11e7-9e64-b67c73383c6b.JPG)

Though we have another **resource** folder inside **src** (highlighted with green box), the generated element is not being created there.

Then I thought, if I could make the current working directory as  **src** and try. So I deleted the newly created **resource** folder, moved to **src** and ran the  'au generate element' command. Same result: i.e. a new **resource** folder has been created under the root of the project directory. (highlighted with red box)

**Comment by JeroenVinke** [comment]
Hey @TuhinAtha, thanks for reporting this issue. This has been fixed in master (https://github.com/aurelia/cli/pull/599) and will be in the next release.
