### ISSUE TITLE
Using sass files from node_modules [question]

### ISSUE THREAD

**Issue by djensen47** [aurelia/cli#641]
I'm attempting to use the Sass `scss` files from the material-components/material-components-web project. All of the scss for each of the components actually live in `node_modules/@material`. This seems to pose a problem when I'm trying to `@import` from my scss file:

```scss
$mdc-theme-primary: #3749f4;
$mdc-theme-accent: #7cb342;
$mdc-theme-background: #fff;

@import "../node_modules/@material/theme/mdc-theme";
@import "../node_modules/@material/button/mdc-button";
```

The problem is that all of the mdc scss file import relative to `node_modules`.

```
Error: File to import not found or unreadable: @material/animation/variables
       Parent style sheet: /mnt/c/Users/david/src/lxss/brewops/brewops-web/node_modules/@material/button/mdc-button.scss
        on line 17 of node_modules/@material/button/mdc-button.scss
>> @import "@material/animation/variables";
```

I've spent quite a bit of time searching github, stackoverflow, and the docs foranswers but I think I'm just missing something.

I'm going to guess this is not a bug and simply something I haven't set up properly?

**Comment by djensen47** [comment]
It looks like if I update `tasks/process-css.js` to pass the `includePaths` option with the node_modules location, then everything works.

```javascript
export default function processCSS() {
  return gulp.src(project.cssProcessor.source)
    .pipe(sourcemaps.init())
    .pipe(sass({includePaths: ["node_modules"]}).on('error', sass.logError))
    .pipe(build.bundle());
}
```

Is this the correct way of solving this?

**Comment by EisenbergEffect** [comment]
That's the way 😀

**Comment by djensen47** [comment]
Thanks!

**Comment by Graphap** [comment]
Hello mr Jensen, I was searching on Google to find my problem about path in sass within node_modules folder indeed, I found your solution useful but Ido not understand where task/proccess-css.js is!!! Is it possible to help me then?
Thank you in advance

**Comment by djensen47** [comment]
It's located in `./aurelia_project/tasks/process-css.js`
