### ISSUE TITLE
Generated resources end up in root/resources instead of src/resources

### ISSUE THREAD

**Issue by Krossmaskinen** [aurelia/cli#643]
**I'm submitting a bug report**

* **Library Version:**
0.29.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.3

* **NPM Version:**
5.0.3

* **Language:**
TypeScript

**Current behavior:**
au generate value-converter (and other resources) generates the resource in `/resources/`

**Expected/desired behavior:**

au generate value-converter should generate the resource in `/src/resources/`

* **What is the motivation / use case for changing the behavior?**
The generated resources cannot be registered from `/resources/`. At the moment I have to manually copy over the generated resources to `/src/resources/` to be able to register them and use them.

**Comment by JeroenVinke** [comment]
Hi @Krossmaskinen. Thanks for opening this bug report. A fix for this will be included in the next release.
