### ISSUE TITLE
`au new` get stuck after the first question

### ISSUE THREAD

**Issue by Lichtjaeger** [aurelia/cli#645]
**I'm submitting a bug report**

* **Library Version:**
0.30.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10 (15063)

* **Node Version:**
8.1.0

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
After answering the first question of `au new` or `au new some-name` PowerShell doesn't accept any input (including ctrl + c). Tried some other terminals, but same behaviour. It works on other machines (but other OS versions). Haven't tested on an other machine with the same Windows version.

**Comment by arabsight** [comment]
same issue, with the same node and npm versions, happened only when I updated those.

**Comment by JeroenVinke** [comment]
I can confirm this behavior with nodejs v8.1.0, but not with v7.10.0. Weird

**Comment by JeroenVinke** [comment]
Could be related to https://github.com/nodejs/node/issues/13557

**Comment by JeroenVinke** [comment]
I'd recommend to downgrade to v8.0.0 @arabsight and @Lichtjaeger

**Comment by Lichtjaeger** [comment]
Works. Thanks.

**Comment by JeroenVinke** [comment]
I'm going to reopen this for visibility, atleast for a little while

**Comment by enriqueMartinezInter** [comment]
With the new nodejs 8.1.1 version that just got released the issue is gone.
