### ISSUE TITLE
New Loader identifies errors incorrrectly

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [aurelia/cli#646]
**I'm submitting a bug report**
New loader reports incorrect failure error.  
NOTE: previous version of loader was hopelessly flawed with dealing with aws-sdk library.

* **Library Version:**
Australia CLI  0.30.0

**Please tell us about your environment:**
* **Operating System:**
Linux / Ubuntu V16

* **Node Version:**
7.10.0

* **NPM Version:**
4.2.0

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

Chrome (up to date)

* **Language:**
TypeScript 2.3.4

**Current behavior:**

Will not fully load the Amazon aws-sdk correctly.

First lines of code fail for incorrect reasons:

ex.  "var s3 = new AWS.S3();" -- run time error response "S3 is not a constructor" -- BUT type definition of "S3" directly references a constructor. 

**Expected/desired behavior:**

Code should not fail.

* **What is the motivation / use case for changing the behavior?**
Bug fix please.

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can you look into this case specifically? I think making sure that we have a solution for working with the AWS JS library is important. Thanks!

**Comment by simonfox** [comment]
How exactly are you trying to use `aws-sdk`?

It is a node.js package that happens to contain a dist that is suitable for use in the browser. Because of this `au install/import` won't get the bundle config correct.

The bundle config you need is 
```
{  
  "name": "aws-sdk",
  "main": "dist/aws-sdk.js",
  "path": "../node_modules/aws-sdk",
  "exports": "AWS"
}
```

After which you should be able to (sorry ES6, but shouldn't be much different for TS):

```
import AWS from 'aws-sdk';

let aws = new AWS.S3(); 
//OR
export class WrapAWS {
  constructor() {
    this.aws = new AWS.S3();
  }
}
```

**Comment by SolidStateLEDLighting** [comment]
Where are you getting your most excellent documentation?   I have looked all over and I can't find anything that tells me about all possible elements of the bundle config.     The "exports" portion of that config seems to be almost a duplicate function of the start of an import statement.   import AWS  or import AWS/S3 etc.   So I did not intuitively pick on the fact that I didn't have an element in that config bundle.

I see "name", "main", "path", "exports" -- are there any other fields possible?  (I do see some of this in the Au Cli doc area)

Why did you break up "../node_modules/aws-sdk" and "dist/aws-sdk.js"  --- when "dist" is part of the path?   What is this path splitting strategy?  Pros and Cons please.

Can "exports" also identify partial packages like "AWS/S3"  -- just like an import statement can?  Why is this naming in both places?   Is it required that this "exports' match the front of the import statement?

I must have put 20 hours of time in research why I couldn't get this large library imported.   I learned a lot of new things -- but I nearly chucked Aurilia in garbage this week.

I suspect that Aurelia could turn out to be a great tool - but we must have full documentation -- with advice on best practices and examples.

I went over to the Aurelia Doc Hub last week to look for "prepend" so I could understand what was going on there with the bundle -- the search box did not reveal the prepend discussion in the the Au Cli sections -- (which I found later).

BYW -- I do see more warnings and helpful information popping out of the tool (Au Cli)... that's great.

The code above worked except for "this".   Had to remove that from my ts. 

Thanks for the follow up and the helpful information.   Looks like there is no issue.

Keith

**Comment by JeroenVinke** [comment]
@SolidStateLEDLighting Sorry that you've had this experience, but I'm glad that you shared this with us. 

Possible options in the aurelia.json are scattered across the [Adding Client Libraries to Your Project](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/10) chapter, which I understand can be very impractical. I have an idea on how to improve this, for which I'll open a new issue to track the progress.

The bundler of the CLI is definitely one of things we need to improve the most, so that it's easier to configure packages. Hopefully you will see the CLI do better with each release

**Comment by SolidStateLEDLighting** [comment]
Let me give you a simple but significant example of what I need.  Examine this statement.

< name - This is the name of the library as you will import it in your JavaScript or TypeScript code. >

This is directly from your documentation.  You repeat this same statement 3 times in the import library section.

What do I need to know?
1) What is the name used for in a practical sense?   For the developer reference?  for software reference?
2) Am I arbitrarily choosing a name based on software design?  or implementation?
3) What is the scope related to the name?
4) Where is the name being used?   -> If it is not being used -- drop it from use and default to the file name internally?!?!

If you are not explicit about what name is used for -- it will be haphazardly used making a real mess later on when you want to tie some real significance to it.

The variable 'name' is not very serious -- but apply these same questions to all the other settings and you'll have some very serious answers that are worth understanding.

**Comment by Alexander-Taran** [comment]
http://aurelia.io/docs/build-systems/aurelia-cli#adding-client-libraries-to-your-project
docs are updated to reflect the meaning of fields, when adding 3d party libraries

can be closed
