### ISSUE TITLE
Unit test helpers not loaded correctly when using SystemJS

### ISSUE THREAD

**Issue by simonfox** [aurelia/cli#648]
@JeroenVinke I have found a case where `au test` will break when using SystemJS......but I also have the solution, just wanted to run past you...

If you define a module in the test folder (for example a mock) and then import that into your test, it does not get loaded (404's). e.g. add `/test/unit/helper.js` then in `app.spec.js` add `import {MyMock} from './helper';`. This is because it is not defined in the bundle, and `/base/test/unit/helper` does not resolve to anything.

All that is needed is a SystemJS package definition added to config that sets the `defaultExtension` property:

```
SystemJS.config({
  "packages": {
    "base/test": {
      "defaultExtension": "js"
    }
  }
});
```
Currently `aurelia-karma.js` has `normalizePath` and `patchRequireJS` which aren't actually used by SystemJS and this file seems like the appropriate place to add the required SystemJS config. Was thinking I could just add `aurelia-karma.system.js` and `aurelia-karma.require.js` as I did with index.html so that `au new` adds the appropriate setup.....thoughts?

**Comment by JeroenVinke** [comment]
I wonder why this isn't needed for the skeletons. Is it because of `  defaultJSExtensions: true,` ?

**Comment by simonfox** [comment]
Yes....`defaultJSExtensions` is removed in SystemJS `0.20.0`. 

However we need the ability to define by package because the amodoro bundle contains module names that do not include the extension - everything in `/src`. We still want src imports in test modules to load from bundles i.e. `import {App} from '../../src/app` so we dont want `defaultExtension` to apply to that path.

Make sense?

**Comment by JeroenVinke** [comment]
It does. Could you put together a PR?

**Comment by simonfox** [comment]
Yes, will do.
