### ISSUE TITLE
0.30.0: Template minification fails on class attribute binding using interpolation expressions

### ISSUE THREAD

**Issue by graycrow** [aurelia/cli#649]
**I'm submitting a bug report**

* **Library Version:**
0.30.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6 | Windows 8.1

* **Node Version:**
8.1.1

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
In a project created with "Minimal Minification" markup processing, `au build` throws a Parse Error at the processMarkup task if markup has attribute binding using string interpolation.

**Steps to reproduce:**
1. Create a new project using "Minimal Minification" markup processing.
2. Edit app.html and change the h1 tag in order to add attribute binding. For example, `  <h1 class="foo ${1 === 1 ? 'active' : ''} bar">${message}</h1>`
3. Build the project. It will throw an error: 
`[09:14:27] gulp-notify: [Error running Gulp] Error: Parse Error: <h1 class="foo dnoee88xo40     </h1>
</template>`. The "garbage" part of the error (dnoee88xo40) seems to be some random value and is different on every run.

* **What is the expected behavior?**
The same code had no issues in aurelia-cli 0.27.0. Binding using string interpolation example is taken from the [Aurelia Documentation](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-class-and-style/1).

* **What is the motivation / use case for changing the behavior?**
Bug report.

**Comment by JeroenVinke** [comment]
Thanks for opening the bug report. This seems to be similar to https://github.com/aurelia/cli/issues/650. Keep an eye on that one
