### ISSUE TITLE
Minification issue

### ISSUE THREAD

**Issue by tdamir** [aurelia/cli#650]
**I'm submitting a bug report**

* **Library Version:**
0.30.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.5.0

* **Language:**
TypeScript 2.3.4

**Current behavior:**
I'm using minimum minification in project and I'm getting a parse error in templates like this:
````
<span class="${isGood ? 'good' : ''}">${message}</span>
````
This is the error I'm getting:
````
gulp-notify: [Error running Gulp] Error: Parse Error: <span class="  m06eqs61u62g0jpt0qrxjemi0       </span>
````
It looks like the ignoreCustomFragments regex in process-markup.ts causes the issue. If I remove it, then everything works as expected (I didn't noticed anything unusual at least).

**Comment by JeroenVinke** [comment]
Thanks for creating the bug report. Changing `ignoreCustomFragments: [/\${.*}/g]` to `ignoreCustomFragments: [/\${.*?}/g]` in `aurelia_project/tasks/process-markup.js` seems to resolve this. I'll create a PR shortly.

**Comment by tdamir** [comment]
I can confirm that the change in regex resolves the issue. Thanks!
