### ISSUE TITLE
Integration of Aurelia with Electron

### ISSUE THREAD

**Issue by maurovitale** [aurelia/cli#664]
* **Library Version:**
major

* **Operating System:**
Ubuntu 16.04

* **Node Version:**
7.10.0

* **NPM Version:**
4.2.0

* **Language:**
ESNext

**Current behavior:**

I have tried to integrate aurelia with electron in the project generated with aurelia cli , with the following steps:

1. Create project with **au new** command
2. Install electron with **npm install electron --save-dev**
3. Extract the electron.asar with **asar extract electron.asar .** command in its folder like this 
```
electron
├── dist
│   ├── locales
│   └── resources
│       ├── browser
│       │   └── api
│       │       ├── auto-updater
│       │       └── exports
│       ├── common
│       │   └── api
│       │       └── exports
│       ├── renderer
│       │   ├── api
│       │   │   └── exports
│       │   ├── extensions
│       │   └── web-view
│       └── worker
└── test
```

now, in _'node_modules/electron/dist/resources/'_ there is the content of electron.asar package.

4. In index.html I have used the following lines : 
```
<script>
     window.nodeRequire = require;
     delete window.require;
     delete window.exports;
     delete window.module;
</script>
```
 5. In aurelia.json I have mapped the content of library that I wanna use in the application, for example: 
```
{
     "name": "ipcRenderer",
     "path": "../node_modules/electron/dist/resources/renderer/api/",
     "main": "ipc-renderer"
} 

```
6. Now I can import "ipcRenderer" in app.js 
```
const ipcRenderer = require('ipcRenderer')

export class App {

  constructor() {
      ipcRenderer.on('file-selected', function(event, filepath){
          console.log('from aurelia:' + filepath);
       });
  }
}
```

In the last step the 'file-selected' event is created in the configuration file of the main process of electron like described [here](https://electron.atom.io/docs/tutorial/quick-start/) . When this event is called the selected file is printed to the console. 

Everything works fine, the event is correctly called from the aurelia application.

**Expected/desired behavior:**

I would like to know if I have followed the correct steps to achieve this.
In my opinion, it is strange that I have to extract the .asar package to use the electron.
Is there an easy way to do It? It is possible to map the asar package without extract it?

Moreover, it's not very clear why I had to put the lines for "require" in index.html (Possible conflict?)

The desired behavior is to have the opportunity to directly generate the "aurelia electron" project from "aurelia-cli".

**Comment by JeroenVinke** [comment]
Perhaps that https://github.com/MeirionHughes/aurelia-cli-electron-app can give you some hints.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/issues/217 as well

**Comment by JeroenVinke** [comment]
closing in favor of https://github.com/aurelia/cli/issues/217
