### ISSUE TITLE
Minification removes new lines and whitespace from <pre> tags

### ISSUE THREAD

**Issue by jeremeevans** [aurelia/cli#669]
**I'm submitting a bug report**

* **Library Version:**
0.30.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.3

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
TypeScript 2.3.4

**Current behavior:**
The build removes new lines in pre tags in the templates.

**Expected/desired behavior:**

Whitespace in pre tags is preserved.

* **What is the motivation / use case for changing the behavior?**

This breaks the expected behavior of a pre tag, which is:

> The HTML `<pre>` tag is used for indicating preformatted text. The code tag surrounds the code being marked up. Browsers normally render pre text in a fixed-pitched font, with whitespace in tact, and without word wrap.

**Comment by Alexander-Taran** [comment]
no longer the case with 0.32

can be closed
