### ISSUE TITLE
aurelia-cli fails in `au new` attempting to install node-sass

### ISSUE THREAD

**Issue by dkent600** [aurelia/cli#670]
**I'm submitting a bug report**

* **Library Version:**
0.30.1 

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.2

* **NPM Version:**
5.0.4

* **Browser:**
n/a

* **Language:**
n/a

**Current behavior:**
Running `au new` produces the following error:

```
Installing project dependencies.

> node-sass@3.13.1 install C:\users\dkent\documents\projects\GitHub\daostack-frontend-aurelia\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

Finishing with:

```
Uncaught promise rejection:
{ Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\dkent\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\lib\utils\
lifecycle.js:255:16)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at ChildProcess.<anonymous> (C:\Users\dkent\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\lib\utils\
spawn.js:40:14)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  code: 'ELIFECYCLE',
  pkgid: 'node-sass@3.13.1',
  stage: 'postinstall',
  script: 'node scripts/build.js',
  pkgname: 'node-sass',
  parent: 'daostack-frontend-aurelia' }
```
**Expected/desired behavior:**
I am attaching the full interaction and output that produced this error:
[au-cli-error.txt](https://github.com/aurelia/cli/files/1112188/au-cli-error.txt)

* **What is the expected behavior?**
No such error

* **What is the motivation / use case for changing the behavior?**
Motivation is to be able to use Aurelia Cli with Sass.  It appears the script  is trying to obtain a pretty old version of sass, the version is hardwired and seems to be no longer even available.

**Comment by JeroenVinke** [comment]
This should be fixed when https://github.com/aurelia/cli/pull/660 gets merged

**Comment by dkent600** [comment]
@JeroenVinke Thanks.  I went ahead and made the changes locally to the relevant file.  Now, I wonder if you might be able to  give me a suggestion as to how I can restart the installation so that it will proceed to a successful conclusion?  Is that possible?  (Sorry, I'm new to Aurelia-cli, partly because every time I've tried it I seem to have issues with it.  Giving it another try, and hoping it will work with webpack....)

**Comment by JeroenVinke** [comment]
@dkent600 sure, try the following steps:

When you're inside the project directory:
- remove the node_modules folder entirely
- confirm that gulp-sass has the correct version in package.json
- run `npm install` again

**Comment by dkent600** [comment]
Thanks!

**Comment by JeroenVinke** [comment]
PR is merged and will be released shortly
