### ISSUE TITLE
Double `dist` folder in `aurelia.json` after package installation

### ISSUE THREAD

**Issue by nawijn** [aurelia/cli#671]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora 25)

* **Node Version:**
6.10.3

* **NPM Version:**
3.10.10

* **Browser:**
all 
* **Language:**
all

**Current behavior:**
After `au install bootstrap-v4-dev` the Bootstrap section in`aurelia` reads
`
          {
            "name": "bootstrap-v4-dev",
            "main": "js/bootstrap",
            "path": "../node_modules/bootstrap-v4-dev/dist",
            "resources": [
              "dist/css/bootstrap-grid.css",
              "dist/css/bootstrap-grid.min.css",
              "dist/css/bootstrap-reboot.css",
              "dist/css/bootstrap-reboot.min.css",
              "dist/css/bootstrap.css",
              "dist/css/bootstrap.min.css"
            ]
          }
`
When building/running the app (cleanly generated with `au new`) the compiler complains:

`Error: File not found with singular glob: /tmp/au-test/ui/node_modules/bootstrap-v4-dev/dist/dist/css/bootstrap-grid.css`
 
As you can see there the `dist` folder is appearing twice, while the actual folder structure
only has a single `dist`.

**Expected/desired behavior:**
No compilation error after a `au install bootstrap-v4-dev`

**Comment by gishmel** [comment]
This is a mistake with your including dist inside of the resources. It is using the path attribute as the base folder and of course you will get two dist folders as its requested in the resources at their beginning. Under resources you should only have them listed as "css/bootstrap-grid.css" and make them like that.

**Comment by gishmel** [comment]
Feel free to check out my latest PR on the Aurelia CLI as I believe it has solved this problem. Sorry for not understanding before that it was aurelia CLI's problem with overlapping the path with the resources path. Hopefully it can get merged in shortly. https://github.com/aurelia/cli/pull/674
