### ISSUE TITLE
Create Package.json store

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#68]
Create a service for modifying the package.json

**Comment by ahmedshuhel** [comment]
Is this a feature we are working on?

**Comment by joelcoxokc** [comment]
Yes.

**Comment by ahmedshuhel** [comment]
What is this feature all about. Could you please explain it's intent and purpose and add it in description.

**Comment by joelcoxokc** [comment]
This store basically provides a clean API for reading and writing to any json file. 

It is on the branch feat/cmd/init, Because I am using it in the init command.

Basically is allows you to load a configFile,
Modify it,

Then save it. 

```
let config = store.load('package.json');

config.settings = {};

config.save();
```

**Comment by EisenbergEffect** [comment]
Deprecated cli
