### ISSUE TITLE
Update gulp-sass dependency

### ISSUE THREAD

**Issue by zeko77** [aurelia/cli#683]
**I'm submitting a improvement request**

On new sass-based projects, gulp-sass ^2.3.2 in package.json complains about missing dependencies of its own (python 2.7, VS runtimes etc...).

Updating gulp-sass to current 3.1.0 solves problem as far as i have tried.

**Comment by JeroenVinke** [comment]
This is already fixed in master (by updating to gulp-sass@3) and will go out with the next release, which will happen very soon. Thanks for mentioning it!
