### ISSUE TITLE
favicon.ico files are all broken

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/cli#688]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
All

* **NPM Version:**
All

* **Browser:**
all
* **Language:**
all

**Current behavior:**
Did anyone notice the `favicon.ico` files are all broken?

```
./lib/resources/content/favicon.ico
./lib/resources/content/javascriptservices/wwwroot/favicon.ico
./lib/resources/img/favicon.ico 
```

I cannot view the files locally.

Browser also reports the file has error when viewing deployed app.

**Expected/desired behavior:**
Not an issue on production app, since every app will replace the default favicon. But broken file is just annoying.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by JeroenVinke** [comment]
Hey @huochunpeng.

Where is this part coming from?

> ./lib/resources/content/favicon.ico
./lib/resources/content/javascriptservices/wwwroot/favicon.ico
./lib/resources/img/favicon.ico 

Also, could you tell me what the error is that you get in the browser?

**Comment by huochunpeng** [comment]
These are the files location in cli source code. One of the favicon.ico is copied to app root directory when `au new app` creats the app.

The favicon.ico in the bootstrapped app can not be viewed in any tool.
When viewing index page in browser http://localhost:9000 , browser shows no icon even after I added `<link ref="icon" href="favicon.ico" type="image/x-icon">` to the html head.

Manual visit at http://localhost:9000/favicon.ico yields broken file. Firefox says cannot be displayed because it has errors.

**Comment by JeroenVinke** [comment]
Oh yeah, I see the error in firefox now too when I try and open the favicon. Would you like to create a PR and update the favicons with [this one](https://raw.githubusercontent.com/aurelia/skeleton-navigation/master/skeleton-esnext/favicon.ico)?

**Comment by huochunpeng** [comment]
Thanks for the invitation. But I am too lazy for a PR, not that obsessed to show my name in the git log.

It would be easier for you to just commit directly.

Need to add `<link rel="icon" type="image/x-icon" href="favicon.ico" />` to html head, it looks like html5 needs this explicitly.

**Comment by diegohb** [comment]
may consider using this: http://realfavicongenerator.net/

**Comment by JeroenVinke** [comment]
Thank you @huochunpeng and @diegohb. I have created a PR here: https://github.com/aurelia/cli/pull/691

**Comment by huochunpeng** [comment]
@JeroenVinke this issue need to be reopened.

App created by cli still has broken `favicon.ico` file. The files in cli repo are good, sadly they are not the real issue.

The real issue is
https://github.com/aurelia/cli/blob/15b1f1f6d4ee74a5a429ca90651d61b0e8d8abdf/lib/project-item.js#L145

That line then use
https://github.com/aurelia/cli/blob/15b1f1f6d4ee74a5a429ca90651d61b0e8d8abdf/lib/file-system.js#L68

To process all files in `utf8` encoding.

The result is copied `favicon.ico` is 24k in every app, which original file in cli repo is 15k.

We need another api on ProjectItem to support copying binary file which should use default encoding `null`. I will compose a PR in few days.

**Comment by huochunpeng** [comment]
@Alexander-Taran thx. I will try to refactor the code to use fs.copyFile which makes more sense.

**Comment by Alexander-Taran** [comment]
@huochunpeng while you at it, may as well check this one? 
https://github.com/aurelia/cli/issues/828

**Comment by huochunpeng** [comment]
Could not use fs.copyFile due to `fileExistsStrategy`.

**Comment by Alexander-Taran** [comment]
@JeroenVinke PR waiting to fix favicon
