### ISSUE TITLE
"Installing dependencies" not working

### ISSUE THREAD

**Issue by pmanu93** [aurelia/cli#695]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Linux Mint 17

* **Node Version:**
v8.4.0

* **NPM Version:**
5.3.0

**Current behavior:**
Aurelia-Cli hangs when installing dependencies.
It's something related to requireJS's repo, but I can't sort it out.
This is what happens at the end
![ScreenShot](https://user-images.githubusercontent.com/15691766/29411110-5e7a7d74-834b-11e7-856a-c7cbb1740178.png)

**Expected/desired behavior:**
Fetch dependencies.

Anything I can do to resolve this?

**Comment by JeroenVinke** [comment]
My Portuguese is not what it used to be, but it looks to be an issue with authenticating to github ((SSH keys maybe). I don't think that this is an issue of the CLI, you'll probably get the same error when you run `npm install` from the project directory. 

Maybe these links can help you:
- https://help.github.com/articles/error-permission-denied-publickey/
- https://stackoverflow.com/a/25884909/3922366

**Comment by JeroenVinke** [comment]
Please reopen if this is still an issue
