### ISSUE TITLE
Running the build command should delete the content of the dist folder

### ISSUE THREAD

**Issue by RomainLanz** [aurelia/cli#697]
Hey everyone!

The command `au build` should clean the `dist` folder before starting to build the application.
Actually, you are ending with a merge between your old build and the new one, this is not what you want.

**Comment by JeroenVinke** [comment]
Yeah I think this would be a good move. @RomainLanz would you like to create a PR?

**Comment by RomainLanz** [comment]
Yes but I must say I'm not quite sure where I should make the modification.

**Comment by JeroenVinke** [comment]
First you have to setup the development environment, for which instructions can be found [here](https://github.com/aurelia/cli#building).

Depending on what your solution will be you will have to update the tasks defined in the CLI, such as the [build.js](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/build.js) task. For every task there is both a js and ts version. If you're going to add a dependency then you should add it to [dependencies.json](https://github.com/aurelia/cli/blob/master/lib/dependencies.json) and add it [here](https://github.com/aurelia/cli/blob/master/lib/commands/new/buildsystems/cli/index.js#L122-L132) so the dependency gets added to the generated package.json file.

I'm not sure if we want to clean the output folder when watch mode has detected changes as the CLI only outputs changed bundles. So we need to do this before `au build` or `au run` but not when the watcher has detected changes

**Comment by Alexander-Taran** [comment]
No pull request so far
common sense -> vNext
or not

**Comment by Alexander-Taran** [comment]
@3cp looks like this is implemented

**Comment by 3cp** [comment]
Yes, it does now.
