### ISSUE TITLE
Create command "au task {taskName}" to be able to reuse existing tasks

### ISSUE THREAD

**Issue by diegohb** [aurelia/cli#698]
**Expected/desired behavior:**
au task "copy-files" --config "/aurelia_project/aurelia.json"

**What is the expected behavior?**
Would like to be able to execute gulp tasks defined (in typescript) using an aurelia-cli command. 

Would also like it to allow taking path to JS/JSON file that defines the specific configuration section/properties object it's looking for. By that I mean that maybe it's a different .json file that just has the properties for the task to run. 

With that, it'd be nice then if aurelia.json could provide a path to a config section instead of an object.. like {copyFiles: "../../sharedCopyFiles.json"} so it can be re-used. Finally, the --config param maybe could take a json object as string ... just for the extra bell & whistle.

**What is the motivation / use case for changing the behavior?**

I am trying to create a project that runs seamslessly with VS Code/Visual Studio/ and or simply command prompt w/ AU commands...   [Branch task014 in this repository](https://github.com/diegohb/samples-aurelia-vanilla_cli/tree/master-task014) shows the changes I made to enable this functionality in an asp.net MVC multi-spa project.. it's less than ideal.. it's be best to be able to proxy out to au commands where appropriate like I've done with gulpfile.js using gulp-shell.

**Comment by diegohb** [comment]
added bonus is that then devs can just add more tasks to the tasks folder in TS without having to figure out how to get gulp tasks in TS working...

**Comment by EisenbergEffect** [comment]
Have you tried just "au taskname"?

**Comment by diegohb** [comment]
@EisenbergEffect  - thanks... that makes a lot of sense!

**Comment by diegohb** [comment]
so while **au copy-files** works as expected, **au process-css** fails with undefined error..

> PS E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc> au process-css
> Starting 'processCSS'...
> { uid: 0,
>   name: 'processCSS',
>   branch: false,
>   error:
>    { TypeError: Cannot read property 'obj' of undefined
>        at Object.exports.bundle (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\node_modules\aurelia-cli\lib\build\index.js:43:17)
>        at processCSS (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\aurelia_project\tasks\process-css.ts:17:35)
>        at bound (domain.js:301:14)
>        at runBound (domain.js:314:12)
>        at asyncRunner (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\node_modules\async-done\index.js:39:18)
>        at _combinedTickCallback (internal/process/next_tick.js:131:7)
>        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
>      domain:
>       Domain {
>         domain: null,
>         _events: {},
>         _eventsCount: 0,
>         _maxListeners: undefined,
>         members: [] },
>      domainThrown: true },
>   duration: [ 0, 12415976 ],
>   time: 1503026962761 }
> { TypeError: Cannot read property 'obj' of undefined
>     at Object.exports.bundle (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\node_modules\aurelia-cli\lib\build\index.js:43:17)
>     at processCSS (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\aurelia_project\tasks\process-css.ts:17:35)
>     at bound (domain.js:301:14)
>     at runBound (domain.js:314:12)
>     at asyncRunner (E:\dev\projects\playground\dotnet-new-test1\dotnetnew-mvc\node_modules\async-done\index.js:39:18)
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
>   domain:
>    Domain {
>      domain: null,
>      _events: {},
>      _eventsCount: 0,
>      _maxListeners: undefined,
>      members: [] },
>   domainThrown: true }

any thoughts how to make this work ?

**Comment by JeroenVinke** [comment]
@diegohb process-css is meant to be called as part of the `au build` task, because the build task initializes the bundler of the CLI. The process-css task feeds CSS/SASS/LESS files into the bundler, so it expects that it has been initialized already.  What would you like to see by calling `au process-css`?

**Comment by diegohb** [comment]
@JeroenVinke - thanks for the explanation .. that makes sense.  I would've liked to be able to use process-css to compile LESS to CSS outside of the bundle for use by the rest of the web app (non SPA parts that don't reference the bundle(s)).

**Comment by AStoker** [comment]
If you don't treat CSS as a module (default behavior), then you might be able to get this behavior. You would just have to manage pulling in your CSS manually. Alternative approach that has some bloat to it is just compile your css to an outside file, but still bundle your css into your application. You'd have two files that contain your CSS, but the non SPA application would have a normal file to look at.

Another idea would be to get compiling the CSS to it's own bundle working, then whoever is trying to access CSS would just need some kind of interceptor that reads the module as text and inserts it into the head (look at RequireJS LoadCSS function).
Just some thoughts.

**Comment by diegohb** [comment]
Thanks a lot! I'm doing that now using VS17 less-compile for outside the SPAs and bundles inside the SPAs. I still need an IDE-solution for compiling using VSCode as i'm trying to ensure this dev workspace works in both IDEs.

I am next going to try to separate the bundles and look for module as text for SystemJS (not using RequireJS).

https://github.com/diegohb/samples-aurelia-vanilla_cli
