### ISSUE TITLE
Namespace 'Webpack' has no exported member 'Compiler'.

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/cli#700]
**I'm submitting a bug report**

* **Library Version:**
0.31.0

**Please tell us about your environment:**
* **Operating System:**
Windows [7|10]

* **Node Version:**
8.1.2

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
TypeScript 2.4.2

**Current behavior:**
I have problem when I call 'webpack' command.
![2017-08-19_9-41-40](https://user-images.githubusercontent.com/8418700/29483736-3fc90e80-84c3-11e7-8810-c3d983ed9363.png)

```
Namespace 'Webpack' has no exported member 'Compiler'.
Namespace 'Webpack' has no exported member 'Options'.
Namespace 'Webpack' has no exported member 'Parser'.
Namespace 'Webpack' has no exported member 'Compilation'.
Namespace 'Webpack' has no exported member 'Resolver'.
Cannot find name 'DependencyOptionsEx'.
Invalid module name in augmentation. Module 'minimatch' resolves to an untyped module at C:/.../Desktop/aunew/autest/node_modules/minimatch/minimatch.js', which cannot be augmented.
```

**Comment by searus** [comment]
@HamedFathi I managed to fix this by adding an explicit reference to the webpack type definition in tsconfig.js:
```
  ...
  "exclude": [
    "node_modules",
    "aurelia_project"
  ],
  "files":[
    "./node_modules/@types/webpack/index.d.ts"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./custom_typings/**/*.d.ts"
  ],
  ...
```

Not sure if this is the correct fix, but it works for me.

**Comment by HamedFathi** [comment]
@searus

Yes it works, I added
  "files":[
    "./node_modules/@types/webpack/index.d.ts"
  ],

to tsconfig and works 
now I hope @EisenbergEffect fix it ASAP.

but now I have another problem 

![aaaa](https://user-images.githubusercontent.com/8418700/29483997-b81b8b2c-84ca-11e7-8914-032d5f1aab0d.png)
![untitled](https://user-images.githubusercontent.com/8418700/29483986-747bbfcc-84ca-11e7-9fff-aa0e90dfa9e2.png)


when I browse localhost:5000 I have above problem !

**Comment by JeroenVinke** [comment]
Sorry guys, seems to be related to https://github.com/aurelia/webpack-plugin/issues/118. I'm looking into it now.

**Comment by JeroenVinke** [comment]
The fix mentioned by @searus (https://github.com/aurelia/cli/issues/700#issuecomment-323502939) resolves the compiler issues for me. 

@HamedFathi I've also tested this in an asp net core setup and after running `dotnet run` and going to localhost:5000 it works. Can you give me steps to reproduce? Thanks

**Comment by HamedFathi** [comment]
@JeroenVinke

1. I used latest CLI and choose SASS, WebPack, ASP.NET Core, VS Code
2. Update csproj with netcoreapp2.0 
3. dotnet restore, dotnet build
4. add @searus `s tip to tsconfig
5. execute 'webpack' command
6. dotnet run

then 

![untitled](https://user-images.githubusercontent.com/8418700/29483986-747bbfcc-84ca-11e7-9fff-aa0e90dfa9e2.png)

**Comment by shahabganji** [comment]
@HamedFathi  and @JeroenVinke would take a look at the followings : 

![invalid addresses](https://user-images.githubusercontent.com/4405518/29484716-ba7b3296-84d9-11e7-8f77-2425e58c363e.jpg)

![invalid addresses 2](https://user-images.githubusercontent.com/4405518/29484718-bd7e3f10-84d9-11e7-981b-29555f894bb0.jpg)


The src reference of index.html files do not match with what is generated in wwwroot of ASP.NET Core folder, they should refer to /dist/app.[hash].bundle.js and /dist/vendor.[hash].bundle.js
and in this case your url should also use the index.html file within the mentioned folder, the URL lokks like : ```http://localhost:5000/dist/index.html```
to eliminate such bad URLs you have to do some configs with ASP.NET Core, within its startup.cs file.

I don't have any idea why its still not useing index.cshtml file and wants to download the hashed versions of the js files while in the index.cshtml file it referenced the app.js and vendor.js.

**Comment by JeroenVinke** [comment]
@shahabganji did you also upgrade to netcoreapp2.0? I don't seem to have issues with netcoreapp1.1. Still looking into it

**Comment by shahabganji** [comment]
@JeroenVinke Yes, I've updated to netcoreapp2.0

**Comment by JeroenVinke** [comment]
@HamedFathi @shahabganji I have a feeling that netcoreapp2.0 is more strict in how it expects the structure to be. 

> I don't have any idea why its still not using index.cshtml file and wants to download the hashed versions of the js files while in the index.cshtml file it referenced the app.js and vendor.js.

Yeah it should be using the Views, which it currently does not do. There are a couple of things that would have to change:
- webpack.config.js should not output files with hashes
- in asp.net core setup we don't need it to generate an index.html from index.ejs

This setup seems to be working (with netcoreapp2.0):
[aurelia_project.zip](https://github.com/aurelia/cli/files/1236230/aurelia_project.zip)

Getting these changes in and verifying that they don't break the non-asp.net setup will take some time. I'll open an issue

**Comment by uelarn** [comment]
The fix with "./node_modules/@types/webpack/index.d.ts" under files section in tsconfig.json 
generate a new problem.

@autoinject on ts files gives this error
[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

Solution:
Replace files section with include section.

**Comment by pat841** [comment]
I was able to fix this and avoid any workaround by using "skipLibCheck: true" in my tsconfig.json.

**Comment by RicardoMoraisPOR** [comment]
> I was able to fix this and avoid any workaround by using "skipLibCheck: true" in my tsconfig.json.

this workaround also worked from my side
