### ISSUE TITLE
Require a class with dependencies from a generator

### ISSUE THREAD

**Issue by gama410** [aurelia/cli#710]
This is not a bug, just a question I can't get the answer from Google, SO nor Gitter and I've been racking my brains on it for 2 days now... 

I have a generator that receives a model class in argument and uses this class to create a basic CRUD based on its properties and decorators.
I have to require this file from the generator using an absolute path (as I understand it, it is because require considers absolute path to be either core modules or node_modules).

This works fine as long as my model file doesn't import dependencies with an absolute path (in which case it fails because it cannot find the file). All of my imports in the code base are absolute path as typescript allows me to specify the baseUrl and path compiler options (and it's much easier to maintain).

So my question is : is there a way to handle these absolute dependencies in a generator? I was thinking maybe to use my app-bundle which contains all these files precompiled but I don't see any way to use it from the generator...

Thanks for your help!

**Comment by zewa666** [comment]
There is a section paths in the file aurelia.json which can be configured to understand tsconfig style paths. Take a look at this example https://github.com/zewa666/aurelia-cli-shared-folder which makes use of that approach to import shared code. Is that what you're looking for or did I misunderstand the question?

**Comment by gama410** [comment]
Thanks for your answer! 

Unfortunately, I don't really see how I could apply this to my problem. Maybe my [SO question](https://stackoverflow.com/questions/45793124/aurelia-cli-generator-cannot-import-dependencies) will be clearer.

My problem is related to the import of code coming from my _src/_ folder by a generator. It works well if the code is imported with a relative path (which I don't mind) AND has no dependencies with an absolute path (which is a big problem for me as all the imports in the code base are absolute).

**Comment by zewa666** [comment]
Could you create a minimal example depicting the issue so we can take a better look at it?

**Comment by gama410** [comment]
Ok, I'll try to do that and put it on github. I'll notify you when it's done. Thanks!

**Comment by gama410** [comment]
I made a minimal repro that I set up in this [repository](https://github.com/gama410/aurelia-generator-repro). Using the generator called "test", you can see that it makes a require() of a file to retrieve some of its properties and generate some code. If you pass 'a' as the sole argument, it will require a class that has an absolute dependency (which is my use case) and fail with a 'file not found' error...

If the problem comes from the fact that the generator is run in a node context that is not able to recognize absolute path (as it seems to say [here](https://nodejs.org/docs/latest/api/modules.html#modules_file_modules) ) would you have an alternative idea? Maybe in a way to use the bundles?
Thanks a lot!

**Comment by zewa666** [comment]
Sorry I didn't get a chance to look at your example yet, too busy with tons of stuff. What I would have tried is to patch the require method as mentioned here near the end https://github.com/Microsoft/TypeScript/issues/9259

**Comment by gama410** [comment]
Sorry for taking so much time to answer : I had other urgent tasks to take care of before coming back to this one...
I took the option you proposed here and it worked well, thanks a lot for pointing me in that direction! I think this ticket can be closed now!
