### ISSUE TITLE
Webpack HMR Support

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/cli#716]
Is HMR now supported with Webpack 3 support?

I created a test project with VS17+aspnetcore 2.0+ webpack.  It does automatically pack on detected changes, but the changes don't show up on the browser.

I asked this question on S.O. [here](https://stackoverflow.com/questions/45829272/aurelia-hot-module-reloading-with-aspnetcore-2-0)

**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
Chrome 

* **Language:**
TypeScript 

**Current behavior:**
The webpack bundles are automatically recompiled on changes, but the changes don't propagate to the browser.

**Expected/desired behavior:**

HMR Support

* **What is the expected behavior?**
Automatic updates in the Browser without refresh

* **What is the motivation / use case for changing the behavior?**
Ease/speed of developement

**Comment by avrahamcool** [comment]
inspecting the cli code, to get it to work you should set `"hmr": true` in `aurelia.json` under `platform`.
and call `au run --hmr --watch`.

**Comment by gregoryagu** [comment]
This works for me as long as I use Chrome. Thanks very much. How to run HMR should be include be included in the docs somewhere as it's a pretty cool feature.

**Comment by gregoryagu** [comment]
I am closing this as resolved.

**Comment by mzvast** [comment]
It will do a full reload rather than do a hmr when using `au run --watch --hmr`.
So It's still broken as I can see.

**Comment by kayle** [comment]
@JeroenVinke should this be reopened for the open issue described above? or create a new issue? It's unfortunate that hmr is broken for app.html.

> edit2: I think this works when you actually use more than 1 module.
changes in the app.html only were not reflected back to the browser.

**Comment by JeroenVinke** [comment]
@kayle I believe this issue is relevant: https://github.com/aurelia/hot-module-reload/issues/9. It’s not something we can fix in the CLI so the hmr repo seems like the best place
