### ISSUE TITLE
aurelia new resets clipboard

### ISSUE THREAD

**Issue by gheoan** [aurelia/cli#722]
**I'm submitting a bug report**

* **Library Version:**
0.31.2

**Please tell us about your environment:**
* **Operating System:**
Manjaro Linux 17.0

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

**Current behavior:**

1. Copy some text.
2. `aurelia new`
3. Paste inserts nothing.

**Expected/desired behavior:**

* **What is the expected behavior?**
Pasting inserts the copied text.

* **What is the motivation / use case for changing the behavior?**
Copy and paste the project name.

**Comment by JeroenVinke** [comment]
I can't reproduce this on Windows, and i'm not sure what could cause the clipboard to get emptied. Do you have this with any other cli tools?

**Comment by JeroenVinke** [comment]
Please reopen if you have more info
