### ISSUE TITLE
Let's add the ability to automatically override defaults in a ~/.aurelia.json file

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/cli#726]
**I'm submitting a feature request**

* **Library Version:**
0.31.2

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
8.4.0

* **NPM Version:**
5.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
It is currently not possible to override the defaults for the CLI other than by running the CLI. It'd be nice to add a way to override the defaults and have them written to a `~/.aurelia.json` file that the CLI will read for future `au new` runs.

Maybe we could make it `au config`. The CLI would run through the setup process and at the end, say "would you like to write these settings to your global Aurelia CLI configuration?

* **What is the motivation / use case for changing the behavior?**
Help developers who don't use RequireJS/ESNext/CSS/etc as their default Aurelia application setup.

**Comment by Alexander-Taran** [comment]
`npx makes aurelia/v1` with parametes does just that, I think

@3cp ?

**Comment by 3cp** [comment]
This is a different idea on maintain a user defined global aurelia.json.
Let's just say we would not implement :-)
npx makes command does provide a silent mode with `-s some,option` which is probably enough.
