### ISSUE TITLE
WebPack bundler is missing nps as devDependencies

### ISSUE THREAD

**Issue by ghiscoding** [aurelia/cli#727]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

* **Browser:**
all 
* **Language:**
all

**Current behavior:**
After running `npm install` and `npm start` the console throws an error:
```bash
'nps' is not recognized as an internal or external command
```

**Expected/desired behavior:**
`npm start` should run without error

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/pull/725
