### ISSUE TITLE
Investigation on bundler missing VSCode Chrome Debugger

### ISSUE THREAD

**Issue by ghiscoding** [aurelia/cli#729]
**I'm submitting a feature request**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

* **Browser:**
Chrome

* **Language:**
all

**Current behavior:**
Not all project/bundler type include VSCode Chrome Debugger (defined by `.vscode/launch.json`)

* **What is the motivation / use case for changing the behavior?**
Have a wonderful debugging experience for project/bundler type

**Comment by ghiscoding** [comment]
This is a continuation of some discussions (with @niieani and @JeroenVinke) which started in the [Aurelia-Skeleton](https://github.com/aurelia/skeleton-navigation/issues/852#issuecomment-325028923) which basically is for having a great debugging experience if/when using VSCode (Visual Studio Code) as the editor with [https://github.com/Microsoft/vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug).

@JeroenVinke I have done my investigations on the Chrome debugger with the new `Aurelia CLI WebPack`, I created 2 different WebPack projects (ESNext & TypeScript) and both Chrome Debugger works so there's nothing to change there. However the `Aurelia CLI with RequireJS` (most probably all others as well) is completely missing the `launch.json` file required for Chrome Debugger. 

To fix `Aurelia CLI RequireJS`, by searching on how the `launch.json` is created/added by the CLI in WebPack, I found that it is done by this file [editor/vscode.js/](https://github.com/aurelia/cli/blob/56b7734bd312107dbdf3575a35ba75ca421a93dd/lib/commands/new/buildsystems/webpack/editors/vscode.js#L9) which itself link the [resources/content/launch.json](https://github.com/aurelia/cli/blob/56b7734bd312107dbdf3575a35ba75ca421a93dd/lib/resources/content/launch.json), however this file is strictly made to work with WebPack and will not work with any other CLI bundler. So I proposed to make another file with a different name, like `launch-requirejs.json` and then use it [editor/vscode](https://github.com/aurelia/cli/blob/56b7734bd312107dbdf3575a35ba75ca421a93dd/lib/commands/new/buildsystems/cli/editors/vscode.js) for CLI RequireJS. I assume we could change that file like so:

```javascript
'use strict';
const ProjectItem = require('../../../../../project-item').ProjectItem;

module.exports = function(project) {
  if (project.model.transpiler.id !== 'typescript') {
    project.addToContent(
      ProjectItem.resource('jsconfig.json', 'content/jsconfig.json')
    );
  } else {
    project.addToContent(
      ProjectItem.directory('.vscode').add(
        ProjectItem.resource('settings.json', 'content/settings.json'),
        // add the missing launch.json with a different name to avoid using the WebPack version of launch.json
        ProjectItem.resource('launch.json', 'content/launch-requirejs.json')
      )
    );
  }
};
```
and also the `launch-requirejs.json` should have the following content to make Chrome Debugger work with `Aurelia CLI with RequireJS` :
```javascript
{
  // Use IntelliSense to find out which attributes exist for node debugging
  // Use hover for the description of the existing attributes
  // For further information visit https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Chrome Debugger",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9000",
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.chrome",
      "sourceMapPathOverrides": {
        "../src/*": "${webRoot}/*"
      }
    }
  ]
}
```

**Comment by JeroenVinke** [comment]
Sounds great @ghiscoding. Different input/output filenames won't be an issue. Your help is greatly appreciated, thank you.

**Comment by ghiscoding** [comment]
@JeroenVinke did you wanted me to create a PR with what I said in my post (different names)?

**Comment by JeroenVinke** [comment]
If you could then please :)

**Comment by ghiscoding** [comment]
Ok I will after my working hours, however I don't know how to test it after. Would I leave that part to you for testing it?

**Comment by ghiscoding** [comment]
@JeroenVinke , I created a PR and left some comments in there, I also don't know how to test the PR. Are you able to do the testing?

**Comment by JeroenVinke** [comment]
@ghiscoding did you follow these steps? https://github.com/aurelia/cli#building

after you've executed `npm link` in the CLI folder, `au new` will use the forked CLI

**Comment by ghiscoding** [comment]
I did now and yes it worked. Could you please review the comment that I left in the [PR #732](https://github.com/aurelia/cli/pull/732), I'm unsure on some piece of code which it not to work with Babel projects. Thanks

**Comment by ghiscoding** [comment]
I did more changes and I am now all done with the PR #732, please review. :)
