### ISSUE TITLE
[feature-request] Handle flag parameters case insensitive

### ISSUE THREAD

**Issue by eriklieben** [aurelia/cli#737]
**I'm submitting a feature request**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.1

* **NPM Version:**
4.0.3

* **Browser:**
n.a.

* **Language:**
all

**Current behavior:**
When performing a build using the command
```
au build --env Prod
```
it seems to run a dev build ( because of the capital P).

**Expected/desired behavior:**
Perform a build for the prod environment, just like ```au build --env prod``` would do

* **What is the expected behavior?**
It would be cool if it could handle flags case insensitive.

* **What is the motivation / use case for changing the behavior?**
Just discovered that our build in TFS was setup this way and it didn't generate revisions / use cache busting. Modified it to lowercase, but it might be something other users of Aurelia experience as well. It might be more friendly to just always lowercase the params (if that is possible for all use cases).

**Comment by AStoker** [comment]
Two things.
First, in general, command line flags are typically case sensitive, so it might be good to just keep with the norm.
Second, if I remember correctly, when you have that environment flag, it's looking for an environment file that matches that exact name. Some OS's are case sensitive, so a "Prod.js" file wouldn't be the same as a "prod.js" file. Additionally, for the sake of information passing, when the environment is unable to be gathered from any command lines, it defaults to using Node's environment (default is `dev`), which is also case sensitive.
So I think that while it seems handy to be case insensitive, I wonder if that would break too far from any norms people are used to... Thoughts?

**Comment by zewa666** [comment]
What about keeping it as it is, but additionally logging a warning that the provided env could not be located and the build task falls back to dev?

**Comment by AStoker** [comment]
That sounds like a good approach.

**Comment by eriklieben** [comment]
Ah didn't know that :-) A warning sounds great to quicker see what's going wrong and give users more information about what's going on 👍 

I do wonder if only a warning enough for this specific case?

By default it is used in dev mode, so the cases where you would use this specific command is either in a production, acceptance or staging build right?

Is it a better option to halt/error the complete process in this case? So the build fails in this case? I am not sure if this is the responsibility of the CLI or the developer (there should be some other process in place to handle this, for example some integration test case that runs before the actual deployment or a manual check).

As an example when this might occur as an issue is in the following case:

- If you use a build server/ CI that automatically deploys to production using ```au build --env prod```.
- For some reason the prod.json could not be accessed / or is not available during build.
- A warning shows in the CI build log
- The deployment is build for dev (default) and is automatically deployed to a production slot.

Not sure if this is an actual use case, might depend upon how well structured your deployment process is.

Or do many CI tools halt on warnings in the command line? because as far as I know visual studio online just ignores them, it will only break the build if you thow errors in the console.

**Comment by zewa666** [comment]
That's a good point. Typically you can setup your ci, eg TFS to stop on warnings, but it's not the default. I personally wouldn't see an issue with the CLI failing if a wrong env is passed not sure though how others think about this.

**Comment by Alexander-Taran** [comment]
fail with a message.
can see it in the console.
can see it when testing build
certainly will investigate failed build

what reasons could be not to fail?
to produce a build that a user didn't ask for?

can it be closed?
or should someone come up with a PR?

**Comment by Alexander-Taran** [comment]
@eriklieben can we close this?
