### ISSUE TITLE
No webpack minification in production environment

### ISSUE THREAD

**Issue by vpanjganj** [aurelia/cli#739]
**I'm submitting a feature request**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6 Sierra

* **Node Version:**
8.3.0

* **NPM Version:**
5.3.0

* **Browser:**
all

* **Language:**
ESNext + Webpack

**Current behavior:**
HelloWorld app created by `aurelia-cli` doesn't minify the bundle on production build.

**Expected/desired behavior:**
A compressed uglified bundle as expected from a production build

I'm happy to make PR.

**Comment by AStoker** [comment]
@vpanjganj, can you provide me with your `aurelia.json` file? I'm unable to reproduce this on the same environment you're on.

**Comment by vpanjganj** [comment]
Sure, 
```
{
  "name": "test-project",
  "type": "project:application",
  "bundler": {
    "id": "webpack",
    "displayName": "Webpack"
  },
  "build": {
    "options": {
      "server": "dev",
      "extractCss": "prod",
      "coverage": false
    }
  },
  "platform": {
    "id": "web",
    "displayName": "Web",
    "port": 8080,
    "hmr": false,
    "open": false,
    "output": "dist"
  },
  "loader": {
    "id": "none",
    "displayName": "None"
  },
  "transpiler": {
    "id": "babel",
    "displayName": "Babel",
    "fileExtension": ".js",
    "options": {
      "plugins": [
        "transform-es2015-modules-amd"
      ]
    }
  },
  "markupProcessor": {
    "id": "none",
    "displayName": "None",
    "fileExtension": ".html"
  },
  "cssProcessor": {
    "id": "sass",
    "displayName": "Sass",
    "fileExtension": ".scss"
  },
  "editor": {
    "id": "vscode",
    "displayName": "Visual Studio Code"
  },
  "unitTestRunner": [
    {
      "id": "jest",
      "displayName": "Jest"
    }
  ],
  "integrationTestRunner": {
    "id": "none",
    "displayName": "None"
  },
  "paths": {
    "root": "src",
    "resources": "resources",
    "elements": "resources/elements",
    "attributes": "resources/attributes",
    "valueConverters": "resources/value-converters",
    "bindingBehaviors": "resources/binding-behaviors"
  },
  "testFramework": {
    "id": "jasmine",
    "displayName": "Jasmine"
  }
}
```
The command I run is : `au build --env prod`
I get the following assets:
```
-  app.e8769c7465cd13a0b79f.bundle.js     918 kB 
-  vendor.be6c9065e5017a000de3.bundle.js  210 bytes
-  common.42980569ceb92a609068.bundle.js     200 kB
- app.e8769c7465cd13a0b79f.bundle.map     146 kB
- vendor.be6c9065e5017a000de3.bundle.map  114 bytes
- common.42980569ceb92a609068.bundle.map    33.3 kB
```

After adding the following plugin to my webpack app.js bundle  becomes 375kb:
```
    new UglifyJsPlugin({
      sourceMap: true,
      compress: {
        drop_console: true,
        warnings: false
      },
      output: {
        comments: false
      }
    })
```
My argument is that, this seems like a better default output from a production build.

**Comment by AStoker** [comment]
Well crap, just realized that this is WebPack :P I thought you were on RequireJS.  
Straight up, WebPack isn't my speciality, so I'm not as familiar with how it minifies.  
At first glance though, it doesn't appear that the aurelia.json has any options in there for minification... Did you remove them, or does WebPack minify/uglify on a separate process that needs to be in the build.js?

**Comment by JeroenVinke** [comment]
Currently the skeleton-navigation-webpack doesn't do uglification, so that has made its way into the CLI. I think we should have uglify preconfigured though
