### ISSUE TITLE
System generated file in `src` folder

### ISSUE THREAD

**Issue by vpanjganj** [aurelia/cli#740]
**I'm submitting a feature request**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6 Sierra

* **Node Version:**
8.3.0

* **NPM Version:**
5.3.0

* **Browser:**
all

* **Language:**
ESNext + Webpack

**Current behavior:**
When running `au build --env prod` a file called  `environments.js` gets generated inside the `src` folder. 
I use a trailing comma rule that gets checked on build using `eslint-loader`. `environments.js`  breaks my build every time and I don't have any control over it. Of course this can be simply resolved by adding it to `.eslintignore` as a quick fix.

**Expected/desired behavior:**
It would be great to have control over the files inside the `src `folder as well as their code style.

**Comment by AStoker** [comment]
Is it a matter of formatting the environment file? If so, you can see the various environment files under the `aurelia-project/environments` folder. Those files represent the various states/environments that your project can run in. For example, for the sake of versioning, we actually include version numbers inside our environment file so we can use that in various places.

**Comment by vpanjganj** [comment]
Thanks
