### ISSUE TITLE
Import reference path incorrect

### ISSUE THREAD

**Issue by colindembovsky** [aurelia/cli#750]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.1

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
TypeScript 2.4

* **Loader/bundler:**
RequireJS

**Current behavior:**
I have installed the [vss-web-extensions-sdk](https://www.npmjs.com/package/vss-web-extension-sdk) using `au install vss-web-extensions-sdk`. The `aurelia.json` file seems correct:

```json
  ...
  "bundles": [
    {
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "node_modules/aurelia-cli/lib/resources/scripts/configure-bluebird.js",
          "node_modules/requirejs/require.js"
        ],
        "dependencies": [
           ...
           {
             "name": "vss-web-extension-sdk",
            "main": "lib/VSS.SDK",
            "path": "../node_modules/vss-web-extension-sdk",
            "resources": []
           }
           ...
        ]
```
I include types from the vss lib like this:

```js
import {IncludeWidgetStyles} from 'TFS/Dashboards/WidgetHelpers';
export class App {
   constructor() {
      IncludeWidgetStyles();
   }
}
```

The typings work in VS Code (there are no errors and I get intellisense for the imported types) - however, `au build` results in this error:

```
Tracing views/settings...
 ------- File not found or not accessible ------
| Location: D:/mdata/ws/vs-ext/src/TFS/Dashboards/WidgetHelpers.js
| Requested by: D:/mdata/ws/vs-ext/src/views/settings.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
```

* **What is the expected behavior?**
The expected behavior is that `au build` succeeds without errors. One of the typings files for the vss-web-extension-sdk declares module `TFS/Dashboards/WidgetHelpers` but it seems the cli is looking for a js file with this path.

* **What is the motivation / use case for changing the behavior?**

**Comment by simonfox** [comment]
I know nothing about `vss-web-extension-sdk` however it looks like your import should be something more like `import VSS from 'vss-web-extension-sdk'`. Looks like the intended export is `VSS` which is intended to be [used like this](https://github.com/Microsoft/vss-web-extension-sdk#use-the-sdk)

**Comment by Alexander-Taran** [comment]
@colindembovsky were you able to resolve your issue?
there is a section in docs describing how to add dependencies to aurelia.json

**Comment by Alexander-Taran** [comment]
```ts
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : fromYears(6) } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

@bigopon

**Comment by 3cp** [comment]
No idea why the lib works. The author said he tries to import a type, but later he used it as a function `IncludeWidgetStyles()` means it needs implementation.

But the whole `lib/VSS.SDK.js` didn't define that function. It's probably defined from somewhere else.

The `lib/VSS.SDK.js` does not use any module system, it only creates global vars `VSS` and `XDM`.
