### ISSUE TITLE
Extend the Environment-Specific Dependencies functionality to 'prepend' and 'append'

### ISSUE THREAD

**Issue by arnederuwe** [aurelia/cli#752]
**I'm submitting a feature request**

**Current behavior:**
The prepend/append section is only configurable with paths to js libraries

* **What is the expected behavior?**
Make it possible to only load certain js libraries depending on the selected environment, like this:
```
"prepend": [
          "scripts/jszip.min.js",
          "node_modules/bluebird/js/browser/bluebird.core.js",
          {
                path: "node_modules/aurelia-cli/lib/resources/scripts/configure-bluebird.js",
                env: "stage & prod"
          },
          {
                path: "node_modules/aurelia-cli/lib/resources/scripts/configure-bluebird-dev.js",
                env: "dev"
          },
          "node_modules/element-closest/element-closest.js",
          "node_modules/requirejs/require.js"
        ],
```

* **What is the motivation / use case for changing the behavior?**
Today I had a headache trying to improve the startup performance in IE, which was terrible...
Turns out it was BlueBird related, and it was previously fixed: https://github.com/aurelia/templating/issues/448
Since the CLI has moved the BlueBird config to an internal js file, this issue is present again as the file doesn't incorporate the fix committed by @EisenbergEffect in the issue above.
As you do want these stack traces in dev mode, this is an ideal use-case for the change I propose. If you could load a different BlueBird config depending on your environment flag, this would be fixed elegantly.

I would be happy to make a PR for this, just point me in the direction where I should start making these changes.

**Comment by JeroenVinke** [comment]
I like it, and a PR would be much appreciated. I think it would have to be done [in this area](https://github.com/aurelia/cli/blob/master/lib/build/bundle.js#L17-L18)

**Comment by arnederuwe** [comment]
Great! I'm on it

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/pull/761
