### ISSUE TITLE
`au import` seems limited

### ISSUE THREAD

**Issue by DamnedScholar** [aurelia/cli#755]
I went down a rabbit hole of messing with dependencies, and I noticed that `au import` was consistently failing to find a strategy for dependencies that had just one folder with an `index.js`. It feels to me like that design should be one of the strategies used by the CLI.

**Comment by bohdyone** [comment]
I've run into this problem too. For instance 'au install axios' fails to follow the dependency chain correctly. I'd call this a bug since it makes au run unusable without a bunch of manual work at the moment.

**Comment by mipod** [comment]
+1 same proble with node "ws" package, you  end up in a loophole of manualy adding dependencies...

**Comment by 3cp** [comment]
`au import` is removed from aurelia-cli. We don't need strategy in latest cli-bundler, just plain `npm install ...`.
