### ISSUE TITLE
Sugestion: support generate web component spec

### ISSUE THREAD

**Issue by AbraaoAlves** [aurelia/cli#757]
**I'm submitting a feature request**

**Current behavior:**
We can't generate Aurelia Plugin like WebComponent spec compliant. eg. [StencilJS](https://stenciljs.com)

* **What is the expected behavior?**
Cli build/generate plugin web component spec that we'll can simple use like this:
import a script[src=file.js] or link[rel=import, src=file.html] and use components tag like any web component spec [WebComponent](https://www.webcomponents.org/introduction#custom-elements)

* **What is the motivation/use case for changing the behavior?**
The history of javascript tells us that only thing survives over time is the patterns and specs like ECMAScript. Aurelia gets much inspiration on specs of next#web, but today I see it as any other Framework. To continue flow on the same thought, Aurelia needs alive and interop with native web components.

related:
https://github.com/aurelia/framework/issues/7
https://github.com/aurelia/web-components/issues/2

**Comment by JeroenVinke** [comment]
I am not sure what to do here. We are going to add a `au new --plugin` feature that would allow you to generate Aurelia plugins. The webcomponent spec isn't the responsibility of the cli, for that I would keep monitoring the two issues that you've linked to.
