### ISSUE TITLE
"au run" doesn't serve files

### ISSUE THREAD

**Issue by rgwch** [aurelia/cli#760]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.10.5, Ubuntu 17.04

* **Node Version:**
7.5.0

* **NPM Version:**
4.6.1

* **Browser:**
Chrome 58.0.3029.110, Safari 10.1.2, Opera 47.0.2631.83

* **Language:**
TypeScript 2.5.3

**Current behavior:**
When I serve the project with `au run --watch`, the browser only tells me "Cannot GET /". The debug console says: "GET http://localhost:9000/ 404 (Not Found)"

if I run `au build --watch`, and `php -S localhost:9000` in the same directory, everything works as expected (only I have to reload browsers manually after rebuild). Also on the deployment server, the project built with `au build --env prod` works as expected.

* **What is the expected behavior?**

I would appreciate if aurelia-cli would give more detailed informations on what went wrong an why it can't serve the files.

**Comment by JeroenVinke** [comment]
Hey @rgwch, is this a webpack project? If so then the project runs under http://localhost:8080

**Comment by rgwch** [comment]
Hi @JeroenVinke, thanks for replying!

localhost;8080 gives "connection refused". Here is the output of the build. There are no error messages:

Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'copyFiles'...
Starting 'configureEnvironment'...
Finished 'copyFiles'
Finished 'processCSS'
Finished 'configureEnvironment'
Starting 'buildTypeScript'...
Finished 'processMarkup'
Finished 'buildTypeScript'
Starting 'writeBundles'...
Tracing allg...
Tracing app...
Tracing environment...
Tracing klima...
Tracing main...
Tracing showcase...
Tracing solar...
Tracing components/component...
Tracing components/doublegauge...
Tracing components/fronius...
Tracing components/lcd7segm...
Tracing components/lcdclock...
Tracing components/lineargauge...
Tracing components/multiswitch...
Tracing components/threewayswitch...
Tracing components/verticalgauge...
Tracing resources/index...
Tracing allg...
Tracing app...
Tracing styles...
Tracing klima...
Tracing nav-bar...
Tracing showcase...
Tracing solar...
Tracing components/doublegauge...
Tracing components/fronius...
Tracing components/lcd7segm...
Tracing components/lcdclock...
Tracing components/lineargauge...
Tracing components/multiswitch...
Tracing components/threewayswitch...
Tracing components/verticalgauge...
Tracing jquery...
Tracing bootstrap/css/bootstrap...
Tracing aurelia-bootstrapper...
Tracing aurelia-history...
Tracing aurelia-history-browser...
Tracing aurelia-loader-default...
Tracing aurelia-logging-console...
Tracing aurelia-pal-browser...
Tracing aurelia-route-recognizer...
Tracing aurelia-router...
Tracing aurelia-templating-binding...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-router...
Tracing aurelia-testing...
Tracing text...
Tracing d3-brush...
Tracing d3-chord...
Tracing d3-dsv...
Tracing d3-force...
Tracing d3-geo...
Tracing d3-hierarchy...
Tracing d3-polygon...
Tracing d3-queue...
Tracing d3-random...
Tracing d3-voronoi...
Tracing d3-zoom...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'
Application Available At: http://localhost:9000
BrowserSync Available At: http://localhost:3001
    
There's also no console output when trying to connect, but it returns the following message;

$ curl localhost:9000
Cannot GET /

$ curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused

**Comment by JeroenVinke** [comment]
That is weird. Could this be a permission issue? does `sudo au run --watch` work? Also, does the browsersync url work?

**Comment by rgwch** [comment]
@JeroenVinke sudo doesn't make a difference. localhost:3001 brings up the Browsersync UI.

To be clear: Probably there is some error in my code or setup, but I can't find out, because I don't have a clue. Wouldn't it be possible for `au run` to give more details on errors? (Which request exactly failed and so on).

**Comment by JeroenVinke** [comment]
Take a look at aurelia_project/tasks/run.js and see what folder browsersync serves from. I have a feeling that browsersync serves from a directory that doesnt contain your index.html. If this doesnt help you, zip up the aurelia_project folder and the directory structure that you use and send it to me on Gitter, or attach it to this issue if it doesnt have sensitive stuff

**Comment by rgwch** [comment]
I'm not sure I understand fully, because I can't see the directory there.

There's no sensitive stuff. If you like, you can clone it here: https://github.com/rgwch/homeview
Just `npm install` and `au run` should work and demonstrate the issue.

Of course I don't want to waste your time, but if you'll find some time to have a look, I would highly appreciate.

**Comment by JeroenVinke** [comment]
Thank you, I am not near a computer right now but my guess is that https://github.com/rgwch/homeview/blob/master/aurelia_project/tasks/run.ts#L17 might have to be changed into `server` like this: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.ts#L17

**Comment by rgwch** [comment]
This was it! Thank you so much. I really don't know how this error in run.ts could happen, must have been some really bad silly global rename I made somewhere in the conversion to aurelia-cli. Sorry for that and again thank you very much.
