### ISSUE TITLE
vendor-bundle is looking for dependencies in node_modules

### ISSUE THREAD

**Issue by lukpep** [aurelia/cli#762]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.3

* **NPM Version:**
3.10.10

* **Browser:**
all 

* **Language:**
TypeScript 2.5.3

* **Loader/bundler:**
RequireJS

**Current behavior:**

my prod and dev builds are broken. au build or au build --env prod produces bundles without error but when I deploy them to remote server I get 404:

> ee/node_modules/aurelia-templating-resources/dist/amd/aurelia-templating-resources.js

it seems that vendor-bundle is looking for dependencies in node modules catalog.
Very simillar issue: https://github.com/aurelia/cli/issues/401

my aurelia.json: https://gist.github.com/lukpep/59e062b068058497f0868b36416bf9f5
app is accessible here: https://lukasz-peplinski.com/oee/

what I tried:
clean install of node_modules and typings - no success

when I use au run --watch locally application works but it serves dependencies from node_modules
![image](https://user-images.githubusercontent.com/2960580/30969030-7ccea48a-a461-11e7-9817-0ab1e7788c2f.png)

**Comment by JeroenVinke** [comment]
I think your bundle config might be resulting in an invalid bundle, which causes requirejs to load everything from their original location instead of the bundle, which is the node_modules folder. I can have a look tonight. One thing I notice is that you have a bluebird config in the src directory, and you prepend that script. Perhaps try to remove that and simplify the bundle config until it works again

**Comment by lukpep** [comment]
I changed bluebird config to orignal location - no success :(

**Comment by lukpep** [comment]
I changed order of some packages in aurelia.json to:
https://gist.github.com/lukpep/9739774f730edcec5c773e76f6a4809d

and some packages disappear from node_packages source:
![image](https://user-images.githubusercontent.com/2960580/30981492-d5e0dcbe-a484-11e7-926c-22b49c588233.png)

**Comment by JeroenVinke** [comment]
@lukpep that seems to be the issue here

try https://gist.github.com/JeroenVinke/c259d9194459fefc5472187491ed9964#file-gistfile1-txt-L63-L79

the order is important. Also, you have two dependencies for `aurelia-ion-rangeslider`, i'd remove one if possible

**Comment by lukpep** [comment]
@JeroenVinke 
I finally came to this: https://gist.github.com/lukpep/76fee66b52169f8dad924d70b8ae9bdb
which results in:
![image](https://user-images.githubusercontent.com/2960580/30988028-3c801994-a499-11e7-9f07-d0d7fb7da6d3.png)

problematic plugin (chartjs-plugin-annotation) dont have UMD support - https://github.com/chartjs/chartjs-plugin-annotation/issues/86

And I import it in module like this:
`import 'chartjs-plugin-annotation';`

- plugin works but is not bundled. Any workarounds?
Also - how can I know what is the right order of dependencies in aurelia.json -to be honest I was really surprised that it's important - I was assuming that bundler could somehow know how to deal with it - basing on "deps" section in single module configuration

**Comment by JeroenVinke** [comment]
@lukpep I see that the app is working now. Did you figure it out? Any more leads?

**Comment by JeroenVinke** [comment]
Feel free to reopen if this is still an issue
