### ISSUE TITLE
Unable to create a new "Hello World" project

### ISSUE THREAD

**Issue by KingRial** [aurelia/cli#764]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v6.10.0

* **NPM Version:**
3.10.10

* **Browser:**
Tested with: Chrome 61 | Firefox 55| Edge ( Latest )

* **Language:**
Tested with: ES6

* **Loader/bundler:**
Tested with: SystemJS | RequireJS

**Current behavior:**
I just created a new "hello world" project using aurelia-cli ( with default options ):
```
au new
```
But when I launch:
```
au run --watch
```
I got an error on the console javascript panel:
```
Uncaught TypeError: plugin.load is not a function
...
Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-templating-resources/if.html_unnormalized2,template-registry-entry!aurelia-templating-resources/if.html,text!aurelia-templating-resources/if.html_unnormalized3,text!aurelia-templating-resources/if.html
```
And nothing is shown on the web page

If I modify the "aurelia.json" configuration for "loader.plugins.stub" to "false" the error becomes:
```
ET http://127.0.0.1:9000/node_modules/aurelia-templating-resources/dist/amd/if.html 404 (Not Found)
Unhandled rejection Error: src/../node_modules/aurelia-templating-resources/dist/amd/if.html HTTP status: 404
```

* **What is the expected behavior?**
I expect to access the usual default page

* **Workaround** ( Edit )
Just found out you need to downgrade "aurelia-templating-resource" to v1.4.0 by using the following commands:
```
npm uninstall aurelia-templating-resources
npm install aurelia-templating-resoirces@1.4.0
```
Related to ticket:
https://github.com/aurelia/templating-resources/issues/313

**Comment by rjpvroegop** [comment]
I can confirm.

* au new --here
* 1 - RequireJS
* 1 - Web
* 1 - Babel
* 1 - Default (minification)
* 3 - Sass
* 1- Yes (unit-testing)
* 4 - Webstorm
* Yes - install

**Comment by rjpvroegop** [comment]
Bundling with Webpack does not fix the issue. Error message:

> Unhandled rejection Error: Unable to find module with ID: aurelia-templating-resources/if.html

**Comment by StrahilKazlachev** [comment]
duplicate:
- aurelia/templating-resources#313
- aurelia/templating-resources#312

Use `aurelia-templating-resources@1.4.0` for now.

**Comment by JeroenVinke** [comment]
There's a fix on the way
