### ISSUE TITLE
[Feature Request] add Plugin project creation to the cli

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/cli#768]
**I'm submitting a feature request**

* **Language:**
all

* **Loader/bundler:**
all

* **What is the motivation / use case for changing the behavior?**
We can benefit a lot from a unified structured way for creating an aurelia plugin.
the CLI is a great tool for creating a new project by the standards of the Aurelia team.
It would be nice to have the same solution for a Aurelia Plugin project.

I'm aware of the [skeleton-plugin](https://github.com/aurelia/skeleton-plugin), but the cli is a better tool for the job.
maybe we can have multiple templates we can choose from?
like JS/TS, output formats (AMD/System..)

**Comment by avrahamcool** [comment]
didn't realize there is a request already.
https://github.com/aurelia/cli/issues/658

**Comment by JeroenVinke** [comment]
Yep, and a lot of work has been done already by @manuel-guilbault. Let's track this feature in #658
