### ISSUE TITLE
Webpack build system doesn't honor environments

### ISSUE THREAD

**Issue by jemhuntr** [aurelia/cli#769]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
OSX Sierra

* **Node Version:**
6.11.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
Webpack

**Current behavior:**
Webpack builds are not referencing environments under `aurelia_project/environments/*.js`.

On an aurelia-cli generated webpack setup, create custom variables under `aurelia_project/environments/prod.js` and reference them from within the app by importing the environment, injecting it into a class, and accessing the custom-set variable. The variables you set wouldn't be available when you build for production, resulting in broken app behaviour.

* **What is the expected behavior?**
The webpack builds should, like every other Aurelia CLI build system does, respect the configuration under `aurelia_project/environments`.

* **What is the motivation / use case for changing the behavior?**
To make the build systems more consistent across platforms and use cases, making migration between build systems easier and less of a breaking change to an existing codebase.

**Comment by JeroenVinke** [comment]
This should work, a fix for this went out in 0.31.2. Make sure that your gulp tasks are up to date. Quickest way is to create a new project with similar configuration as your current project, and copying over the gulp tasks from the `aurelia_project/tasks` folder. Let me know if that doesn't fix it, it could be something platform specific

**Comment by jemhuntr** [comment]
Hmm. It works when I use `au build --env [env]`.

Am I supposed to prefer the aurelia-cli for building and running the scripts instead of using `nps` directly?

Moreover, is the aurelia-cli referencing `nps` internally? does this mean I can't modify or customize `package-scripts.js`?

**Comment by JeroenVinke** [comment]
> Am I supposed to prefer the aurelia-cli for building and running the scripts instead of using nps directly?

Yes, that would be best because you'd be using the gulp tasks. One of these gulp tasks is copying of the environment specific files from `aurelia_projects/environments` to the `src` directory.

> Moreover, is the aurelia-cli referencing nps internally? does this mean I can't modify or customize package-scripts.js?

No, the aurelia-cli doesn't use nps internally. We can (and should IMO) remove nps at a later stage. For now it's necessary because I wasn't able to get protractor working through gulp nicely, so the only use for `nps` is to be able to run the protractor tests.

**Comment by jemhuntr** [comment]
Ahhh. Alright. Thanks for clarifying :)
