### ISSUE TITLE
[Enhancement/Bug] When CSS Source is Array of glob patterns, AU --watch should trigger rebuild on change in any source specified

### ISSUE THREAD

**Issue by diegohb** [aurelia/cli#774]
**I'm submitting a bug report**

* **Library Version:**
AU CLI 0.31.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.6.0

* **NPM Version:**
5.4.2

* **Browser:**
all

* **Language:**
TypeScript 2.4.2

* **Loader/bundler:**
 SystemJS 

**Current behavior:**
when setting css processor source property to array of globs [like so](https://github.com/diegohb/samples-aurelia-vanilla_cli/compare/master...master-task029-task030?expand=1#diff-2f7834e4b0452dbcf936db7c5f0e552aR31)... and running **au build --watch**, changing a source file covered in those globs doesn't trigger the processCSS task.

* **What is the expected behavior?**
I'd expect it to processCSS for each glob specified.

* **What is the motivation / use case for changing the behavior?**
Less files that live inside "src" as sibling to each component or view... but also generic site-wide less files that live as a sibling to "src" dir. or any other place you want css processing to happen within solution/project.

**Comment by diegohb** [comment]
Please see this branch that shows the change to reproduce and my attempt at fixing this...  it is watching for changes correctly and triggering processCss() ....and it **says** it writes bundles.. but it doesn't actually update the bundle's definition of the css.

https://github.com/diegohb/samples-aurelia-vanilla_cli/compare/master...master-task029-task030?expand=1

**Comment by diegohb** [comment]
This issue may be an enhancement to the watch.ts task to allow for multiple globs for css sources... but as far as why my fix didn't change in my last comment... it was a typo! https://github.com/diegohb/samples-aurelia-vanilla_cli/commit/6ce5eca111863736d703cf58214cfdfd3c339e67

**Comment by Alexander-Taran** [comment]
@3cp this is also interesting.. (-:

**Comment by 3cp** [comment]
I just tested it. Latest skeleton works well. Pls reopen if you see more problems.

I am very surprised globalResources api can be used to load css resource :-)
```js
aurelia.use.globalResources("./one.css");
```

**Comment by Alexander-Taran** [comment]
@3cp your comment is gold (-:
