### ISSUE TITLE
index.html not being created along with bundled files

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/cli#775]
**I'm submitting a bug report**

* **Library Version:**
0.3.next

**Please tell us about your environment:**
Windows 10
ASP.net Core 2.0

* **Node Version:**
Latest

* **Language:**
TypeScript 2.5

* **Loader/bundler:**
Webpack

**Current behavior:**

I created a new ASPNETCORE 2.0 project and used the latest bits from the master branch.  It created the 
new webpack.netcore.config.js as expected.

I then follow the instructions in instuctions.txt.

When I run the app, the Dist folder is c;reated, and the two bundles are also created.  However, Dist/index.html is not created.

* **What is the expected behavior?**
I believe the Dist/index.html file should be created.  If this is not the desired behavior in the new updates, then at least views/home/index.cshtml should be updated with the usual framework launch html:

```
<div aurelia-app="main">
  <script src="~/dist/app.bundle.js"></script>
  <script src="~/dist/vendor.bundle.js"></script>
</div>
```

After I added this to index.cshtml, then the app ran as expected.

**Comment by JeroenVinke** [comment]
We prefer not to replace existing Views/.cs files when they exist, because they can contain logic that the user does not want to lose. Therefore we provide instructions (that we put in an instructions.txt file in the project directory). Those were missing for the Views as you noticed. I've added those now, thanks for the heads up!

**Comment by gregoryagu** [comment]
I tested using the updated bits and followed the instructions in instructions.txt and it worked great. The hot module reloaded worked perfectly which is what I was trying to achieve.

 (Note, however, there is still the other issue with the tsconfig.json, but that's a different issue).
