### ISSUE TITLE
add a Document how to do cli job manually

### ISSUE THREAD

**Issue by javadbat** [aurelia/cli#777]
**I'm submitting a feature request**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
 ESNext

* **Loader/bundler:**
SystemJS

**Current behavior:**

* **What is the expected behavior?**

before i use aurelia im using jspm to install aurelia in .net framework website and it was easy to see and customize and no problem at run but when today i am trying to start a new project and get familiar with aurelia cli and use it it was great and worked but i dont know how it build the project and what change it make and the wrost thing is how can i customize it and change the path and etc....
in jspm way i just configure and load project and set it to iis and everyone in my team can use it by using the address of main page i cant tell them run "au run" or something else .  
* **What is the motivation / use case for changing the behavior?**
i just wnt you to doc all process and how we can do it by our-self without cli and how can i run it without any cli tools just by setting up in project and iis in this case im really confused and even try other framework but none of them work with es next class so please add this doc im really needing it

**Comment by javadbat** [comment]
here is example work done for react js before :  
https://www.andrewhfarmer.com/build-your-own-starter/

**Comment by gheoan** [comment]
A similar tutorial is on the to-do list for https://github.com/aurelia/documentation/issues/181.
[Here](https://github.com/aurelia-guides/aurelia-guides.md-articles/blob/master/Building-Skeleton-Navigation-From-Scratch.md) is an old one (found [here](https://github.com/aurelia/documentation/issues/181#issuecomment-168092677)) and another one [here](https://ilikekillnerds.com/2017/03/creating-minimal-aurelia-typescript-webpack-application-scratch/) (found [here](https://discourse.aurelia.io/t/aurelia-collected-tutorials/204)).

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 answerQuestion()
 let response = await getResponseFromOP( { timeout : longEnough} )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by JeroenVinke** [comment]
i've added a document on the task system here: https://github.com/aurelia/cli/pull/747
