### ISSUE TITLE
Screen clearing is annoying and hides errors

### ISSUE THREAD

**Issue by PWKad** [aurelia/cli#779]
**I'm submitting a bug report**

* **Library Version:**
0.29.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.10.3

* **NPM Version:**
2.15.2

* **Browser:**
n/a

* **Language:**
ESNext

* **Loader/bundler:**
all

**Current behavior:**

The screen clears after ever command that is issued

* **What is the expected behavior?**

The screen does not clear after each command

* **What is the motivation / use case for changing the behavior?**

1. It "flashes" on the screen when it clears
2. It's slightly annoying
3. If there is an error (ex. task not found) it is displayed but then the screen is cleared so the user has to scroll up anyway to see it.

**Comment by gheoan** [comment]
What commands are you referring to? Isn't `aurelia new` the only one that clears the screen?

**Comment by PWKad** [comment]
Does it for me for on help and all commands it seems.

**Comment by Alexander-Taran** [comment]
@PWKad do you think you could come up with a non-breaking-change PR for `--no-cls` option? (-:

**Comment by JeroenVinke** [comment]
I think we should remove this screen clearing thing, it's been more annoying than anticipated

**Comment by Alexander-Taran** [comment]
Oh.. while we are at it.. there was another issue about ui-less flow..
I tried an old hack with `au new name < answers.txt`
and it gets the first answer.. but all the rest is missed.. I guess whatever is used for reading console swallows all the input after the first answer and when tries to readLine there is EOF aka ^Z
