### ISSUE TITLE
Webpack + karma misses jest plugins

### ISSUE THREAD

**Issue by s-hoff** [aurelia/cli#782]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
7.7.3

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
Webpack

**Current behavior:**
Choosing the webpack bundler with karma for testing, one gets two errors for missing jest modules on running `au karma`:
```
ERROR in ./test/karma-bundle.js
Module not found: Error: Can't resolve 'jest-jasmine2/jasmine-async' in '/home/shoff/workspaces/awk/test'
 @ ./test/karma-bundle.js 3:0-77

ERROR in ./test/karma-bundle.js
Module not found: Error: Can't resolve 'jest-matchers' in '/home/shoff/workspaces/awk/test'
 @ ./test/karma-bundle.js 52:15-39

```

I tested this with a fresh project both for babel and typescript.
Installing `jest-matchers` took care of the second error, but `npm i --save-dev jest-jasmine2` didn't do the trick for `jest-jasmine2/jasmine-async`.

* **What is the expected behavior?**

The `au karma` command should run without errors on a newly created webpack setup.

**Comment by JeroenVinke** [comment]
Hi, could you try this with the latest cli? `npm install aurelia-cli@latest -g` and create a new project. Thanks

**Comment by s-hoff** [comment]
Just tried it. Looks like `jest-jasmine2/jasmine-async` is there now, but `jest-matchers` is still missing.

**Comment by sizilium** [comment]
I have a similar issue with au 0.32.0 and a generated webpack skeleton (vanilla).
npm test failed:
> ERROR in ./test/karma-bundle.js
Module not found: Error: Can't resolve 'jest-matchers' in 'C:\repositories\aurelia-webpack\webpack-test\test'
 @ ./test/karma-bundle.js 54:17-41

**Comment by JeroenVinke** [comment]
Thank you, i'll have a look

**Comment by s-hoff** [comment]
Adding `jest-matchers` to the dev dependencies should do the trick. Thats what fixed it for me.

For those not running `32.0` and getting the `jest-jasmine2/jasmine-async` error: Go to your `karma-bundle.js` and change the import from `'jest-jasmine2/jasmine-async'` to `'jest-jasmine2/jasmine_async'`.

**Comment by JeroenVinke** [comment]
@s-hoff thanks for the update. I wonder if we can separate the karma and jest setups entirely so that when you only need karma you don't need to install any jest libraries
