### ISSUE TITLE
Error installing dependencies in a new typescript project

### ISSUE THREAD

**Issue by bliu886** [aurelia/cli#783]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6 

* **Node Version:**
9.0.0

* **NPM Version:**
5.5.1

* **Browser:**
all

* **Language:**
TypeScript

* **Loader/bundler:**
RequireJS

**Current behavior:**
When installing the project dependencies in a new TypeScript project results in this error:

![screen shot 2017-11-06 at 12 05 01 pm](https://user-images.githubusercontent.com/13091681/32453640-d1055312-c2ea-11e7-91ad-09368a50fd78.png)

This is my project setup:

![screen shot 2017-11-06 at 12 07 06 pm](https://user-images.githubusercontent.com/13091681/32453754-23b20416-c2eb-11e7-8648-9a74532e9623.png)

* **What is the expected behavior?**

The expected behaviour is the aurelia cli will create a new aurelia project with the dependencies. To reproduce this, create a new aurelia project using the "au new" command. Name the project anything. Use the default TypeScript setup. Create the project and install the project dependencies.
* **What is the motivation / use case for changing the behavior?**
You should be able to create new projects in aurelia using the default typescript setup.

**Comment by JeroenVinke** [comment]
Please reopen if this is still an issue
