### ISSUE TITLE
webpack template - Use CommonsChunkPlugin more?

### ISSUE THREAD

**Issue by volak** [aurelia/cli#784]
No breaking issue here - just a suggestion.  

Fired up a new webpack project and after some toying and fidling I'm at a pretty good place now.  I've setup webpack to bundle my build into a `vendor `and an `app` chunk using the CommonsChunkPlugin [documentation](https://webpack.js.org/plugins/commons-chunk-plugin/#explicit-vendor-chunk)

The way the template is setup now it creates multiple entries

```
  entry: {
    app: ['aurelia-bootstrapper'],
    vendor: ['bluebird'],
  },
```
this creates 2 chunks - but it difficult to work with as everytime more vendor libraries are added you have to add to the entry.vendor list and in typescript dynamic imports require code like

`import('bluebird' /* webpackChunkName: 'vendor' */).then(BlueBird => { /* do something */});`

using the CommonsChunkPlugin as suggested by webpack we can split out everything under `node_modules` into a vendor bundle really simply like so

```

    new CommonsChunkPlugin({
      name: "vendor",
      minChunks: function(module){
        return module.context && module.context.indexOf("node_modules") !== -1;
      }
    }),
    new CommonsChunkPlugin({
      name: "manifest",
      minChunks: Infinity
    }),
```

and all the imports with with no special comment instructions.

To find and debug this I also used WebpackBundleAnalyzer plugin which produces very nice reports on whats actually inside bundles 

`new WebpackBundleAnalzyer({analyzerMode: 'static', openAnalyzer: false})`

**Comment by Alexander-Taran** [comment]
no more common chunks plugin
webpack 4

**Comment by volak** [comment]
Yeah that's true - upgrade to webpack 4 will make this unnecessary
