### ISSUE TITLE
au run --watch doesn't detect file changes in some cases

### ISSUE THREAD

**Issue by Gimly** [aurelia/cli#787]
**I'm submitting a bug report**

* **Library Version:**
Aurelia cli 0.32.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Debian Jessie inside Docker container), Windows 10 (Docker Host)

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **Browser:**
all

* **Language:**
TypeScript 2.6

* **Loader/bundler:**
RequireJS

**Current behavior:**
I'm testing Aurelia, and since I didn't want to install too much things directly on my machine, I decided to try to create a Docker image for development with Aurelia. I based it upon Debian Jessie and installed all the necessary dependencies to get Aurelia CLI working (Git, NodeJs, NPM).

I have linked the ports (9000 and 3001) of the Docker image to the same ports on my Windows 10 host, and created a volume in the Docker image that is linked to a local folder in the host. I then created a new Aurelia project using `au new` inside of the volume used by the Docker image. This way, I can access the app code from my local machine as well as from the Docker image.

When I start the app with `au run --env dev --watch`, it builds and I can access it fine by going to localhost:9000 from my local machine. If I modify a file directly from the Docker image (using vi for example), it detects that the file changed and triggers a rebuild, and I see the changes in the page directly.

However, if I change the files from the host, the watcher doesn't see that a file has changed and doesn't trigger the build. I can see that the file has changed on the Docker image, and that the "modified date" was updated, but the watcher doesn't see it. If I simply `touch filename`, then the watcher triggers a rebuilds and serves the new file.

* **What is the expected behavior?**

I would expect the watcher to detect the file change, even if it's coming from the host.

**Comment by JeroenVinke** [comment]
Could you provide a repository that has this setup? That would make it easier to start debugging

**Comment by ccrd** [comment]
I had a similar observing files changes in a samba mount. Adding usePolling to gulp.watch configuration solved it.
` ...
gulp.watch(project.transpiler.source, chokidarConfig, refresh).on('change', onChange);
...`

**Comment by huochunpeng** [comment]
This is likely a limitation from chokidar (which gulp-watch uses) instead of aurelia-cli.

https://github.com/paulmillr/chokidar/issues/242

The solution is similar to @ccrd suggested, just use polling.

**Comment by Alexander-Taran** [comment]
documentation
help_needed

edge case with watching not real file system

**Comment by Sascha89** [comment]
Hi, not sure if this topic is already solved. The watcher does detect file changes and refreshes the browser. You only need to assure, that you also map the browsersync port (3000) to your local environment. Following an example of my docker-compose file. This works for me:


```
# docker-compose.dev.yml
version: '2'

services:
  aurelia-cli-runner:
    image: saschan/aurelia-cli:latest
    ports:
      - "9001:9000"
      - "3000:3000"
    volumes:
      - ./app/:/usr/local/etc/app
    working_dir: //usr/local/etc/app
    command: "au run --watch"
```
Then you can run ```docker-compose -f docker-compose.dev.yml up -d```. After a few seconds of booting, everything should run smoothly.

**Comment by JeroenVinke** [comment]
added this to https://github.com/aurelia/cli/issues/787
