### ISSUE TITLE
project created with cli copied to git and cloned : missing dependencies with npm install

### ISSUE THREAD

**Issue by jmdavid** [aurelia/cli#788]
I created a project with cli, then pushed my project on bitbucket, then cloned it elsewhere.  When running npm install, many dependencies are missing in node_modules (ex. aurelia-binding and many more).
Is there another package.json used by au new that I can copy from?

Thanks you.

**Comment by JeroenVinke** [comment]
Could you compare node and npm versions between the two machines? `Npm -v` and `node -v`

**Comment by jmdavid** [comment]
Ok I found the problem.  Apparently, my package-lock.json file was corrupted.  After deleting it, everything is ok.  However, I have no idea how that file got corrupted.
