### ISSUE TITLE
Overriding the default build environment

### ISSUE THREAD

**Issue by jemhuntr** [aurelia/cli#797]
**I'm submitting a feature request**

**Current behavior:**

As you can see on https://github.com/aurelia/cli/blob/master/lib/cli-options.js#L17 from that last bit, aurelia cli assumes that when no environment is set, it automatically falls back to `dev`.

* **What is the expected behavior?**

If there was a way to configure this default, or at the very least just be able to pass a fallback environment like `CLIOptions.getEnvironment('defaultenv')`, that would be great.

Or perhaps there could be a key on aurelia.json to specify this default?

* **What is the motivation / use case for changing the behavior?**

As it currently is, I cannot customize my environments the way I want it. Simply put, I use only two environments: `debug` and `release`. I don't want to call them "dev" and "prod", as that isn't really an accurate name for my case.

**Comment by JeroenVinke** [comment]
Nice idea, and I also think we can add a setting to aurelia.json for this

**Comment by jwx** [comment]
I've already added this to the build targets PR https://github.com/aurelia/cli/pull/765.

**Comment by JeroenVinke** [comment]
Ah excellent, i'm having a look today or in the weekend

**Comment by Alexander-Taran** [comment]
@JeroenVinke  how can we help with merging the PR or.. don't know..

**Comment by Alexander-Taran** [comment]
@3cp I'm at loss (-:

**Comment by 3cp** [comment]
`aurelia_project/environments/` files can be renamed to `debug.js` and `release.js` (or ts).
Unfortunately there is no changeable default option for env.

However, user can use npm scripts in package.json to avoid manual setting of env in command line.

```
"build": "au build --env release"
"build:debug": "au build --env debug"
"start": "au start --env debug"
```

We are unlikely to add more features to existing aurelia-cli. Sorry.
