### ISSUE TITLE
Popper is not defined error in vendor-bundle.js

### ISSUE THREAD

**Issue by ganesh-phadtare** [aurelia/cli#800]
I have setup a client application using Aurelia-Cli. On further I am trying to run the application using au run command. I am getting an issue in browser console as **"Popper is not defined"**. My pages are working properly even this error occurred.
But whenever I am trying to run the **au test** command it is throwing the same error and I cannot execute the test cases.

I have added popper in index.html, the Browser console issues fixed,  but the unit test issue still persists.

please let me know is any other package dependency is required to be added.

**Comment by GunsAkimbo** [comment]
Try referencing the file `bootstrap.bundle.min.js` instead of `bootstrap.min.js` in aurelia.json

**Comment by fkleuver** [comment]
You need to reference the file in Popper's umd folder in your aurelia.json:
```
{
    "name": "popper.js",
    "path": "../node_modules/popper.js",
    "main": "dist/umd/popper.min.js"
}
```

Then, referencing Popper anywhere in your application (main.js/ts for app, setup.js/ts for tests) should work fine:

`import * as Popper from "popper.js";`

**Comment by ganesh-phadtare** [comment]
Thanks, "bootstrap.bundle.min.js" works for me.

**Comment by wtilton** [comment]
@ganesh-phadtare how did it work? Currently trying to get this to work. What syntax did you use? Nothing works for me.
