### ISSUE TITLE
gulp is a devDependency, when it should be a regular or peerDependency

### ISSUE THREAD

**Issue by heikomat** [aurelia/cli#801]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **Browser:**
not important

* **Language:**
not important

* **Loader/bundler:**
not important

**Current behavior:**
when installing aurelia-cli, gulp is not installed alongside it, because it is listed in the `devDependencies`.
running commands like `au build` doesn't work in that environment, because they require gulp

* **What is the expected behavior?**
gulp should be a regular dependency, or at least a peerDependency, because it is required to run commands like `au build`, and not only for the development of the aurelia-cli.

* **What is the motivation / use case for changing the behavior?**
I have a specific postinstall-script that moves and links dependencies depenending on what is mentioned in the package.json of local modules. because of that, and because the aurelia-cli doesn't state gulp as a dependency, the aurelia-cli ends up using a gulp-version of a different local module that is incompatible.

also: the aurelia-commands seem to require gulp version 4.0.0, but version ^3.9.1 is listed in the devDependencies.

**Comment by Alexander-Taran** [comment]
@JeroenVinke how can this issue be improved to be actionable?
