### ISSUE TITLE
running au with 'help' or no options results in TypeError

### ISSUE THREAD

**Issue by ShawnTalbert** [aurelia/cli#811]
**I'm submitting a bug report**
* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Mint)

* **Node Version:**
8.9.4

**Current behavior:**
Running `au` (no options) or `au help` results in:

```
TypeError: Cannot read property 'model' of null
    at module.exports.getLocalCommandText (/home/shawn/node_modules/aurelia-cli/lib/commands/help/command.js:42:32)
    at ui.displayLogo.then (/home/shawn/node_modules/aurelia-cli/lib/commands/help/command.js:24:21)
    at <anonymous>
```

**Comment by AshleyGrant** [comment]
Works fine on Windows 10/git bash env, but I can definitely see how the code can fail.

**Comment by ShawnTalbert** [comment]
I just confirmed the same error on the new 'Microsoft Bash' (Bash on Ubuntu on Windows) in Win10.

**Comment by Alexander-Taran** [comment]
runs fine for me on mint
how did you install node / aurelia-cli

**Comment by JeroenVinke** [comment]
also, could you explain more about the project structure? Is there an aurelia_project directory next to the node_modules folder? When I rename my `aurelia_project` folder to `aurelia_project1` I can reproduce the error.

**Comment by ShawnTalbert** [comment]
I was running it from my home directory, in which there is a `node_modules` folder and that's where aurelia-cli was installed (with `npm install aurelia-cli`)

I expect _any_ commandline app should not just explode for the **help** or **no options** use case. Am I wrong?

**Comment by Alexander-Taran** [comment]
was able to reproduce it:

in any folder install aurelia-cli locally as per op `npm install aurelia-cli`
run au
./node_modules/.bin/au

or
yarn add aurelia cli
yarn au

so there is no project.json (in case of npm), just node modules


seems like a.. "you are holding it wrong".. I guess (-;

**Comment by JeroenVinke** [comment]
@ShawnTalbert could you explain the reason for not installing the cli globally using the -g flag?

**Comment by Alexander-Taran** [comment]
@ShawnTalbert it's not just any cmd-line tool.
and for global installs of npm packages there is a certain workflow
if you install it otherwise than the thinking is that you know what you are doing and why you are doing that.

If you need help with runing your setup, please feel free to follow up with questions.

can be closed

**Comment by zewa666** [comment]
I am not too sure about that. I also prefer not to pollute the global package space. I think this should be handled by at least throwing a proper cmd info that its supposed to be operated differently vs crashing hard.

**Comment by Alexander-Taran** [comment]
@zewa666 
`try {} catch{ console.error ('you are holding it wrong ') }` ???
(-:

**Comment by JeroenVinke** [comment]
how about https://github.com/aurelia/cli/pull/850

**Comment by Alexander-Taran** [comment]
will it handle:
> in any folder install aurelia-cli locally as per op npm install aurelia-cli
> run au
> ./node_modules/.bin/au

**Comment by zewa666** [comment]
If it catches Alex case I'm all for that PR. :+1:

**Comment by JeroenVinke** [comment]
@Alexander-Taran by handle you mean that it displays the message that no project could be found? i've confirmed that it does that

**Comment by Alexander-Taran** [comment]
I'm happy if you are (-:

**Comment by zewa666** [comment]
Awesome

**Comment by nuxy** [comment]
Experiencing this _same issue_ with a fresh install of `aurelia` and the latest version of the `aurelia-cli`.

- **Library Version:**
  0.33.1

- **Operating System:**
  Ubuntu (bash)

- **Node Version:**
  8.9.4

**Current behavior:**

1. Create new NPM project using `npm init`
2. Install both `aurelia` and the `aurelia-cli`
3. Execute `./node_modules/.bin/au help`

```
TypeError: Cannot read property 'model' of null
    at module.exports.getLocalCommandText (/home/projects/Open Source/Github/aureliajs-seed/node_modules/aurelia-cli/lib/commands/help/command.js:42:32)
    at ui.displayLogo.then (/home/projects/Open Source/Github/aureliajs-seed/node_modules/aurelia-cli/lib/commands/help/command.js:24:21)
    at <anonymous>
```

If you need any other information, I'm happy to help.

**Comment by Alexander-Taran** [comment]
@nuxy and why would you do it like that?

**Comment by Alexander-Taran** [comment]
Yep. That's why issue is not yet closed.
Would be great If you'd like to test out the PR https://github.com/aurelia/cli/pull/856
that is supposed to resolve this

**Comment by ShawnTalbert** [comment]
@JeroenVinke as a matter of security I generally don't `npm install` anything with `-g`. Rather than use other approaches I just npm install things I use often in my home directory and have `~/node_modules/.bin` in my path. Hence no need to write to protected spots on the filesystem nor reconfigure npm to use a different 'global'.
