### ISSUE TITLE
opening the browser when running `au run -o`

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/cli#813]
**I'm submitting a feature request**
I would like to see a `--open` or `-o` option for the `au run` command, that will open the browser at the application location.

* **What is the motivation / use case for changing the behavior?**
currently, we have to open the browser ourself at navigate to `localhost:9000`,
it will be very helpful if it could be automated.

**Comment by AshleyGrant** [comment]
This shouldn't be too hard to implement. Is there any chance you would be interested in trying to implement it for the default ESNext project? You could have it default to Chrome, but could open a different browser if the user wishes. https://www.browsersync.io/docs/options#option-browser

You would need to add the flag here: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.json

And then you would need to check to see if the flag exists, and pass the `browser` option to browser sync in this file: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.js

An example of how to check for a flag being given can be seen here: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.ts#L45

If you want to, you can also add the code to the typescript version of the run command here: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/run.ts

**Comment by avrahamcool** [comment]
that was easier than I expected.
I created a PR for this - https://github.com/aurelia/cli/pull/815

I choose to go with default browser only - because I think it's the easiest way to use (in term of user experience).

I've edited the `js` as well as the `ts` versions.

**Comment by avrahamcool** [comment]
the `webpack` version of the cli project uses a different approach.
it expect a value inside `project.platform.open`.

but I think it's not handy for the user.
