### ISSUE TITLE
Bundled files are not alwasy concatenated in the same order causing rev to change

### ISSUE THREAD

**Issue by Jenselme** [aurelia/cli#816]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora 27)

* **Node Version:**
v8.9.4

* **NPM Version:**
5.6.0

* **Browser:**
NA

* **Language:**
ESNext

* **Loader/bundler:**
RequireJS

**Current behavior:** When building a project with [build revision](http://aurelia.io/docs/build-systems/aurelia-cli#build-revisions) enabled, each time I build my project, I get bundles with differrent hashes (eg `dist/vendor-bundle-51213c0533.js` and `dist/vendor-bundle-f32b0be81c.js`) even if nothing changed in my project.

To reproduce:
- Clone the project `git clone --branch feat/enable-rev https://gitlab.com/arenaoftitans/arena-of-titans.git`
- Install dependencies: `yarn install`
- Build the project multiple times by running `npm run build -- --env staging` multiple times
- Look in the `dist` folder, you will see bundles with different hashes

* **What is the expected behavior?**
I expect the hash of the bundles to be the same if my code doesn't change.

* **What is the motivation / use case for changing the behavior?**
This is a more logical behavior and allow caching of bundles that haven't changed.

* **Analysis of the problem**
I managed to look into this problem and I found out that the bundles files of my application are not always appended in the same order (with sources defined like `"[**/services/*.js]",`). I saw that by diffing two bundles. I guess this is because the globs aren't always resolving files in the same order. I also found out that the list of the files included in a bundle is not always in the same order, causing the hash of the vendor bundle to change erratically.

I managed to correct `lib/build/bundle.js` to correct this behavior here: https://github.com/Jenselme/cli/tree/fix/sort-bundle-prevent-hash-changes I can open a PR if you want.

**Comment by JeroenVinke** [comment]
Thanks for looking into it. A PR is always very welcome.

Is this easy to reproduce? I'd like to have a look at the problem as well, and it would help me to test the PR

**Comment by Jenselme** [comment]
It is easy to reproduce on my project (see the provided steps) at least on a linux machine. I'll open a PR rigth away!

**Comment by Alexander-Taran** [comment]
@JeroenVinke does team prefer PRs as single commit? I could not find exact wording in [contribution guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#submit).

Other than 3 commits - pr seems relatively simple.

**Comment by JeroenVinke** [comment]
@Alexander-Taran I usually think about what the changelog would look like. If I want one thing to show up as a feature and another as a bug fix then I create two commits, if not I try to do it as a single commit

**Comment by huochunpeng** [comment]
@JeroenVinke I am working on proper shim support on #862, I need to change the sorting algorithm to properly deal with shimmed packages with deps.

So if shimmed "A" has deps on "B", I need to make sure "B" writes to the bundle before "A" to ensure those legacy libs to work.
