### ISSUE TITLE
import and install: "This command is only available for the Aurelia CLI Bundler"

### ISSUE THREAD

**Issue by jonathaneckman** [aurelia/cli#821]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

* **Operating System:**
Windows 10

* **Node Version:**
8.9

* **NPM Version:**
5.6

**Current behavior:**
Reading the [documentation](http://aurelia.io/docs/build-systems/aurelia-cli#adding-client-libraries-to-your-project), I see I should be able to `au install library` or `au import library`. Running either of these commands returns the error:

> This command is only available for the Aurelia CLI Bundler

**Comment by Alexander-Taran** [comment]
Yep. If you chose to run along with webpack you just npm install or yarn add and see where that gets you.

**Comment by jonathaneckman** [comment]
I thought that was the case but keep running into Aurelia plugins that fail to import. I was hoping I was missing something or that there was some manual configuration I could add to aurelia.json to teach it how to load these incompatible libraries.
