### ISSUE TITLE
Using aurelia with requireJS in a Razor page, app-bundle.js isn't found

### ISSUE THREAD

**Issue by JPAhnen** [aurelia/cli#823]
* **Operating System:**
Windows 10

* **Node Version:**
8.2.0

* **NPM Version:**
5.6.0

* **Browser:**
all 

* **Language:**
TypeScript

* **Loader/bundler:**
RequireJS

**Current behavior:**
I use my Aurelia application inside a Razor page (ASP.NET Core 2). The content of the .cshtml file looks like the content of index.html which was generated by aurelia-cli.
But `vendor-bundle.js` references `app-bundle.js` by its parent path, which doesn't work:
`"app-bundle":"../scripts/app-bundle"`
If I manually change that to `"app-bundle":"/scripts/app-bundle"` then `app-bundle.js` is loaded correctly.

* **What is the expected behavior?**
Aurelia should work in Razor pages when using requireJS.

Is using requireJS in this context even possible at the moment? Or would using another module loader (e.g. SystemJS) work better?

**Comment by Alexander-Taran** [comment]
@JPAhnen 
check out this issue:
https://github.com/aurelia/cli/issues/200
does it look the same?

**Comment by JPAhnen** [comment]
I don't think it's the same. If I put `index.html` into the `wwwroot` folder it works, but if I use an MVC Razor page for loading it, it doesn't.
In my case, the Aurelia app is a separate part of my web application and is included in a Razor page.

And in this case the route is e.g. `localhost:5000/Game/Play/1001`, and so it tries to load `app.bundle.js` from `localhost:5000/Game/Play/scripts/app.bundle.js` because it uses relative path.

When using `localhost:5000/index.html`, it uses correctly  `localhost:5000/scripts/app.bundle.js`.

But I just got another idea, I'll try to solve this using URL rewriting in my web application.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect  maybe can be closed.
Maybe there needs to be some explanation on relative vs absolute paths in bundle production.
