### ISSUE TITLE
aurelia cli does not run after installing dependency from npm

### ISSUE THREAD

**Issue by monis01** [aurelia/cli#826]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04)

* **Node Version:**
8.6.0

* **NPM Version:**
5.6.0

* **Language:**
ESNext

**Current behavior:**
(I am following the contact manager example from the [contact-manager](http://aurelia.io/docs/tutorials/creating-a-contact-manager#building-the-application-shell) )
All working good til the point I got `plugin.load` error, after little debugging found out bootstrap is not present in `node_modules`. So I stopped the application and `npm install bootstrap` worked fine but when I am doing `au run --watch` it does not run the server instead it shows me the screen when we normally do just `au`

![image](https://user-images.githubusercontent.com/7036532/36251265-9655ddd8-1266-11e8-8e45-ca3d58a74b4e.png)

* **What is the expected behavior?**
After installing any dependency it should run the application

PS: I am new to Aurelia and coming from AngularJS  background
Thanks

**Comment by charlesodili** [comment]
I am experiencing the exact same thing with the Contact Manager tutorial application. Everything was working fine until I ran ```au run --watch``` after installing bootstrap and jquery, as recommended by the tutorial.  While I await a fix for this, I think I will try re-doing the tutorial without the bootstrap and jquery dependencies - whatever they are intended for, in the project, I can write by hand.

**Comment by monis01** [comment]
so, any update on this other than doing tweaks?

**Comment by charlesodili** [comment]
See what I explored here: https://twitter.com/chaluwa/status/966611908274130950

**Comment by monis01** [comment]
But the point is tutorial itself is breaking if following official docs (I mean it does not work until if we tweak and trick things out). Btw I have not came across other tutorials for aurelia other than what is mentioned in docs, if anyone here plz do share.
Thanks

**Comment by Rud156** [comment]
@monis01 I think this will be helpful https://www.youtube.com/channel/UCtWxbsaQzLIHR3Jl-Q0ZlmA

**Comment by JeroenVinke** [comment]
for some reason it seems to uninstall aurelia-cli from your node_modules after installing bootstrap, but we'd have to debug it further. I wonder if this has anything to do with the package-lock.json file that NPM creates

**Comment by Alexander-Taran** [comment]
There is a lot of bad rep for recent versions of npm. Like kining the production servers and such.
I'd wait out the storm

**Comment by fkleuver** [comment]
@monis01 @JeroenVinke This is a npm 5.6.0 problem and it should be fixed with the recent 5.7.1. Maybe update the docs to explicitly mention this because lots of people will probably still be running 5.6.0 for a while..

**Comment by Alexander-Taran** [comment]
CLI has been updated
@monis01 & @charlesodili 
do you still have this problem ?

**Comment by JeroenVinke** [comment]
I'd think so, because this is an issue with the NPM version installed on your machine, not the version that the CLI uses internally

i've added this to the docs PR here: https://github.com/aurelia/cli/pull/747
