### ISSUE TITLE
Aurelia CLI does not compile on invalid media query (Stylus, RequireJS)

### ISSUE THREAD

**Issue by Rud156** [aurelia/cli#829]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
9.5.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
TypeScript 2.7

* **Loader/bundler:**
RequireJS

**Current behavior:**
If you setup Aurelia CLI to use Stylus and write some invalid media query like `@media only screen and (max-width: )` and save the file. Then complete the media query like `@media only screen and (max-width: 50px){}` and resave the file. The compiler gets blocked saying `A build is already in progress, deferring change detection`. The compiler needs to be restarted to compile further.

* **What is the expected behavior?**
The compiler throws error for the invalid `stylus` and then recompiles automatically when the offending file has been fixed.

* **What is the motivation / use case for changing the behavior?**
The compiler should error as it does now. But upon saving a valid stylus code it should recompile automatically instead of requiring a restart.

**Comment by Alexander-Taran** [comment]
@Rud156 whould you like to provide a PR for this?

**Comment by Rud156** [comment]
@Alexander-Taran I would like to but have no idea as how to go about it

**Comment by Alexander-Taran** [comment]
I'll try to reproduce the error and give some pointers on how to handle this.
Meanwhile you can try to trace the behavior with debuging the cli

https://discourse.aurelia.io/t/better-know-a-framework-4-debugging-cli/871/2

**Comment by Alexander-Taran** [comment]
Ok. I got it reproduced.

**Comment by Alexander-Taran** [comment]
@Rud156 
I've submited a pull request to fix cli for future generations of stylus users
in the mean time, to fix your setup, you can modify your 
aurelia_project/tasks/process-css.ts to look like this

```
import * as gulp from 'gulp';
import * as changedInPlace from 'gulp-changed-in-place';
import * as sourcemaps from 'gulp-sourcemaps';
import * as stylus from 'gulp-stylus';
import * as plumber from 'gulp-plumber';
import * as notify from 'gulp-notify';
import * as project from '../aurelia.json';
import {build} from 'aurelia-cli';

export default function processCSS() {
  return gulp.src(project.cssProcessor.source)
    .pipe(plumber({ errorHandler: notify.onError('Error: <%= error.message %>') }))
    .pipe(changedInPlace({firstPass:true}))
    .pipe(sourcemaps.init())
    .pipe(stylus() )
    .pipe(build.bundle());
};
```

**Comment by Rud156** [comment]
Thanks a lot. But I think that shouldn't plumber and notify be present in each gulp file. Currently 2 files are left out. On  is the `lint` file and the other is the `processMarkup` file.

**Comment by Alexander-Taran** [comment]
@Rud156 are there any known issues with the plugins used in those that throw exceptions and prevent watch from continuing?

**Comment by Rud156** [comment]
@Alexander-Taran These are the files that can cause a problem.
```
https://github.com/aurelia/cli/blob/master/lib/resources/tasks/process-pug.js
https://github.com/aurelia/cli/blob/master/lib/resources/tasks/process-sass.js
https://github.com/aurelia/cli/blob/master/lib/resources/tasks/lint.js
```
 I'll make a PR for this tonight

**Comment by Alexander-Taran** [comment]
@EisenbergEffect @JeroenVinke 
do we want to play safe and add plumber to all tasks just in case?

**Comment by EisenbergEffect** [comment]
I'll leave this decision up to @JeroenVinke

**Comment by JeroenVinke** [comment]
@Alexander-Taran i wonder if this would change the exit code to always be zero which could affect CI's (e.g. CI's that do au build and fail when the exitcode is non-zero)

**Comment by Alexander-Taran** [comment]
@Rud156 can you test what exit code would au build produce with my fix? I already deleted the repro

**Comment by Alexander-Taran** [comment]
@JeroenVinke yep. Like this it will be zero.
there is a relevant comment:
https://gist.github.com/floatdrop/8269868#gistcomment-1751738

proposed solution is conditional variable

we are trying to be DRY and to be awesome during development and in CI
where in dev we want it to be smooth and forgiving but fail hard otherwise.

we already use plumber in  other tasks for less, markup and transpile (babel)

**Comment by Rud156** [comment]
@Alexander-Taran The build doesn't stop. It throws an error but continues to build. Sorry about the super late reply
