### ISSUE TITLE
moduleNameMapper section in jest config sometimes prevents testing

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/cli#834]
# clarification of a confg setting needed

https://github.com/aurelia/cli/blob/81b029191f4752fecdaf0192bb03c7cd0bc87d8f/lib/commands/new/buildsystems/webpack/unit-test-runners/jest.js#L90-L92

while figuring out https://github.com/aurelia/framework/issues/869 and https://github.com/aurelia/testing/issues/80

I discovered that for my setup 
typesccript 
jest
and a jest section in package.json like this:
```
  "jest": {
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest"
    },
    "modulePaths": [
      "<rootDir>/src",
      "<rootDir>/node_modules"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testRegex": "\\.spec\\.(ts|js)x?$",
    "setupFiles": [
      "<rootDir>/jest-pretest.ts"
    ],
    "testEnvironment": "node"
  }
```
everything works fine without that mapping.

for a project created by cli

```
    "moduleNameMapper": {
      "aurelia-(.*)": "<rootDir>/node_modules/$1"
    }, 
```

seems to work fine.. but I don't understand why it is needed in the first place.
Seems somehow tied to typescript compilation target?

It is for mocking the modules after all.

Please provide some insight at why it is there and I'll start on a PR documenting the configs.

**Comment by JeroenVinke** [comment]
I'm in the process of updating webpack to 4.0 and noticed an issue with this as well (it tried to locate aurelia-polyfills in `node_modules/polyfills` instead of `node_Modules/aurelia-polyfills`. I had to change

```
moduleNameMapper: { 
   'aurelia-(.*)': '<rootDir>/node_modules/$1' 
 }, 
```
to
```
moduleNameMapper: { 
   'aurelia-(.*)': '<rootDir>/node_modules/aurelia-$1' 
 }, 
```

I'll have a closer look to see if this is still necessary

**Comment by Alexander-Taran** [comment]
@JeroenVinke 
with that change you probably will face the other issue as in m.configure is not a function.
This one is really weird one. Can't understand the need for it.

**Comment by JeroenVinke** [comment]
I didn't get that error, but i'll remove the section, it seems to be unnecessary

**Comment by Alexander-Taran** [comment]
No clarification then huh? (-:

**Comment by JeroenVinke** [comment]
Maybe @niieani can shed some light on this

**Comment by niieani** [comment]
It is there in case of duplicated Aurelia modules inside of nested `node_modules`. This ensures we resolve to the top-level version of each Aurelia module. Naturally, there was a typo, as it should be:

```js
moduleNameMapper: {
  'aurelia-(.*)': '<rootDir>/node_modules/aurelia-$1'
},
```

**Comment by JeroenVinke** [comment]
Thanks @niieani 

@Alexander-Taran do you have the issue even when using `'<rootDir>/node_modules/aurelia-$1'` instead of `'<rootDir>/node_modules/$1'?

**Comment by Alexander-Taran** [comment]
It's not me who had it. And I think there were some. Yes.
It was very strange. 
I still think that it should stay removed unless there will be issues with jest without it. Jest docs say it is meant to mock modules specified by name with modules located at value.

**Comment by Alexander-Taran** [comment]
troublesome code removed
closing this one
