### ISSUE TITLE
Request: Update Webpack to 4.0+

### ISSUE THREAD

**Issue by aligneddev** [aurelia/cli#845]
It would be great if the cli was updated to use webpack 4+.
[Here is a write-up using webpack 4](https://medium.com/@mikko.vuorinen/aurelia-skeleton-with-webpack-and-asp-net-core-af9dc5f5b233)

https://github.com/vuorinem/aspnet-aurelia-webpack-skeleton is his linked Github project.

This also might lead the way so I can retry PWAs. https://stackoverflow.com/questions/48023333/aurelia-cli-pwa-with-webpack-and-workbox..

Thanks.

Sorry if this is a duplicate issue.

**Comment by aligneddev** [comment]
I created a new Aurelia app with `au new` and webpack as the option.  I have Aurelia-cli 0.32.0 installed.
Then I went through these steps:
* update all webpack
* error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead. 
  * https://bluebottle.idv.tw/?p=12482 ???
* https://medium.com/@mikko.vuorinen/aurelia-skeleton-with-webpack-and-asp-net-core-af9dc5f5b233 talks about WP4
  * https://github.com/vuorinem/aspnet-aurelia-webpack-skeleton/blob/master/webpack.development.js  
* copied in his webpack files
* copy in package.json scripts
* npm install webpack-cli --save
* built!!
* ERROR in ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
Module not found: Error: Can't resolve 'ts-loader' in 'c:\git\aurelia\pwa\hn-pwa'
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server aurelia-bootstrapper
i ｢wdm｣: Failed to compile.
  * npm install ts-loader --save
* It kind of works now:


ERROR in c:\git\aurelia\pwa\hn-pwa\tsconfig.json
[tsl] ERROR
      TS5051: Option 'sourceRoot can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided.
i ｢wdm｣: Failed to compile.

I'll try to sneak some time in tomorrow during work to push this a bit further and have a better write with project (if I can get past the production bug when I left for the day :-)).

**Comment by Alexander-Taran** [comment]
You can use webpack 4 with updated version of aurelia webpack plugin

For configs you can lookup jods4 repository with demoes

Next version of CLI will have it

**Comment by aligneddev** [comment]
Thanks @Alexander-Taran. I'm adding the link to the repo for easier finding: https://github.com/jods4/aurelia-webpack-build

**Comment by aligneddev** [comment]
https://twitter.com/AureliaEffect/status/973943835146444800
