### ISSUE TITLE
Implement SSR support in Aurelia CLI

### ISSUE THREAD

**Issue by rquast** [aurelia/cli#847]
Since SSR seems to be working reasonably well, an SSR option to the CLI for webpack builds. This would be a great thing for new people who want SEO without having to fork the typescript skeleton or create a static build. Both TS and esnext should also be supported.

**Comment by Alexander-Taran** [comment]
How do you envision this?

**Comment by rquast** [comment]
The addition of server-main.js, webpack server config, server.js, ssr dependencies and anything else required to run a Koa SSR server.

**Comment by Alexander-Taran** [comment]
Would you like to get a stab at pull request for it @rquast?

**Comment by rquast** [comment]
@Alexander-Taran Sure. I'll give this a go once I've submitted the PR for the ssr updates.

**Comment by Alexander-Taran** [comment]
Yeah.. no rush with that.
Would love to have your how-to ssr though in contrib.
Like a journey to a result.

**Comment by JeroenVinke** [comment]
@rquast that’s the plan exactly

**Comment by Alexander-Taran** [comment]
)-: never happened

@3cp can be closed I think.
Although I remember @rquast being very enthusiastic about the topic.
And made a huge progress.
