### ISSUE TITLE
latest 0.33.0 release breaks apps bootstrapped with requirejs/systemjs

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/cli#848]
**I'm submitting a bug report**

* **Library Version:**
0.33.0

* **Loader/bundler:**
SystemJS | RequireJS

**Current behavior:**
* **What is the expected behavior?**
* **What is the motivation / use case for changing the behavior?**

@EisenbergEffect latest 0.33.0 release breaks apps bootstrapped with requirejs/systemjs

The `gulp-babel` version was upgraded from `7.0.1` to `8.0.0-beta.2` in a routine version pump.
https://github.com/aurelia/cli/blob/a38fb45a57ab18bda89dfcf77decf442eccb6659/lib/dependencies.json#L49

But `8.0.0-beta.2` requires additional peer dependency on `@babel/core`.

Even after manually install `@babel/core`, the app would not build properly, gulp complains
```
gulp-notify: [Error running Gulp] Error: .code is only allowed in root programmatic options
```

Revert back to `7.0.1` solves the issue. This issue doesn't affect webpack since it doesn't use `gulp-babel`.

**Comment by EisenbergEffect** [comment]
Released fix! Apologies!

**Comment by tjad** [comment]
I've run into a similar issue since updating my dependencies. What is the actual meaning / cause of this error?

**Comment by tjad** [comment]
I generated a fresh project and swapped out my .babelrc for the new .babelrc.js which is not 100% yet, but looks much healthier!

**Comment by huochunpeng** [comment]
It could be you have babel6 in your existing app. When you upgrade cli on an app you haven’t touched for quite a while, there are lots of other deps have to be upgraded too.

It is easier to create a fresh app skeleton then copy over your existing source code.
