### ISSUE TITLE
"au new --here" still has old defaults

### ISSUE THREAD

**Issue by mobilemancer** [aurelia/cli#855]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Current behavior:**
The "au new --here" alternative still use the old deafult for bundler (RequireJS)

* **What is the expected behavior?**
Default bundler: WebPack

**Comment by ghiscoding** [comment]
Also noticed that and was very surprised of it since I heard it was supposed to change.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/pull/867
