### ISSUE TITLE
GZip compression as a build option?

### ISSUE THREAD

**Issue by gama410** [aurelia/cli#871]
**I'm submitting a feature request**

* **Library Version:**
any

**Please tell us about your environment:**
* **Operating System:**
any

**Current behavior:**
No compression on output bundles

* **What is the expected behavior?**

I was wondering if there was a reason why output compression was not activated/activatable with the serve task.
I was thinking it could maybe be activated behind a flag like _au run --watch --compress_...
Which would just add a compression middleware to browsersync's server config...

* **What is the motivation / use case for changing the behavior?**

In my opinion, this could be a nice addition without any side effect...
Thanks for your insight!

**Comment by avrahamcool** [comment]
actually, this is applicable for `build` even more than for `run`.
you typically use `run` in the developing stage, where compression is not relevant as much.

`run` calls `build` internally, so if the flag is available for `build` - you will be able to also use it with `run`.

**Comment by gama410** [comment]
I was not really thinking of gzipping the bundles themselves but rather gzipping them on the fly as my output is actually served from a different server in production environment in which compression is handled implicitely.

I implemented that feature in my codebase (for the run task) and it works quite well. This looks like this:
``
var compress = require('compression');
...
var middlewares = (CLIOptions.hasFlag('compress')) ? 
[historyApiFallback(), compress(), function(req, res, next) { res.setHeader('Access-Control-Allow-Origin', '*');  next(); }] :
[historyApiFallback(), function(req, res, next) { res.setHeader('Access-Control-Allow-Origin', '*');  next(); }];
...
server: {
                baseDir: [project.platform.baseDir],
                middleware: middlewares
            }
``

**Comment by Alexander-Taran** [comment]
@gama410  It looks more like a recipe. Would you like to provide one?

**Comment by gama410** [comment]
@Alexander-Taran gladly! Although I'm not sure of what I would have to do...

**Comment by Alexander-Taran** [comment]
# How to enable gzip compression when..

step by step instruction 
(-:

and PR here: https://github.com/aurelia-contrib/aurelia-getting-started/tree/master/guides

I sometime wish to see the true minified sizes too

**Comment by gama410** [comment]
I created a PR for aurelia-getting-started [here](https://github.com/aurelia-contrib/aurelia-getting-started/pull/30)

**Comment by gama410** [comment]
Although I would be interested to know the point of view of some aurelia's core team member about the presence of this flag directly in aurelia-cli 's code...

**Comment by Alexander-Taran** [comment]
@gama410 thanks for the PR

**Comment by Alexander-Taran** [comment]
@gama410 about adding it to CLI itself.. I for one don't think it is a good idea.
It brings down a dependency.
It has to be supported
For webpack as well
and 99% of the time it will not be used.

I merged your pr and made some edits.. mostly cmd-line formatting.
I'll add it to index and will have a post @ discourse

**Comment by michaelw85** [comment]
I would love to see this by default. I can't think of a reason why you would not want to use gzip and minification when publishing something to production.

To get gzip compression working with webpack I did the following changes:
1) `npm i compression-webpack-plugin --save-dev`
2) Edit webpack.config, 
add to top: `const CompressionPlugin = require('compression-webpack-plugin');`
add to plugins section: 
```
...when(production || server, new CompressionPlugin({
      algorithm: 'gzip'
    })),
```

In addition to gzip I also added Uglify for production
1) `npm install uglifyjs-webpack-plugin --save-dev`
2) edit webpack.config
add to top: `const UglifyJSPlugin = require('uglifyjs-webpack-plugin');`
add to plugins section: `...when(production || server, new UglifyJSPlugin())`

**Comment by huochunpeng** [comment]
Most web server (like nginx) handles gzip for static resources. I believe CDN also handle it transparently. It is most commonly being handled in that stack. It is unnecessary to build js.gz in app bundling.

That is why we did not bring it in here. Pre-build js.gz file might complicate setup in lower stack of the server.

**Comment by michaelw85** [comment]
Are you sure this is true? Serving gzip files yes but as far as i'm aware compressing the files is not done by default.

**Comment by michaelw85** [comment]
Fair point, make the server handle it instead of adding it to the build would be easier to manage. 
Could this issue be closed if it will not be fixed?

**Comment by huochunpeng** [comment]
Nginx does not need you provide gz file. It does gzip on the wire.

http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip

With help of reverse proxy cache, it is likely it will only compress once for a resource.

**Comment by huochunpeng** [comment]
@EisenbergEffect this can be closed.
