### ISSUE TITLE
"No strategies were able to configure" bpmn-js

### ISSUE THREAD

**Issue by pmanu93** [aurelia/cli#872]
**I'm submitting a bug report**
* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
Linux Mint 17.3 Rosa

* **Node Version:**
v8.10.0

* **NPM Version:**
5.8.0

* **Language:**
all

* **Loader/bundler:**
RequireJS

**Current behavior:**

I'm trying to install the "bpmn-js" library using the `au install` command but returns the following exception:
[gist](https://gist.github.com/pmanu93/3d69801ff93f3ce00fc30fa9d3f4af2c)

* **What is the expected behavior?**
As written in the error above, Aurelia CLI should (?) be able to configure the package.

I'm only filling this issue as requested in the error.

Btw, I ended up configuring the library with the following:
```json
{
 "name": "bpmn-js",
 "main": "bpmn-navigated-viewer.production.min",
 "path": "../node_modules/bpmn-js/dist",
 "resources": []
}
```

**Comment by Alexander-Taran** [comment]
@pmanu93 thank you for report

**Comment by huochunpeng** [comment]
Ref bpmn-io/bpmn-js#842
