### ISSUE TITLE
Aurelia Cli with webpack, `au run --watch` does not work with spaces in project directory

### ISSUE THREAD

**Issue by 4imble** [aurelia/cli#873]
**I'm submitting a bug report**

* **Library Version:**
Au Cli - 0.33.1
Webpack - 4.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.9.4

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Loader/bundler:**
Webpack

**Current behavior:**
- Create a folder `C:\Temp\Aurelia Project`
- Create new project there using CLI, I chose Webpack with Typescript
- Install dependencies
- run `au build`
- run `au run --watch`
- Navigating to localhost:xxxx will display `hello world`
- Change any code to trigger watch (it will say all good in console output)
- Go back to browser and notice changes are not reflected (even on refresh)

This seems to be related to the spaces within the path of the project.
If I remove the spaces `--watch` works as expected.

**Comment by TonyLugg** [comment]
Same issue here.  I was actually getting "Cannot GET /" when navigating to localhost:8080 but it suddenly started working.  I have the watch issue though.  It is apprently an issue with the Webpack dev server, see https://github.com/webpack/webpack-dev-server/issues/1375.

**Comment by avrahamcool** [comment]
I almost killed myself today in a live presentation because of this issue.
for the sake of a fellow developers, can somebody fix this?

**Comment by Alexander-Taran** [comment]
@avrahamcool webpack issue.. linked in @TonyLugg reply

**Comment by TonyLugg** [comment]
@Alexander-Taran Agreed.  Since Webpack 4 is now Aurelia's default CLI configuration, will the Aurelia team not be keeping an eye on this Webpack issue to get the Aurelia community a fix as soon as possible.  It is such a fundamental flaw that will likely bite many of us.

**Comment by Alexander-Taran** [comment]
@JeroenVinke would we want to temporarily lock the webpack < 4.2 ? or remove `lazy:true` and lock < 4.5 ?

**Comment by TonyLugg** [comment]
I created a new project and it is building with webpack 4.12.0 and this issue is resolved.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect  this one can be closed then (-:
