### ISSUE TITLE
after npm install au run fails with missing module gulp

### ISSUE THREAD

**Issue by fjogstad** [aurelia/cli#878]
**I'm submitting a bug report**

* **Library Version:**
0.33.0

**Please tell us about your environment:**
* **Operating System:**
Linux (KDE neon (ubuntu 16.04)

* **Node Version:**
10.1.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
all 

**Current behavior:**
When I install packages with npm install bootstrap etc, au run fails to start and complains with missing module gulp. Even if I install gulp it will still fail, but then with missing packages text.

This also happens if I use au install name

Error message:
$ au run
{ Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise (/home/XXX/PROJECT/node_modules/aurelia-cli/lib/commands/gulp.js:19:20)
    at new Promise (<anonymous>)
    at module.exports.execute (/home/XXX/PROJECT/node_modules/aurelia-cli/lib/commands/gulp.js:18:12)
    at _establishProject.then.then (/home/XXX/PROJECT/node_modules/aurelia-cli/lib/cli.js:36:24) code: 'MODULE_NOT_FOUND' }

I am not sure if this is a problem with npm, au cli or node...

* **What is the expected behavior?**
au run should not be affected and installing new packages should not affect my configuration and other installed modules 

To reproduce:
Create a new project with au new and install a packages like jquery or bootstrap. Then attempt to run the project: au run

**Comment by fjogstad** [comment]
Reverted back to 0.32.0 and bug went away.

**Comment by avrahamcool** [comment]
did you try upgrading to 0.33.1 instead of downgrading?

**Comment by fjogstad** [comment]
I tried to upgrade and got the same behavior. I have also tried to delete the project and generate it from scratch multiple times with different loaders and configuration. No difference.

What I have not tried it is to upgrade a project made with the au new 0.32.0 to a 0.33.X and then install a package. I can try that later to day.

**Comment by fjogstad** [comment]
Hm, I do not have yarn, but are there other similar tools that I can have installed that does the same? 

Not sure how I should debug this, any help is much appreciated. I am quite new to node universe and playing with aurelia is my introduction to this world. My background is from the traditional libc, gnu and linux developer world...

**Comment by Alexander-Taran** [comment]
well start from using stable node 8.x.x  and upgrading npm from 5.6.0 it is a source of many issues.
yep. start from upgrading npm.

**Comment by sundayz** [comment]
Same issue with 0.33.1, npm 5.6.0 and node 8.9.4. Downgraded to 0.32.0 and same thing. Everything was working fine until I installed the http client packages.

**Comment by TylerJPresley** [comment]
I've had this issue consistently with NPM 5.6.0. Upgrading NPM fixed this for me. I still have coworkers that run into it after reinstalling node (which installs NPM 5.6.0)

**Comment by jalmansa88** [comment]
I still have this issue here, with v0.33.1 and npm 5.6.0. Removing the npm_modules and making `npm install`, works. However, the issue still happens everytime I make` npm install -somelibrary-`.

**Comment by zewa666** [comment]
The issue is definitely related to npm in v < 6.x.x. This is happening all over the places, also with other frameworks, so please just make sure to update npm.

**Comment by JeroenVinke** [comment]
In the next version `au install` asks wheter to use yarn or npm. Package lock files are not cross compatible so you typically want to use either npm or yarn. That should solve the problems we are seeing in this issue

**Comment by jalmansa88** [comment]
Thank you guys.
