### ISSUE TITLE
"au install" does not work with webpack

### ISSUE THREAD

**Issue by stevies** [aurelia/cli#880]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

* **Loader/bundler:**
Webpack

**Current behavior:**
au install does now work
au import does not work

Example: 
`au install aurelia-store` -  generates error:

> Error: This command is only available for the Aurelia CLI Bundler

If I use npm to install, and then do `au import aurelia-store` - same error as above.

Although webpack is now the CLI default, there does not appear to be any instructions for adding packages (or anything relating to webpack) at: https://aurelia.io/docs/build-systems/aurelia-cli

**Comment by zewa666** [comment]
With respect to aurelia-store nothing besides npm/yarn Install should be needed. What would you expect to happen with au install?

**Comment by stevies** [comment]
When I just did `npm install aurelia-store`, then when I run my app, I get error: 
`Unhandled rejection Error: Unable to find module with ID: aurelia-store`.

Then I followed the instructions at: https://aurelia.io/docs/build-systems/aurelia-cli - that does not work, hence raising this defect.  Perhaps it is the documentation that is out-of-date and needs to be fixed?

Anyway, I still need a means of registering any new included modules when using the CLI with webpack.  Can't find any documentation on how to do this.

**Comment by zewa666** [comment]
The issue you mentioned sounds more like an in App configuration issue. Can you share your main.js/ts where you register the plugin?

Yes the Docs are still pointing to the requirejs cli, and Au Install and import are only necessary for that target since aurelia.json needs to be updated, which isnt needed for webpack though. Npm Install should be enough

**Comment by stevies** [comment]
Standard main.js created from CLI `au new` plus I have an empty object at "./state.js" - just starting to convert over the sample app at aurelia-store and getting blocked at this very early stage. 

```
import environment from './environment';
import {PLATFORM} from 'aurelia-pal';
import 'babel-polyfill';
import * as Bluebird from 'bluebird';
import {initialState} from './state';

// remove out if you don't want a Promise polyfill (remove also from webpack.config.js)
Bluebird.config({warnings: {wForgottenReturn: false}});

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature(PLATFORM.moduleName('resources/index'));

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  if (environment.testing) {
    aurelia.use.plugin(PLATFORM.moduleName('aurelia-testing'));
  }

  aurelia.use.plugin('aurelia-store', {initialState, history: {undoable: true}});

  aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```
I am not sure if I need to start manually hacking around in webpack.config.js - I was assuming `au import` would do any configuration necessary.

**Comment by stevies** [comment]
Looks like I need to add `PLATFORM.moduleName`:
```
  aurelia.use.plugin(PLATFORM.moduleName('aurelia-store'), {initialState, history: {undoable: true}});
```
Nothing else needed now as far as I can see.  OK to close this, I think.

**Comment by zewa666** [comment]
Exactly what I thought. That was the reason
