### ISSUE TITLE
au run does not work (freezing/waiting)

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/cli#881]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7/10 
Tested on two computers

* **Node Version:**
Node 8 / 10 

* **NPM Version:**
5.3.0/6.0.1

* **Browser:**
all

* **Language:**
TypeScript 2.5/2.8

* **Loader/bundler:**
Webpack

**Current behavior:**
Recently I created a new clean project with `au new` and ran with `au run` but compilation does not complete so after browsing `localhost:8080` I have an error but seems the error comes from an incomplete compilation
![untitled](https://user-images.githubusercontent.com/8418700/40097195-07d14f28-58ea-11e8-88de-bf47b9b8a420.png)

I waited about 2 minutes but compilation does not finish !!!

![untitled2](https://user-images.githubusercontent.com/8418700/40097211-197f03d2-58ea-11e8-9997-6b0dbb51ed06.png)

I did not change anything this is a new clean sample, not more !!!

3 Custom > 3 Webpack > 1 Web > 2 Typescript > 3 Maximum Minification > 3 Sass > 3 Jest > 1 Protractor > 1 VS Code > 1 Create Project > 1 Install dependencies

no more no less
no change in code just clean project

`au run` and ... You know !!!
this is the first time to use the latest version of CLI I did not have the problem before

and of course in `Default Typescript` option with custom port `9000`
![sample](https://user-images.githubusercontent.com/8418700/40097243-5167f10a-58ea-11e8-8bd8-59b94754928b.png)

the same result in another PC

![untitled3](https://user-images.githubusercontent.com/8418700/40097288-891057f0-58ea-11e8-80e8-a3d91d5acd14.png)

Can anyone guide me?

**Comment by avrahamcool** [comment]
what is the `npm` version in the other computer?
can you upgrade `npm` and try again?

**Comment by HamedFathi** [comment]
@avrahamcool 

```node -v => 8.9```
```npm -v => 5.3.0```

Based on your request I updated nodejs to 10.1.0 on my office PC so now

```node -v => 10.1.0```
```npm -v =>  5.3.0```

The same as before :(

**Comment by avrahamcool** [comment]
I just tried with `yarn` and `npm` and it works fine.
(also I had problems when installing dependency because of bad network)

can you try answering `no` to the `cli` when he tries to install your dependencies, and then install them by yourself, and see if something changes?

`npm -v` : `6.0.1`
`yarn -v`: `1.6.0`
`node -v`: `v8.11.1`

**Comment by HamedFathi** [comment]
@avrahamcool 

Thank you, my friend 👍
