### ISSUE TITLE
Switch option order for integration test choise

### ISSUE THREAD

**Issue by mobilemancer** [aurelia/cli#885]
**I'm submitting a feature request**

* **Library Version:**
0.33.1

**Current behavior:**
Would you like to configure integration testing?

1. Protractor (Default)
   Configure your app with Protractor
2. No
   Skip testing. My code is always perfect anyway.

* **What is the expected behavior?**
Would you like to configure integration testing?

1. No
   Skip testing. My code is always perfect anyway.
2. Protractor (Default)
   Configure your app with Protractor

* **What is the motivation / use case for changing the behavior?**
I propose a switch of order to be more consistent with the other options that use option 1 for None/Default

**Comment by bigopon** [comment]
This feels funny to me, someone may actually write test because of this, not sure if it's a bad thing 😆

**Comment by zewa666** [comment]
Wonder why for other scenarios No is the default answer.

**Comment by mobilemancer** [comment]
Imo, for when setting up a quick project to do a spike, I think the defaults should all lead to the least amount of install time. But whatever is decided upon, it should at least be consistent :)
