### ISSUE TITLE
Proposal: 4 space indentation instead of the current default 2

### ISSUE THREAD

**Issue by Vheissu** [aurelia/cli#887]
Currently when you start a new Aurelia CLI project the default setting in `.editorconfig` is 2 space indentation. This is an argument that has hung over the heads of programming since the dawn of time (it's inscribed in caves from thousands of years ago).

I am proposing we change this to be 4 by default. It might be personal preference and bias, but I find that 4 character space indentation looks the nicest and is easier to read.

Perhaps more radically we could offer users the option to configure if they want tabs (who seriously even wants tabs anyway?) and spaces, or just the number of spaces for indentation.

**Comment by fkleuver** [comment]
Option to configure: 👍
4 space default: 👎
I like my code dense. Less scrolling, less eye movement. More info at a glance.

**Comment by Alexander-Taran** [comment]
that's why tabs could work better in teams with more than 1 person.
everyone can have their own tab "width" (-:
