### ISSUE TITLE
Out-of-the-box high vulnerabilities for Aurelia-CLI generated projects

### ISSUE THREAD

**Issue by zewa666** [aurelia/cli#888]
**I'm submitting a bug report**

* **Library Version:**
latest

**Please tell us about your environment:**
* **Operating System:**
all

**Current behavior:**
The out-of-the box setup has a dependency on npm which is introducing vulnerabilities with `https-proxy-agent`. Run `npm audit` to see the vulnerability marked as `high`

* **What is the expected behavior?**
Do we even need npm as a dependency? Chances are extremely high the user has node installed anyways, so dropping that and defining a min version via the engines section in the package.json file.

* **What is the motivation / use case for changing the behavior?**
Get rid of high vulnerabilities

**Comment by JeroenVinke** [comment]
Yeah we should just run `npm install` from the project directory

**Comment by zewa666** [comment]
@JeroenVinke so something like the following should be enough?

```typescript
const npm = spawn('npm', ['install'], { cwd: projectPath });
npm.on("exit", () => {
  // continue with process
});

npm.on("error", (e) => {
  // handle error
});
```

**Comment by JeroenVinke** [comment]
@zewa666 exactly

**Comment by JeroenVinke** [comment]
@huochunpeng can we really close this, or are there other vulnerabilities left?

**Comment by huochunpeng** [comment]
There are two low vulnerabilities left due to outdated deep dep on loash from browser-sync. Nothing I can do about it.

**Comment by zewa666** [comment]
I think this is good enough. The mission with this story was to eliminate the critical ones.
