### ISSUE TITLE
Bundle bug, copy bundle to dist

### ISSUE THREAD

**Issue by zewa666** [aurelia/cli#89]
Today I've worked through the process of bundling and together with @ahmedshuhel found out that it seems to be necessary to copy over the bundled file into the `dist` folder, which is a problem because you cannot do another bundle run afterwards because it tries to bundle that file as well.

Besides that it seems that choosing `app` as bundle name is not good as it collides with some framework internals. Lets maybe update the README and name it either `build` or `deploy`.

**Comment by PWKad** [comment]
To circumvent the issue and prevent adding another task to move the bundle (which I do currently in my bundles, but seems to confuse users not familiar with gulp) I suggest we simply add another path to the config.js to point to the bundles and have a bundles folder

**Comment by ahmedshuhel** [comment]
@zewa666 @PWKad I want to investigate this issue a little more. This seems more like a  systemjs `path` issue than bundling where cli place the bundle. @PWKad excellent Idea. I am assigning this to myself.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect @zewa666 @PWKad @joelcoxokc 

CLI wil now handle this. Suppose, if we configure the bundle in `aureliafile.js` as:

```javascript
  aurelia.command('bundle', {
    js: {
      "dist/app-bundle": {
        modules: [
          '*',
          'aurelia-bootstrapper',
       },
    options: {
        inject: true
    }
```
considering the paths as:
```javascript
  "paths": {
    "*": "dist/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
```

If we run `aurelia bundle`, `app-bundle.js` will be created in `dist` folder and the injection in `config.js` will look like:

```javascript
  "bundles": {
    "app-bundle": [
      "npm:core-js@0.9.15/modules/$.fw",
      "npm:core-js@0.9.15/modules/$.dom-create",
      "npm:core-js@0.9.15/modules/$.shared",
 ```

Thus, application will load the bundle seamlessly.

**Comment by corydeppen** [comment]
In your example, you're referencing the `dist` directory, which would suggest the scripts within it have already been transpiled and may reference source maps if that option was specified. It's also possible the `sourceMaps` option can be specified when bundling using jspm. Considering the source files would be the transpiled scripts, it doesn't seem like the source maps produced by the bundle command would be useful.

**Comment by ahmedshuhel** [comment]
@corydeppen I am not sure about it yet. Let us find out and we will let you know.

**Comment by ahmedshuhel** [comment]
@corydeppen you are right, setting `sourceMaps` in the bundle config will not be useful in this case. But I am wondering if the source map that is produced by gulp transpile sitl works after bundling.

@EisenbergEffect Do you have any suggestion regarding this?

**Comment by EisenbergEffect** [comment]
I'm not sure that it's a good idea to include source maps in the final bundle. That would increase the size substantially, would it not?

**Comment by ahmedshuhel** [comment]
Right, for the final bundle it would probably be a burden. But, sometime issues occur after bundling such as [this](https://github.com/aurelia/cli/issues/118). So for debugging purpose it may be useful to have `sourceMaps `.

**Comment by ahmedshuhel** [comment]
The original issue is fixed already so closing this issue. @EisenbergEffect If you think we should investigate options for sourceMaps, we can create a new issue and continue discuss there.

**Comment by PWKad** [comment]
Agreed with @EisenbergEffect on this one, the source maps are larger than the minified files.  To debug issues it would seem to make more sense to simply unbundle IMO.

**Comment by EisenbergEffect** [comment]
We can track adding a source maps option in a separate issue, but I would put that at the bottom of the list. Many more important things to do first.
