### ISSUE TITLE
au run not working with custom WebPack insllation but npm start works

### ISSUE THREAD

**Issue by ghiscoding** [aurelia/cli#892]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.11.0

* **NPM Version:**
5.6.0

* **Browser:**
all 

* **Language:**
TypeScript 

* **Loader/bundler:**
Webpack

**Current behavior:**

* **What is the expected behavior?**
`au run` should start the application

* **What is the motivation / use case for changing the behavior?**
I would like to use default CLI command `au run` instead of running `npm start`. This always happen when I choose a custom installation with (1. `WebPack`, 2. `TypeScript`, 3. `SASS`, 4. `Jest` & finally 5. `Protractor`)

**Comment by avrahamcool** [comment]
try to run `au run --watch`.

https://github.com/aurelia/cli/issues/863

**Comment by ghiscoding** [comment]
thanks @avrahamcool 
I couldn't find any ticket referencing this issue but after seeing the issue you sent, I see it's a duplicate of #852 so I'll close and thanks for the command, I'll give that a try.

**Comment by avrahamcool** [comment]
yes.. its the same workaround..
