### ISSUE TITLE
Errors in default, empty webpack project: Uncaught (in promise) - Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by hanssens** [aurelia/cli#894]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
macOS 10.13.5

* **Node Version:**
8.9.4

* **NPM Version:**
5.5.1

* **Browser:**
Chrome 67.0.3396.87 (Official Build) (64-bit)

* **Language:**
TypeScript 2.5.2

* **Loader/bundler:**
Webpack

**Current behavior:**
On starting a new, Default TypeScript project (with Webpack), without any modifications, my Google Chrome browser throws the following errors multiple times:

> Uncaught (in promise) {message: "Could not establish connection. Receiving end does not exist."} [browser-polyfill.js:610]

![image](https://user-images.githubusercontent.com/493382/41847488-6ee71d32-787a-11e8-81fc-03d4536b433e.png)

* **What is the expected behavior?**
Expected behaviour is not having any console errors. 

Steps to reproduce:
1. Run `au new` to create a new app (with CLI v0.33.1), giving it name `foo`
2. Choose options 2 => 1 => 1 to create a _Default TypeScript_ project and install all dependencies
3. Navigate to folder, `cd foo` and run `au run --watch`
4. Open the browser and the console errors pop up, on my system

**Comment by doktordirk** [comment]
hmm, works for me but i have a more current node and tsc. maybe update those if you can

**Comment by alexss3** [comment]
I have been experiencing this problem for a few days now. Initially I thought it was something in my Angular 6 code as it first appeared after I made some changes, but it is now appearing on completely different websites.

**OS:**
Windows 7 Enterprise x64

**Node:**
8.11.1

**NPM:**
6.1.0

**Browser:**
Chrome Version 66.0.3359.139 (Official Build) (64-bit)


![webpack-errors](https://user-images.githubusercontent.com/24757608/41971859-264687a6-7a10-11e8-95c4-fe977796eb45.PNG)

**Comment by doktordirk** [comment]
hmm, i don't have a 'browser-polyfill' in my tsc project. i did find some in some babel projects!?

**Comment by alexss3** [comment]
I should comment that my issue is most likely not related to the aurelia project, but I stumbled upon this thread from a Google search.  Perhaps my previous comment can help provide clues as to how these errors are occurring.

**Comment by hanssens** [comment]
I think I found the cause - and the solution to this. I asked a colleague to try and reproduce the problem. Without success. He ran pretty much the same configuration as me.

I started playing around with my Chrome Extensions, disabling them one-by-one, and the problem was resolved once I **disabled the Selenium IDE** extension.

![image](https://user-images.githubusercontent.com/493382/41975752-e3e98d98-7a1b-11e8-8993-86d6f7a5d549.png)

For me this fixes it, therefor I'll close this issue.

**Comment by PankajMoolrajani** [comment]
It was selnium after all :)

**Comment by darwinguz** [comment]
pfff thanks so much, selenium was the problem.

**Comment by VijayTallolli12** [comment]
Yes it was selenium extension installed in my browser so am i was getting those errors in console thank you so much for guiding us.

**Comment by mekbiba** [comment]
In my case, it was Adblock Plus, I was testing a vuejs application so i had to white-list the domain.

**Comment by ashok-login** [comment]
After going through all the threads, I understood that, this error is something related to some extension. Hence, I carefully verified all the extensions.
For me, the error was due to **McAfee WebAdvisor 8.1.0.24**. But, here the strange thing is that I have disabled this extension, and hence the error has gone. Once again I enabled the extension, but NO more error.

**Comment by ashok-login** [comment]
After going through all the threads, I understood that, this error is something related to some extension. Hence, I carefully verified all the extensions.
For me, the error was due to **McAfee WebAdvisor 8.1.0.24**. But, here the strange thing is that I have disabled this extension, and hence the error has gone. Once again I enabled the extension, but NO more error.

**Comment by Sakaggi** [comment]
> In my case, it was Adblock Plus, I was testing a vuejs application so i had to white-list the domain.

Same for me

**Comment by devlopersabbir** [comment]
Can anyone explain to me why this error occurred???
I don't want solutions I just want to know why this is happening.
