### ISSUE TITLE
Auto generated Navbar not displaying route titles in Firefox/Safari

### ISSUE THREAD

**Issue by aerickson1024** [aurelia/cli#902]
**I'm submitting a (possible) bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
macOS 10.13 | Windows 10

* **Node Version:**
6.10.3 | 8.13.3

* **NPM Version:**
3.10.10 | 6.2.0

* **Browser:**
Firefox 61.0.1 | Firefox Developer Edition 62.0b8 | Safari 11.1.2

* **Language:**
Javascript

* **Loader/bundler:**
Webpack

**Current behavior:**
The repeat.for section, of my nav-bar element, is not rendering to the screen the title of each navigation object from the router.

* **What is the expected behavior?**

I'm not absolutely sure this is a bug, as I could be doing something wrong, but this does seem to work just fine in Chrome, but in Firefox and Safari it doesn't.  I've created a simple example to show the behavior that I'm talking about.  It can be found [here](https://github.com/aerickson1024/aurelia.routing.problem.git).  

What I am trying to do is mimic the example that is found in the Aurelia documentation on how to pass the router to a bindable property on a custom element and iteratively display each routes title on the screen.  So for example if you have three routes configured and their route names are "Link 1", "Link 2", and "Link 3", then those names would be written to the screen.  As far as I can tell, I have copied the concept exactly as it is shown on the documentation and it does seem to work in Chrome, but in Firefox and Safari, there is zero output to the screen.  I have verified that nothing is added to the DOM when inspecting the parent element.  I have done a lot of testing to determine the issue, and I have found that if I delete all references to the Bluebird library, the routes will then magically appear like they should and when I replace the references to Bluebird, they disappear again.  I suspect this must be a bug of some type, but so far I am unable to determine what exactly the issue is.  Can anyone else confirm this issue or at least explain what might be the cause?

* **What is the motivation / use case for changing the behavior?**
I would like to use the example pattern, from the Aurelia documentation, for an auto generated navigation bar.

**Comment by avrahamcool** [comment]
I don't think this issue is related to the CLI.

look like the issue that is talked here:

https://stackoverflow.com/questions/51348676/aurelia-nav-bar-not-showing-up-any-more

https://discourse.aurelia.io/t/using-require-breaks-router/1411/23?u=huochunpeng

https://github.com/aurelia/templating-resources/issues/355
