### ISSUE TITLE
Build Fail returns a success exit code

### ISSUE THREAD

**Issue by eviatarkhen** [aurelia/cli#903]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.4

* **Node Version:**
10.6.0

* **NPM Version:**
6.1.0

* **Browser:**
all 

* **Language:**
all 

* **Loader/bundler:**
Webpack

**Current behavior:**
`Built at: 07/18/2018 7:13:30 PM
                                Asset      Size  Chunks                    Chunk Names
 a52b483f848b87d49a85f0c58ca28699.eot  8.87 KiB          [emitted]
 ad2ecd48a495cc67b3b33764bee90f14.ttf  8.69 KiB          [emitted]
f9b5d834b2fea5a2b440074e662c2281.woff  15.3 KiB          [emitted]
   app.69055a606879e6f329d3.bundle.js  6.33 MiB     app  [emitted]  [big]  app
vendor.69055a606879e6f329d3.bundle.js   490 KiB  vendor  [emitted]  [big]  vendor
                           index.html  4.42 KiB          [emitted]
                          favicon.ico    30 KiB          [emitted]
Entrypoint app [big] = app.69055a606879e6f329d3.bundle.js
Entrypoint vendor [big] = vendor.69055a606879e6f329d3.bundle.js
[./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js] 5.17 KiB {app} [built]
[./node_modules/aurelia-bootstrapper/node_modules/aurelia-polyfills/dist/native-modules/aurelia-polyfills.js] 24.4 KiB {app} [built]
[./node_modules/aurelia-loader-webpack/dist/native-modules/aurelia-loader-webpack.js] 15.2 KiB {app} [built]
[./node_modules/aurelia-pal/dist/native-modules/aurelia-pal.js] 2.18 KiB {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js] 585 bytes {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/pal-loader-entry.js] 1.56 KiB {app} [built]
[./node_modules/bluebird/js/browser/bluebird.js] 175 KiB {vendor} {app} [built]
[./node_modules/bluebird/js/browser/bluebird.js-exposed] 64 bytes {vendor} {app} [built]
[./node_modules/process/browser.js] 5.29 KiB {vendor} {app} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {vendor} {app} [built]
[aurelia-framework] ./node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js 14 KiB {app} [built]
[aurelia-pal-browser] ./node_modules/aurelia-pal-browser/dist/native-modules/aurelia-pal-browser.js 16.3 KiB {app} [built]
[main] ./src/main.ts 1.5 KiB {app} [built]
[0] multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper 52 bytes {app} [built]
[1] multi bluebird 28 bytes {vendor} [built]
    + 147 hidden modules

ERROR in ./src/stylesheets/app.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'weher-widget';
^
      File to import not found or unreadable: weher-widget.
      in /Users/eviatarkhen/Medorion/medorion-web-ui/src/stylesheets/widgets/widgets.scss (line 9, column 1)
 @ ./src/app.html
 @ ./src/app.ts
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.37 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.ejs] 4.86 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
eviatarkhen:~/Medorion/medorion-web-ui()$ echo $?
0`
* **What is the expected behavior?**
A fail exit code

* **What is the motivation / use case for changing the behavior?**
This behavior is problematic for continues delivery pipelines as there is no indication that the build  failed

**Comment by JeroenVinke** [comment]
Can you try this in `aurelia_project/tasks/build.ts`?

```
function onBuild(err, stats) {
  if (!CLIOptions.hasFlag('watch') && err) {
    console.error(err.stack || err);
    if (err.details) console.error(err.details);
    process.exit(1);
  } else {
    process.stdout.write(stats.toString({ colors: require('supports-color') }) + '\n');

    if (!CLIOptions.hasFlag('watch') && stats.hasErrors()) {
      process.exit(1);
    }
  }
}
```

**Comment by eviatarkhen** [comment]
Perfect. Worked.
Thanks and best regards.
