### ISSUE TITLE
Using NODE_ENV instead of --env produces incorrect warning

### ISSUE THREAD

**Issue by ricardograca** [aurelia/cli#912]
**I'm submitting a bug report**

* **Library Version:**
0.34.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 16.04.5

* **Node Version:**
8.9.3

* **NPM Version:**
6.1.0

* **Browser:**
all
* **Language:**
all

* **Loader/bundler:**
all

**Current behavior:**

When running `NODE_ENV=prod au run` I'm greeted with this contradictory message:

> The selected Node Environment (prod) is not a preconfigured option ('dev', 'stage', and 'prod')

Which is obviously wrong since *it is* one of the preconfigured options.

* **What is the expected behavior?**

The message isn't displayed.

* **What is the motivation / use case for changing the behavior?**

Not getting confused about whether the environment name is actually correct or not.

**Related PR:**

#491

**Proposed solution**

Taken straight from @n2liquid's comment in the linked PR:

```js
let validOptions = ['dev', 'stage', 'prod'];
if (!validOptions.includes(NODE_ENV)) {
  console.log(`The selected Node Environment (${NODE_ENV}) is not a preconfigured option (${validOptions.join(', ')})`);
}
```

**Comment by avrahamcool** [comment]
you should run `au run --env prod`

**Comment by ricardograca** [comment]
That doesn't change the fact that the message is incorrect and using `NODE_ENV` is still a supported way of specifying the environment, so it should work properly.

**Comment by avrahamcool** [comment]
didn't know about that. sorry 👍
