### ISSUE TITLE
Question about dependency on npm

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/cli#914]
The npm package itself is pretty cumbersome. Is there any particular reason why we have to depend on it?

**Comment by huochunpeng** [comment]
I guess you were asking why webpack app still has aurelia-cli dep in package.json?

If so, you are right, aurelia-cli package is not really needed for webpack app. It's just for convenience to run `aurelia_project/tasks/*`. You can try remove aurelia-cli, then have a direct gulp v4 setup to all those tasks.

1. those tasks are in es6 or TS format, you probably need to update them into commonjs format (which is not much work) to make it easier for your gulp setup.
2. those tasks use some help methods from aurelia-cli, like CLIOptions, Configuration, you need to replace those usage.

**Comment by khuongduybui** [comment]
Thanks for the answer, which might be what I will end up doing.
However, my question is really about https://github.com/aurelia/cli/blob/master/package.json#L41

**Comment by huochunpeng** [comment]
Interesting.
@JeroenVinke why we need an explicit "npm" package?
https://github.com/aurelia/cli/commit/987cc68cc6800be6814caa3996ccb2f61011fce7

**Comment by JeroenVinke** [comment]
I don’t know why that dependency was introduced, instead of spawning a “npm install” process. We’re already doing that when the user has yarn installed. We can remove the dependency and replace it with spawn()

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/cli/issues/888 mentions the same, so I think we can close this issue and continue there

**Comment by huochunpeng** [comment]
@khuongduybui for reference, that "npm" is for `au install` command which is irrelevant for webpack users.
