### ISSUE TITLE
Create a new and improved logger

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#93]
Remove the existing logger, and replace it with a new Logger. 

@/all Any Suggestions on the design of the logger?

**Comment by ahmedshuhel** [comment]
We better try to use the [Aurelia Logger](https://github.com/aurelia/logging) without creating a new one.

**Comment by joelcoxokc** [comment]
This Aurelia logger is a logger for the command line.

**Comment by joelcoxokc** [comment]
I made this issue... Because the logger we are using is merely temporary.

**Comment by EisenbergEffect** [comment]
CLI deprecated
