### ISSUE TITLE
Aurelia application wont start on au run

### ISSUE THREAD

**Issue by cluka** [aurelia/cli#932]
**I'm submitting a bug report**

* **Library Version:**
^1.0.0-beta.1

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
10.10.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.0.1

* **Loader/bundler:**
RequireJS

**Current behavior:**
The application does not start after i issue au run command
it throws an error.

* **What is the expected behavior?**
The application should start

Reproduce:
npm install aurelia-cli -g
au new
selected custom bundler then selected RequireJS
restored packages with yarn
then I did: au run and got the error

Error is in the image

![aurelia-error](https://user-images.githubusercontent.com/1827208/46790432-36c03500-cd3f-11e8-8e63-0391a0cc2c1c.png)

* **What is the motivation / use case for changing the behavior?**

**Comment by huochunpeng** [comment]
I could not reproduce the error with nodejs v10.10.0 and yarn on macOS.
Could you try normal nodejs in windows? I mean not in mingw64.

**Comment by cluka** [comment]
I did, tried in windows command prompt. The result is the same error.

**Comment by huochunpeng** [comment]
I will find a windows box to test tomorrow.

Not very familiar with win. Your win command line nodejs, is a different installation than the mingw one, right? If not, please try a normal windows nodejs installation.

Would you mind to test nodejs v8 on your windows box? Thx. It at least worked for few guys I know.

**Comment by cluka** [comment]
Ok,
I tried the following:
1. au run in MingW - same error
2. au run in Windows Command Prompt - same error
3. au run in Windows Command Prompt with Administrative privilegies - same error
4. disable windows firewall and windows defender - same error
5. I tried **netstat -ao**,  and no 9000 or 3001 port is used

Then I tried to start it in a vmware virtual machine that runs Windows 10 too
**it works!**
It seems something on my machine won't let it run.
When I look at the error it says: Error: listen EACCES 0.0.0.0:3001, i don't know if this is correct or not.
I am using Acrylic UI as DNS proxy- maybe this is the issue. will try disabling it and see

**Comment by cluka** [comment]
Yep it seems that **Acrylic UI DNS proxy** was the cause of my problems. After i have deinstalled it, all works.

**Comment by cluka** [comment]
Closing issue

**Comment by cluka** [comment]
The problem was not part of aurelia ecosystem, but machine configuration and used software
