### ISSUE TITLE
Revisions are not inserted into index.html properly

### ISSUE THREAD

**Issue by fragsalat** [aurelia/cli#933]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.1

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 18.10

* **Node Version:**
10.7.0

* **NPM Version:**
6.1.0

* **Browser:**
all

* **Language:**
ESNext

* **Loader/bundler:**
RequireJS

**Current behavior:**
When enabling the revision option in the bundler, it is generating bundles with revision but not updating references in index.html except for vendor-bundle.
```js
"options": {
  "minify": "prod",
  "sourcemaps": "prod",
  "rev": "prod"
}
```
Result
```html
<script src="dist/vendor-bundle-85d36844fc.js" data-main="aurelia-bootstrapper"></script>
<script src="dist/plugin-bundle.js"></script>
<script src="dist/3rd-party.js"></script>
<script src="dist/app-bundle.js"></script>
```

* **What is the expected behavior?**
By enabling the revisioning I would expect all bundles to be updated properly in the index.html

* **What is the motivation / use case for changing the behavior?**
When running in a docker build `au test` and right after `au build --env prod` the live version will use the bundles built for the test runner. In my case it contains code coverage code of istanbul babel plugin^^

**Comment by huochunpeng** [comment]
This is the old v0.35.1 code before auto-tracing

https://github.com/aurelia/cli/blob/c91fb3ef5e3b83f57d3da30ad1d1f225112fec7d/lib/build/bundle.js#L233-L249

Note line 248, it only touches index file for (line 233) a single bundle `loaderOptions.configTarget === this.config.name`, that's vendor bundle by default.

**Comment by fragsalat** [comment]
I also found this code and understood it but I can say that I moved the scripts into the index.html by intent to improve the performance.
I want to load all bundles in parallel to have the code ready when the framework is bootstrapped.

**Comment by huochunpeng** [comment]
Do you have some benchmark comparing to one single fat bundle? Interested to see how much you gain.

**Comment by huochunpeng** [comment]
I have to say code splitting is designed to improve performance by limiting first load.

If you split your code probably, your first page load should be small. For example, if a 3rd party lib is only used by part-a, put the dependence to part-a-bundle.

**Comment by fragsalat** [comment]
1. First of all I'm on a PR to propose a fix of this issue.

2.
I began like you said and had every npm package in the vendor bundle which were quite slow. Now I've splitted up the aurelia core, plugins, 3rd-party which is used by the app and the app itself. With this split I can load the app, the used plugins and so on while the vendor-bundle has to be loaded, parsed, evaluated and the bootstrapper requires the main.js.
I'll make a test soon to get real numbers how much faster that made the load.

**Comment by fragsalat** [comment]
Minified bundles:
```
148K	dist/3rd-party-89dbb4e6cd.js
348K	dist/app-bundle-0b60f48eff.js
176K	dist/plugin-bundle-6a1ca90789.js
16K	dist/test-bundle-4cd90235c8.js
452K	dist/vendor-bundle-32dcc8bb32.js
```

**Comment by huochunpeng** [comment]
It's actually not big. Your users got very limited bandwidth?

**Comment by Alexander-Taran** [comment]
I might be wrong, but script tag in that way tells browser to: 

- stop everything.. 
- load script. 
- run it. 
- and only then go to the next line of html.

so you are gaining nothing.

**Comment by huochunpeng** [comment]
But it obviously made some difference for @fragsalat's app. The "run" step is definitely sequential, but modern browser maybe parallel the fetch (load) step?
