### ISSUE TITLE
ASP.NET core 2 project: Cannot change target to dotnet core 2.1

### ISSUE THREAD

**Issue by IngoBleile** [aurelia/cli#940]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.1

* **Operating System:**
Windows 10

* **Node Version:**
8.12.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.0

* **Loader/bundler:**
Webpack

**Current behavior:**
I cannot change the Visual Studio Project's target from dotnet core 2.0 to dotnet core 2.1, which is installed on my PC. In other ASP.NET core projects, I can set the target to 2.1.

**Comment by Alexander-Taran** [comment]
@IngoBleile can you provide steps to reproduce your issue?

**Comment by jmoerdyk** [comment]
This is more a dotnet core SDK issue, 
It's being pinned by  the global.json file to dotnet core SDK 2.0.0, which only supports dotnet core 2.0 or below:

`{
  "sdk": { "version": "2.0.0" }
}`

 If you install a newer dotnet SDK that supports dotnet core 2.1 (latest is SDK 2.1.500) and update  the sdk version in the global.json, you will be able to change the Target Framework to 2.1 in Visual Studio.

**Comment by IngoBleile** [comment]
Thank you, that solved it! I wasn't aware of the global.json and the settings in there.

**Comment by Alexander-Taran** [comment]
@IngoBleile can you close this?
