### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Robbe64** [aurelia/cli#944]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.14

* **Node Version:**
9.8.0

* **NPM Version:**
5.7.1

* **Browser:**
all

* **Language:**
TypeScript 3.1.3

* **Loader/bundler:**
RequireJS

**Current behavior:**
I'm using the new auto tracing feature and try to to use "sockjs-client:1.3.0". It accesses "var Driver = global.WebSocket || global.MozWebSocket;" but getting this error in the browser:
"Uncaught ReferenceError: global is not defined"
There are solutions for "process" and "Buffer" in the documentation but how can I do this for "global"?

* **What is the expected behavior?**
"global" should be available at runtime.

**Comment by huochunpeng** [comment]
This is in the doc.
https://aurelia.io/docs/cli/cli-bundler/dependency-management

Check "Known problem of auto stubbing core Node.js modules".

**Comment by huochunpeng** [comment]
Try the solution in the doc first.
The sockjs-client probably mapped `global` to `window`.

**Comment by huochunpeng** [comment]
I will test sockjs-client, it got some interesting browser patch.
Meanwhile, you can try its UMD build, I think it will work properly. Add following explicit config to `aurelia.json`.

```
{
  "name": "sockjs-client",
  "path": "../node_modules/sockjs-client/dist/sockjs.min.js"
}
```

**Comment by huochunpeng** [comment]
It's a huge pain for sockjs-client to work with any bundler (including webpack). https://github.com/sockjs/sockjs-client/issues/401

Let me know if my suggested work-around works for you.

**Comment by huochunpeng** [comment]
Ok, tested with 2 successful solutions. You can use either one.

**option1** stub process and global in `main.js`
```js
import process from 'process';
window.process = process;
window.global = window;
```

**option2** add explicit dependency config in `aurelia.json` vendor-bundle` dependencies section.
```
{
  "name": "sockjs-client",
  "path": "../node_modules/sockjs-client/dist/sockjs.min.js"
}
```

You can close this issue, there is no way I can make the npm package automatic.

**Comment by Robbe64** [comment]
Many thanks!
