### ISSUE TITLE
Special Character on Path prevents project from being created

### ISSUE THREAD

**Issue by Rud156** [aurelia/cli#953]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3

* **Operating System:**
Windows 10

* **Node Version:**
10.9.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
all

* **Current behavior:**
If a special character exists on the path. Then `au new` command displays `No Aurelia project found.` then stops asking for the prompts to create the project.

* **What is the expected behavior?**
`au new` should ask for prompts after displaying `No Aurelia project found.`

* **What is the motivation / use case for changing the behavior?**
`au new` does not behave in the expected way to cerate a new project

**Comment by 3cp** [comment]
I am trying to verify this issue. Do you remember what special character had the problem. I tried few (space, `()`, `~!@#%^&-_=+{`) but could not reproduce the issue with 1.0.0-beta.3.

**Comment by 3cp** [comment]
Pls reopen if needed.
