### ISSUE TITLE
Webpack Production Build Broken Using `au build --env prod`

### ISSUE THREAD

**Issue by Vheissu** [aurelia/cli#956]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3

* **Operating System:**
Windows 10

* **Node Version:**
8.11.3

* **NPM Version:**
6.4.1

* **Browser:**
N/A

* **Language:**
TypeScript 3.0.3

* **Loader/bundler:**
Webpack

**Current behavior:**

Build a fresh project using Webpack as the bundler (default). Then attempt to do a production build using `au build --env prod` - the build succeeds, but you get a tonne of log information which appears to be the configuration itself and this breaks CI builds because it's a non zero code.

Worth pointing out, doing a Webpack build using NPS does not break. This can be tested by running `nps build` to do a production build. I strongly suspect this is related to the change in the recent version where a deprecated hook was replaced with a Webpack 4 version.

* **What is the expected behavior?**
Webpack output displays without this wall of text.

**Comment by Vheissu** [comment]
Anyone coming across this issue, even if you update the CLI it won't fix the issue unless you replace `build.js` or `build.ts` in your tasks folder with the new version.  However, the fix is easy to manually make to existing projects.

Replace this line `compiler.hooks.done.tap('AureliaCLI', done);` inside of `aurelia_project/tasks/build.ts` (or .js if you're not using TypeScript) with this: `compiler.hooks.done.tap('done', () => done());` the line is inside of the `buildWebpack` function.

**Comment by 3cp** [comment]
Was fixed by the PR.
