### ISSUE TITLE
Duplication in bundle output using CLI generated webpack config (duplicated modules) 

### ISSUE THREAD

**Issue by chrisckc** [aurelia/cli#958]
With the default CLI generated webpack config, adding jQuery and bootstrap causes issues.

When either jQuery, Bluebird or the jQuery bootstrap extensions are used in code, running webpack results in duplication across both the app and vendor bundles. This causes all kinds of issues when using jQuery.

The CLI generates a package.json that references webpack v4, this also occurs in webpack v3 as used in the skeleton webpack repo, refer to the issue i logged here for more details:

https://github.com/aurelia/skeleton-navigation/issues/894

In the skeleton repo which already includes jquery and bootstrap, the issue is caused by the line `vendor: ['bluebird', 'jquery', 'bootstrap'],` in the webpack.config.js under the `entry` property. 

If jquery and bootstrap are added to the vendor list in the CLI generated config, as initial logic would suggest, referencing jquery in code causes duplication of jquery across the app and vendor bundles.

webpack v4 uses the split-chunks-plugin, the `vendor` under `entry` should not be used:

https://webpack.js.org/plugins/split-chunks-plugin/

https://stackoverflow.com/questions/49017682/webpack-4-migration-commonschunkplugin

Note that commenting out the vendor line results in no vendor bundle being generated and everything being in the app bundle.

To create the separate vendor bundle add the following to webpack.config.js

```
optimization: {
    splitChunks: {
      chunks: "initial",
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          name: "vendor",
          enforce: true,
          priority: 10
        }
      }
    }
  }
```

The above config is just a simple example, the vendor bundle is pretty big and additional config should be added to split it up further, for example separate out the aurelia modules from the rest of the node modules.

The CLI needs to be updated to output a better webpack config to avoid potential developer frustration and the resulting deep dive into webpack that will be required to figure out what's going on.

**Comment by chrisckc** [comment]
This will also be the cause of this issue:
https://github.com/aurelia/cli/issues/918

**Comment by chrisckc** [comment]
Here is a CLI generated project with source files from the skeleton added and various improvements including this fix:
https://github.com/chrisckc/aurelia-cli-skeleton-typescript-webpack

Consider incorporating some of my changes to the webpack config into the CLI code generator to improve the starting experience for newcomers to either Webpack, Aurelia or both.

I have previously started from the 'skeleton-typescript' which uses a gulp based build system. For new projects i have now decided to use webpack but the initial experience has not really been much better and has required a webpack deep dive to get off the ground.

It would be beneficial for Aurelia if devs did not have to do this until much later in the dev cycle when the build system will need to be understood properly.

**Comment by bigopon** [comment]
@chrisckc Very nice. Thanks for this work.

**Comment by chrisckc** [comment]
Closing this as original issue is now fixed, further improvements to webpack config to be discussed here: https://github.com/aurelia/cli/issues/969
