### ISSUE TITLE
Duplicate index.html created with au new and Asp.Net Core

### ISSUE THREAD

**Issue by JamesFenton** [aurelia/cli#962]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
8.9.4

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
SystemJS

**Current behavior:**
After running `au new --here` and selecting SystemJS, the index.html file is created in both the current folder and in the wwwroot folder

* **What is the expected behavior?**
The index.html file should be created only in the wwwroot folder

* **What is the motivation / use case for changing the behavior?**
 The index.html file in the current folder is a duplicate and is never used. This was fixed for RequireJS in https://github.com/aurelia/cli/issues/898 but not SystemJS

**Comment by 3cp** [comment]
systemjs has been removed from our scaffold, because the systemjs we supported was way outdated. Latest systemjs doesn't work with aurelia-loader-default.
