### ISSUE TITLE
Import json file in Typescript 2.9+

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/cli#963]
**I'm submitting a bug report** (I am not sure!)

* **Library Version:**
1.0.0-beta.3

**Please tell us about your environment:**
* **Operating System:**
10

* **Node Version:**
v10.1.0

* **NPM Version:**
6.4.0

* **Language:**
TypeScript 3.1.3

* **Loader/bundler:**
Webpack

**Current behavior:**
I created a webpack, typescript sample with aurelia-cli.
I updated Typescript compiler to latest version 3.1.x and I faced with a problem by importing ` json` files.

![json](https://user-images.githubusercontent.com/8418700/47968518-66cdd000-e080-11e8-96ab-d58540b1b5b4.png)

> Often in Node.js applications a .json is needed. With TypeScript 2.9, --resolveJsonModule allows for importing, extracting types from and generating .json files.

I found out it is a new Typescript 2.9 feature. so I added ```"resolveJsonModule": true,``` to `tsconfig`
but the problem exists.

 After that, I checked this tsconfig with very simple non-aurelia typescript application and all things work perfectly.
![json2](https://user-images.githubusercontent.com/8418700/47968568-376b9300-e081-11e8-89f5-f5cbe0f0eafc.png)

* **What is the expected behavior?**

It should work without error.

Can anybody guide me what is the problem?

**Comment by jbockle** [comment]
I think its due to it being outside the scope of tsconfig, so its inheriting from tslint:recommended.  try adding ```"./aurelia_project/**/*.ts"``` to the tsconfig include array

**Comment by HamedFathi** [comment]
@jbockle 

Thanks, it works now :)
