### ISSUE TITLE
Add `--extractCss' flag to CLI Webpack

### ISSUE THREAD

**Issue by chrisckc** [aurelia/cli#983]
**I'm submitting a feature request**
add `--extractCss' flag to au commandline in webpack projects

This can be acheived by editing "/aurelia_project/tasks/build.ts" as follows:

line 14, from:
```
const extractCss = buildOptions.isApplicable('extractCss')

```
To
```
const extractCss = buildOptions.isApplicable('extractCss') || CLIOptions.hasFlag('extractCss'); // Added to support --extractCss on the CLI commandline

```

**Current behavior:**

The following does not result in separate css files:
```
au run --extractCss
```
instead you have to revert to using an npm command:

```
npm start -- webpack.server.extractCss
```

* **What is the expected behavior?**

To be able to specify extractCss on the au commandline

The docs should also mention the new option:
https://aurelia.io/docs/cli/webpack#running-the-application

* **What is the motivation / use case for changing the behavior?**

To provide a better dev experience and allow easier running of the app with extracted css together with other options.

Note: using the --hmr and --extractCss flags together will result in css updates not being applied.

will also help with this:
https://github.com/aurelia/skeleton-navigation/issues/855

**Comment by 3cp** [comment]
#1137 has made our webpack setup simply uses webpack and webpack-dev-server themself.

This option (`--env.extractCss`) is turned on by default, more details in package.json of a new app.

`au run` is now an alias to `npm start`.

**Comment by 3cp** [comment]
I will restore the option name change in next v1.1.1 release. The option name change is unnecessary breaking. It will be `au run --extractCss`.
