### ISSUE TITLE
RequireJS loader `stub` option with `@useView` decorator -  throws errors

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/cli#984]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta6

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v10.13.0

* **NPM Version:**
6.4.1

* **Browser:**
all
* **Language:**
TypeScript 3.1.6

* **Loader/bundler:**
RequireJS/Aurelia-CLI Auto-tracing Bundler

**Current behavior:**

When having a view model class with `useView` decorator:

```
@useView("/templates/my-view")
class MyView {
    // Code here...
}
```

And loader option `stub: false` in `aurelia.json/loader/plugins` section for `requirejs/text` plugin:
```
    "loader": {
      "type": "require",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": false
        }
      ]
    }
```
new Aurelia-CLI Auto-tracing Bundler tries to resolve `useView` path as NodeJS folder:

> INFO [Bundler] Error: Unable to find package metadata (package.json) of template
> ERROR [Bundler] Failed to add Nodejs module template/my-view

* **What is the expected behavior?**
As in all previous versions of `aurelia-cli`, bundler should not throw errors, while trying to resolve `@useView("/template/my-view")`. View template is, at the end, fetched dynamically from the server, when view is initialized for the first time in the application, but this errors make it ambiguous - if this is supported use-case or accidental behavior.

* **What is the motivation / use case for changing the behavior?**
Make sure/clear that fetching view template dynamically from a web server is supported use case.

**Comment by huochunpeng** [comment]
Please remove leading `/`, requirejs module name does not starts with `/`, also please use html file extension.

Pls try
```
@useView('template/my-view.html');
```

Relative module id should also work
```
@useView('template/my-view.html');
```

**Comment by huochunpeng** [comment]
I am not familiar with webpack. It would be difficult if not impossible. I don’t think the effort is justified as existing requirejs setup did the job really well.

Webpack itself does not provide a runtime module loader. Also aurelia’s loader part is abstracted by aurelia-loader, with aurelia-loader-webpack for webpack setup and aurelia-loader-default for requirejs and systemjs setup. I guess you would bring some dynamic loader (maybe just ajax since you only need a runtime view template), plus monkey patching aurelia-loader-webpack.

**Comment by huochunpeng** [comment]
Stub is only for our requirejs/systemjs setup. It is designed to save little bit on bundle size (by removing text plugin).

I personally think the stub feature should be removed. What it saved is trivial comparing to any real app size, while generating unnecessary confusion.

**Comment by nenadvicentic** [comment]
Just to clarify and perhaps simplify my question.

Is there intention for Aurelia support scenarios where view-templates that are not bundled are fetched from web server?
In other words, is this general feature, regardless of bundler and module loader used behind a scenes by `aurelia-cli`?

**Comment by bigopon** [comment]
@nenadvicentic  Here is an example how you can do it with a `RemoteViewStrategy` https://codesandbox.io/s/8ljmrq3vql

**Comment by nenadvicentic** [comment]
@bigopon Thank you! This is very interesting example.
Is it possible to apply `RemoteViewStrategy` only for certain views, instead of globally? In my use-case, only few "special" views are fetched remotely. Default strategy is used for most of the application.

**Comment by nenadvicentic** [comment]
@bigopon just to come back to you. This was very helpful.

I modified `RemoteViewStrategy` to cache template, so it's downloaded only 1st time view is about to be displayed. I also added `useRemoteView` decorator, to make it easier to configure view-model. Code bellow is TypeScript.

Usage ends up being:

```typescript

@useRemoteView("/template/my-view")
export class MyView {
    // more code here...
}

```
And `RemoteViewStrategy` and `useRemoteView` decorator look like this:

```typescript
import { DOM, ResourceLoadContext, TemplateRegistryEntry, useViewStrategy,
        ViewCompileInstruction, ViewEngine, ViewFactory, ViewStrategy } from "aurelia-framework";

export function useRemoteView(path: string) {
    return useViewStrategy(new RemoteViewStrategy(path));
}

class RemoteViewStrategy implements ViewStrategy {
    private readonly _path: string;
    private _entry: TemplateRegistryEntry;

    constructor(absolutePath: string) {
        this._path = absolutePath;
        if (!absolutePath) {
            throw new Error("Invalid view path");
        }
    }

    public async loadViewFactory(
        viewEngine: ViewEngine, compileInstruction: ViewCompileInstruction,
        loadContext?: ResourceLoadContext, target?: any): Promise<ViewFactory> {
        if (this._entry === undefined) {
            this._entry = await this.loadRemoteView(this._path);
        }

        return viewEngine.loadViewFactory(
            this._entry,
            compileInstruction,
            loadContext,
            target
        );
    }

    public loadRemoteView(path: string): Promise<TemplateRegistryEntry> {

        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open("get", path, true);

            xhr.onerror = (ex) => {
                const view = "<template>Unerwarteter Fehler ist aufgetreten.</template>";
                const entry = new TemplateRegistryEntry(path);
                entry.template = DOM.createTemplateFromMarkup(view);
                resolve(entry);
            };
            xhr.onload = () => {
                const view = xhr.responseText;
                const entry = new TemplateRegistryEntry(path);
                entry.template = DOM.createTemplateFromMarkup(view);
                resolve(entry);
            };
            xhr.send(undefined);
        });
    }
}
```

**Comment by bigopon** [comment]
@nenadvicentic nice. You may want to use fetch instead of xhr too. not sure why i used it 😄

**Comment by nenadvicentic** [comment]
> @nenadvicentic can we close this one? Is there any other task we want from this?

@huochunpeng As far as I'm concerned, it can be closed. You guys provided some very useful information here. Thanks.
