### ISSUE TITLE
Docs not rendering the npm install command

### ISSUE THREAD

**Issue by PWKad** [aurelia/cli#989]
![image](https://user-images.githubusercontent.com/4238393/49241093-7b299200-f3cc-11e8-8cb6-399876708547.png)

It flashes on for a second so you can see it then the value gets removed.

**Comment by huochunpeng** [comment]
![screen shot 2018-11-30 at 7 39 00 am](https://user-images.githubusercontent.com/1188806/49250482-05c4cc80-f473-11e8-989e-2362f3d39ba6.png)

It displays fine with "JavaScript" syntax (strangely not "Shell") in my browser.
The doc is moved to https://github.com/aurelia/documentation/master/current/en-us/11.%20cli/

@EisenbergEffect is that syntax auto detected in client side, or preprocessed in backend?

**Comment by EisenbergEffect** [comment]
It's pre-processed as part of the build. Can someone provide the url and browser info, so I can check it out more?

**Comment by huochunpeng** [comment]
https://aurelia.io/docs/cli/basics#machine-setup
My browser: Safari 12.0 on macOS 10.14.

**Comment by EisenbergEffect** [comment]
This is odd, I can't reproduce it on Safari on Mac. @PWKad Can you try refreshing with a clear cache and see if it's some old CSS or something?

**Comment by PWKad** [comment]
This link does it for me each time - 

https://aurelia.io/docs/build-systems/aurelia-cli/

It looks like that is a separate link than what @huochunpeng shared so probably there is two separate docs for the same thing, let me look.

**Comment by huochunpeng** [comment]
That's looks like messed up old cli doc, if you go one level back, there is a strange "aurelia-cli" section under "build system".

@EisenbergEffect How does it get there? There is no source for the menu item.
https://github.com/aurelia/documentation/tree/master/current/en-us/12.%20build-systems

**Comment by PWKad** [comment]
Fwiw I got there through googling Aurelia cli

**Comment by EisenbergEffect** [comment]
I'm going to guess that we pushed the new docs and because urls changed, the old docs are still there even though they aren't in the site nav. I'll check on it.

**Comment by EisenbergEffect** [comment]
Oh! This explains a lot. I had another user report a CSS issue. It's old pages that aren't getting cleaned on a re-build. Thanks! I'll get this handled soon.

**Comment by huochunpeng** [comment]
@EisenbergEffect besides removing old production files during deployment, please also turn on cli bundle hash.

**Comment by EisenbergEffect** [comment]
@huochunpeng Mind PRing that change in? 😏

**Comment by huochunpeng** [comment]
Looks like Rob cleaned up the outdated pages. Can be closed.
