### ISSUE TITLE
1.0.0-beta.6 compilation error: TS2339: Property 'config' does not exist on type 'typeof Async'.

### ISSUE THREAD

**Issue by YardGnomeNinja** [aurelia/cli#991]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.6

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.12.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.1.6

* **Loader/bundler:**
Webpack

**Current behavior:**
1. `au new newproject`
2. Select: Default TypeScript
3. Displays:
```
    Name: newproject
    Platform: Web
    Bundler: Webpack
    Loader: None
    Transpiler: TypeScript
    Markup Processor: Minimal Minification
    CSS Processor: None
    Unit Test Runner: Jest
    Unit Test Runner: Karma
    Integration Test Runner: None
    Editor: Visual Studio Code
```
4. Select: Yes (I would like to create this project)
5. Select: Yes (I would like to install project dependencies)
6. `au run --env dev --watch`
7. Receive compilation error:
```
[main] ./src/main.ts 1.09 KiB {app} [built] [1 error]
    + 64 hidden modules

ERROR in C:\src\newproject\src\main.ts
./src/main.ts
[tsl] ERROR in C:\src\newproject\src\main.ts(9,10)
      TS2339: Property 'config' does not exist on type 'typeof Async'.
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.36 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.ejs] 890 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
i ?wdm?: Failed to compile.
```

* **What is the expected behavior?**
A new project should compile with no errors. ;)

* **What is the motivation / use case for changing the behavior?**
Zero error messages gives developers happy thoughts.

**Comment by robinchesterman** [comment]
I'm also seeing this problem

**Comment by huochunpeng** [comment]
The error is from
```ts
Bluebird.config(...)
```

Looks like some bluebird typing messed up.

**Comment by huochunpeng** [comment]
Latest TS is somehow strict.
do `npm i -D @types/bluebird`

PR coming.

**Comment by mobilemancer** [comment]
Install the typings to fix the problem.
`npm install @types/bluebird`

**Comment by huochunpeng** [comment]
cli generated skeleton by default didn't turn on esModuleInterop.
esModuleInterop is recommanded by Microsoft for babel compatibility.

@jeremy-holt would you mind to create an issue in aurelia-router on the activationStrategy+TS+ esModuleInterop? Recently the router project has been migrated from esnext+flow to TS, might be related.

**Comment by jeremy-holt** [comment]
Sure
