### ISSUE TITLE
Error on blank project: TS2339 Property 'config' does not exist on type 'typeof Async'

### ISSUE THREAD

**Issue by hanssens** [aurelia/cli#999]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.7

**Please tell us about your environment:**
* **Operating System:**
OSX 10.14.1

* **Node Version:**
v8.12

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.2.1

* **Loader/bundler:**
Webpack

**Current behavior:**
Clean, empty project crashes with error on `au run --watch`

* **What is the expected behavior?**
Clean, empty project should start normally.

* **What is the motivation / use case for changing the behavior?**  
Steps to reproduce: 

1. Create a new project with `au new`, using the options mentioned below
2. Attempt to run the project with `au run --watch`
3. Error occurs and app crashes:

> ERROR in /src/main.ts
> [tsl] ERROR in /src/main.ts(9,10)
> TS2339: Property 'config' does not exist on type 'typeof Async'.

Options used for new project:

```
3. Custom
1. Webpack
1. Web
2. TypeScript
1. Default (no markup processing)
3. Sass
3. Jest
1. No integration testing
1. VS Code
1. Yes (create project)
2. Yes, use NPM
```

**Comment by hanssens** [comment]
Seems to be a duplicate issue (or regression?) of #991. As mentioned in that issue, can be fixed by running:

```
npm install --save-dev @types/bluebird
```

Still seems to occur in beta7 though?

**Comment by huochunpeng** [comment]
Yes it’s fix but not yet released.
